### ISSUE TITLE
avoid searching given project based on flag existence

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1060]
Most of the projects receive minor changes when doing resync with the parent. Usually this is harmless to the search however when the changes delete some files it might result in imprecise search results or errors. The way around this is to reduce the time window when source code and index are inconsistent is to creatively use file-system level snapshots with 2 applications however this introduces additional complexity to the setup. Another, less powerful workaround would be to make the webapp recognize a per project flag in the form of a dot file placed under the project directory. If the flag is present, webapp searches will avoid index of this project (and display the fact above the search results). So, the mirroring/resyncing script can touch the script prior and remove it after the resync.

**Comment by tarzanek** [comment]
sounds like a good idea - when such project is search a notification about it being reindexed could occur based on some "lock" file, I think lucene might even have such methods to detect reindex being done

**Comment by vladak** [comment]
That would be nice, to cover both cases - resync and reindex.

**Comment by tulinkry** [comment]
This would be possible with #1195

**Comment by vladak** [comment]
Implemented in cset 3f6755e9
