### ISSUE TITLE
OpenGrok 0.11.1 indexing performance issues with CVS/SVN

### ISSUE THREAD

**Issue by PawanKulkarniS** [oracle/opengrok#1115]
Dear Admins,

  I have severe performance issues when indexing the Repos, 
  We have a local SVN repo and opengrok source sandboxes checked out are close to ~20 to ~25 GB,
  We support and index close to 80 opengrok branches with number of visits ranging from 1100-1500 with hits around 12K to 15K  .

   For typical indexing it takes close to 8-9 Days , with following index command ...
```
my $cmd = join(" \\n",
                   $JAVA,
                   '-server -Xms2048m -Xmx4096m',
                   "-Dorg.opensolaris.opengrok.history.Subversion=$SVN",
                   "-Dorg.opensolaris.opengrok.history.cvs=$CVS",
                   "-Djava.util.logging.config.file=$JAVA_LOGGER",
                   "-jar $OPENGROK_JAR",
                   "-O on", # Optimize Indexed Data
                   "-T 8",
                   "-R $configuration_file",
                   '-S');
```
File system is ext3 , with following HP - ProLiant DL 585 G7 server with H/W configuration CentOS release 5.8 (Final) 16Cpu,128GB RAM, 5TB
we dont see a huge resource crunch at any time uptime max reaches 10~11.
however indexing is very slow. We are expecting indexing/branch to complete within 1 Day not 9 Days .
Opengrok Daemon runs with - 
```
/usr/java/default/bin/java -Dnop -server -d64 -Dsun.java2d.opengl=false -Djava.awt.headless=true -Xms8000m -Xmx32000m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:NewRatio=3 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/tomcat-instances/opengrok/log/heapdump.log -XX:OnError=/opt/tomcat-instances/opengrok/bin/self-heal.sh -XX:OnOutOfMemoryError=/opt/tomcat-instances/opengrok/bin/self-heal.sh -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:NewRatio=3 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/tomcat-instances/opengrok/log/heapdump.log -Djava.endorsed.dirs=/opt/apache-tomcat/endorsed -classpath /opt/apache-tomcat/bin/bootstrap.jar:/opt/apache-tomcat/bin/tomcat-juli.jar -Dcatalina.base=/opt/tomcat-instances/opengrok -Dcatalina.home=/opt/apache-tomcat -Djava.io.tmpdir=/opt/tomcat-instances/opengrok/temp org.apache.catalina.startup.Bootstrap start
```
Is this expected speed ? 8-9 days per branch indexing, how i can reduce the indexing speed.

**Comment by tarzanek** [comment]
can you give a shot to 0.13 RC please?
also it's very hard to see if the time isn't unnecessary spent in SCM commands, svn might need more improvement, but try out 0.13 RC first before anything else
then try out to move svn binary away to see if the history generation is the culprit
I'd also expect index of 20G to be done with 4-6h (WITH SCM turned on), but 2-3h without any SCM commands
Also note svn and cvs are very very slow by default ... we do tricks like indexing the whole source tree without history first and then incrementally add history over night (to avoid service interruption), also improving incremental history for cvs and svn might help, but since not many people use these SCMs, it might be tricky (considered moving to git/hg ? )

**Comment by tarzanek** [comment]
but first try 0.13 with svn/cvs disabled - this time is important (to show you what actually takes such a long time)
also note that if you use svn/cvs binaries that are not part of OS and compiled outside, they might not be compiled optimally and cause delays because of that ...

**Comment by tarzanek** [comment]
https://github.com/OpenGrok/OpenGrok/releases/tag/0.13-rc1

**Comment by tarzanek** [comment]
btw. based on what you wrote with your machine, the svn/cvs are really the prob - so the trick with indexing first without history and running partial incremental index in background is something you will get this fixed soon
OpenGrok indexpart 
is the command you look for ... (and then disable svn/cvs for first index, enable for the partial indexpart one, ev. run more indexparts with history in parallel, if the repos will allow it)

**Comment by vladak** [comment]
Too old and response, hence closing.
