### ISSUE TITLE
universal ctags clojure related warning

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1137]
When running the indexer with universal ctags I am getting this warning:

```
Jul 19, 2016 11:03:58 AM org.opensolaris.opengrok.analysis.Ctags$1 run
WARNING: Error from ctags: universal-ctags: Warning: Language "clojure" already defined
```

**Comment by tarzanek** [comment]
ok, so this is my "fault"
we are using our internal definition of clojure until bug
https://github.com/universal-ctags/ctags/issues/988
will be fixed in upstream ctags ...

**Comment by tarzanek** [comment]
this warning will basically happen for every language we override, e.g. like pascal, ...

**Comment by tarzanek** [comment]
actually I am seriously tempted to remove stopper label from this bug, since this only says that we override ctags language by our own defs

**Comment by daleghent** [comment]
FWIW, with latest universal-ctags and 0.13 RC5, the warnings emitted during an index now look like so:

```[opengrok@xenon]~$ OpenGrok index $SRC_ROOT
Loading the default instance configuration ...
19:45:18 WARNING: Error from ctags: ctags: Warning: Language "clojure" already defined
ctags: Warning: Language "pascal" already defined
ctags: Warning: Language "rust" already defined```

**Comment by xiangp126** [comment]
still see the warnings on Opengrok 1.1-rc29

**Comment by cross** [comment]
This is still happening in 1.2.x, with at least three languages.  It is a warning emitted by ctags, but because of something opengrok has done to the ctags environment.  Is there no way to get ctags to know these are okay things, and not to warn about them?
