### ISSUE TITLE
use live auto-suggestions

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1151]
Lucene has a module which offers suggestions (referenced e.g. from http://blog.mikemccandless.com/2014/01/finding-long-tail-suggestions-using.html), we should consider using it.

**Comment by vladak** [comment]
This should be even more possible after the changes for #1132 which will reduce cost of searching.

**Comment by tulinkry** [comment]
We already have suggester in 1.1.2

**Comment by vladak** [comment]
Yeah, dream come true :-)
