### ISSUE TITLE
Resin is not supported

### ISSUE THREAD

**Issue by lewellyn** [oracle/opengrok#1178]
Resin is not supported by the OpenGrok script, nor does the WAR deploy due to Resin being picky about the order of properties in web.xml.

**Comment by lewellyn** [comment]
#1179 makes OpenGrok at least minimally functional on Resin. If any functionality is lacking, I will submit further pull requests to avoid One Huge Patchset.

**Comment by vladak** [comment]
no further Resin related issues so far, closing.
