### ISSUE TITLE
color scheme used in annotations for changesets is hard to perceive

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1361]
It seems people have general problem with understanding the colors in the Annotate view:

> 
> It seemed obvious to me the colors indicated how recent the change was made.
> I thought at first the scale was:
>
> yellow= recent < orange = more recent < dark orange = most recent
>
> But it is actually
>
> dark orange = recent < orange = more recent < yellow = most recent 

Something more obvious is needed. Perhaps the thermo analogy ? (the whole gradient from blue to red)

**Comment by tulinkry** [comment]
Some color schemes were presented in #1099. My most preferred way is the green which it used to be.

**Comment by vladak** [comment]
Another issue is that the hues are not very far from each other. For example:

![colors](https://cloud.githubusercontent.com/assets/2934284/22945071/2e9b5d96-f2f3-11e6-89e1-e3ab6a5cd76c.png)

the difference between cset 6c5588de and 8ad6c897 is almost imperceivable.
