### ISSUE TITLE
in opengrok-0.13-rc7 doing a search for "#if 0" "#if 1" etc - causes error

### ISSUE THREAD

**Issue by ilovemaui** [oracle/opengrok#1379]
in new opengrok, when you try to do a search for "#if 0" "#if 1" etc.. it causes an error.. 
There was an error!

null

java.lang.NullPointerException

**Comment by vladak** [comment]
Does the message come with a stack trace ? How exactly is the search performed ?

**Comment by ilovemaui** [comment]
there was no stack trace. if you simply did a search where you typed into the full search field. you typed "#if 0" or any other number.. but if you typed "#if x" it didn't give this error. something else I noticed, is that sometimes it works. but if you typed "#if a" it would sometimes give this error, and sometimes not. so not sure what is really happening here..

**Comment by vladak** [comment]
If you could inspect Tomcat logs when this happens that would be great.

**Comment by ilovemaui** [comment]
will check.

**Comment by vladak** [comment]
Can't reproduce in the latest, closing. Feel free to reopen if the issue persists.
