### ISSUE TITLE
Let user choose default project in startup script

### ISSUE THREAD

**Issue by michaelPf85** [oracle/opengrok#1387]
The startup script allows for many options but not to select a default project when a user has multiple projects.
Could we add it ? I suppose we'd just need another environment var (like OPENGROK_DEFAULT_PROJECT) and read it in the script.
I'm currently using the Docker container so it's the easiest way to use the feature. If you agree with the idea I could write a PR.

**Comment by vladak** [comment]
Feel free to submit PR for this (do not forget to arrange for OCA).

**Comment by michaelPf85** [comment]
@vladak  Sorry but what is OCA ?

**Comment by vladak** [comment]
OCA = Oracle Contributor Agreement, more here: http://www.oracle.com/technetwork/community/oca-486395.html

The process is usually pretty straightforward and quick. It is sufficient to start the process and then state OCA is in progress in the PR.

**Comment by tulinkry** [comment]
Why don't you use the read-only configuration? It's there just for this purpose. You can then just point the `READ_XML_CONFIGURATION ` variable to that file and it will be merged with the current opengrok configuration. You can set bunch of other features and options there including the default project.

**Comment by vladak** [comment]
This became obsolete with #2217, use `-p` Indexer option or read-only configuration.
