### ISSUE TITLE
support source.war to be deployed in ROOT of tomcat

### ISSUE THREAD

**Issue by tarzanek** [oracle/opengrok#1597]
#1038 says:

Running this in a docker container on alpine. Using Tomcat as my app server. By doing the following, I get the UI at the root context. I decided not to modify the OpenGrok script, since it has source.war hardcoded. Not sure what this would look like on other app servers though.
'''
ENV OPENGROK_WEBAPP_CONTEXT ""
RUN rm -rf $OPENGROK_TOMCAT_BASE/webapps/*
RUN cp -p $OPENGROK_INSTANCE_BASE/lib/source.war $OPENGROK_TOMCAT_BASE/webapps/ROOT.war
'''

We could support a "ROOT" conversion of webapp with empty webapp context at least for tomcat ...

**Comment by idodeclare** [comment]
This has been fully supported since 1.1-rc27 by rewriting of xrefs based on `getContextPath()`.
