### ISSUE TITLE
select all is very slow with a large number of projects

### ISSUE THREAD

**Issue by drusifer** [oracle/opengrok#1665]
The select all operation (and clear/invert) is very slow when there are a large number of projects in the list.  In my example I have about 2000 projects and select all takes about 15 seconds on Chrome and much longer on IE.  

I'm using opengrok-1.0 and I think the issue has to do with the code in searchable-option-list that updates the selected display area once per project (see _addSelectionDisplayItem/_removeSelectionDisplayItem).

**Comment by vladak** [comment]
The project picker performance was addressed in the fix for #1227 that was integrated before 1.0 shipped; looks like more work is needed.

**Comment by tulinkry** [comment]
We use a plugin which apparently was not designed to handle such data

**Comment by drusifer** [comment]
I think the biggest issue has to do with [the code in _selectionChange](https://github.com/OpenGrok/OpenGrok/blob/7f1a64d188f4593e3cbb3971abb0ad1f572fc1ff/web/js/searchable-option-list-2.0.3.js#L981)  which does a linear search on each option.  This is getting called a lot with Select All, Clear, and Invert operations and it's probably not needed.  

The other big bottleneck is when it updates the display items that show what's been selected [here](https://github.com/OpenGrok/OpenGrok/blob/7f1a64d188f4593e3cbb3971abb0ad1f572fc1ff/web/js/searchable-option-list-2.0.3.js#L1050) and [here](https://github.com/OpenGrok/OpenGrok/blob/7f1a64d188f4593e3cbb3971abb0ad1f572fc1ff/web/js/searchable-option-list-2.0.3.js#L1071).  This works by first creating a new element but then hiding it and updating the count of selected projects when there are too many selected.  So it's doing a lot of dom manipulation that never gets displayed.

**Comment by tulinkry** [comment]
I'll get into this next week and try to improve it possibly. If you have a time for this your help is welcome

**Comment by amckenna-pinterest** [comment]
The slowness is coming from the init_searchable_option_list() function, it would be great if there was an option to disable this and go back to the old style of selecting projects.

**Comment by vladak** [comment]
How many projects do you have and how long it takes ?

pá 15. 2. 2019 2:17 odesílatel amckenna-pinterest <notifications@github.com>
napsal:

**Comment by amckenna-pinterest** [comment]
We have over 1k projects and it takes a couple seconds.

**Comment by amckenna-pinterest** [comment]
2.5 seconds for selectAllProjects(), 3.5 seconds for deslectAllProjects();

**Comment by vladak** [comment]
That's indeed significant.

**Comment by amckenna-pinterest** [comment]
Really need an easy way to disable this and go back to the old selector.  I have a set of patches but they keep breaking on every release.

**Comment by vladak** [comment]
What do the patches look like ? Perhaps if they can be parametrized it
could be accepted as a workaround.

Dne pá 22. 3. 2019 19:09 uživatel amckenna-pinterest <
notifications@github.com> napsal:

**Comment by danielviorreta** [comment]
@vladak any update about this?
Currently we have more than 1000 projects and the select all/invert operation takes more than 10 seconds. 
We would like to add more projects to our grok instance but with 5000 projects and 250 groups the operation takes almost 2 minutes.
It looks like the big bottleneck is in [here](https://github.com/oracle/opengrok/blob/57396dcb69c9b0521bc58f615ccd0bf7c141a544/opengrok-web/src/main/webapp/js/searchable-option-list-2.0.8.js#L1196)
<img width="1226" alt="Screenshot 2020-04-08 at 10 37 27" src="https://user-images.githubusercontent.com/1553658/78771988-59adc280-7991-11ea-8c86-6b598db72fa3.png">

Thanks,
Daniel
