### ISSUE TITLE
add directory listing window

### ISSUE THREAD

**Issue by tanglianggithub** [oracle/opengrok#1677]
If has a directory tree or file tree, we will go to other files very conveniently.
Now I will backup, then go to the target file. a little inconvenient.

**Comment by vladak** [comment]
Not sure I got the question. Could you maybe describe the steps and the desired outcome in the last one ?

**Comment by harryxp** [comment]
@tanglianggithub If it helps, I can translate Chinese into English.

**Comment by tanglianggithub** [comment]
for example:
 reading code in dir/a.cc, then I want to go dir/a.h to look for sth.
I must back to dir first, then go to a.h

If there is a directory tree or file tree, I won't need to back to dir first. Through tree,  I can jump to a.h in current page directly.
just like Nerdtree in vim.
![image](https://user-images.githubusercontent.com/3445470/28566949-5b8e0b48-7163-11e7-82de-1ac2d9b08a94.png)

**Comment by vladak** [comment]
I see, this would make OpenGrok more IDE-like :-)

**Comment by vladak** [comment]
I guess another floating window can be put up however we would probably have too many of them (Scopes, Navigate).
