### ISSUE TITLE
get rid of opensolaris in the class hierarchy

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1778]
I think it's time to get rid of the `opensolaris` path/hierarchy component so the class naming is not tied to an operating system. Can do it in one rename - OpenGrok knows how to deal with renamed files.

**Comment by tarzanek** [comment]
I am voting for org.opengrok...

**Comment by vladak** [comment]
so src/org/opensolaris/opengrok/configuration becomes src/org/opengrok/opengrok/configuration ?

**Comment by tarzanek** [comment]
hehe, no, just one opengrok

**Comment by tarzanek** [comment]
so shall we do this rename ?
I think logging.properties will be impacted, perhaps few ant/mvn files

**Comment by vladak** [comment]
yeah, I'd like to do it.

**Comment by vladak** [comment]
I'd like to have the upcoming foundation reflected in the naming scheme so putting this on hold for now.

**Comment by tarzanek** [comment]
@chandanbn the name of foundation will be part of the scheme, hooray!

**Comment by vladak** [comment]
@Orviss is working on this.
