### ISSUE TITLE
Updating a non-optimised index results in repeated `fileRemove`

### ISSUE THREAD

**Issue by cnst** [oracle/opengrok#18]
I'm running {OpenGrok 0.11-rc2 with the `-O off` option (together with `-v` etc), and I am keeping a separate log file for each run.

I've noticed that my fresh daily log only grows with each day; that is, the log of today's run is bigger than the log of yesterday's run.  Even doing an empty run (without any changes of the indexed source code) results in a lot of entries of files being removed (`org.opensolaris.opengrok.index.DefaultIndexChangedListener fileRemove`), when the source code hasn't changed at all from the prior run, and these files that are listed as removed, are not simultaneously listed as being added back, either, but they're still supposed to be part of the index.

When the index is not optimised, is it indeed expected to be bombarded with all the `fileRemove` messages for all the files that have changed since the original index, but which were already supposed to have been re-indexed on the follow-up non-optimised reindex runs?

**Comment by vladak** [comment]
The `-O off` option was probably removed in the course of time. Interestingly, this bug resurfaced much later on with the optimization being off by default. Closing as dup of #4030.
