### ISSUE TITLE
RESTful API for Messages

### ISSUE THREAD

**Issue by noorflex** [oracle/opengrok#1801]
is there a json API which gives me list of all projects which i can display in my interface.

**Comment by vladak** [comment]
The existing web services (https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-web-services) are more tailored for searching. You can use `Messages` script to get the list of projects remotely however exposing the listening port to anyone is not a wise choice as this can be used to write configuration. Marking as enhancement - feel free to submit a pull req.

**Comment by vladak** [comment]
Ideally the code in `ProjectMessage.java` should be refactored and used for web services API.

**Comment by vladak** [comment]
Also, it's not clear to me whether currently the web services API is going through authorization code. @tulinkry ?

**Comment by vladak** [comment]
The other thing to solve is how to authorize the project (non-search) related requests.

**Comment by tulinkry** [comment]
It does the authorization

https://github.com/OpenGrok/OpenGrok/blob/7ccbd27804c2eaf410b0350e5a385587c941bb65/src/org/opensolaris/opengrok/web/JSONSearchServlet.java#L119-L123

and

https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/search/SearchEngine.java#L259-L296

**Comment by noorflex** [comment]
Right, Existing web services are for searching, but to limit the scope of search to a subset of project (e.g one set of Branch out of many branches) will give more control to search.
