### ISSUE TITLE
"Type" dropdown field/box missing with non-project mode

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#1830]
Type dropdown field/box for language selection is missing with non-project mode.
Project mode should be okay.

![image](https://user-images.githubusercontent.com/32307869/31774601-300ea4de-b4b4-11e7-8d47-b0aa24eb3620.png)

`OPENGROK_ENABLE_PROJECTS=false`

This issue started from 1.1-rc15.

**Comment by emergie** [comment]
Regression introduced in https://github.com/OpenGrok/OpenGrok/pull/1796.
In init_searchable_option_list in absence of #project searchableOptionList is never hooked on #type.
Underlying select has visibility:hidden and stays invisible.

**Comment by vladak** [comment]
backed out via d9cfe49da92817a54f04f2553155041d8317edab, reopening.

**Comment by emergie** [comment]
My bad, I ignored the fact, that this code is executed everywhere and didn't check properly the extracted piece.

Change solving #1877 problem in https://github.com/emergie/OpenGrok/commit/15244a1db72410980d865c13ad04b72015fef5b5 commit.

**Comment by vladak** [comment]
No worries, that's what RC's are for. Could you submit new PR ?

**Comment by emergie** [comment]
I've opened https://github.com/OpenGrok/OpenGrok/pull/1883

**Comment by shyoshiz** [comment]
Verified on 1.1-rc19.  Thank you!
