### ISSUE TITLE
Pascal strings are being escaped

### ISSUE THREAD

**Issue by minhaalm** [oracle/opengrok#1902]
Hi, 

Pascal strings are being escaped when the string begins with a slash. 
For example:
` aPathName    := '\directory\subdirectory\';`

I think the code which may need enhancing is in [ OpenGrok/src/org/opensolaris/opengrok/analysis/pascal/PascalSymbolTokenizer.lex ](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/pascal/PascalSymbolTokenizer.lex)

Found in OpenGrok v1.0

I'm happy to code the fix with a bit of guidance on how to get started.

**Comment by tarzanek** [comment]
Hi,
symbol tokenizer is for "defs"
then there is the xref lexer which is used for what you see on web page (cross references generated to html page)

also note , that @idodeclare changed in recent commits the way how we can include common things, so have a look at sh, ada analyzers to see how to share common jflex files or how to consume and properly write escaped chars (java analyzer also handles something similar : https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/java/JavaSymbolTokenizer.lex#L57 )

looking forward to the PR and do ask, we will try to help/guide you (or fix the process)

have fun
L

**Comment by idodeclare** [comment]
@minhaalm , see https://github.com/OpenGrok/OpenGrok/wiki/How-to-build-OpenGrok-from-source about how to build (easiest with NetBeans as the IDE).

See 06a0e69fe12ed92d17ca9db8b0128ac0f7e1b0dc and 118242329b756436508f5a01e111dc1d1194ab17 for examples about adding Xref and Symbol tests for a language, which I think you will need to do for a Pascal fix.

I recommend you add tests and first commit the results for the existing Pascal handling and then commit your fixes separately so the reviewers can easily see their impact.

Please read LICENSE.txt, with special attention to "3.2. Modifications" and "3.3. Required Notices".
