### ISSUE TITLE
Wrong git structure in mirror table at OpenGrok homepage

### ISSUE THREAD

**Issue by barelnir** [oracle/opengrok#1903]
Hi,

I am using the projects field to seperate between product versions,
under each version I have multiple git repositories which I index.

I put all files at the same level like that
/data1/source/<Project>/<git repo>/*

example:
/data1/source/9.0.18.000/server
/data1/source/9.0.18.000/client
/data1/source/9.0.18.000/web

when users open the OpenGrok homepage the table at the bottom shows that the first git repository is the parent of the others. (screenshot attached)

![opengrok](https://user-images.githubusercontent.com/5445098/33434985-a684f54a-d5e9-11e7-9fa5-ef0f2b1ca451.png)

**Comment by Teriand** [comment]
Have same problem in screenshot below:

![git_grok](https://user-images.githubusercontent.com/26705069/34777955-caec4c22-f613-11e7-8605-277e52d894c9.png)

Red - wrong 1st git
Green - all other ok.

**Comment by dn2k-dev** [comment]
why there are levels? if every git clone is totally different and they just share same project (in my case software version) what levels meant for?

**Comment by Teriand** [comment]
I have more 1 project:

rootdir /
---------tfs_1
---------...
----------tfs_x
----------git_folder /
---------------------git_1
---------------------...
---------------------git_x

for git_folder see as git_1

**Comment by dn2k-dev** [comment]
Hi,

Do you think it will be solved, do you need more help?

**Comment by vladak** [comment]
Pull requests are always welcomed :)

Dne 15. 3. 2018 15:40 napsal uživatel "dn2k-dev" <notifications@github.com>:

**Comment by Teriand** [comment]
I found quick fix for self problem git_folder:
 repos.jspf:

 for (RepositoryInfo ri : repos) {
                                if (cnt > 0 && ri.getParent() == null)
                                    // discard repositories without a parent url
                                    continue;
                                //if (cnt != 0) {
                                    projDesc = ri.getDirectoryName()
                                                 .replace(cfg.getSourceRootPath() + File.separator, "");
//                                }
   <tr><td class="name <%= cnt >= 0 ? "subrepository" : "repository" %>">

All repos in git_folder is subrepository of git_folder and dont need skip 1st subfolder.
Other problem i cant fix - how to add git_folder as "repository".
"git_folder" is not part  "for (Project proj : repositories)" and cant get it..

**Comment by Teriand** [comment]
i thing its fixed after #2679

**Comment by tulinkry** [comment]
Yes, it looks like the similar problem.

**Comment by Teriand** [comment]
test 1.2.2, repo fixed.
![image](https://user-images.githubusercontent.com/26705069/53000768-25e4a600-343a-11e9-8684-cf4e16d7e6e6.png)

**Comment by tulinkry** [comment]
Glad to hear that. Close the issue then.
