### ISSUE TITLE
repository credentials should be per-project tunable

### ISSUE THREAD

**Issue by Suwadith** [oracle/opengrok#1946]
Whenever I try to check the revisions of a particular file (Using the History option) It says "Error reading file" (Except for the final Commit/Revision).
I guess it's unable to get those files and because of that I'm unable to use the Annotate option as well. (By unable I mean it literally does nothing.) 

This happened with both v1.0 and v1.1-rc17

But when I indexed this repo: https://svn.apache.org/repos/asf/excalibur/trunk/components/datasource/
It worked perfectly fine. Even the Annotate option works. 

What can be the cause of this? 

Thanks.

**Comment by vladak** [comment]
Most likely the `svn` command that was used to fetch historical versions of the file failed. You'll have to dig into Tomcat logs to see what `svn` commands were run from the webapp. Again, Tomcat uses `logging.properties` so it can be tuned to increase the verbosity of the messages.

**Comment by Suwadith** [comment]
I think it's an authorization issue. 

`13-Dec-2017 19:29:31.213 WARNING [http-nio-80-exec-7] org.opensolaris.opengrok.util.Executor.exec Non-zero exit status 1 from command [C:\Program Files\TortoiseSVN\bin\svn.exe, cat, -r, 60207, SourceCode\Java\se\xx\xx\xx\xx.java@] in directory E:\Source\Test\xx_xx: svn: E170013: Unable to connect to a repository at URL 'https://subversion.xx.se/PC/Standard/xx_xx/branches/R1.1_xx_xx/SourceCode/Java/se/xx/xx/xx/xx.java'
svn: E175013: Access to '/PC/Standard/xx_xx/branches/R1.1_xx_xx/SourceCode/Java/se/xx/xx/xx/xx.java' forbidden`

When I tried to access the URL through my browser it asked for my credentials. But I have already set the Environmental variables as you mentioned before. 

In the OpenGrok logs it's using them. 

`2017-12-13 18:58:04.743+0530 FINE t101 Executor.exec: Executing command [C:\Program Files\TortoiseSVN\bin\svn.exe, log, --non-interactive, --username, xxx, --password, xxx, --xml, -v] in directory E:\Source\Test\xx_xx_xx`

![image](https://user-images.githubusercontent.com/20539850/33974948-6830a01e-e0b1-11e7-8bf9-f8c78ee33818.png)

Should I do something else to let Tomcat Access the SVN too?

**Comment by Suwadith** [comment]
BTW I'm able to get Previous revisions of a particular repo using this command

`svn checkout https://subversion.xx.se/PC/Standard/xx_xx/branches/R1.1_xx_xx -r 26578`

But I didn't use any authentication parameters (E.g --username, --password) with that.

**Comment by vladak** [comment]
Yeah, the webapp needs to be able to access these environment variables in order to authenticate and fetch the history, otherwise it will just run the `svn` commands without the username/password options.

**Comment by vladak** [comment]
Actually, this could be a dup of #1601.

**Comment by vladak** [comment]
Anyhow, the way how the authentication is implemented for SVN repos is wrong. Relying on environment variables makes the setup more complicated (as demonstrated above) and also prevents anyone from using distinct credentials for different SVN repos. They should really be stored as per-project tunable.

**Comment by vladak** [comment]
Also, it might be possible to store SVN configuration in configuration directory (http://svnbook.red-bean.com/en/1.7/svn.advanced.confarea.html) along with the username/password however #531 might be needed for that.

**Comment by vladak** [comment]
As for setting the environment variables in Tomcat, this is usually done via the `setenv` file (https://tomcat.apache.org/tomcat-7.0-doc/RUNNING.txt mentions `setenv.bat` for Windows and `setenv.sh` for Unix).

**Comment by vladak** [comment]
Lastly, this should be documented somewhere.

**Comment by vladak** [comment]
The basis for per-project configuration was delivered in #1693

**Comment by Suwadith** [comment]
@vladak How should I declare the user pass combination inside the setenv.bat file 

I created the setenv.bat file.
I added the following lines inside it.
`set "svn=C:\Program Files\TortoiseSVN\bin\svn.exe --username xxx --password xxx"
set "SUBVERSION=C:\Program Files\TortoiseSVN\bin\svn.exe --username xxx --password xxx"
exit /b 0`
I added it inside the bin folder.
But it doesn't seem to be working. How should I define them?

**Comment by vladak** [comment]
Dunno, my Windows experience is close to 0.

**Comment by Suwadith** [comment]
@vladak Ohh ok. I'll keep digging.

**Comment by vladak** [comment]
Also, it would not hurt if you got the changes for #1950. Or just wait for the next RC.

**Comment by Suwadith** [comment]
@vladak For some reason History and Annotate functions are working properly when you use the Zipped version of Tomcat. (By executing startup.bat)
When you install it as a service (Service.bat), that's when the "Error Reading File" Message shows up. Any ideas why this is happening?

**Comment by vladak** [comment]
No idea. Pls leave this issue only to track the enhancement. Feel free to create new issues for unrelated questions.
