### ISSUE TITLE
Non-zero exit status 129 from command while indexing with history

### ISSUE THREAD

**Issue by Arieltk1** [oracle/opengrok#1963]
Hi all,
Working with OpenGrok version 1.0, git 2.7.4 on Ubuntu 16.04.3. 
While indexing a big repository with history but without renamed history: 	OPENGROK_RENAMED_FILES_HISTORY=off ./OpenGrok index /home/user01/src

I get the following error:
WARNING t24 Executor.exec: Non-zero exit status 129 from command [/usr/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, --date=rfc, --follow, --, myfile.cs] 

On every execution the error is on different source files and this warning causes the indexing to stop.

Executing without history at all succeeded, but I need history.

Help/workarounds are appreciated.

Thanks,

Ariel

**Comment by vladak** [comment]
This looks like the problem described in #1884, i.e. ancient git.

See the logs more carefully, they should contain the root cause.

**Comment by Arieltk1** [comment]
Thanks vladak.
The git version is 2.7.4. 
Currently in the logs I see just the error of the executed command, that by the way when I execute it manually it passes correctly.

**Comment by vladak** [comment]
Is the indexing run as the same user ?

**Comment by Arieltk1** [comment]
yes

**Comment by vladak** [comment]
What is the elapsed time of the `git log` when it succeeds ? Any special environment variables that would affect the command ? (proxies etc.)

Could you post the complete log somewhere ? (to gist.github.com for instance)

**Comment by vladak** [comment]
There are couple of properties of the environment which can differ (other than privileges) and you might want to check:
  - environment variables
  - resource limits (those influenced by `ulimit` etc.)
 
Also, only now I read the initial submission in full and there is one more thing that can cause the failure - command timeout. If such termination happens, it is logged with the `INFO` level. By default the timeout is set to 10 minutes so you might want to set it higher value in your readonly configuration.

**Comment by vladak** [comment]
Closing for lack of response, feel free to reopen.
