### ISSUE TITLE
escape character does not work

### ISSUE THREAD

**Issue by tanglianggithub** [oracle/opengrok#1966]
use loop\\(\\) to search  'loop()', but opengrok cannot find the result.

**Comment by vladak** [comment]
I think the parenthesis characters are stripped away in the process of indexing.

**Comment by tarzanek** [comment]
I am wondering if OpenGrok indexes "("
definitely worth talking about if this is a viable use case and worthwhile to improve tokenizers (at least the full plain one)

**Comment by idodeclare** [comment]
> definitely worth talking about if this is a viable use case and worthwhile to improve tokenizers (at least the full plain one)

@tarzanek , I would say it's viable, and in fact I have a branch that uses my `JFlexSymbolMatcher` event model and `JFlexTokenizer` refactoring to do just what you’re suggesting w.r.t. `PlainFullTokenizer`.

But with the Oracle repo grab and not seeing @tarzanek or @vladak or @tulinkry in https://github.com/orgs/oracle/people — and moreover with reviews at a dead halt — I'm thinking of closing all my PRs here. I've forked FreeGrok and am waiting to see what's happening here within the next short interval.

**Comment by tarzanek** [comment]
@idodeclare sorry, we're stuck on some legal talks, but we have a resolution, the repo transfer was a bit unfortunate and premature, but solution is in progress

me & @vladak can still accept PRs, I will try get back to your PRs, bear with us please

**Comment by deeparora29** [comment]
I am also facing the similar issue where I search for M\{ and it returns false positives. FTR, I am using version 0.9.0

**Comment by tarzanek** [comment]
@deeparora29 can you get to 1.2.x please?
0.9 is really old and Chris had his fixes in 1.x I think
