### ISSUE TITLE
Different syntaxes for tags getconf and setconf with config type messages

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#1973]
Hello,

I am using 1.1-rc5.

When getting conf with Messages tool, I type:
`Messages --verbose --type config --tag getconf > conf.xml`
When setting conf, I type:
`Messages --verbose --type config setconf conf.xml`

Why such a (n a priori unexpected) difference ? I needed to dig into code to see _--tag_ must not be used when tag is _setconf_ so that the message text can indeed be considered a file...

**Comment by vladak** [comment]
Looks like a bug to me, will look in more detail later to confirm.

**Comment by vladak** [comment]
I think this is only a problem in the `Messages` shell script. The `ConfigMessage` handling considers `setconf` to be a tag.

**Comment by ChristopheBordieu** [comment]
Thanks! Issue can be closed. Will reopen if needed.

**Comment by vladak** [comment]
I will fix the script along with other Message changes.

Dne 12. 1. 2018 23:48 napsal uživatel "ChristopheBordieu" <
notifications@github.com>:
