### ISSUE TITLE
ship rendered OpenGrok wiki pages with each release

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1982]
In PR #1981 a discussion was started basically about what sort of documentation should be present in the source and what on the wikis. My take on this is that most of the stuff (even the top level README) should be on the wikis because they are easier to change (also the README is too big now I think and should probably be split).

We can package the wikis (or rather their HTML/plaintext representation) with each release. Pulling the content is easy (https://help.github.com/articles/adding-and-editing-wiki-pages-locally/), just need to figure out the format translation (use https://github.com/github/markup to convert to HTML. Of course this should be done in a way that will not hamper #1967).

**Comment by tarzanek** [comment]
perfect idea !

**Comment by tulinkry** [comment]
may be relevant https://github.com/oracle/opengrok/blob/master/web/js/showdown-1.4.2.min.js

**Comment by vladak** [comment]
@tulinkry I was not able to quickly find out if showdown supports multiple markdown formats. In our wikis there are 2 formats used: "md" and mediawiki.

As for the `github-markup` I was not able to get it installed on my trusty Ubuntu laptop yet because of dependencies.

**Comment by vladak** [comment]
Tried `showdown` CLI (had to install `nodejs-legacy` package on my legacy Ubuntu laptop :) for the `node` command) and it converted "md" wikis just fine, with mediawiki it produced incomplete HTML (tried the supported revision control systems table) that also made my FF to crash :)

**Comment by vladak** [comment]
Need to convert everything to Markdown first. Then we can use https://github.com/joeyespo/grip

**Comment by vladak** [comment]
I don't think this idea is worth it, closing.
