### ISSUE TITLE
For a single search result redirect to the file immediately

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#1984]
May be a useful feature.

Iff there is a single search result we can maybe immediately redirect to that xref.

Use case:
Clicking on class name in some Java file leads directly to the file with that class (assuming unique name per project) rather than to a search results with one result.

**Comment by vladak** [comment]
@tulinkry feel free to submit a PR for this.

**Comment by tulinkry** [comment]
Looks quite challenging as `totalHits` after the search means total files which matches the query (and not the particular lines). There isn't a evident simple way to get the total line count out of the search.
