### ISSUE TITLE
The GitHub repository description has a rogue { in it

### ISSUE THREAD

**Issue by chrisseaton** [oracle/opengrok#1995]
> {OpenGrok is a fast and usable source code search and cross reference engine, written in Java http://oracle.github.io/opengrok/

Is that `{` supposed to be there? Looks like maybe it was a Markdown code annotation that you realised wouldn't work in that field but not completely deleted.

**Comment by idodeclare** [comment]
See http://oracle.github.io/opengrok/. It's been the trademark of the project since its inception. Strangely, it's not mentioned in the [Story of OpenGrok](https://github.com/oracle/opengrok/wiki/Story-of-OpenGrok).

**Comment by chrisseaton** [comment]
Oh sorry.

**Comment by idodeclare** [comment]
I was mistaken. At the end of the "Refactoring" section in the [Story of OpenGrok](https://github.com/oracle/opengrok/wiki/Story-of-OpenGrok):

> The logo has a opening flower bracket ... Which is a common block start symbol in languages like C and Java. It has no closing bracket to signify open source.
