### ISSUE TITLE
I want to skip connect tomcat when index start.

### ISSUE THREAD

**Issue by jiungbaek** [oracle/opengrok#2024]
scm : git
opengrok version : 1.1-rc21
jdk : 1.8.0_65
os : ubuntu 16.04
tomcat : 8

I want to skip connect tomcat when index start.
I'm using 0.12 version, i want to upgrade to 1.1-rc21

but some issue i have.

my system is like below

```
                             nfs
opengrok web --------- source(almost 100 kind of source, each source has 80GB)
```

Now, I'm indexing by each servers(almost 100 servers) at once and connect main opengrok web server by nfs.
0.12 version is fine. However when i test by 1.1-rc21, i need check connect to tomcat when indexing start.

so how i skip check connect tomcat when i indexing start?

**Comment by vladak** [comment]
I gather you hit the `"projectsEnabled = true"` config update in `main()` in the Indexer. To suppress connecting to the webapp, set the `OPENGROK_WEBAPP_CFGADDR` env var to `none` (if using the `OpenGrok` shell script).

**Comment by jiungbaek** [comment]
thanks

**Comment by tarzanek** [comment]
fwiw with my commit #1871 this should be only a warning now in current trunk/master
