### ISSUE TITLE
Need refreshed Slack invite token for the wiki

### ISSUE THREAD

**Issue by daleghent** [oracle/opengrok#2029]
As mentioned at https://github.com/oracle/opengrok/wiki/Discussions#Slack

**Comment by tarzanek** [comment]
done, we have now a link that never expires:
https://join.slack.com/t/opengrok/shared_invite/enQtMzI1Mzc1MTU3ODQ2LTM5MTdhYWJiODVlOTU4OTYzNjM5ZGYzYzU2ZTU4ODZiMTFkZWRiNWRlMmJkNGYwZjMyMjQzMjY2ZTYyOGQ4MzM

hth
L

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Hey @tarzanek, it appears that the Slack invite link has expired again. Would it be possible to generate a new Slack invite link?
Thanks!
![image](https://user-images.githubusercontent.com/68922586/88709211-15763780-d0d2-11ea-949a-59ef5213af9f.png)
