### ISSUE TITLE
Search returns only two files out of 27 expected matches

### ISSUE THREAD

**Issue by fairmonk** [oracle/opengrok#2047]
Environment in use:
opengrok-1.1-rc21
jdk1.8.0_121
ctags58
windows 2008r2
tomcat8
Here is indexing command I run:
`java -Xmx28g -jar C:\opengrok\opengrok-1.1-rc21\lib\opengrok.jar -W C:\opengrok\Data_tmp\configuration.xml -c C:\opengrok\ctags58\ctags.exe -P -S -v -s C:\opengrok\src_tmp -d C:\opengrok\Data_tmp -i *.zip -i *.tmp -i *.db -i *.jar -i *.class -i *.dylib -i *.pdb -i *.har -i *.tar.gz -i *.bin -i *.pdf -i *.doc -i *.msp -i *.msi -i f:regress-274888.js -i f:test553 -i f:test56 -i f:source-map.debug.js -i d:openjdk8-b132 -i d:.svn -G -T 8
`
Here is search results ( actual behavior ))
![image](https://user-images.githubusercontent.com/9027632/37899514-613dcfd2-30f4-11e8-98c9-fc5981208ab9.png)

Here is expected behavior, i.e. all files from src_tmp directory should match ( but only two do matching )
![image](https://user-images.githubusercontent.com/9027632/37899639-c7d36eb4-30f4-11e8-8734-c6276addea27.png)

Logs show all files are added to index, see attached logs
[index_logs.log](https://github.com/oracle/opengrok/files/1847283/index_logs.log)

**Comment by tarzanek** [comment]
what if you search for wildcard?
*autopass*
simple "autopass" will just find standalone tokens ...

**Comment by fairmonk** [comment]
Indeed, searching with wildcard returned all results ! Thank you for fast reply, I'm closing this as not an actual issue but rather misuse of the application.
