### ISSUE TITLE
How to auto update index on git commit?

### ISSUE THREAD

**Issue by kuchaguangjie** [oracle/opengrok#2055]
I am using gitlab for projects, and has linked git repos for opengrok to index.

Currently, a manual re-index is needed to see new commits to git repositories.

I am wondering what is the best approach to re-index automatically on commit to gitlab?

Thanks.

**Comment by tulinkry** [comment]
I think using [git hooks](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks) and partial index for particular project may be the way to go.

**Comment by kuchaguangjie** [comment]
@tulinkry What do you mean by partial index, does it means to re-index a single project or something else?
Currently I am setting evn `$OPENGROK_INSTANCE_BASE` as the instance dir, and call `$OPENGROK_HOME/bin/OpenGrok index` to do index.

Can you give an example for partial index, thanks.

**Comment by tulinkry** [comment]
https://github.com/oracle/opengrok#523-partial-reindex

@vladak uses partial indexing approach so he may be more appropriate than me for this question

**Comment by tulinkry** [comment]
But you don't need to do the partial index, that is just an option. But you need to set up the git hook to trigger the `OpenGrok index` command.

**Comment by kuchaguangjie** [comment]
@tulinkry  I see, I think the above comments have already provide enough information to finish to task, thank you !
