### ISSUE TITLE
HEADER, SRC_ROOT and DATA_ROOT are not valid webapp parameters

### ISSUE THREAD

**Issue by sjaensch** [oracle/opengrok#2062]
The [webapp configuration](https://github.com/oracle/opengrok/wiki/Webapp-configuration) wiki page mentions HEADER, SRC_ROOT and DATA_ROOT as parameters. These don't seem to be read by the webapp listener, and don't seem to have any effect when set. Either this should be fixed or they should be removed from the documentation.

**Comment by vladak** [comment]
While this could be a fun excursion into the history to dig out when/if these parameters worked in the past, it makes limited sense to duplicate these in the `web.xml` so I fixed the wiki instead.
