### ISSUE TITLE
Warning: Language "pascal" already defined

### ISSUE THREAD

**Issue by asakura0603** [oracle/opengrok#2064]
While indexing of the latest source, 
the following warning message is displayed , and the index does not end.
```
23:54:06 警告: Error from ctags: ctags-exuberant: Warning: Language "pascal" already defined
```

**Comment by tulinkry** [comment]
I guess the warning is harmless, see #1137. The cause for the endless index must be something else.

**Comment by asakura0603** [comment]
thanks, tulinkry.
I continue to wait until the indexing work is over!

**Comment by tarzanek** [comment]
you should track/trace what the app is doing ... which phase is it stuck in ...
scm fetch? indexing? (lucene? xref writes?)

**Comment by asakura0603** [comment]
thanks, tarzanek.
How can I track what an app is doing?
(I'm sorry I made a bad question...)

**Comment by tarzanek** [comment]
you can use various (observability) tools, the easiest is to check opengrok logs which will give you a little bit of context - after that use your OSes debug tools to see the process list/tree, try to attach to the process using strace to see what is going on
try to dump jstack to see what java threads are doing
after such exercise you might close up on what is going on ... (and it's fun to look under the hood too :-D )
