### ISSUE TITLE
symlink loop will make the indexer to enter infinite cycle

### ISSUE THREAD

**Issue by ilovemaui** [oracle/opengrok#2080]
not sure if this is a real problem - but if you try to create an opengrok index with version 3.6 of openshift (might give these warnings with other versions too), you get these warnings. Perhaps these are related to symlinks.
Version of Opengrok: 1.1-rc23
latest version of Universal ctags.
jdk version - 1.8.0_72
OS - Linux RH 6.8 (santiago)

so here are a couple examples:
WARNING: Failed to resolve name: /myopengrok/src/github/openshift-ansible-release-3.6/playbooks/aws/openshift-cluster/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks /myopengrok/src/github/openshift-ansible-release-3.6/playbooks/aws/openshift-cluster/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/default.yaml

WARNING: Failed to resolve name: /myopengrok/src/github/openshift-ansible-release-3.6/playbooks/byo/openshift-cluster/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks /myopengrok/src/github/openshift-ansible-release-3.6/playbooks/byo/openshift-cluster/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/longer-warning-period-json-results.yaml

**Comment by vladak** [comment]
The clone of https://github.com/openshift/openshift-ansible contains bunch of symlinks that reference the `roles` directory. Notably:
  - the `playbooks/aws/openshift-cluster` directory contains the `roles` symlink pointing to `../../../roles`
  - the `roles/openshift_certificate_expiry/examples/playbooks` directory contains the `roles` symlink pointing to `../../../roles`

The latter forming a loop:

```
13:21:50 WARNING: Could not read /var/opengrok/src/openshift-ansible/playbooks/aws/openshift-cluster/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles/openshift_certificate_expiry/examples/playbooks/roles
```

The symlinks are "local" (i.e. within a project) therefore they are accepted for recursive traversal by the indexer. I don't think the indexer can do anything about it (loop detection would produce a warning anyway), it's just a noise.

**Comment by vladak** [comment]
One question: does the index actually finish for the project or is it looping forever ?

**Comment by ilovemaui** [comment]
well it still hasn't finished. I am doing a complete reindex, which started on 4/18. and still not done, not sure if this is normal or not.

**Comment by idodeclare** [comment]
It won’t finish, unfortunately. The fix to end the recursion is trivial but this issue also reveals that there is an issue with displaying History for symlink directories.

I wonder if there’s a straight-forward fix for that....

**Comment by vladak** [comment]
Okay, marking as bug then. The history directory view for symlinked directories should be treated in separate issue.

**Comment by ChristopheBordieu** [comment]
I open ED a bug for suce same issue.
