### ISSUE TITLE
Want intuitive way to update indexes and to error out on outdated ones

### ISSUE THREAD

**Issue by daleghent** [oracle/opengrok#2084]
Often, or often enough, a new OpenGrok release will update the version of Lucene it delivers and that will occasionally require a complete re-indexing of all projects.

The re-indexing process itself is kind of unintuitive and rough around the edges, especially for the unfamiliar administrator of an OpenGrok installation. The only hint that something is amiss after such an update of OpenGrok is a fat stack trace when doing a search, often looking like this:

```
java.lang.IllegalArgumentException: Could not load codec 'Lucene62'.  Did you forget to add lucene-backward-codecs.jar?
...
...
```

The actual problem isn't as dire as a stack trace makes it appear to be, and the solution for now is to manually `rm -rf` the data directory and initiate a new indexing with `OpenGrok index`. 

This issue is to propose the addition of a new sub-command to `OpenGrok` to facilitate this action from a single command, as well as to catch errors from indexes containing prior Lucene versions and display a more elegant and understandable error message, rather than just a naked stack trace.

**Comment by vladak** [comment]
AFAIK Lucene indexes can contain segments with multiple different versions. Let's assume OpenGrok indexes always have just a single version. However, each project has its own index so ideally the versions of each should be checked.

The `SegmentInfos` Lucene class contains `VERSION_CURRENT` integer member  that has the current version. As noted in https://stackoverflow.com/questions/44155910/how-to-determine-the-lucene-index-version it can be extracted using `IndexReader`.

This sort of failure should be propagated from the indexer to the wrapper script, i.e. not just appear in the logs but on the screen as well. The script can use a dedicated option of `Indexer` to check the version before the indexer run and bail out if inconsistency is found. That said, there are probably cases when Lucene upgrade does not imply full reindex so strict equality check is probably not desired.

As for the "wipe-out" option, the `OpenGrok` shell script already has the `clearHistory` sub-command so adding more generic one to wipe out the indexes (perhaps with interactive confirmation and a force flag) should be fine.

**Comment by vladak** [comment]
According to https://wiki.apache.org/lucene-java/BackwardsCompatibility it should be sufficient to check major version only:

> Minor versions should always have back-compatiblity for supported APIs (i.e. public and protected). That's to say, any code developed against X.0 should continue to run without alteration and without recompilation (ie, simply drop in the new JAR) against all X.N releases, as long as only supported APIs are used.

Even though major versions could be compatible, I'd like to avoid having any sort of logic in OpenGrok to track this.
