### ISSUE TITLE
update Servlet API

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2089]
When compiling the web project in Jenkins it produces this warning:

```
 [javac] /tank/hudson/home/jobs/OpenGrokAnt/workspace/test/org/opensolaris/opengrok/web/DummyHttpServletRequest.java:40: warning: [deprecation] HttpSessionContext in javax.servlet.http has been deprecated
    [javac] import javax.servlet.http.HttpSessionContext;
    [javac]                          ^
```

This needs to be fixed to prevent future breakage.

**Comment by Orviss** [comment]
I think this points to general update of servlet-api. There is already version `4.x` (<http://mvnrepository.com/artifact/javax.servlet/javax.servlet-api>) out and OpenGrok is still using old `2.5`. This should be also coordinated with minimum supported Tomcat version: <http://tomcat.apache.org/whichversion.html>

**Comment by vladak** [comment]
Marking as enhancement then :-)

**Comment by tarzanek** [comment]
I'd say we should go to at least tomcat8 ... or whatever is the tomcat that supports latest stable jdk

**Comment by vladak** [comment]
Let's go with Tomcat 8.5 as minimum as this is seems to be the frequently used non-superseded version currently.
