### ISSUE TITLE
Move debian directory to platform repository

### ISSUE THREAD

**Issue by Orviss** [oracle/opengrok#2096]
I believe `debian` directory should be moved to <https://github.com/OpenGrok/platform>. Also, it seems a bit outdated (at least readme mentions Java 7 which is not supported anymore).

**Comment by vladak** [comment]
Yep. OpenGrok repo itself should be as platform agnostic as possible.

Dne pá 4. 5. 2018 14:49 uživatel Adam Hornáček <notifications@github.com>
napsal:
