### ISSUE TITLE
Sanitize HTML tags in JavaDoc

### ISSUE THREAD

**Issue by hhtat** [oracle/opengrok#2105]
HTML tags in JavaDocs are rendering as HTML elements when viewing the source in OpenGrok.

Repo:

```
/**
 * Foo
 *
 * @param bar The <Input> type for Foo.
 */
```

The `<Input>` portion is being rendered as an actual input field with: `<em><input></em>`

**Comment by idodeclare** [comment]
@hhtat what version are you using? I believe this should have been fixed as of 1.1-rc19.

**Comment by hhtat** [comment]
Looks like 1.1-rc4. We'll update soon, thanks!
