### ISSUE TITLE
JsonAnalyzer is taking several hours to add/index large JSON files.

### ISSUE THREAD

**Issue by wizwin** [oracle/opengrok#2118]
```
OS              : Ubuntu 12.04.5 LTS
Opengrok Version: 1.1-rc26
Tomcat Version  : 8.5.31
Java            : Oracle JRE/JDK 8u172
Ctags           : Universal Ctags 0.0.0(6418097) - Based on Exuberant Ctags 5.8 
Hardware        : Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz with 16GB RAM
Project         : AOSP
```
JsonAnalyzer is taking several hours to add/index large JSON files.

**From Opengrok index log:**
```
INFO: Add: /external/chromium-trace/trace-viewer/tracing/test_data/tall_trace.json (JsonAnalyzer)
**May 19, 2018 7:38:19 PM** org.opensolaris.opengrok.index.DefaultIndexChangedListener fileAdd
INFO: Add: /external/chromium-trace/trace-viewer/tracing/test_data/tcmalloc_multi_renderer.json (JsonAnalyzer)
**May 19, 2018 9:22:03 PM** org.opensolaris.opengrok.index.DefaultIndexChangedListener fileAdd
```
There are several large JSON files in this directory and indexing stalls for several hours.

There are around 6 threads running for indexing at this stage (using 26.9% memory):
2 threads are using around 80% CPU.
4 threads mostly stay near 20% CPU usage.
Around 22-26 threads under indexing parent process are sleeping.

**Comment by tarzanek** [comment]
are these jsons available somewhere so I can reproduce locally?

**Comment by wizwin** [comment]
I was indexing Marshmallow code base. JSONs files are located in the following directory:
http://androidxref.com/6.0.1_r10/xref/external/chromium-trace/trace-viewer/tracing/test_data/

**Comment by wizwin** [comment]
Observations:
- After around 12 hours of indexing.
- Even JARAnalyzers are taking 25-50 minutes to add/index JAR files (~>1.0MB).
- C, plaintext etc. goes through very fast initially.

**Comment by wizwin** [comment]
More observations:

I switched to Ubuntu 14.04 LTS on the same machine. Downgraded to 1.1rc22 (not sure if this has any effect), excluded prebuilts (which had many jars), jar and json files and enabled history cache.

Now indexing is going on without issues on 1.1rc22.

**Comment by tarzanek** [comment]
@idodeclare could it be that the highlighter has impact on jar/json analyzers that it slows them down?

**Comment by idodeclare** [comment]
@tarzanek , no the uhighlighter is only active post-indexing.

**Comment by idodeclare** [comment]
@wizwin , I homed in on the performance problem with these multi-megabyte, single-line JSON files and will raise a PR to work around it.

**Comment by wizwin** [comment]
@idodeclare, Thank you for the fix.
