### ISSUE TITLE
configuration.xml was not created

### ISSUE THREAD

**Issue by wizwin** [oracle/opengrok#2124]
After https://github.com/oracle/opengrok/issues/2118

I ran indexing on 6-8 projects using 1.1rc22, after 2 days and 10 hours opengrok indexing failed with the following error:
```
May 25, 2018 9:29:24 AM org.opensolaris.opengrok.index.IndexDatabase indexParallel
WARNING: 1 failures (0.0%) while parallel-indexing
```
configuration.xml was not created for any of the projects that already completed indexing.

I see there is projadm tool now (in github) but not in 1.1rc22. Is there a way to create configuration.xml by hand so that I need not re-index.

**Comment by wizwin** [comment]
I tried the same re-index task using the same configuration without deleting data. It got stuck again at the same place. 

It is stalled for almost 2 hours now. When I checked disk IO, there is activity going on with Opengrok tasks itself.

Will update the status on the same.

**Comment by wizwin** [comment]
Indexer was able to complete after a few hours even with these warnings.

I am closing this issue for now as it does not look like a failure or a bug.

**Comment by tarzanek** [comment]
@wizwin you will need new RC with fixes for json (which will hopefully mitigate the parallelism problem you saw)
we also did some changes that change index+xref so a reindex from scratch will be needed
