### ISSUE TITLE
Diff bar is cut off

### ISSUE THREAD

**Issue by Orviss** [oracle/opengrok#2133]
This happens on my setup in Safari and Chrome. 

<img width="1440" alt="screen shot 2018-05-30 at 09 28 13" src="https://user-images.githubusercontent.com/12401160/40705798-2cbb2e6e-63ec-11e8-8322-7ecdf74b2fe1.png">

Try this link to see for yourself <http://demo.opengrok.org/diff/lucene-solr/solr/contrib/ltr/src/test/org/apache/solr/ltr/feature/TestFieldValueFeature.java?r1=%2Flucene-solr%2Fsolr%2Fcontrib%2Fltr%2Fsrc%2Ftest%2Forg%2Fapache%2Fsolr%2Fltr%2Ffeature%2FTestFieldValueFeature.java%40ac3f1bb3&r2=%2Flucene-solr%2Fsolr%2Fcontrib%2Fltr%2Fsrc%2Ftest%2Forg%2Fapache%2Fsolr%2Fltr%2Ffeature%2FTestFieldValueFeature.java%401a6d0f58>

**Comment by vladak** [comment]
yep, the top line of the buttons is missing in 1.1-rc22 and FF 60.0.1. I think it's been like that for a long(er) time.
