### ISSUE TITLE
OpenGrok with default config can't parse View.java end

### ISSUE THREAD

**Issue by onlyxxp** [oracle/opengrok#2135]
tomcat:8.5.31
Universal Ctags 0.0.0(6f7654b)
MacOS: 10.13.4

I use OpenGrok,  with default config, to index android-8.1.0_r20 source code, but it  can't parse some java file end.
Such as it parse the java file [View.java.zip](https://github.com/oracle/opengrok/files/2056663/View.java.zip), And parse result is this xref file : [View.java.gz](https://github.com/oracle/opengrok/files/2056656/View.java.gz) at <src_root>/data/xref
the ctags does not parse the function structure end success.  

BTW, this java class, is parse right in the [androidxref](http://androidxref.com/8.0.0_r4/xref/frameworks/base/core/java/android/view/View.java#)  .
It has right navigate in that site
 
I don't know what's wrong?
Do I need config the <src_root>/etc/ctags.confg, so it may work ok?

**Comment by onlyxxp** [comment]
@vladak  Thank you very very much for tip!

I switch to OpenGrok 1.0 & Exuberant Ctags 5.8,  it is work right know!

**Comment by idodeclare** [comment]
This seems to be a Universal Ctags problem. OpenGrok has no trouble parsing the file.

Below is an excerpt from tags on View.java: a method is tagged at line 4561 and then a local variable at line 4580 — and unexpectedly nothing is tagged until a method at line 8369.

I didn't eyeball any reason why the code would confound Universal Ctags.

```
View    View.java       /^    public View(Context context) {$/;"        method  line:4561       class:View      signature:(Context
 context)
targetSdkVersion        View.java       /^            final int targetSdkVersion = context.getApplicationInfo().targetSdkVersion;$
/;"   local   line:4580
numViewsForAccessibility        View.java       /^    private static int numViewsForAccessibility(View view) {$/;"      method  li
ne:8369       class:View      signature:(View view)
```
