### ISSUE TITLE
rc27 builds as version rc22 for ant builds

### ISSUE THREAD

**Issue by screenblaster** [oracle/opengrok#2144]
I just cloned from 6-5-2018 `https://github.com/oracle/opengrok.git` and build it should be rc27 but the version string `java -jar opengrok.jar -V`  reports as version rc22.  It might be that the `https://github.com/oracle/opengrok/blob/master/build.xml#L96` has not been updated to the rc27 version.

**Comment by vladak** [comment]
While this can be easily fixed, the ant builds are pretty much neglected in anticipation of #2032 which removes Ant support.

**Comment by vladak** [comment]
fixed in master
