### ISSUE TITLE
UI Error - Everything is displayed twice after searching for just 'e'

### ISSUE THREAD

**Issue by SchubP** [oracle/opengrok#2146]
Hi,
thanks for your very active and great work on a next OpenGrok release now! :-)

I just tried out your new demo server (http://demo.opengrok.org/) - looks and feels awesome! (y)

But I experienced an UI bug: If you select all provided projects and do a full text search for 'e' (I know this might not search might not be so useful, but nonetheless) you get everything twice on that page (some at the top some if you scroll down).
Here is a link to that search: http://demo.opengrok.org/search?project=elasticsearch&project=incubator-netbeans&project=intellij-community&project=lucene-solr&project=opengrok&q=e&defs=&refs=&path=&hist=&type=
![grafik](https://user-images.githubusercontent.com/23518402/41081722-3754b35e-6a2c-11e8-81ce-297f590fc983.png)
![grafik](https://user-images.githubusercontent.com/23518402/41081767-58e2f80a-6a2c-11e8-91de-b55d76a35de3.png)

**Comment by SchubP** [comment]
Hi,
thanks for the quick reply! Well, sorry for any inconveniences, I did search the issues for "twice" etc. but did not find anything matching in the open issues. My fault. But anyway, yes, you're right, it's now fixed in the demo! :-)
Cheers, Paul

**Comment by Orviss** [comment]
I was not able to find it either. Should this be reopened @vladak or can you please reference it? 

Either way, I was looking at it for a while and was not able to resolve it correctly. I don't have much experience in JSP but I was able to find this <https://stackoverflow.com/questions/2417047/how-to-catch-and-throw-errors-in-jsp> which says that it is not possible to redirect to error page when some of the JSP content is already written. So one solution might be to completely separate the business logic from JSP. (which is not an easy task :/ )

**Comment by vladak** [comment]
Pls open a new bug for this.

Dne čt 7. 6. 2018 22:33 uživatel Adam Hornáček <notifications@github.com>
napsal:
