### ISSUE TITLE
Browser's Back button doesn't goes back between anchors on the same page (Bugzilla #17555)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#215]
status CLOSED severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-12-06 15:48:13 +0000, Miroslav Osladil wrote:

> Steps to reproduce:
> 1. Search for some function
> 2. Select some result and jump into by line anchor
> 3. Click on the function on that line which switch you on the place where it is defined
> 4. Let's assume that it is the same file
> 5. Now, click on Back button in your browser
> 
> Expected result:
> You stay on the line by function anchor, after browser Back, page is back on line anchor.
> 
> Actual result:
> First Back action - nothing happens.
> Second Back action - you are back on search result
> 
> You can try to use attached file by opening sample.cpp# 68 and then by clicking on function().
> 
> Seems Windows affected only using IE7/FF3.6. I'm not able to reproduce it on Mac.
> 
> Used software:
> OpenGrok 0.10-rc, Apache Tomcat 6.0.29, Sun Java 6 1.6.0_20-b02, Debian GNU/Linux 5.0, IE

On 2010-12-09 12:15:08 +0000, Miroslav Osladil wrote:

> Oops, some network issue sends two same requests when filling bug. Marking as DUPLICATE of the second one which contains also an attachment.
> 
> I'm sorry.
> 
> **\* This bug has been marked as a duplicate of bug 17556 ***

**Comment by vjtayal08** [comment]
Hi Vladak,
Did you find the solution to this ?
I am also facing this issue.
can you please also share the link of original bug for which you have marked this duplicate ? 
Thanks

**Comment by tarzanek** [comment]
after back hit refresh button and browser will jump to proper anchor, this is an ancient firefox bug

**Comment by tarzanek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=565008

**Comment by vjtayal08** [comment]
Hi,
thanks for replying
I am still facing this issue on latest chrome,firefox and edge browser.Is there any way to fix this?

**Comment by tarzanek** [comment]
chrome(and edge?) should actually work, I think this was only on firefox
I only know a workaround - hit refresh (or ctrl+F5)
