### ISSUE TITLE
StringIndexOutOfBoundsException when searching definitions

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2187]
I get StringIndexOutOfBoundsException when I do search some strings in Definition.  Or, I get incorrect results (search shows incorrect results).  This issue occurs on 1.1-rc29/30.  I do not have this issue on 1.1-rc19.  Please look at the attached png file for more details.

![stringindexoutofboundsexception](https://user-images.githubusercontent.com/32307869/41982041-6758c37a-79f8-11e8-8f3c-920ecfe6a618.PNG)

**Comment by shyoshiz** [comment]
Additional information:

Until 1.1-rc22, one source file shows one result and shows [all...] if there are multiple results most of the time.  This issue does not exist.
On 1.1-rc23, one source file can show multiple results (more and 100?) and shows [all...].  This issue does not exist.
On 1.1-rc24, one source file shows maximum 10 results and shows [all...].  Then, this issue has started.

**Comment by vladak** [comment]
1.1-rc23 received new highlighter.

**Comment by vladak** [comment]
It would help if you could isolate the problem to a particular file causing this.

**Comment by shyoshiz** [comment]
Hi,
I found one file that triggers this issue and attached in the zip file.  Please take a look.

[toc.zip](https://github.com/oracle/opengrok/files/2201627/toc.zip)

**Comment by vladak** [comment]
In the archive there is this short JS code snippet:

```js
(function($) {
$.fn.toc = function(options) {
  var container = $(opts.container);
  var headings = $(opts.selectors, container);
  var headingOffsets = [];
  var activeClassName = opts.prefix+'-active';
};
})(jQuery);
```

After indexing new project containing just this file and trying to search for `error` in definitions in this project, the problem was not triggered.

**Comment by shyoshiz** [comment]
Please prepare source files set as test bed first then place the toc.js file (e.g. onto the project root).  For example, I downloaded Linux kernel source files from github (https://github.com/torvalds/linux/archive/master.zip) and placed the toc.js file like this (
![image](https://user-images.githubusercontent.com/32307869/43085737-b672eed8-8e69-11e8-8427-12838ac7f051.png)
).  Then, created index and deployed.

Here is the script I use:
`#!/bin/bash
export OPENGROK_PATH=/nobackup/scalexan/shyoshiz/opengrok/default
export PATH=$OPENGROK_PATH/bin:$PATH
export OPENGROK_TOMCAT_BASE=$CATALINA_HOME
export OPENGROK_INSTANCE_BASE=/nobackup/scalexan/shyoshiz/opengrok-work
export OPENGROK_CONFIGURATION=/nobackup/scalexan/shyoshiz/opengrok-work/etc
export PATH=$PATH:/usr/cisco/bin:/auto/tte/dsarisky/xmlposter
export OPENGROK_ENABLE_PROJECTS=true
export OPENGROK_WEBAPP_CFGADDR=none
CWD=`pwd`
cd ${OPENGROK_INSTANCE_BASE}/data
rm -rf *
cd ${OPENGROK_PATH}/bin
OpenGrok index
OpenGrok deploy
cd $CWD
`

I modified WEB-INF/web.xml file in source.war like this:
`        <param-name>CONFIGURATION</param-name>
        <param-value>/nobackup/scalexan/shyoshiz/opengrok-work/etc/configuration.xml</param-value>
        <description>Full path to the configuration file where OpenGrok can read it's configuration</description>`

At this point, unfortunately, my test environment got broken after several attempt and I now get this error (
![image](https://user-images.githubusercontent.com/32307869/43087924-f93d1b3a-8e6e-11e8-83f5-892471ee1d14.png)
) when I run this script.
So, I cannot provide actual sample problem screens but please note that most of the problems are wrong search results.  For example, if you search "error", most of results are correct but some results are wrong.  I mean no "error" keyword included in the results.  In my experience, 1 to 2 files have wrong results out of 10 files in one page.  (Just my feeling though.)  Sometimes, all results are correct in one page.  But, you can see wrong results maybe next page.  Or, you may see Java exception error stack trace for some source file on some page.  Please see this image (
![image](https://user-images.githubusercontent.com/32307869/43088621-96d22272-8e70-11e8-8280-dcf5d3348b7a.png)
).  This is not actual Linux kernel source but from my another test environment.  In this example, the second and the third files have wrong results.

**Comment by shyoshiz** [comment]
My test environment has recovered.  Here is the console log of the above script.  (
![image](https://user-images.githubusercontent.com/32307869/43093894-6b325dd0-8e7f-11e8-892e-fcb8271be2d1.png)
)  There is one exception.


On search results screen of "error", there is one wrong result (
![image](https://user-images.githubusercontent.com/32307869/43093997-bd3257c0-8e7f-11e8-83b7-3236a764a1e3.png)
) on the second page.

There is one wrong result (
![image](https://user-images.githubusercontent.com/32307869/43094107-0e855bf4-8e80-11e8-8872-53d5a1edc6a1.png)
) on 6th page.

Although there are some more wrong results, this is Java exception (
![image](https://user-images.githubusercontent.com/32307869/43094281-73c2d618-8e80-11e8-8079-200be503e4ab.png)
) on 10th page.

**Comment by vladak** [comment]
I don't think the `toc.js` file placed in the source root will make any difference. It will not be indexed together with the `linux-master` project so most probably cannot impact the search.

**Comment by vladak** [comment]
I wonder if the bad search happens also when you constrain the path to e.g. `macintosh` or `leds`.

**Comment by vladak** [comment]
Tried to reproduce this with above mentioned linux master zip and 1.1-rc33 to no avail - the search yields some 69 pages, I clicked through lots of them only to see correct results.

**Comment by vladak** [comment]
Also, you did not mention what Ctags version you are using, perhaps trying the latest Universal ctags could help ?

**Comment by shyoshiz** [comment]
Hi, I was using Exuberant Ctags 5.8 but I changed to Universal Ctags 0.0.0 then the problem fixed.  I'm going to test more on this and will close this if everything is OK.  Thank you for your help!

**Comment by shyoshiz** [comment]
Hi, I switched to the Universal Ctags and it runs as expected.  And, I think the OpenGrok now officially suggests for Universal Ctags, right?  Anyway, thank you for your help!

**Comment by tarzanek** [comment]
this means we need to officially drop ectags 5.8 ... or at least pronounce is deprecated and admit it can lead to errors ... (candidate for release notes headline)

**Comment by vladak** [comment]
I am all for removing Exuberant ctags support (see #2261). It causes more and more trouble, the chances that it will be revived are slim and it will simplify the code.
