### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by Orviss** [oracle/opengrok#2188]
After https://github.com/oracle/opengrok/pull/2184 is integrated, there should be a proper API documentation.

It would be best to use some existing tools, e.g.:
* <https://swagger.io>
* <https://apiary.io>

**Comment by vladak** [comment]
There is also http://stoplight.io/

**Comment by vladak** [comment]
Along with documentation, we should try to leverage the testing capabilities of these services (e.g. Apiary has https://github.com/apiaryio/dredd).

**Comment by vladak** [comment]
As for self-documenting API, see https://api.github.com/ , it gives a JSON of URLs.

**Comment by vladak** [comment]
https://github.com/oracle/opengrok/wiki/Web-services#endpoints will likely be superseded once this issue is addressed.

**Comment by vladak** [comment]
There is also a set of projects that auto-generate documentation from augmented Jersey annotations - https://simplapi.wordpress.com/2013/08/19/generating-documentation-for-java-jersey-framework/ however as one answer (could be viewed as extreme however there is probably a grain of truth in it) from https://stackoverflow.com/questions/1966243/restful-api-documentation says, the really interesting stuff cannot be auto-generated.

**Comment by vladak** [comment]
fixed in 480f365a8ae34761e1de09c704c1e27b4e64dc65
