### ISSUE TITLE
REST API can be reflected in the statistics

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2201]
Opengrok contains some sort of statistics for the web interface.

We should include or customize the statistics for REST API so it's more intuitive to read and investigate.

**Comment by vladak** [comment]
You mean make it available (see #2229) or actually record information about RESTful API calls in the `Statistics` ?

**Comment by tulinkry** [comment]
yes

**Comment by tulinkry** [comment]
I meant to make it available

**Comment by vladak** [comment]
Why close it then ?

Dne st 17. 10. 2018 10:14 uživatel Kryštof Tulinger <
notifications@github.com> napsal:

**Comment by tulinkry** [comment]
Because it is available under `api/v1/stats`

**Comment by tulinkry** [comment]
Or if you want to add the rest api usage into the statistics, reopen
