### ISSUE TITLE
Definition search malfunction

### ISSUE THREAD

**Issue by karel947** [oracle/opengrok#2224]
OpenGrok version v1.1-rc22, CentOS 7.4

When searching via Definition results are incorrect - pointing to the different file where there is not such a defined symbol. Issue seen in more than one instance of OpenGrok - different source codes. Always line 27 pointed out in source code. The searched symbol is in different file not included in result.

**Comment by vladak** [comment]
Can you isolate this to a small reproducible test case ?

Dne po 23. 7. 2018 17:48 uživatel karel947 <notifications@github.com>
napsal:

**Comment by karel947** [comment]
Unfortunately I can not. I work very unpredictably. When I have a few files I works fine. When I add another bunch of the files and reindex OpenGrok it start malfunction. Symbols which I was able to find before I could find after adding new files. When try the same approach with different files, Definition search finds symbol but after opening the file, symbol is not there. 
I cannot determine which file/s do that.

**Comment by vladak** [comment]
Does this happen for some projects or all of them ? Can you share more details about the setup ? (esp. how the indexer is run exactly)

**Comment by karel947** [comment]
I happens just for some projects. 

Ctag verison 5.8

Indexer run 
java -jar /data/opengrok/lib/opengrok.jar -W /data/opengrok/data/project/configuration.xml -c /bin/ctags -w project -P -S -v -s /data/local_src/project -d /data/opengrok/data/project/data  -i .jazz5   -i *.pdb -i *.dll -i *.exe -i *.pdf -i *.fm -i *.sdf -i *.doc -i *.xrml -i *.png -i *.bmp -i *.jpg -i *.gif -i *.ico -i *.ppt -i *.msi -i *.zip -i .git 

![bug](https://user-images.githubusercontent.com/12020277/43194321-5eacebd2-9002-11e8-8223-3ffbc1b33e07.png)

**Comment by vladak** [comment]
I see nothing wrong with how the indexer is run. Could you try replacing Exuberant ctags with the latest Universal ctags ? (reindex needed)

**Comment by mrashmiranjan** [comment]
Even I faced this problem. Using Universal ctags solved the issue.

**Comment by vladak** [comment]
Looks like the Exuberant ctags got confused by the content of the file(s). Maybe we should finally drop the support for Exuberant ctags ?

**Comment by sreehari83** [comment]
Am also facing same issue with definition search .Its giving wrong file

**Comment by karel947** [comment]
Thank you for all your effort, Installing universal ctags solved issue.
