### ISSUE TITLE
RESTful API endpoint for updating/creating statistics

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2229]
It should be possible to query/change statistics using the RESTful API.

**Comment by vladak** [comment]
Ah, thanks.

**Comment by tulinkry** [comment]
Just for completeness I'm adding a link to doc https://github.com/oracle/opengrok/wiki/Web-services#stats

**Comment by vladak** [comment]
Actually, according to the documentation it is not possible to create/change statistics using the RESTful API, so reopening.

**Comment by tulinkry** [comment]
The endpoint isn't working?

**Comment by vladak** [comment]
The `/stats` endpoint there, just not usable for updating/creating.

**Comment by vladak** [comment]
We do not actually want be able to change the meters externally, closing.
