### ISSUE TITLE
Info.getFullVersion not working correctly

### ISSUE THREAD

**Issue by gtoph** [oracle/opengrok#2253]
In the recent Maven integration, looks like a path is slightly off for the versioning information as it's returning 'unknown'.   Not exactly sure what the correct fix is, but made the changes below and that fixes it for now.

/opengrok-indexer/build.xml

 --  mkdir dir="${build.classes.dir}/org/opengrok"/>"
 ++ mkdir dir="${build.classes.dir}/org/opengrok/indexer"/>"

-- file="${build.classes.dir}/org/opengrok/info.properties">
++ file="${build.classes.dir}/org/opengrok/indexer/info.properties">

**Comment by Orviss** [comment]
Yes, that solves the issue :) 

Can you create a PR? :)

If not I can do it.

**Comment by gtoph** [comment]
Welp, I'm not a contributer, and well no clue how to go about that anyway.  So I guess I'll let you have the honor :)
