### ISSUE TITLE
get rid of 3rd party jrcs code

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2258]
When going through Sonar results, I noticed lots of problems inside the `jrcs` module. This is in fact `org.apache.commons.jrcs` code, i.e. 3rd party code.

It should be possible to install it as dependency using Maven, i.e.:
  - `org.suigeneris.jrcs.diff`
  - `org.suigeneris.jrcs.rcs`

Both from `org.jvnet.hudson`.

**Comment by Orviss** [comment]
This is not that simple because those versions are outdated and OpenGrok has done some modifications to the `jrcs` module since then. Also, there is an update from the author on BitBucket which went completely different way.

I played with it a little here <https://gitlab.com/ahornace/jrcs/tree/develop> but it still does not contain OpenGrok's changes. I wanted to do that but didn't get to it and I'm wondering if it is worth it.

**Comment by vladak** [comment]
I tried making the conversion in vladak/OpenGrok:jrcs and hit a road block in the form of code in `RCSRepository.java`:

```
            // A comment in Archive.getRevisionNodes() says that it is not
            // considered public API anymore, but it works.
            for (Node n : archive.getRevisionNodes()) {
                String rev = n.getVersion().toString();
                String author = n.getAuthor();
                a.addLine(rev, author, true);
            }
```

Guess what, the `org.jvnet.hudson` classes do not have this private API anymore.

**Comment by vladak** [comment]
I also found https://github.com/tarzanek/jrcs which seems like a code dump.

**Comment by vladak** [comment]
In overall, the motivation is strong I think - get rid of 3rd party binaries/code from our code base. It causes problems with checks and is hard to maintain.

**Comment by vladak** [comment]
Or, given the state of the libraries, we might just bite the bullet and get rid of Java code accessing the RCS archives and replace it with `Executor` on top the `rcs`, `rcsdiff` command line utilities.

**Comment by vladak** [comment]
The `diff` portion (used mostly by the webapp) will be still usable I think.

**Comment by vladak** [comment]
The annotate functionality should be possible to get via the `blame` command, at least on Debian/Ubuntu where it is available via the `rcs-blame` package.

**Comment by vladak** [comment]
Also, the top level comment of the `org.suigeneris.jrcs.rcs.Archive` class (https://github.com/tarzanek/jrcs/blob/master/src/java/org/suigeneris/jrcs/rcs/Archive.java) which is heavily used in RCS repository handling code says:

> This class is NOT thread safe.

which makes it not very usable for our purposes.

**Comment by vladak** [comment]
The `getRevisionNodes()` method mentioned above was introduced in cset  381a9b85 (titled `Local changes to JRCS by Gustav Gunnarsson`) and seems to be used specifically to get annotation support for RCS. Replacing this with `blame` command parsing should do the job.
