### ISSUE TITLE
for cycle in RepositoryDateFormat#format() does not loop

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2278]
Looks like this method:

```
        @Override
        public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
            for (DateFormat formatter : formatters) {
                return formatter.format(date, toAppendTo, fieldPosition);
            }
            return toAppendTo.append("(date null)");
        }
```

needs to catch exceptions as documented on https://docs.oracle.com/javase/7/docs/api/java/text/Format.html#format(java.lang.Object,%20java.lang.StringBuffer,%20java.text.FieldPosition) similarly to what the `parse()` method does.

Also, there is https://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#format(java.util.Date) with different signature that should probably be overridden too ?

**Comment by tulinkry** [comment]
`public StringBuffer format` this method is not used as far as I know but the interface needs it to be implemented.
the trick with multiple formatters here we used just to convert the repository date to `ju.Date`

**Comment by tulinkry** [comment]
`public abstract Date parse(String source, ParsePosition pos)` should call `parse` with the position set to the beginning of the string, that's why the implementation is only in the `parse` method

**Comment by vladak** [comment]
Ok, so maybe implement these methods as dummy and let them throw `java.lang.UnsupportedOperationException` ?

**Comment by tulinkry** [comment]
Yes. Definitely better solution.
