### ISSUE TITLE
Copy of snippet of code without line number (Bugzilla #17972)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#228]
status CLOSED severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

On 2011-03-05 16:00:59 +0000, Olivier Catteau wrote:

> When you copy a piece of code by using OpenGrok, you also copy line numbers. So when you paste the copied code in an editor, you have to remove all line numbers.
> 
> It would be really usefull to copy lines without line numbers such like Google code browser.
> For exemple : http://code.google.com/p/mtjtrader/source/browse/trunk/code/src/forex/auto/trade/ui/CandleChart.java?spec=svn3&r=3
> 
> Thanks.

On 2011-03-06 20:36:54 +0000, Lubos Kosco wrote:

> Hi Olivier
> there is a button called "Line #"
> which can disable line # and you can copy & paste the code ;)
> 
> give it a try, if it doesn't fit your use case, please let me know and change this bug back to new state
> 
> if it does, please close this bug
> 
> cheers
> L

On 2011-03-06 22:34:29 +0000, Olivier Catteau wrote:

> Oh sorry, I have used regularly OpenGrok since 5 years and I didn't notice the button... That does the job.
> 
> Thanks a lot !
> 
> (In reply to comment # 1)
> 
> > Hi Olivier
> > there is a button called "Line #"
> > which can disable line # and you can copy & paste the code ;)
> > 
> > give it a try, if it doesn't fit your use case, please let me know and change
> > this bug back to new state
> > 
> > if it does, please close this bug
> > 
> > cheers
> > L

**Comment by byxor** [comment]
It'd be nice if this was easy to do without disabling line numbers.

**Comment by cybertk** [comment]
This issue still exists in latest version v1.0
