### ISSUE TITLE
Missing git history

### ISSUE THREAD

**Issue by fstefanov** [oracle/opengrok#2286]
I'm missing history for 13 repositories
in logs for all of them i see:
FINER t6074 IndexDatabase.accept: ignoring <full_path>
no folders in historycache/
OPENGROK_VERBOSE=true does not print anything additional
grok version 1.0

**Comment by vladak** [comment]
Do you have other git repositories that do have history present ?

Dne pá 10. 8. 2018 3:15 uživatel Filip Stefanov <notifications@github.com>
napsal:

**Comment by fstefanov** [comment]
Yep i have 500+ repos AOSP code base, just these 13 does not have.

**Comment by vladak** [comment]
So, there must be something special about these repositories. Could you
share some details about them ? (where they are placed w.r.t. source root,
can you run git log in them that produces meaningful output, any more
context from the indexer logs)

Dne pá 10. 8. 2018 9:18 uživatel Filip Stefanov <notifications@github.com>
napsal:

**Comment by fstefanov** [comment]
Found it
OPENGROK_SCAN_DEPTH=4
They all are at 5+ :)
