### ISSUE TITLE
Blocked in “18:16:05 严重: CTag reader cycle was interrupted!”

### ISSUE THREAD

**Issue by bidjc** [oracle/opengrok#2287]
version: 1.1 r33

18:16:05 警告: CTags parsing problem:
java.lang.StringIndexOutOfBoundsException: String index out of range: 1030
...
...
18:16:05 严重: CTag reader cycle was interrupted!

Blocked in " CTag reader cycle was interrupted!",and unable to recover.

**Comment by vladak** [comment]
What ctags are you using ?

Dne pá 10. 8. 2018 3:42 uživatel bidjc <notifications@github.com> napsal:

**Comment by bidjc** [comment]
Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct  7 2014, 13:52:37
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

**Comment by vladak** [comment]
Try using Universal ctags instead.

Dne pá 10. 8. 2018 9:18 uživatel bidjc <notifications@github.com> napsal:

**Comment by bidjc** [comment]
done,TKS@ vladak
