### ISSUE TITLE
Old IndexAnalysisSettings should be removed

### ISSUE THREAD

**Issue by Orviss** [oracle/opengrok#2290]
I believe that before release the old deprecated `IndexAnalysisSettings` should be removed and replaced by `IndexAnalysisSettings2`.

The whole reindex will be needed so I think it is the best time to do it.

**Comment by vladak** [comment]
Time to do it before 1.1 release then.

**Comment by vladak** [comment]
Incidentally, I hit the problem with the `IndexAnalysisSettings` after deploying the changes that happened after the mavenize restructuring. I did not reindex and when searching an exception was thrown as a result of failure to de-serialize `IndexAnalysisSettings`.
