### ISSUE TITLE
PLSQL search by definition 

### ISSUE THREAD

**Issue by pioro** [oracle/opengrok#2293]
Hello,

I have a problem with PL/SQL code in opengrok. When I'm trying to index PL/SQL files
all looks good but I can search procedures/function/packages only using full search not a definition one.
It's works OK for table - all tables are indexed and searchable by definition.
ctags are displaying all lines with PL/SQL types like this

$ /usr/bin/ctags --sql-kinds=+l --langmap=sql:+.pkb --langmap=sql:+.PKB /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB

$ cat tags
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.8     //
CHILD   /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PIORO".CHILD AS$/;"       P
func    /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  function func returning number as$/;"       f
sec     /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure sec AS$/;"        p
third   /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure third as$/;"      p

It would be nice to search by definition so if you click in code on function/procedure name, search actually return all places where it exist.

Is this expected behavior or a bug in code ? 

regards,
Marcin

**Comment by vladak** [comment]
Have you tried Universal ctags if it makes any difference ?

**Comment by pioro** [comment]
Hello,

Yes I tested it with ctags compiled today from source

$ ./ctags --version
Universal Ctags 0.0.0(794d7db), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 13 2018, 07:26:08
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory

The are two changes:

- errors while generating index

$ /home/oracle/opengrok-1.1-rc33/bin/OpenGrok index /home/oracle/plsql1/
Loading the default instance configuration ...
WARNING: OpenGrok generated data path /var/opengrok/data doesn't exist
  Attempting to create generated data directory ...
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "clojure" already defined
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "rust" already defined
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "clojure" already defined
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "rust" already defined
10:22:20 WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined
10:22:20 WARNING: Error from ctags: => , t: 7, k: -1

- diff between tags file generated manually 
`$ diff tags_ctags tags
3,6c3,7
< !_TAG_PROGRAM_AUTHOR  Darren Hiebert  /dhiebert@users.sourceforge.net/
< !_TAG_PROGRAM_NAME    Exuberant Ctags //
< !_TAG_PROGRAM_URL     http://ctags.sourceforge.net    /official site/
< !_TAG_PROGRAM_VERSION 5.8     //
---
> !_TAG_OUTPUT_MODE     u-ctags /u-ctags or e-ctags/
> !_TAG_PROGRAM_AUTHOR  Universal Ctags Team    //
> !_TAG_PROGRAM_NAME    Universal Ctags /Derived from Exuberant Ctags/
> !_TAG_PROGRAM_URL     https://ctags.io/       /official site/
> !_TAG_PROGRAM_VERSION 0.0.0   /794d7db/
8,10c9,11
< func  /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  function func returning number as$/;"       function
< sec   /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure sec AS$/;"        procedure
< third /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure third as$/;"      procedure
---
> func  /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  function func returning number as$/;"       function        package:CHILD
> sec   /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure sec AS$/;"        procedure       package:CHILD
> third /home/oracle/plsql1/PIORO1/PACKAGE_BODY/CHILD.PKB       /^  procedure third as$/;"      procedure       package:CHILD`



So actually new version release that procedure and function are part package which wasn't a case before,
but I still can't search using definition - search with this URL - /source/s?defs=CHILD&project=PIORO1
return: Your search defs:CHILD did not match any files. 

Doing a full text searching for table name - return a file list but also there is word table - which is a type definition, searching for ex. sec in full text mode returning a file and lines but there is no information that procedure sec is a actual procedure.

regards,
Marcin

**Comment by vladak** [comment]
The warnings emitted during reindex are inncuous.

OpenGrok is dependent on ctags to produce list of definitions. Could you produce minimalistic isolated example of a function definition in PLSQL ?

**Comment by pioro** [comment]
Hello,

I did a following tests:

1. simple function definition - fun_test.sql file attached - works as expected - I can find function via definition

2. simple procedure definition - proc_test.sql file attached - works as expected - I can find procedure via definition

3. Package spec and body - child.pks and child.pkb attached - it doesn't work as expected - procedures and functions inside package body or spec are not recognized even if ctags is recognizing it as functions and procedures and also it's able to add a package scope - tags file attached.

[opengrok.zip](https://github.com/oracle/opengrok/files/2286354/opengrok.zip)

regards,
Marcin

**Comment by pioro** [comment]
Hello,

I'm not sure if this is a ctags issue. Maybe I wasn't clear in my comment but i can see correct tags generated by ctags and use them with vim. Indexer is not picking it up.

regards,
Marcin

**Comment by pioro** [comment]
Thanks

**Comment by tulinkry** [comment]
Currently tried this and it looks this works with current master (post 1.2.1).

<img width="614" alt="screenshot 2019-02-17 at 19 43 26" src="https://user-images.githubusercontent.com/6997160/52917477-59b1b580-32ec-11e9-8bcf-bdee94546864.png">

**Comment by pioro** [comment]
Hi,

I can confirm - it's working now.
I'm sorry guys - I forgot that this issue was still opened.

I think it was working before as well but I struggle with Tomcat cache.
Please close it now.

regards,
Marcin
