### ISSUE TITLE
enable AppVeyor for builds

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2300]
While Windows builds on Travis would be nice, the support for them in Travis might or might not be added in the future (https://github.com/travis-ci/travis-ci/issues/2104). The AppVeyor seems to be the go to platform used for Windows builds and it should be possible to run Java builds there - https://www.appveyor.com/docs/build-environment/ as it has JDK, Maven, Git.

**Comment by vladak** [comment]
Done.

**Comment by 0xfeeddeadbeef** [comment]
@vladak [AppVeyor build status badge](https://www.appveyor.com/docs/status-badges/) in README.md would look nice.

**Comment by vladak** [comment]
Well, yes. Except it is currently failing :)

Dne st 15. 8. 2018 23:33 uživatel George Chakhidze <notifications@github.com>
napsal:
