### ISSUE TITLE
Error: directory '<directory-name>' exists and is a directory, but cannot be listed: list() returned null. (Bugzilla #18098)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#231]
status CLOSED severity _blocker_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Lubos Kosco

On 2011-03-29 06:32:59 +0000, Sreedhara Reddy D wrote:

> Once the open file limit is exceeded the following message is displayed to the user:
> 
> Error: directory '<directory-name>' exists and is a directory, but cannot be listed: list() returned null.
> 
> So the users are unable to make use of OpenGrok.
> 
> I am running OpenGrok 0.10 release.
> 
> OS and other configuration:
> "uname -a" command output.
> Linux opengrok 2.6.18-164.el5 # 1 SMP Thu Sep 3 03:28:30 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
> 
> What has to be done in this case? So that I can get rid of this issue immediately. Could you please help me out immediately.
> 
> Regards
> Sreedhara Reddy D

On 2011-04-12 12:34:06 +0000, Lubos Kosco wrote:

> have you tried e.g.
> http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
> 
> ?

On 2011-05-10 08:02:40 +0000, Trond Norbye wrote:

> Do you have a leakage of file-descriptors? (is it growing over time?), if so please reopen the bug. 
> 
> If that isn't the case you need to set the allowed number of filedescriptor to match your deployment.

**Comment by dhireng** [comment]
sounds like a defect. Is this closed because it is fixed?

**Comment by tarzanek** [comment]
@dhireng because it was a config problem
we never saw such thing on Solaris ;)
(but yes, I saw this on linux occasionally, but with different java apps than opengrok)
