### ISSUE TITLE
Facing an issue with setting a new configuration.xml file

### ISSUE THREAD

**Issue by adarsh200496** [oracle/opengrok#2314]
Hey guys!

I'm using OpenGrok 1.0, JDK 1.8.0_181, OS - CentOS 5.7 and have the following issue -

I have 2 indices A and B. PFA the structure of the src files of indices A and B

#########################################################
<img width="500" alt="capture" src="https://user-images.githubusercontent.com/42631985/44508840-5e930500-a6cd-11e8-89bb-ad2e8dc14588.PNG">

What I want to do -
1) I am maintaining 2 indices. I want to re-index   B, and then ask   A   to use   B's   configuration.xml for doing the searches.

What I am doing - 
1) I index both   A   and   B.
2) Then, I send a ConfigMessage using “setconf” to poke A and tell it to start using   B's   configuration.xml.
3) The command is used is - ./Messages -v -s <server> -p <port> -n config "setconf" A/etc/configuration.xml.
4) I have also tried - ./Messages -v -s <server> -p <port> -n config "setconf" B/etc/configuration.xml.
5) The src and data directories get updated correctly in the tomcat webapps/A/WEB-INF/web.xml, but I I’m facing the below mentioned problem.

The Error - 
1) When I do a search query, it is searching in B/dev/**A**/<other files>, whereas I want it to ideally search in B/dev/**B**/<other files>

What I know –
1) When I index, the method used is writeConfiguration(), which I think internally sends a ConfigMessage.
2) When I try to send a Message to   A  using “setconf” to start using   B’s  configuration.xml, the method used is applyConfiguration().
3) I believe this might be some kind of caching issue which I am not able to locate and resolve.
4) After restarting the Tomcat server, everything works perfectly fine. I need a way for the changes to reflected **WITHOUT** having to restart the server every time there is a change in index B. :/   

Any kind of help or a direction to look in would be greatly appreciated.

Thanks, and have a great time guys! :)

**Comment by adarsh200496** [comment]
First time user of GitHub, so please pardon me if I'm doing something wrong. :)

**Comment by vladak** [comment]
You did not say how exactly is the indexer run or what is actually your use case.

Anyhow, the location of data used by the webapp is stored in the `dataRoot` property in the configuration file. The data root (as specified with the -d option) is written into the configuration file at the end of the indexing (if the -W option is used). So, either you will need to modify the configuration file or set the property itself (via another Message, or rather RESTful API call in the latest versions) after that.

**Comment by vladak** [comment]
closing as a dup of #2354
