### ISSUE TITLE
indexer parameter "-e" (--economical) shows only blank pages when running indexer without -H

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2316]
When I create index with -e (--economical) parameter, I can see file list correctly.  However, when I click the source file to see the contents, only blank page is displayed.

**Comment by vladak** [comment]
Confirmed on the latest master (cset 31256c90e23def96ac9b26214b043921cf804c84)

**Comment by shyoshiz** [comment]
I think this issue is not fixed yet on both 1.1-rc39/1.1-rc40.  When I click the source file to see the contents, it shows blank page.  No xref is generated.  Please let me know how can I help to get more detail info.  Here is my usage (note:  I don't use default source/data location.):

`  indexer.py -C -D \
      -j ${JAVA_HOME}/bin/java \
      -J=-Djava.util.logging.config.file=${OPENGROK_INSTANCE_BASE}/logging.properties \
      -J=-Djava.io.tmpdir=/opt/pisces/opengrok-test/tmp \
      -J=-Xmx40960m -J=-Xms20480m -J=-server -J=-d64 \
      -a ${OPENGROK_LIB}/opengrok.jar \
      -- -P \
      --verbose --depth 24 -r off -m 256 -e \
      -c ${OPENGROK_CTAGS} \
      -s ${OPENGROK_INSTANCE_BASE}/src \
      -d ${OPENGROK_INSTANCE_BASE}/data \
      -W ${OPENGROK_CONFIGURATION}/configuration.xml
  deploy.py -D \
      -c ${OPENGROK_CONFIGURATION}/configuration.xml \
         ${OPENGROK_LIB}/source.war \
         ${OPENGROK_TOMCAT_BASE}/webapps`

**Comment by vladak** [comment]
Actually, you are indexing without creating history cache (there is no -H option used) so in `list.jsp` this will go to the else branch first in order to get the redirect (so that the latest revision will appear in the URL):

```java
345     } else {
346         // requesting cross referenced file
347         File xrefFile = null;
348 
349         // Get the latest revision and redirect so that the revision number
350         // appears in the URL.
351         String location = cfg.getLatestRevisionLocation();
352         if (location != null) {
353             response.sendRedirect(location);
354             return;
355         } else {
356             xrefFile = cfg.findDataFile();
357         }
358 
359         if (xrefFile != null) {
360 %>
361 <div id="src" data-navigate-window-enabled="<%= navigateWindowEnabled %>">
362     <pre><%
363             boolean compressed = xrefFile.getName().endsWith(".gz");
364             Util.dumpXref(out, xrefFile, compressed, request.getContextPath());
365     %></pre>
366 </div><%
367         }
368     }
```

where `cfg.getLatestRevisionLocation()` will return `null` on line 351 because `PageConfig#getLatestRevision()` starts with:

```java
1224      protected String getLatestRevision() {
1225          if (!getEnv().isHistoryEnabled()) {
1226              return null;
1227          }
```

The call to `cfg.findDataFile()` will also return `null` because you are running in the economy mode and thus empty page body will be displayed.

**Comment by vladak** [comment]
`Configuration` has two members:

```java
113      /**
114       * Should the history log be cached?
115       */
116      private boolean historyCache;

...


122      /**
123       * flag to generate history. This is bigger hammer than @{code historyCache}
124       * above. If set to false, no history query will be ever made and the webapp
125       * will not display any history related links/allow any history queries.
126       */
127      private boolean historyEnabled;
```

There is currently no way how to turn off just the history cache from indexer after the changes for #32.
The comment https://github.com/oracle/opengrok/issues/32#issuecomment-310743355 explains why the change was made - basically it would make the indexing too slow because it would fetch the history of each file individually in the 2nd phase of indexing.

**Comment by shyoshiz** [comment]
I confirmed that the issue is fixed with 1.1-rc41 (without -H).  Thank you very much for your prompt action!
I just have simple question.  I notice that xref/ directory is not created under data/ with this -e.  I thought the xref/ directory will be automatically created when the source code is accessed.  But, actually it seems not.  So, my question is that what is this xref/ directory?  It will be created on only History mode?

**Comment by vladak** [comment]
As it is implemented now, econony mode means no xref will ever be generated
(to save disk space).

Dne pá 7. 9. 2018 19:57 uživatel shyoshiz <notifications@github.com> napsal:

**Comment by vladak** [comment]
Xrefs (from cross-referencing) are the HTML pages you see when browsing
code.

Dne pá 7. 9. 2018 22:25 uživatel shyoshiz <notifications@github.com> napsal:

**Comment by shyoshiz** [comment]
I'm very sorry to ask many times but I still don't understand regarding xref.  Now, my test branch does not have xref under data due to -e parameter.  Then, I can browse all source code without xref.  Also, when I click any keywords, I can see all cross reference list without xref.  To me, it looks like OpenGrok simply does not use xref.  The reason I stick this item because I want to save workspace disk space without impacting any functionality to existing our users.

**Comment by vladak** [comment]
It is quite simple, in economy mode xrefs are always generated on demand.
It is very much the same process I believe as if they were generated during
reindex. They are just not stored on disk. The functionality should be the
same except a bit slower.

Dne po 10. 9. 2018 20:06 uživatel shyoshiz <notifications@github.com>
napsal:

**Comment by shyoshiz** [comment]
That totally makes sense to me.  Thank you so much for your response!!!
