### ISSUE TITLE
URI-size when "select all" is used...

### ISSUE THREAD

**Issue by grajsor** [oracle/opengrok#2349]
Is it possible to NOT list every project when "select all" is used and use some flag instead? It's expensive and looks horrible in logs -- not to mention 98% of all searches are done using "select all"... 

We have ~500 projects and the URI is almost 40k (!!!) and had to poke both in tomcat and firewall, due to size constraints in default settings, to make it work. 

When people just want to select a "few projects", they do just that... Why SPAM everything when "select all" is used? Please consider this change...

**Comment by vladak** [comment]
This is a dup of #1357. There is a PR open for this #1621 however has not been touched in a while so likely will be closed.
