### ISSUE TITLE
File Path index/search works

### ISSUE THREAD

**Issue by Lokendra-Saini** [oracle/opengrok#2351]
Hello All,

I am using Opengrok1.0. 

I am trying to understand how the File path indexing and searching works.
When I search for _**". py"**_ it searches _**path:". py"**_ and lists the files with .py extension. (Note that there is a space after dot).
And for _**".py"**_ it searches _**path:.py**_ and doesn't give any results. (No space after dot).

Want to understand how the space makes a difference in the search.

Thanks in advance!! :-)

**Comment by vladak** [comment]
The path is tokenized using the `.` and `/` separators. So when searching for `.py` you are searching for a token that could not exist while searching for `. py` you are searching for 2 tokens - `.` and `py`. The way most people perform path suffix searches is to use proximity search, e.g. `". py"~1`
