### ISSUE TITLE
Using separate configuration files and sources to index and update a single application

### ISSUE THREAD

**Issue by adarsh200496** [oracle/opengrok#2354]
Hello experts!

I'm using OpenGrok 1.0, JDK 1.8.0_181, OS - CentOS 5.7

I have an index named custom6. This is what the directory structure looks like - 

![image](https://user-images.githubusercontent.com/42631985/45413966-fb770b80-b697-11e8-87e0-fb415cf9486e.png)

Contents of OpenGrok.sh1:

OPENGROK_INSTANCE_BASE=var/custom6/base1
OPENGROK_WEBAPP_CONTEXT=custom6
OPENGROK_WEBAPP_CFGADDR=localhost:2437
REMOTE_PORT_NUM=2437

Contents of OpenGrok.sh2:

OPENGROK_INSTANCE_BASE=var/custom6/base2
OPENGROK_WEBAPP_CONTEXT=custom6
OPENGROK_WEBAPP_CFGADDR=bg-nvgrok-dev:2437
REMOTE_PORT_NUM=2437

There is only 1 application deployed on tomcat, namely custom6.war and both OpenGrok.sh1 and OpenGrok.sh2 are trying to work with this application. Base1 and Base2 have almost similar src directory (The only difference being base1 has " code/1.0 " and base 2 has " code/2.0 ". Please refer to the image above.)

Command used to index (using OpenGrok.sh1 and base1): 
env OPENGROK_CONFIGURATION=var/custom6/OpenGrok.sh1 var/OpenGrok-1.0/OpenGrok index

Indexing goes well, and everything works perfectly fine. I am able to query anything without facing any errors.

Then, when I try to index using OpenGrok.sh2 and base 2, 
Command used to index (using OpenGrok.sh2 and base2): 
env OPENGROK_CONFIGURATION=var/custom6/OpenGrok.sh2 var/OpenGrok-1.0/OpenGrok index

I get the below stated error:

<Start of error>
There was an error!
var/custom6/base2/src/code/1.0/A (No such file or directory)

java.io.FileNotFoundException: /var/custom6/base2/src/code/1.0/A (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.opensolaris.opengrok.search.Results.prettyPrint(Results.java:236)
	at org.apache.jsp.search_jsp._jspService(search_jsp.java:799)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opensolaris.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.opensolaris.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at com.nvidia.realm.SecurityValve.invoke(SecurityValve.java:139)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
<End of error>

What I notice is - when I index using OpenGrok.sh2, the SRC_ROOT ( var/custom6/base2/src ) gets updated perfectly fine, however, the - 
" code/1.0/A " does not get updated to " code/2.0/A ", which means the file path is being cached somewhere. Which is causing issue for me and I would like this to not happen. Redeploying or restarting the server solves this issue, but I can not do that.

What I would like to do:
When I index using OpenGrok.sh1, I want to index and search ONLY the contents of base1. When I index using OpenGrok.sh2, I want to index and search ONLY the contents of base2, and want nothing to do whatsoever with the contents of base1 ( basically, I mean I dont want " code/1.0/A "  to be cached anywhere) 

What I would like to know:
Why is this happening? How can I avoid this? If this cannot work as I want it to, is there a work around that can reproduce what I am trying to do?

Looking forward to hearing from you and resolving this problem. :)

Thanks, and have a great day!

**Comment by adarsh200496** [comment]
Hi guys! Any kind of help, or any direction to look into would be great.

Please do help me out. :)

**Comment by adarsh200496** [comment]
Yes bang on! It works when I have 2 different webapps or when I restart the server after changing the base

**Comment by adarsh200496** [comment]
> I think you need to run 2 web apps, or have only one running at a time. The indexer gets the base at runtime as you have done, but the webapp gets the base at the startup. Does your config work if you have 2 different webapps or restart tomcat after changing base?

Startup of what exactly? The server or Opengrok First Index?

Thanks

**Comment by vladak** [comment]
This looks like a dup of #2314. You need to say what is your goal/use case first to receive a meaningful answer. Why do you have 2 OpenGrok setups and just one web application ?

**Comment by vladak** [comment]
I think I can see what you're trying to do - basically have 2 separate OpenGrok instances (meaning separate source+data+configuration) and 1 web application with the ability to switch the between the 2. This should be doable. It is not clear to me why `OPENGROK_WEBAPP_CFGADDR` differs in the 2 scripts.

**Comment by vladak** [comment]
Also, `OPENGROK_INSTANCE_BASE` should be absolute path, it seems to be missing the leading slash.

**Comment by vladak** [comment]
Another thing is that it is not clear how exactly the error was triggered. It comes from search JSP - what the search URL looked like ?

**Comment by vladak** [comment]
Also, what is the value of the `CONFIGURATION` parameter in your `WEB-INF/web.xml` file ?

**Comment by vladak** [comment]
I did a small experiment with 1.1-rc41:
  - created `/var/tmp/OG1` and `/var/tmp/OG2`. This is how the tree structures look (after reindex):
```
/var/tmp/OG1
├── data
│   ├── historycache
│   │   └── foo
│   ├── index
│   │   └── foo
│   ├── suggester
│   │   └── foo
│   └── xref
│       └── foo
└── src
    └── foo

/var/tmp/OG2
├── data
│   ├── historycache
│   │   └── bar
│   ├── index
│   │   └── bar
│   ├── suggester
│   │   └── bar
│   └── xref
│       └── bar
└── src
    └── bar
```
  - deployed the web app:
```
/var/tmp/opengrok-1.1-rc41/bin/deploy.py -c /var/tmp/configuration.xml \
    /var/tmp/opengrok-1.1-rc41/lib/source.war ~/apache-tomcat-8.0.27/webapps/source.war
```
  - started Tomcat
```
~/apache-tomcat-8.0.27/bin/startup.sh
```
  - indexed first instance:
```
/var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
    -s /var/tmp/OG1/src -d /var/tmp/OG1/data -W /var/tmp/configuration.xml \
    -U http://localhost:8080/source -P -H -S
```
  - tried search within the `foo` project
  - indexed 2nd instance:
```
/var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
    -s /var/tmp/OG2/src -d /var/tmp/OG2/data -W /var/tmp/configuration.xml \
    -U http://localhost:8080/source -P -H -S
```
  - tried search within the `bar` project

Both searches worked fine.

**Comment by adarsh200496** [comment]
> I did a small experiment with 1.1-rc41:
> 
> * created `/var/tmp/OG1` and `/var/tmp/OG2`. This is how the tree structures look (after reindex):
> 
> ```
> /var/tmp/OG1
> ├── data
> │   ├── historycache
> │   │   └── foo
> │   ├── index
> │   │   └── foo
> │   ├── suggester
> │   │   └── foo
> │   └── xref
> │       └── foo
> └── src
>     └── foo
> 
> /var/tmp/OG2
> ├── data
> │   ├── historycache
> │   │   └── bar
> │   ├── index
> │   │   └── bar
> │   ├── suggester
> │   │   └── bar
> │   └── xref
> │       └── bar
> └── src
>     └── bar
> ```
> * deployed the web app:
> 
> ```
> /var/tmp/opengrok-1.1-rc41/bin/deploy.py -c /var/tmp/configuration.xml \
>     /var/tmp/opengrok-1.1-rc41/lib/source.war ~/apache-tomcat-8.0.27/webapps/source.war
> ```
> * started Tomcat
> 
> ```
> ~/apache-tomcat-8.0.27/bin/startup.sh
> ```
> * indexed first instance:
> 
> ```
> /var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
>     -s /var/tmp/OG1/src -d /var/tmp/OG1/data -W /var/tmp/configuration.xml \
>     -U http://localhost:8080/source -P -H -S
> ```
> * tried search within the `foo` project
> * indexed 2nd instance:
> 
> ```
> /var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
>     -s /var/tmp/OG2/src -d /var/tmp/OG2/data -W /var/tmp/configuration.xml \
>     -U http://localhost:8080/source -P -H -S
> ```
> * tried search within the `bar` project
> 
> Both searches worked fine.


Hi, thanks for your kind response. :)
Please follow the above steps with the below mentioned directory structure of src. I think you will get an error.

If there is no error, I will stop bugging you guys, I'm sure you guys are all very busy.  😖 

/var/tmp/OG1
├── data
│   ├── historycache
│   │   └── foo
│   ├── index
│   │   └── foo
│   ├── suggester
│   │   └── foo
│   └── xref
│       └── foo
└── src
    └── foo
        └── 1.0
            └── Hello.txt (Contents - Hello)

/var/tmp/OG2
├── data
│   ├── historycache
│   │   └── foo
│   ├── index
│   │   └── foo
│   ├── suggester
│   │   └── foo
│   └── xref
│       └── foo
└── src
    └── foo
        └── 2.0
            └── Hello.txt (Contents - Hello)

**Comment by vladak** [comment]
You need to fix or respond to the problems found first - the missing absolute path, discrepancy in the webapp address etc.

Also, it is worth trying the latest gratest version of OpenGrok.

**Comment by adarsh200496** [comment]
> I think I can see what you're trying to do - basically have 2 separate OpenGrok instances (meaning separate source+data+configuration) and 1 web application with the ability to switch the between the 2. This should be doable. It is not clear to me why `OPENGROK_WEBAPP_CFGADDR` differs in the 2 scripts.

They should not be different, they're the same. That was an error on my  part, which I have fixed now.



> Also, `OPENGROK_INSTANCE_BASE` should be absolute path, it seems to be missing the leading slash.

Yeah, I am using the absolute path /home/path/to/index/base1 and /home/path/to/index/base2


> Also, what is the value of the `CONFIGURATION` parameter in your `WEB-INF/web.xml` file ?

/home/path/to/index/base1/etc/configuration.xml

**Comment by vladak** [comment]
The `CONFIGURATION` pointing to one instance only can be problematic (even though the configuration is sent to the web app at the end of the indexing via Message) because if the last indexer run was for the 2nd instance and Tomcat is restarted it will load the 1st one. Other than that I don't see a problem.

**Comment by vladak** [comment]
As for the directory structure, the sub-directories should not matter. Could you try with the latest 1.1 RC ?

**Comment by vladak** [comment]
Trying with the sub-directories:

  - created `/var/tmp/OG1` and `/var/tmp/OG2`:
```
rm -rf /var/tmp/OG[12]
mkdir -p /var/tmp/OG{1,2}/{src,data}
mkdir /var/tmp/OG1/src/1.0
echo Hello > /var/tmp/OG1/src/1.0/Hello.txt
mkdir /var/tmp/OG2/src/2.0
echo Hello > /var/tmp/OG2/src/2.0/Hello.txt
```
  - deployed the web app:
```
/var/tmp/opengrok-1.1-rc41/bin/deploy.py -c /var/tmp/configuration.xml \
    /var/tmp/opengrok-1.1-rc41/lib/source.war ~/apache-tomcat-8.0.27/webapps/source.war
```
  - started Tomcat
```
~/apache-tomcat-8.0.27/bin/startup.sh
```
  - indexed first instance:
```
/var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
    -s /var/tmp/OG1/src -d /var/tmp/OG1/data -W /var/tmp/configuration.xml \
    -U http://localhost:8080/source -P -H -S
```
  - tried full text search for `Hello` (no project specified):
```
$ curl -X GET http://localhost:8080/source/api/v1/search?full=Hello
{"time":3,"resultCount":1,"startDocument":0,"endDocument":0,"results":{"/1.0/Hello.txt":[{"line":"<b>Hello</b>","lineNumber":"1"}]}}
```
  - tried the same search from a browser, this time with the `1.0` project selected
  - indexed 2nd instance:
```
/var/tmp/opengrok-1.1-rc41/bin/indexer.py -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- \
    -s /var/tmp/OG2/src -d /var/tmp/OG2/data -W /var/tmp/configuration.xml \
    -U http://localhost:8080/source -P -H -S
```
  - tried search for `Hello` again (again no project selected):
```
$ curl -X GET http://localhost:8080/source/api/v1/search?full=Hello
{"time":2,"resultCount":1,"startDocument":0,"endDocument":0,"results":{"/2.0/Hello.txt":[{"line":"<b>Hello</b>","lineNumber":"1"}]}}
```
  - tried to search for `Hello` using a browser, this time the `2.0` project was selected

All searches worked fine. For the browser initiated searches, I clicked on the result to make sure the file contents are displayed correctly.

**Comment by vladak** [comment]
Also, I wonder if the port number is set correctly in `WEB-INF/web.xml`. Otherwise the web app could not receive new configuration at the end of each reindex. With 1.1 this problem does no longer exist because all communication with the web application goes through RESTful API over the standard port.

**Comment by vladak** [comment]
Looking at the original error error again, it is mixing source root from one instance with data from the second instance. I am not sure if this is due to mis-configuration or problem in the `OpenGrok` shell script (which would add just another reason to ditch it) however as you can see above, 1.1 does not have this problem.
