### ISSUE TITLE
Search results du(tri)plicated after reindex since 1.1-rc39

### ISSUE THREAD

**Issue by dobrou** [oracle/opengrok#2355]
Steps to reproduce:
1) Completely clean the index database and start first indexing
2) Search results are OK
3) Run reindex
4) Search results are duplicated
5) Every next reindex adds duplicate entries. See attached screenshot after second reindex run.
In indexer it's visible it adds all files as new each time.

![image](https://user-images.githubusercontent.com/2125998/45545236-05c11300-b81a-11e8-8fa0-35efa56f4544.png)

Env: Windows, Tomcat, JRE 10.0.2, indexing GIT repositories, **Opengrok 1.1-rc39**
**Opengrok 1.1-rc38 is OK.**

My indexer commandline:
`
java -Xmx5048m -Xms512m --add-modules java.xml.bind -jar .\bin\opengrok-current\lib\opengrok.jar --history -U "http://opengrok/" -R .\configuration-default.xml -W .\configuration-git.xml -P -S -v -s .\sources\git -d .\index\git -p __all__ 
`

My xml config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<java version="9.0.1" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void property="groupsCollapseThreshold"><int>0</int></void>
  <void property="hitsPerPage"><int>50</int></void>
  <void property="allowLeadingWildcard"><boolean>true</boolean></void>
  <void property="projectsEnabled"><boolean>true</boolean></void>
  <void property="historyCache"><boolean>false</boolean></void>
  <void property="historyEnabled"><boolean>true</boolean></void>
  <void property="generateHtml"><boolean>false</boolean></void>
  <void property="quickContextScan"><boolean>false</boolean></void>
  <void property="optimizeDatabase"><boolean>true</boolean></void>
  <void property="cmds">
   <object class="java.util.Collections" method="unmodifiableMap">
    <object class="java.util.HashMap">
     <void method="put">
      <string>org.opengrok.indexer.history.GitRepository</string>
      <string>git</string>
     </void>
    </object>
   </object>
  </void>
  <void property="ctags">
   <string>.\bin\ctags-current\ctags.exe</string>
  </void>
  <void property="remoteScmSupported">
   <object class="java.lang.Enum" method="valueOf">
    <class>org.opengrok.indexer.configuration.Configuration$RemoteSCM</class>
    <string>OFF</string>
   </object>
  </void>
 </object>
</java>
```

**Comment by vladak** [comment]
Seems like some of the Windows fixes broke this. Maybe we can wait for #2335 to be fixed and see if it resolves this problem as well.

**Comment by tarzanek** [comment]
well yes, uuid is not generated properly now, so lookup will fail and indexer adds new records

**Comment by tarzanek** [comment]
I will close this as part of push for #2335, hence closing

**Comment by dobrou** [comment]
Thank you.
