### ISSUE TITLE
How to track usage of OpenGrok

### ISSUE THREAD

**Issue by newtoniumx3** [oracle/opengrok#2357]
What are some ways we could monitor OpenGrok, both usage and specific searches? Is there any systems either built in or that can be added as extensions?

We are running OpenGrok on the intranet but we have no visibility of how it's being used and how much usage it gets.

Currently OpenGrok is being installed through a puppet pipeline. 

```
class opengrok {
  package {[
    'opengrok-tomcat',
    'ctags',
  ]
...
file { '/usr/share/tomcat8/webapps/opengrok-1.0':
  ensure  => directory,
  owner   => 'root',
  group   => 'root',
  mode    => '0755',
}
```

**Preliminary ideas:**
1) Add a proxy forwarding endpoint in front of opengrok to record the "hits" and send it to some DB store. That wouldn't track low level usage of opengrok (i.e. search queries), just the hits.

2) Somehow enable tomcat logs and parse through the logs? I'm not sure how much info I would get from the logs and the parsing might get involved. Then send this info to some DB store.

**Comment by vladak** [comment]
As for Tomcat logs, the access log (which is I believe generated by default) contains entries like this:

```
1.0.0.1 - - [26/Sep/2018:18:23:46 +0200] "GET /source/xref/foo/bar.sh HTTP/1.1" 302 -
1.0.0.1 - - [26/Sep/2018:18:23:46 +0200] "GET /source/xref/foo/bar.sh?r=36361%3Ad9765b458071 HTTP/1.1" 200 78603
1.0.0.1 - - [26/Sep/2018:18:23:56 +0200] "GET /source/default/img/indicator.gif HTTP/1.1" 304 -
1.0.0.1 - - [26/Sep/2018:18:23:57 +0200] "GET /source/api/v1/suggest?projects%5B%5D=foo&field=full&full=XXX&defs=&refs=&path=&hist=&type=&caret=11 HTTP/1.1" 200 476
1.0.0.1 - - [26/Sep/2018:18:23:58 +0200] "GET /source/s?path=config/authentication_method&project=foo HTTP/1.1" 200 28137
1.0.0.1 - - [26/Sep/2018:18:24:03 +0200] "GET /source/api/v1/suggest?projects%5B%5D=foo&field=full&full=XXX.&defs=&refs=&path=&hist=&type=&caret=12 HTTP/1.1" 404 27390
1.0.0.1 - - [26/Sep/2018:18:24:04 +0200] "GET /source/api/v1/suggest?projects%5B%5D=foo&field=full&full=XXX.LI&defs=&refs=&path=&hist=&type=&caret=14 HTTP/1.1" 404 27390
```

i.e. classic Apache style logs and there is a number of tools out there that parse such logs.

**Comment by vladak** [comment]
More info for access logging in Tomcat:
  - https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Access_Logging
  - https://tomcat.apache.org/tomcat-8.5-doc/logging.html

In `server.xml` (within `Host` element) it looks like this:
```xml
<!-- Access log processes all example.                                  
             Documentation at: /docs/config/valve.html                          
             Note: The pattern used is equivalent to using pattern="common" --> 
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"                      
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
```

**Comment by vladak** [comment]
The analysis tools can be googled ad infinitum it seems, e.g. https://webmasters.stackexchange.com/questions/4852/what-is-the-best-apache-logs-analyzer

**Comment by vladak** [comment]
Based on the reactions to the individual comments I assume the answers were found satisfactory, hence closing.

**Comment by wy193777** [comment]
Seems https://opengrok.docs.apiary.io/#reference/0/statistics/returns-statistics isn't available on newer version of opengrok or at least not available on the document.

**Comment by vladak** [comment]
> Seems https://opengrok.docs.apiary.io/#reference/0/statistics/returns-statistics isn't available on newer version of opengrok or at least not available on the document.

The `/statistics` API endpoint was replaced by a bit more general monitoring. Currently supported: Prometheus for the web app and StatsD for the indexer. See https://github.com/oracle/opengrok/wiki/Monitoring

**Comment by wy193777** [comment]
thanks for your reply, will look into it.

**Comment by vladak** [comment]
To demonstrate the setup I've created https://github.com/OpenGrok/opengrok-monitoring-docker
