### ISSUE TITLE
OpenGrok don't create History for Perforce repository.

### ISSUE THREAD

**Issue by AndrzejPolska** [oracle/opengrok#2358]
Hello.

I wan't use OpenGrok for create repository browser on Tomcat server on my Ubuntu. 
Indexer works fine - but the problem I don't know how integrate it with Perforce.

I run this command:
$JAVA -Xms2G -Xmx16G -Dorg.opensolaris.opengrok.history.Perforce=/usr/bin/p4 -jar "${OpenGrokJar}" -r on -H -m 2048 -c "$CTAGS" -w "myProject" -s "$VIEW" -d "$DB_DIR50" $IGNORE_PATTERNS $VERBOSE_PROGRES -z 1000 -t 4 -P -vvv -W "$CONF_FILE" -a on -O on

I was run this command :  p4 dir /$VIEW and it return that this location is under P4 Client.

In log file I have lines:
INFO: Generating history cache for all repositories ...
Sep 27, 2018 10:20:14 AM org.opensolaris.opengrok.history.HistoryGuru createCacheReal
INFO: Creating historycache for 0 repositories
INFO: Done historycache for all repositories (took 6 ms)

Please, could you point me how integrate OpenGrok with Perforce - step by step.

**Comment by vladak** [comment]
What is the OpenGrok version you are running ?

Dne čt 27. 9. 2018 10:19 uživatel adiablos <notifications@github.com>
napsal:

**Comment by AndrzejPolska** [comment]
I was build OpenGrok from sources (Tag 1.0):
   git clone https://github.com/oracle/OpenGrok
   git checkout -b 1.0

**Comment by vladak** [comment]
Okay, so the system property used for setting path to Perforce binary is
probably correct. What do you see in the indexer logs ?

Dne čt 27. 9. 2018 10:44 uživatel AndrzejPolskaSztuk1 <
notifications@github.com> napsal:

**Comment by AndrzejPolska** [comment]
In my log file I see only those lines connected with history or repo:

	Line 7: INFO: Generating history cache for all repositories ...
	Line 7: INFO: Generating history cache for all repositories ...
	Line 8: Sep 27, 2018 11:16:36 AM org.opensolaris.opengrok.history.HistoryGuru createCacheReal
	Line 8: Sep 27, 2018 11:16:36 AM org.opensolaris.opengrok.history.HistoryGuru createCacheReal
	Line 9: INFO: Creating historycache for 0 repositories
	Line 9: INFO: Creating historycache for 0 repositories
	Line 11: INFO: Done historycache for all repositories (took 7 ms)
	Line 11: INFO: Done historycache for all repositories (took 7 ms)
	Line 510: INFO: Done indexing data of all repositories (took 2.647 seconds)



Please, could you confirm my understanding of OpenGrok:

OpenGrok - version Tag 1.0.
In environment exists exports:  P4PORT P4USER P4PASSWD P4CLIENT
I was use command for generating Data base Index file:

$JAVA -Xms2G -Xmx16G -Dorg.opensolaris.opengrok.history.Perforce=/usr/bin/p4 -jar "${OpenGrokJar}" -r on -H -m 2048 -c "$CTAGS" -w "myProject" -s "$VIEW" -d "$DB_DIR50" $IGNORE_PATTERNS $VERBOSE_PROGRES -z 1000 -t 4 -P -vvv -W "$CONF_FILE" -a on -O on


$VIEW - this path point to perforce repository and when I run p4 dirs $VIEW - in result I see path in my Perforce server.

**Comment by AndrzejPolska** [comment]
For test I add only one components and $VIEW folder contains standard structure for gbs:
common\
include\
internal\
packaging\
src\
test.manifest
CMakeLists.txt

As I understood my configuration is enought for generate Perforce History? Is it the way to generate more datailed logs? any option to see what was executed by Indexer?

**Comment by vladak** [comment]
Incidentally we discussed Perforce support in OpenGrok with @nerakhon last night, perhaps he has a set of steps to follow ?

**Comment by AndrzejPolska** [comment]
I will be very grateful for step by step tutorial.

Thank you for advance,

**Comment by nerakhon** [comment]
Can you please specify what is present in the $VIEW? Is it a mapped perforce client view? Ideally provide an output of p4 client -o (redacted as you see fit) in the $VIEW directory?

**Comment by vladak** [comment]
In project mode, the source root directory should contain subdirectories with repositories. This might be the reason why the repository was not detected.

**Comment by AndrzejPolska** [comment]
In Perforce not exists sth like root of projects. In client view I map many p4 directiries (repositories) to my client directories.

E.g: in Perforce I have 

//YEAR2018/APPLICATIONS/APP_MAIN/.. //P4CLENT//APPLICATIONS/APP_MAIN/..
//there is App1   App2 App3
/YEAR2018
      /APPLICATIONS
            /APP_MAIN
                 /App1
                 /App2
                 /App3
      /this subdir have more directories

Now in my configuration I point root as 
    //P4CLENT//APPLICATIONS/APP_MAIN/App1.

Is there a way to generate project configuration xml - to -R "cfg_file"?

**Comment by vladak** [comment]
I meant the structure under source root. With projects it should look like this:
```
/var/opengrok
├── data
│   ├── historycache
│   ├── index
│   ├── suggester
│   └── xref
└── src
    ├── bar
    └── foo
```

where `foo` and `bar` are sub-directories of `/var/opengrok/src` which is the source root. The sub-directories can be a checkout of whatever SCM at hand. If you checkout to `/var/opengrok/src` directly then I'm afraid the indexer will not be able to recognize this as a repository (at least if projects are enabled).

**Comment by nerakhon** [comment]
OK to probably better explain - create something like this:

srcroot/
      client1
      client2
      client3

where client 1-3 are individual perforce clients which map logically together things you want to individually index as projects.

**Comment by AndrzejPolska** [comment]
Thank you. 
Is 'project' in OpenGrok is equal to Workspace. Did I understood it correctly? - lets name this option A.
Or 'project' means line in Workspace map?  - lets name this option B.
Should I configure more than one Workspace?

**Case A: project is Workspace:**

P4CLENT1 path /var/opengrok/src/client1
P4CLIENT1 map:

```
    //YEAR2018/APPLICATIONS/APP_MAIN/App1.. //P4CLENT1/..
```

P4CLENT2 path /var/opengrok/src/client2
P4CLIENT2 map:

```
    //YEAR2018/APPLICATIONS/APP_MAIN/App2.. //P4CLENT2/..
```

**When I checkout source it will be create - in case A:**
```
/var/opengrok
└── src
     ├── clien1/all subfolders from App1   #it's a root for Workspace CLIENT1
     └── client2/all subfolders from App2 #it's a root for Workspace CLIENT2
```

**Case B: project is map in worksplace:**
P4CLENT1 path /var/opengrok/src/client1
P4CLIENT1 map:
```
    //YEAR2018/APPLICATIONS/APP_MAIN/App1.. //P4CLENT1/App1..
    //YEAR2018/APPLICATIONS/APP_MAIN/App2.. //P4CLENT1/App2..
```
**When I checkout source it will be create - in case B:**
```
/var/opengrok
└── src        #it's a root for Workspace CLIENT1
     ├── App1
     └── App2
```

**Comment by nerakhon** [comment]
Case A is the correct setup you should setup per client workspaces.

**Comment by AndrzejPolska** [comment]
Still the same - 
`Sep 28, 2018 8:23:23 AM org.opensolaris.opengrok.history.HistoryGuru createCacheReal
INFO: Creating historycache for 0 repositories`

**Comment by nerakhon** [comment]
Did you try simply using the default paths and running OpenGrok index? To me it smells like something is wrong with the manual execution parameters

**Comment by AndrzejPolska** [comment]
Not yet.  I will try.

**Comment by AndrzejPolska** [comment]
Ok, now I see what I want :)   when I use OpenGrok index.
Thank You.

**Comment by gtoph** [comment]
For what it's worth, I got perforce working pretty good, but I've customized it's handling as well.  So the way I have it setup is that my perforce branches are organized by target type directories.  I.e.

d:\builds\targetA\branch1
d:\builds\targetA\branch2
etc.   
That part in kind of irreverent, other than to say that each branch is it's own perforce client spec.
so a "p4 client -o" will return a different config for each of those branches because there is a ".p4config" file in each root.

The beauty of how I have it setup, is these can be anywhere they want, and all I do is symbolically link them to a main project directory that opengrok deals with.  So my directory layout is thus:

d:\opengrok
├── bin                      < Contains all the openGrok executables
│     ├── opengrok.jar
├── grokdata             < Where the database will be created
│     ├── body_include     
│     ├── header_include   
├── logs                 
├── projectLinks              < Projects to index
│     ├── addproject.bat   < Scripts to add & remove symlinks to the projects you want indexed
│     ├── branch1            < Symlinks
│     ├── branch2
│     └── rmproject.bat             
├── full_index.bat       < Script to run that will index all projects
├── logging.properties   < Logging options

So for each perforce project you want to index:
mklink /D d:\opengrok\projectLinks\branch1 d:\builds\targetA\branch1

I've tweaked the perforce opengrok code as well though, so maybe that's why it all works for me.  I've added things like 'realPath' to get the actual paths and updated the options and such.
`  
@@ -72,6 +73,13 @@ public class PerforceHistoryParser {
 
    private History parseDirectory(File file) throws IOException {
        ArrayList<String> cmd = new ArrayList<String>();
        Path realPath = file.toPath();
            
        try{
            realPath = realPath.toRealPath();
        }catch (IOException e){}
        file = realPath.toFile();
        //Gets the CL's
        cmd.add("p4");
        cmd.add("changes");
        cmd.add("-t");
@@ -84,14 +92,21 @@ public class PerforceHistoryParser {
 
    public static History getRevisions(File file, String rev) throws IOException {
        ArrayList<String> cmd = new ArrayList<String>();
        Path realPath = file.toPath();
            
        try{
            realPath = realPath.toRealPath();
        }catch (IOException e){}
        file = realPath.toFile();

        cmd.add("p4");
        cmd.add("filelog");
        cmd.add("-slti");
        cmd.add(file.getName() + PerforceRepository.getRevisionCmd(rev));
        Executor executor = new Executor(cmd, file.getCanonicalFile().getParentFile());
        executor.exec();
`
Things like that.  Too many other changes to list here.. but basically I can get history just fine back to the beginning of time and compare any version to any other version, including my current workspace version.

The only thing I did was break the perforce test, so I have that disabled when I compile.  Actually have all tests disabled cause of the SVN issue I've seen on here too.  Someday I'll fix the perforce test, but not high on my list, since this all a side thing I'm doing at work anyway and it works in actual practice.

**Comment by vladak** [comment]
One thing I noticed in the original indexer command is that it lacks the `-S` option (to discover repositories). Could you try running with it ?

**Comment by vladak** [comment]
@gtoph thanks for the info. Would be nice if you could make it a PR someday. Incidentally I did not realize we can augment our Windows testing by `mklink`.

**Comment by AndrzejPolska** [comment]
Hi.  Ok I will try tomorrow.

Btw.  there is a way to change p4 filelog -slti to version  -slt..    option -i produce quite big history - from more 10 years ago.
Or is there a way to limit to current brunch.

**Comment by gtoph** [comment]
Im not aware of an option to limit how much history p4 can get, though admittedly i didnt look that hard.

I run with the -i option as its been handy to see the entire history and i feel the indexing of the tens of thousands of files per project is still relatively fast. Your mileage may vary though.

**Comment by vladak** [comment]
Any luck with `-S` ? You can also try `--listRepos` along with `-S` to see what repositores were detected.

**Comment by AndrzejPolska** [comment]
Hi.

Hard to tell :)...
Finally I was use run index proces by command:

**Comment by vladak** [comment]
the actual command was omitted from your last response. So you were able to resolve the problem ? If so, how ?

**Comment by AndrzejPolska** [comment]
Sorry..  sth lost in my last post.

I was try use open grok by cmd:
OPENGROK_CONFIGURATION_FILE=/var/opengrok/etc/og.config OpenGrok index /srcPath/

Og.config have lines:
OPENGROK_CACHE_HISTORY=uionly

But the problem in web app I can't see Any History - href History and Anonate is not active :/


Please, confirm if I understood correctly. When I wa t generate index but History will be available ony in web on demand:
I have to define:
OPENGROK_CACHE_HISTORY=uionly

Don.t define OPEN_GROK_SCANREPOS at all to discover Repos.

**Comment by vladak** [comment]
I think you are getting ahead of yourself. There needs to be a repository in order to generate the history - does not matter if just in web app or during the indexing.

**Comment by vladak** [comment]
Can you post your current `configuration.xml` ?

**Comment by AndrzejPolska** [comment]
Yes. I will tomorrow - now Im OOO.

**Comment by AndrzejPolska** [comment]
Ok, I noticed it's not working as I was think.

If I config like:
#dont define OPENGROK_SCAN_REPOS - any text here will disable scan for repo
define OPENGROK_CACHE_HISTORY=uionly

With this all History Cache was generated during Indexing process.

**Comment by AndrzejPolska** [comment]
But fortunately I discover some hijack for do not generate HistoyCache during index process.
Steps:

1. Configure and run Index
`
OPENGROK_SCAN_REPOS=on  <--this line disable Scan for Repo
OPENGROK_SCAN_DEPTH=1
OPENGROK_GENERATE_HISTORY=on

OPENGROK_FLUSH_RAM_BUFFER_SIZE="-m 64"
OPENGROK_READ_XML_CONFIGURATION=/var/opengrok/etc/read_only_configuration.xml`

read_only_configuration.xml do not contains any repository.

2. Modify read_only_configuration.xml - add repositories and rerun index process.

configuration.xml file have defined repositiories but index process do not generate any history.


Please, could you tell me how disable HistoryCache generation during build index but turn it on History and Annonate in web app.  (I can rebuild OpenGrok).

**Comment by vladak** [comment]
It looks like you were able to solve the original problem of not being able to generate history for Perforce repository at all (even though it is not clear to me what change fixed it for you).

Yes, the logic of `OPENGROK_SCAN_REPOS` is flawed in the `OpenGrok` shell script. Consider switching to OpenGrok 1.1 - there the `indexer.py` script is just a thin layer on top of the Java program so confusion like this does not happen there.

Looks like `uionly` does not work for you. This is very likely a dup of #1498.
