### ISSUE TITLE
economy mode (-e parameter) shows blank page for unindexed text files

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2360]
If economy mode (-e parameter) is specified on index, only blank page is displayed when unsupported (un-indexed) text files are clicked on directories.  e.g. .txt file, .config file, etc.  If economy mode is not specified, the file contents are correctly displayed.

**Comment by vladak** [comment]
Actually, closing as unsupported until a PR fixing this is submitted.
