### ISSUE TITLE
upgrade to latest jflex 1.7.0

### ISSUE THREAD

**Issue by tarzanek** [oracle/opengrok#2365]

**Comment by vladak** [comment]
For such stuff I'd say do not bother filing issues, just submit the PR right away.

**Comment by tarzanek** [comment]
I am trying to test Ideas integration with github and https://www.jetbrains.com/help/idea/managing-tasks-and-context.html which seem to have per branch/bug strategy, so let's see how it will work out :)

**Comment by vladak** [comment]
I see, looks neat. At the end please share your experiences with it.
