### ISSUE TITLE
Wiki for sync script should add -U also for the mirroring

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2368]
https://github.com/oracle/opengrok/wiki/Repository-synchronization#syncpy

The wiki example for `sync.py` contains `-U` parameter for the reindex script.
This should be also filled for the mirror script so it's not confusing.

**Comment by vladak** [comment]
Like for #2370 - please fix the wiki yourself.

**Comment by tulinkry** [comment]
Did you fix it? Because I haven't so I'd keep this open please
