### ISSUE TITLE
Wiki documentation of sync.py should say to use -U twice if webapp address is non-default

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2370]
When running the sync.py with the configuration based on https://github.com/oracle/opengrok/wiki/Repository-synchronization#syncpy I end up with 

```python
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /source/api/v1/configuration (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbee8cba048>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

errors and indentified that the `URI` was not set at all eventhough the `-U` parameter is provided in the `sync.conf`

It appears that in command 
```bash
/opengrok/bin/reindex-project.py -D -J=-d64 -J=-XX:-UseGCOverheadLimit -J=-Xmx12g -J=-server --jar /opengrok/lib/opengrok.jar -t /opengrok/etc/logging.properties.template -p %PROJ% -d /opengrok/log/OpenGrok -P OpenGrok -- --renamedHistory off -r dirbased -G --memory 256 -c /opt/universal_ctags/bin/ctags -U http://localhost:8150/source -H OpenGrok OpenGrok
```

the `-U` option must precede the `--` otherwise is ignored and the default is applied. 

The other script may have this as well so it is worth mentioning it in the wiki at least or fix it somehow.

**Comment by vladak** [comment]
The Python scripts use RESTful API to communicate with the web app so if the URI is not default, for the scripts that run the indexer it needs to be specified both for the script itself as well as indexer argument. Feel free to fix the wiki yourself - anyone can edit them.

**Comment by tulinkry** [comment]
Did you fix it? Because I haven't so I'd keep this open please

**Comment by vladak** [comment]
Ok, I was counting on you :-)

**Comment by vladak** [comment]
made some changes to the wiki, hence closing.

**Comment by vladak** [comment]
made some changes to the wiki, hence closing.
