### ISSUE TITLE
Definition Search not working fine for perl variables 

### ISSUE THREAD

**Issue by Lokendra-Saini** [oracle/opengrok#2373]
Hello All,

I was searching for some variable names using Definition Search in a perl file. However no result was returned by Definition search. Symbol search is returning results for the same.

**Opengrok Used**   : http://demo.opengrok.org
**Definition Search** : database
**Type**                     : Perl

No results were returned by above search, though "database" exists in this [file](http://demo.opengrok.org/xref/opengrok/opengrok-indexer/src/test/resources/analysis/perl/sample.pl).

Thanks in advance!! :-)

**Comment by vladak** [comment]
Trying the latest Universal ctags on `opengrok/opengrok-indexer/src/test/resources/analysis/perl/sample.pl`:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/d0807887/
STDOUT	/home/vkotal/Downloads/sample.pl	/^    format => "%s");$/;"	f
STDOUT	/home/vkotal/Downloads/sample.pl	/^ format STDOUT =$/;"	f
snazzle	/home/vkotal/Downloads/sample.pl	/^sub snazzle($) {$/;"	s
```

So by itself `ctags` does not produce variable definitions, hence OpenGrok does not index them.

A workaround might be to supply regular expression parameter to ctags (which OpenGrok supports via the `ctags.config` file under `etc`) that could look like this:

```
--regex-perl='/^my[[:space:]]+\$([[:alnum:]]+)/\1/v,variables/'
```

which produces:

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/d0807887/
KK	/home/vkotal/Downloads/sample.pl	/^my $KK = "b";$/;"	v
STDOUT	/home/vkotal/Downloads/sample.pl	/^    format => "%s");$/;"	f
STDOUT	/home/vkotal/Downloads/sample.pl	/^ format STDOUT =$/;"	f
a	/home/vkotal/Downloads/sample.pl	/^my $a = qr$abc$ix;$/;"	v
cost	/home/vkotal/Downloads/sample.pl	/^my $cost = <<'VISTA';  # hasta la ...$/;"	v
database	/home/vkotal/Downloads/sample.pl	/^my $database='dbi:DB2:sample';$/;"	v
snazzle	/home/vkotal/Downloads/sample.pl	/^sub snazzle($) {$/;"	s
thingie	/home/vkotal/Downloads/sample.pl	/^my $thingie = shift;$/;"	v
this	/home/vkotal/Downloads/sample.pl	/^my $this = {};$/;"	v
x	/home/vkotal/Downloads/sample.pl	/^my $x;$/;"	v
```

Anyhow, filing a new issue against https://github.com/universal-ctags/ctags might be in order. If anything at least we might learn why variable detection is not implemented.
