### ISSUE TITLE
ConfigMerge Java program does not print help

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2379]
```bash
./bin/config-merge.py -j /usr/java/jdk1.8.0/bin/java --jar ./lib/opengrok.jar -- -h
```

prints just a blank line

**Comment by vladak** [comment]
It should print what is the first (base config - usually read-only config) and second argument (current config as retrieved from web app).

**Comment by tulinkry** [comment]
I think it doesn't print anything because the return code is 0 (OK) however the usage is printed to stderr.

**Comment by vladak** [comment]
This seems to be the same case with the `groups.py` program.

**Comment by tulinkry** [comment]
This is it, in config-merge `redirect_stderr=True`

**Comment by vladak** [comment]
Yes, the separate stdout/stderr redirect is there intentionally - otherwise logger messages would intermingle with `ConfigMerge` output.
