### ISSUE TITLE
-U parameter needs to by specified twice for the python scripts

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2380]
For some of the python scripts it is necessary to specify the -U (--uri) parameter twice - first for the python script and secondly as the java parameter later.

Example:
```bash
$ ./projadm.py --uri http://example.com -a project -- -U http://example.com
```

If not specified on both places, the results may be suprising. The python script should propagate the first --uri option down to the java itself.

Also, the parameters are -U/--uri for the python and -U/--host for the java which could be united.

**Comment by vladak** [comment]
This looked as a good idea initially, however when I started writing the Python I very much wanted to avoid mixing the script arguments with indexer arguments. This change would break this. Also, if anyone wants to avoid sending configuration to webapp (such as when indexing in the background to prepare for near zero downtime switch over) this would stand in the way.

So, I'd rather see it documented properly on the wiki.
