### ISSUE TITLE
adding installation tarball to releases via Travis no longer works

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2381]
It seems that installation package tarballs (opengrok-1.1-rcXX.tar.gz) are not provided from 1.1-rc42.  Could you please add these files?

**Comment by vladak** [comment]
The build (https://api.travis-ci.org/v3/job/437494936/log.txt) failed with:
```
Skipping a deployment with the releases provider because a custom condition was not met
```

**Comment by vladak** [comment]
I believe the custom condition in `.travis.yml` is:
```
 condition: "$TRAVIS_TAG =~ rc[0-9]+$"
```

**Comment by vladak** [comment]
I see that `TRAVIS_TAG` is set correctly for tagged builds so something might have change in the condition evaluation (https://docs.travis-ci.com/user/deployment#conditional-releases-with-on says it is a `bash` condition and it works fine on my Ubuntu system).

**Comment by vladak** [comment]
It seems that removing the double quotes around the condition fixed the problem of not creating the release (https://api.travis-ci.org/v3/job/437751075/log.txt) however the files are still not uploaded.

**Comment by vladak** [comment]
In the end I think this is due to not following https://github.com/oracle/opengrok/wiki/Release-process properly - the version change to `pom.xml` files needs to be pushed first, then the tag.

**Comment by vladak** [comment]
Filed https://github.com/travis-ci/travis-ci/issues/10190 to get better info on failing to find the file(s) to upload.

**Comment by vladak** [comment]
Since 1.1-rc49 it works again.

**Comment by shyoshiz** [comment]
Thank you very much for your quick fix!!!
Just, a simple question.  Why many releases are created today?

**Comment by vladak** [comment]
They were created as a means to debug the problem.

Dne pá 5. 10. 2018 21:30 uživatel shyoshiz <notifications@github.com>
napsal:

**Comment by shyoshiz** [comment]
I got it.  Thanks for the response!
