### ISSUE TITLE
setting configuration property via API is not propagated to all threads

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2382]
Today I think I hit a race condition when doing the parallel indexing and using the sync.py script (mostly from the wiki).

My flow is following:

1. Delete all unwanted projects with projadm.py
2. Download all sources from the SCM
3. Add all projects with projadm.py (no index at this step)
4. Generate groups and publish them to the webapp
5. Index the sources using sync.py script with mirroring.

I'm using 10 repositories, some of them take longer time to index but most of them can finish in almost the same time. I'm using the number of workers 4.

When the sync.py script is finished, with no errors, the page itself displays only 9 (sometimes 8) projects most of the time, with one of them missing randomly. After looking in the webapp configuration the project itself is not marked as indexed (therefore not visible).

However, looking at the indexer logs, there is a 10 times a mention that the uri `projects/{p}/indexed` has been fired and return 204.

```bash
-bash-4.1$ cat /opengrok/log/**/opengrok0.0.log | grep "indexed HTTP/1.1" | wc -l
10
```

Also looking at the tcpdump communication (posted below), I can see 10 calls for the indexed url.

I couldn't dig any deeper at this point, but there's something wrong going on.

Sync-config.yml:
```yaml
commands:
- command:
  - http://localhost:8150/source/api/v1/messages
  - POST
  - cssClass: info
    duration: PT2H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
- command: [ /opengrok/bin/mirror.py, -U, 'http://localhost:8150/source', -c, /opengrok/etc/mirror-config.yml ]
- command: [
    /opengrok/bin/reindex-project.py,
    -j,
    '/usr/java/jdk1.8.0_60/bin/java',
    -J=-d64,
    '-J=-XX:-UseGCOverheadLimit',
    -J=-Xmx12g,
    -J=-server,
    -J=-Dorg.opengrok.indexer.history.git=/opt/git/git283/bin/git,
    --jar,
    /opengrok/lib/opengrok.jar,
    -t,
    /opengrok/etc/logging.properties.template,
    -p,
    '%PROJ%',
    -d,
    /opengrok/log/%PROJECT%,
    -P,
    '%PROJECT%',
    --uri,
    'http://localhost:8150/source',
    --,
    -U,
    'http://localhost:8150/source',
    --renamedHistory,
    'off',
    -r,
    dirbased,
    --memory,
    '256',
    -c,
    /opt/universal_ctags/bin/ctags,
    -i,
    'Assets.webtest',
    -P,
    -H,
    '%PROJECT%',
  ]
  env: {LC_ALL: en_US.UTF-8}
- command: ['http://localhost:8150/source/api/v1/messages?tag=%PROJECT%', DELETE, '']
cleanup:
  command: ['http://localhost:8150/source/api/v1/messages?tag=%PROJECT%', DELETE, '']

```

Tcpdump:
```
[root@notebook]# tcpdump -s 0 -A -i lo -v -l -n  port 8150 | egrep -i "POST /|GET /|PUT /|DELETE /|Host:"
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
..@o..@oPOST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
..@p..@pPOST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
..@z..@zPOST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
..@...@.POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
..C'..C'GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
..C3..C3GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
..CZ..CZGET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
..Cm..CmGET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
..C...C.GET /source/api/v1/projects/api.fuel/repositories HTTP/1.1
Host: localhost:8150
..C...C.GET /source/api/v1/repositories/type?repository=%2Fapi.fuel HTTP/1.1
Host: localhost:8150
..C...C.GET /source/api/v1/projects/api.apitest/repositories HTTP/1.1
Host: localhost:8150
..D...D.GET /source/api/v1/repositories/type?repository=%2Fapi.apitest HTTP/1.1
Host: localhost:8150
..D%..D$GET /source/api/v1/projects/api.avails/repositories HTTP/1.1
Host: localhost:8150
..D)..D)GET /source/api/v1/repositories/type?repository=%2Fapi.avails HTTP/1.1
Host: localhost:8150
..D7..D7GET /source/api/v1/projects/api.analytics/repositories HTTP/1.1
Host: localhost:8150
..D;..D;GET /source/api/v1/repositories/type?repository=%2Fapi.analytics HTTP/1.1
Host: localhost:8150
..G...G.GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
..HI..HIGET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
..H...H.GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
..J...J.GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
..O...O.PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
..Pt..PqPUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
..P...P.PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
..Sc..S`PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
..{E..{DPUT /source/api/v1/projects/api.apitest/indexed HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/projects/api.avails/indexed HTTP/1.1
Host: localhost:8150
...@..{VPUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...v...rDELETE /source/api/v1/messages?tag=api.apitest HTTP/1.1
Host: localhost:8150
...~...~POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
...V...VGET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/projects/api.fuel_js/repositories HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/repositories/type?repository=%2Fapi.fuel_js HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...T...TDELETE /source/api/v1/messages?tag=api.avails HTTP/1.1
Host: localhost:8150
..._..._POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
...a...aGET /source/api/v1/projects/api.navajo/repositories HTTP/1.1
Host: localhost:8150
...g...fGET /source/api/v1/repositories/type?repository=%2Fapi.navajo HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
...'....PUT /source/api/v1/projects/api.fuel_js/indexed HTTP/1.1
Host: localhost:8150
.......6PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
........DELETE /source/api/v1/messages?tag=api.fuel_js HTTP/1.1
Host: localhost:8150
........POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
...e...eGET /source/api/v1/projects/api.orion/repositories HTTP/1.1
Host: localhost:8150
...k...kGET /source/api/v1/repositories/type?repository=%2Fapi.orion HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
...,...#PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
...>...=PUT /source/api/v1/projects/api.analytics/indexed HTTP/1.1
Host: localhost:8150
...m...hPUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...j...fDELETE /source/api/v1/messages?tag=api.analytics HTTP/1.1
Host: localhost:8150
...r...rPOST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/projects/api.orion-gateway/repositories HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/repositories/type?repository=%2Fapi.orion-gateway HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
...t...kPUT /source/api/v1/projects/api.orion/indexed HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
.......TPUT /source/api/v1/projects/api.orion-gateway/indexed HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...-...%DELETE /source/api/v1/messages?tag=api.orion-gateway HTTP/1.1
Host: localhost:8150
...9...1POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...@...@GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
........DELETE /source/api/v1/messages?tag=api.orion HTTP/1.1
Host: localhost:8150
........POST /source/api/v1/messages HTTP/1.1
Host: localhost:8150
...m...mGET /source/api/v1/projects/api.orionapitest/repositories HTTP/1.1
Host: localhost:8150
...u...qGET /source/api/v1/repositories/type?repository=%2Fapi.orionapitest HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration/sourceRoot HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/projects/api.oxy/repositories HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/repositories/type?repository=%2Fapi.oxy HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
........GET /source/api/v1/configuration HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
...q...mPUT /source/api/v1/configuration/projectsEnabled HTTP/1.1
Host: localhost:8150
...k....PUT /source/api/v1/projects/api.orionapitest/indexed HTTP/1.1
Host: localhost:8150
.. ... .PUT /source/api/v1/projects/api.fuel/indexed HTTP/1.1
Host: localhost:8150
..&.....PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
..)...).DELETE /source/api/v1/messages?tag=api.orionapitest HTTP/1.1
Host: localhost:8150
..N...N.PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
..O[..O[DELETE /source/api/v1/messages?tag=api.fuel HTTP/1.1
Host: localhost:8150
..O...O.PUT /source/api/v1/projects/api.oxy/indexed HTTP/1.1
Host: localhost:8150
..`#..O.PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
..a<..a<DELETE /source/api/v1/messages?tag=api.oxy HTTP/1.1
Host: localhost:8150
...{...yPUT /source/api/v1/projects/api.navajo/indexed HTTP/1.1
Host: localhost:8150
........PUT /source/api/v1/system/refresh HTTP/1.1
Host: localhost:8150
...t...tDELETE /source/api/v1/messages?tag=api.navajo HTTP/1.1
Host: localhost:8150
[root@notebook]# 
```

**Comment by vladak** [comment]
Very likely this is not caused by the Python scripts (as you see all these API calls being done) rather than the API call handling in the web app itself.

**Comment by tulinkry** [comment]
It's definitely not the python part. It's something in the webapp, but I haven't debugged the webapp part yet.

**Comment by tulinkry** [comment]
Now when I kinda workarounded this, on a larger setup one of my projects is missing the repository information, so the table looks there is something, but no row is rendered.

<img width="1483" alt="screen shot 2018-10-06 at 13 32 25" src="https://user-images.githubusercontent.com/6997160/46570910-54bb1d80-c96c-11e8-8567-30260f891936.png">

The project is there, is indexed, but no repository information is connected to it.

**Comment by tulinkry** [comment]
Finally, I got some results. These are two run of the sample setup with some logging on the webapp side.

First run (all projects marked indexed):
```text
[http-nio-8080-exec-7] Setting api.orion-gateway indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-7.
[http-nio-8080-exec-1] Setting api.orionapitest indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-1.
[http-nio-8080-exec-6] Setting api.avails indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-6.
[http-nio-8080-exec-8] Setting api.orion indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-8.
[http-nio-8080-exec-3] Cannot refresh project api.avails because it is not indexed yet
[http-nio-8080-exec-4] Setting api.oxy indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-4.
[http-nio-8080-exec-10] Setting api.fuel_js indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-10.
[http-nio-8080-exec-8] Setting api.apitest indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-8.
[http-nio-8080-exec-4] Setting api.analytics indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-4.
[http-nio-8080-exec-8] Setting api.fuel indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-8.
[http-nio-8080-exec-3] Setting api.navajo indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-3.
```

Second run (only 8 project marked as indexed and displayed on the index site):
```text
[http-nio-8080-exec-9] Setting api.orion-gateway indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-9.
[http-nio-8080-exec-1] Setting api.orionapitest indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-1.
[http-nio-8080-exec-2] Cannot refresh project api.orionapitest because it is not indexed yet
[http-nio-8080-exec-3] Setting api.avails indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-3.
[http-nio-8080-exec-2] Setting api.orion indexed in configuration org.opengrok.indexer.configuration.Configuration@6e93bda6 in thread http-nio-8080-exec-2.
[http-nio-8080-exec-4] Cannot refresh project api.orion because it is not indexed yet
[http-nio-8080-exec-7] Setting api.oxy indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-7.
[http-nio-8080-exec-8] Setting api.fuel_js indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-8.
[http-nio-8080-exec-2] Setting api.apitest indexed in configuration org.opengrok.indexer.configuration.Configuration@6e93bda6 in thread http-nio-8080-exec-2.
[http-nio-8080-exec-5] Cannot refresh project api.apitest because it is not indexed yet
[http-nio-8080-exec-8] Setting api.analytics indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-8.
[http-nio-8080-exec-6] Setting api.fuel indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-6.
[http-nio-8080-exec-3] Setting api.navajo indexed in configuration org.opengrok.indexer.configuration.Configuration@1d2d3713 in thread http-nio-8080-exec-3.
```

As we can see, it is a different instance of the thread local `Configuration` object.

**Comment by tulinkry** [comment]
Now we're caught with the thread local variable. At the beginning there's thread local per each thread returning SAME configuration reference as per:

```java
    private RuntimeEnvironment() {
        configuration = new Configuration();
        threadConfig = ThreadLocal.withInitial(() -> configuration);
    }
```

There's no problem so far.

However, after applying my flow:

> 1. Delete all unwanted projects with projadm.py
> 2. Download all sources from the SCM
> 3. Add all projects with projadm.py (no index at this step)
> 4. Generate groups and publish them to the webapp
> 5. Index the sources using sync.py script with mirroring.

In step 4, which is essentially
```java
        this.configuration = configuration;
        threadConfig.set(configuration);
```

we set a new thread local variable for the calling thread (which was one of the tomcat http handling threads) and thus it suddenly owns different reference to a configuration then the rest of the threads.

Then it is just a matter of accident if that thread is used to handle incoming http request (REST API, page render) and so rendering different view of the configuration.

**Comment by tulinkry** [comment]
What we're looking for here is a concept of thread local variable but when setting that variable it needs to affect all of the threads at the same time.

**Comment by tulinkry** [comment]
This is actually a bad bug making the webapp pretty non-deterministic.

**Comment by tulinkry** [comment]
I wonder if these (which have been in OpenGrok since I started contributing) are related to this problem. It looks like the instance is the old instance (from step 4 above).

```
06-Oct-2018 19:25:58.091 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@613d3e40]) and a value of type [org.opengrok.indexer.configuration.Configuration] (value [org.opengrok.indexer.configuration.Configuration@1d2d3713]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

This is a quote from doc:

> Each thread holds an implicit reference to its copy of a thread-local variable as long as the thread is alive and the ThreadLocal instance is accessible; after a thread goes away, all of its copies of thread-local instances are subject to garbage collection (unless other references to these copies exist).

**Comment by vladak** [comment]
Looks like a mis-design. How come we are not seeing this when the whole configuration is set at the end of (non-partial) indexing ?

**Comment by vladak** [comment]
As for the memory leaks, something similar is tracked by #1761 (and possibly #2161) and I believe there is even some issue referencing the `Configuration` instances.

**Comment by vladak** [comment]
The reason for using `ThreadLocal` on https://www.javacodegeeks.com/2013/01/how-to-shoot-yourself-in-foot-with-threadlocals.html:
> It is often the easiest way to render a stateful class thread-safe. And encapsulate non-thread-safe classes so that they can safely be used in multithreaded environments. In addition to simplicity, using ThreadLocal to store a per-thread-singleton or per-thread context information has a valuable information included – by using a ThreadLocal, it’s clear that the object stored in the ThreadLocal is not shared between threads, simplifying the task of determining whether a class is thread-safe or not. Which we have found is not an easy task when you have a codebase of 1,000,000 lines at hand.

In our case, `RuntimeConfiguration` is a singleton and is subject to change, making `ThreadLocal` "easy" choice.

**Comment by tulinkry** [comment]
For the full index it seems that the problem is still there, however is vanished when clients access the webapp with the PageConfig call to

```java
    /**
     * Get the current runtime environment.
     *
     * @return the runtime env.
     * @see RuntimeEnvironment#getInstance()
     * @see RuntimeEnvironment#register()
     */
    public RuntimeEnvironment getEnv() {
        if (env == null) {
            env = RuntimeEnvironment.getInstance().register();
        }
        return env;
    }
```

where this register call eventually sets the correct instance to the all pending threads.

**Comment by tulinkry** [comment]
While the partial reindex interacts with the webapp during the indexing and the threads do not call register always, that causes the configuration mismatch.

**Comment by tulinkry** [comment]
> In our case, RuntimeConfiguration is a singleton and is subject to change, making ThreadLocal "easy" choice.

I don't have a problem with thread local but the set mechanism must apply to all affected threads.

**Comment by vladak** [comment]
The trouble is that in the presence of thread pool this cannot be reasonably achieved I think. Adding some sort of refresh trigger will only lead to more problems.

**Comment by tulinkry** [comment]
Actually this way we use the thread local is not actually making the configuration thread local as eventually the thread local variables return always the same instance of configuration to all of the threads which is not thread safe.

**Comment by tulinkry** [comment]
I isolated a test case for this with some descriptions.

```java
    @Test
    public void testParallel() {
        Configuration config = new Configuration();
        Project project = new Project();
        project.setIndexed(false);
        project.setName("name");
        project.setPath("/name");
        project.setHistoryEnabled(true);

        Map<String, Project> projects = new HashMap<>();
        projects.put("name", project);

        config.setProjects(new HashMap<>(projects));

        env.setConfiguration(config);


        Response response;

        /*
         * Now we set the new configuration into the env. However this only sets it as a thread local
         * in the http handling thread, so after this step the env.getConfiguration() and the http thread
         * configuration are different objects.
         */
        response = target("configuration").request().put(Entity.xml(config.getXMLRepresentationAsString()));
        assertEquals(204, response.getStatus());

        /*
         * Now we set the project as indexed. It is set only in the http handling thread, so it does not affect
         * our configuration object here.
         */
        response = target("projects").path("name").path("indexed").request().put(Entity.text(""));
        assertEquals(204, response.getStatus());

        /*
         * We do not want this kind of behaviour (described above), so this test fails on the indexed flag for our project.
         */
        assertEquals("We expect that the project is marked as indexed after the api call.", true, env.getProjects().get("name").isIndexed());
    }
```

The hotfix #2388 does not of course fix this test, as the problem should be addressed globally.

**Comment by tulinkry** [comment]
I went through a little bit and now I see the options. The configuration is *shared* with all of the threads on a premise that no thread will actually try to modify it (kinda read-only concept) while it is on some places violated.

The shared configuration is installed to each thread via `RE.register()` on the thread's demand (pulling the state). If the thread does not call this function before it access the configuration, it can't be sure if it has the fresh instance.

Now I see options:
1. Continue with this design, while pushing the new state to threads (and not polling). The configuration will still be shared with all of the threads on the premise that almost no thread will modify it. (this is not thread safe, yet faster)
2. Synchronize all methods on Configuration and for collections return synchronized collections. (this is almost thread safe, yet slower)
3. Synchronize all get methods on configuration with read lock and set methods with write lock. (the same as 2), may perform better, but `synchronize` is a built in concept)
4. Continue with 1) while maintaining a copy of the configuration in each thread, propagate all writes to  all threads holding a copy of the configuration. (thread safe, big overhead, many config copies in memory)

**Comment by tulinkry** [comment]
Thoughts? @vladak @tarzanek

**Comment by vladak** [comment]
I'd just ditch the `ThreadLocal` pattern for `Configuration` - it is not intended for this use case - and replace it with `ReadWriteLock`.

**Comment by tarzanek** [comment]
yes, 3) looks nice, although I am not that sure it will be faster than 2),  it might be, but then it's more error prone, so it sounds like more fun and hopefully closer to 1)
+1 for 3)

**Comment by tulinkry** [comment]
Good pattern indeed but with 30+ fields and everyone of them is

```
set field
w.lock()
try {
  this.field = field
} finally {
  w.unlock()
}

get field
r.lock()
try {
  return this.field
} finally {
  r.unlock()
}
```

like this, it doesn't look that good anymore :D

**Comment by tulinkry** [comment]
The configuration is now changed pretty often I'd say. During reindex each project calls markIndexed at least, and then there is the repository refresh. Not mentioning custom scripts and api calls.

So we almost surely have just one thread updating but during reindex it can happen very often.

**Comment by tulinkry** [comment]
I'm also not sure if 3 is definitely faster than 2 so I'd vote for 2)

**Comment by vladak** [comment]
I meant lock the whole `Configuration` object, not individual fields.

**Comment by tulinkry** [comment]
Ah, ok :-D

**Comment by vladak** [comment]
The locks just have to be used in getters/setters.

It would be really nice if there were annotations similar to Jave EE Concurrency handling (https://docs.oracle.com/cd/E19798-01/821-1841/gipsz/index.html), i.e.:
```java
@ConcurrencyManagement(CONTAINER)
@Singleton
public class ExampleSingletonBean {
  private String state;

  @Lock(READ)
  public String getState() {
    return state;
  }

  @Lock(WRITE)
  public void setState(String newState) {
    state = newState;
  }
}
```

**Comment by vladak** [comment]
I was also thinking about using reflection (as @Orviss suggests) so that getters would change from `return threadConfig.get().getAllowedSymlinks();` to something like `return getReadLockedConfig("allowedSymlinks");` however this is not such a good solution because of the type handling intricacies.

**Comment by tulinkry** [comment]
It's not a big deal you can put the expected type as the second parameter I think

**Comment by Orviss** [comment]
I don't think it is such a big problem having locking mechanism in each getter/setter. It is obvious what is happening there. I personally would choose that solution.

However, if you truly want something cool, then look at https://projectlombok.org/features/GetterSetter Maybe it could be tweaked somehow to generate locks as well; however, you would probably need to change IDE plugins as well...

**Comment by tulinkry** [comment]
It's not a problem, it's just ugly. I'm all for of course.

**Comment by tarzanek** [comment]
we seriously need scala or kotlin

**Comment by vladak** [comment]
or learn how to program in Java properly :)

Seriously, switching to different language would lead to even greater
instability and might increase barrier for adoption.

Dne út 16. 10. 2018 10:14 uživatel Lubos Kosco <notifications@github.com>
napsal:

**Comment by tulinkry** [comment]
> we seriously need scala or kotlin ;-)

We don't
