### ISSUE TITLE
commands.py emmiting an error

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2383]
```python 
File "/opengrok/bin/commands.py", line 104, in call_rest_api
   put(self.logger, uri, headers=headers, data=json_data)
UnboundLocalError: local variable 'headers' referenced before assignment
```

**Comment by vladak** [comment]
The `headers` local variable will only be set if data length is strictly greater than 0 in `call_rest_api()`. What triggered such condition in your case ?

**Comment by vladak** [comment]
Anyhow, this is a bug and should be fixed.

**Comment by vladak** [comment]
According to https://stackoverflow.com/questions/4191593/is-it-considered-bad-practice-to-perform-http-post-without-entity-body POST without body should be okay.

**Comment by tulinkry** [comment]
`- command: ['http://localhost:8150/source/api/v1/projects/%PROJECT%/indexed', PUT, '{}']`
in sync-config.yml
