### ISSUE TITLE
projadm doesn't flush or seek before passing tempfile to config merge causing array out of bounds exception

### ISSUE THREAD

**Issue by dpsi** [oracle/opengrok#2386]
rc49: Finally figured out why I have been having so many issues with config-merge and projadm. The tempfile 'fcur' created in projadm doesn't rewind or flush after writing to it and then immediately passes it to config-merge. This results in a java.lang.ArrayIndexOutOfBoundsException likely because it can see the size of the file but not realize the file handle for it is at the end. 

adding fcur.seek(0) on line 135 of projadm.py fixes this issue. I suspect this might also be needed in other python scripts writing to files.

**Comment by vladak** [comment]
What is the platform you are experiencing this on ?

**Comment by vladak** [comment]
In `projadm` it basically works like this (pseudo-code):
```python
  data = get_configuration()
  with tempfile.NamedTemporaryFile() as fcur:
    fcur.write(data)

    if copy:
      copyfile(fcur.name, dst)
    else:
      args = [..., fcur.name]
      execute(args)
```

After the `with` block is over, i.e. after both the condition branches are done, the `fcur` handle is closed and the temporary file deleted. The 2 consumers of the temporary file do not work with the file handle (i.e. the file descriptor), rather they work with the file name (that's the reason why `NamedTemporaryFile` was used - to make it visible in the file system) and hence they open the file anew. So, they should not be sharing the file offset with the writer. What seems to be happening is that the `write()` (or rather the OS kernel) does not finish writing the data before either `copyfile` or `execute` are called so they end up with incomplete data.

**Comment by vladak** [comment]
Based on https://stackoverflow.com/questions/3167494/how-often-does-python-flush-to-a-file could you try adding `fcur.flush()` below the call to `write()` to see if this helps ? As noted in the Python documentation, this does not write the data to disk however I think this should not be necessary as the kernel buffers (file system cache) should be used anyway when opening the file anew (its `vnode` should be still present in kernel memory given the file has not been closed yet).

**Comment by tulinkry** [comment]
By the way I'm experiencing this as well on macosx.

```
(env) [ktulinger@ktulinger-57GTFM OpenGrok]$ opengrok-projadm --java `which java` --jar distribution/target/dist/opengrok-1.1-rc57.jar --roconfig /tmp/opengrok/etc/groups.xml --configmerge `which opengrok-config-merge` --refresh --upload --uri http://localhost:8080
Lock 4508500096 acquired on /var/folders/w4/fr4pd7zn0x1f9lwc8hsmhbwh0000gp/T/opengrok-projadm.lock
Refreshing configuration (merging with read-only config)
cannot merge configuration
Standard output: []
Error output: ['ERROR:opengrok-config-merge:[\'Oct 09, 2018 10:24:30 AM org.opengrok.indexer.configuration.Configuration read\\n\', \'INFO: Reading configuration from /private/tmp/opengrok/etc/groups.xml\\n\', \'Oct 09, 2018 10:24:30 AM org.opengrok.indexer.configuration.Configuration read\\n\', \'INFO: Reading configuration from /private/var/folders/w4/fr4pd7zn0x1f9lwc8hsmhbwh0000gp/T/tmple9of61c\\n\', \'Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0\\n\', \'\\tat java.beans.XMLDecoder.readObject(XMLDecoder.java:250)\\n\', \'\\tat org.opengrok.indexer.configuration.Configuration.decodeObject(Configuration.java:1361)\\n\', \'\\tat org.opengrok.indexer.configuration.Configuration.read(Configuration.java:1339)\\n\', \'\\tat org.opengrok.indexer.configuration.ConfigMerge.main(ConfigMerge.java:145)\\n\']\n', 'ERROR:opengrok-config-merge:command failed (return code 1)\n']
Lock 4508500096 released on /var/folders/w4/fr4pd7zn0x1f9lwc8hsmhbwh0000gp/T/opengrok-projadm.lock
```

Adding
```python
fcur.flush()
...
fmerged.flush()
```

solves this and the script finishes ok and install my groups to the webapp.

**Comment by vladak** [comment]
Proceed with a PR then :)

Dne út 9. 10. 2018 10:34 uživatel Kryštof Tulinger <notifications@github.com>
napsal:
