### ISSUE TITLE
opengrok-tools should be capable of skipping tests on -DskipTests

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2392]
The tests now run always

**Comment by vladak** [comment]
I just hit this when building behind a proxy. Previously, it was sufficient to have `MAVEN_OPTS` with the proxies, now I have to set `https_proxy` even though I had tests disabled.

**Comment by tulinkry** [comment]
That is the `python setup.py install` I think

**Comment by vladak** [comment]
This is a bit strange given that `python-test` is bound to the `test` phase.

**Comment by tulinkry** [comment]
Yeah, but exec plugin does not react automatically to skipTests property
