### ISSUE TITLE
opengrok-tools version in setup.py needs to be updated automatically or have its own versioning scheme

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2393]
opengrok-tools python package contains a hard-coded version

```python
setup(
    name='opengrok-tools',
    version='1.1rc58',
    packages=[ ...
)
```

We should either
1. run some maven execution to synchronize it with the current version in maven
2. introduce new versioning scheme (for example starting from 0.0.1) and increasing always when there is a change in the package

Let's do some discussion in this thread

**Comment by vladak** [comment]
I'd like to avoid changing https://github.com/oracle/opengrok/wiki/Release-process so better fix this soon.

**Comment by vladak** [comment]
Why exactly it will fail actually ?

**Comment by tulinkry** [comment]
Because of this in assemly.xml

```
      <file>
        <source>${project.basedir}/../opengrok-tools/dist/opengrok-tools-${parsedVersion.majorVersion}.${parsedVersion.minorVersion}${parsedVersion.qualifier}.tar.gz</source>
        <outputDirectory>tools</outputDirectory>
        <destName>opengrok-tools.tar.gz</destName>
</file>
```

the filename mismatch.

**Comment by vladak** [comment]
Also, does the tarball with the tools have to have a version in its name ?

**Comment by tulinkry** [comment]
The template produced by `python setup.py sdist` is something we can't control. Hoewever we can for example put another maven plugin to rename the file to be without the version?

I also find out on https://packaging.python.org/guides/single-sourcing-package-version/ that as setup.py is python we can actually extract the version mentioned in `pom.xml`.

Another thing is that there is a definitely maven plugin which can replace properties in files so we could do the version in setup.py as `version = ${project.version}` and let the plugin to replace it.

However this is the build stage and the version bump is run afterwards (if I got it correctly from the release process) so this doesn't really help us.

**Comment by vladak** [comment]
+1 for renaming the file so it does not contain the version.
