### ISSUE TITLE
got error "java.lang.ArrayIndexOutOfBoundsException" when running indexer.py

### ISSUE THREAD

**Issue by brightchuh** [oracle/opengrok#2396]
Dear OpenGrok developers,

#### My Opengrok version:
opengrok-1.1-rc52

#### Error detail:
ERROR:indexer.py:17:45:25 严重: Unexpected Exception
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.desktop/java.beans.XMLDecoder.readObject(XMLDecoder.java:251)
	at org.opengrok.indexer.configuration.Configuration.decodeObject(Configuration.java:1361)
	at org.opengrok.indexer.configuration.Configuration.read(Configuration.java:1339)
	at org.opengrok.indexer.index.Indexer.lambda$null$1(Indexer.java:405)
	at org.opengrok.indexer.util.OptionParser.parse(OptionParser.java:644)
	at org.opengrok.indexer.index.Indexer.parseOptions(Indexer.java:789)
	at org.opengrok.indexer.index.Indexer.main(Indexer.java:136)

Exception: 0
ERROR:indexer.py:Indexer command failed (return code 1

#### Operation Flow:
1. Deploy opengrok webapp
./deploy.py -c "$OPENGROK/etc/configuration.xml" \
	$OPENGROK/lib/source.war \
	$TOMCAT/webapps/opengrok.war
2. Index the Source dir
./indexer.py -J=-Djava.util.logging.config.file=$OPENGROK/doc/logging.properties \
	-a $OPENGROK/lib/opengrok.jar -- \
	-s $CODE -d $OPENGROK/data -H -P -S -G -v \
	-R $OPENGROK/etc/readonly_configuration.xml -W $OPENGROK/etc/configuration.xml -U http://localhost:8080/opengrok

#### PS:
1. $OPENGROK $CODE are already set in ~/.bashrc
2. readonly_configuration.xml is empty. And I also tried using sample in page "https://github.com/oracle/opengrok/wiki/Project-groups", however still the same error.
3. It's OK if not use "-R $OPENGROK/etc/readonly_configuration.xml" when running indexer.py.

**Comment by vladak** [comment]
I think the read-only configuration has contain at least a boostrap configuration, which can be generated using:
```
./indexer.py -D -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- --updateConfig -U http://localhost:8080/source -W read-only.conf
```

**Comment by vladak** [comment]
As for the "Project-groups" wiki, it still contains old configuration attributes containing `opensolaris` and hence the parsing will fail. Let me fix the wiki.

**Comment by tulinkry** [comment]
Maybe we should consider for this particular exception printing (or rethrowing) something more meaningful, like "the configuration /tmp/.. is empty".

**Comment by brightchuh** [comment]
@vladak @tulinkry Thanks a lot! It works!
BTW, the method to turn on navigation window in WIKI Page"Per-project-configuration" only works for a single project. How can we turn on navigation window for every project?

**Comment by vladak** [comment]
Good to hear. Please file a separate issue for the Navigation window question.

**Comment by brightchuh** [comment]
@vladak New issue #2397 is filed for this already. Thanks!
