### ISSUE TITLE
About "TEMPLATE" and "PATTERN" arguments of reindex-project.py

### ISSUE THREAD

**Issue by brightchuh** [oracle/opengrok#2398]
Dear opengrok developers,

reindex-project.py needs "TEMPLATE" and "PATTERN" arguments, or it will print error info as below:
reindex-project.py: error: the following arguments are required: options, -t/--template, -p/--pattern, -d/--directory

So, where could i find a sample TEMPLATE and PATTERN? Thanks a lot!

**Comment by vladak** [comment]
See the example given on https://github.com/oracle/opengrok/wiki/Repository-synchronization#syncpy

The template is a `logging.properties` file that contains path with the pattern. The goal is that indexer run for each project logs into a separate file.

Do you actually need `reindex-project.py` at all ? Using `indexer.py` to reindex all projects is fine.

**Comment by vladak** [comment]
The reason why pattern has to be separately specified for `reindex-project.py` is that when it is run from `sync.py` all `%PROJECT%` patterns in the command arguments are replaced by actual project name. However, `reindex-project.py` needs to perform pattern replacement by project name itself in the logging template file, so a distinct pattern has to be specified to avoid the substitution by `sync.py`.

**Comment by brightchuh** [comment]
@vladak It's necessary to index a single project if there are many projects in SRC dir, because index all projects will take a long time. Could you please give me a sample usage of reindex-project.py?

**Comment by brightchuh** [comment]
I see this in WIKI Page "Per-project-management", but it seems that this page is too old.

**Comment by vladak** [comment]
In 1.1 at least, the parallelism of indexing big enough it does not make sense to index each project separately in parallel. The parallel processing only makes sense when the **mirroring** part takes a long time.

**Comment by vladak** [comment]
The https://github.com/oracle/opengrok/wiki/Per-project-management seems up to date to me. Why do you think it is old ?

**Comment by brightchuh** [comment]
consider this situation: there're several projects in src dir, only one or two projects' code changes frequently. i only need to reindex these two projects, leaving others alone, instead of index all of them. it will save a lot of time, i think.

**Comment by vladak** [comment]
That's true, definitely a good use case.

Dne út 9. 10. 2018 14:48 uživatel brightchuh <notifications@github.com>
napsal:

**Comment by brightchuh** [comment]
So, is it suitable to use reindex-project.py for this usecase? if yes, could you please give me a sample usage? i tried input the arguments mentioned in title, however it stilll print error: please input argument option. i do not know why

**Comment by vladak** [comment]
Definitely. For example to reindex project `foo`:
```
reindex-project.py --jar /opengrok/dist/lib/opengrok.jar \
    -t /opengrok/etc/logging.properties.template \
    -p '%PROJ%' -d /opengrok/log/foo -P foo -- \
        -c /usr/local/bin/ctags -H foo foo
```

**Comment by vladak** [comment]
What is the exact command you ran that caused the error ?

**Comment by vladak** [comment]
Anyhow, `reindex-project.py` is meant to be run from `sync.py` along with `mirror.py` that performs repository mirroring. That said, `mirror.py` does not give any indication as to whether any of given project's repositories actually received any changes (#2399) so `sync.py` will continue the execution process anyway.

**Comment by brightchuh** [comment]
**My command:**
```
./reindex-project.py --jar $OPENGROK/lib/opengrok.jar \
	-U http://localhost:8080/opengrok \
    -t $OPENGROK/doc/logging.properties \
    -p '%PROJ%' -d $OPENGROK/log -P coreutils
```
**Error info:**

> reindex-project.py: error: the following arguments are required: options

Then I found the error gone after "-- -H" was omitted to the end of the command.

**Comment by vladak** [comment]
Yes, you need to pass some indexer options. `reindex-project.py` usage is quite clear about it:
```
usage: reindex-project.py [-h] [-D] [-j JAVA] [-J JAVA_OPTS] [-e ENVIRONMENT]
                          (-a JAR | -c CLASSPATH) -t TEMPLATE -p PATTERN -P
                          PROJECT -d DIRECTORY [-U URI]
                          options [options ...]
```
i.e. the `options` argument is mandatory.

As a side note, after cset 22478587 (#2334) it is no longer necessary to specify the project as argument to `-H`; in fact it is undesirable because it would any skip sub-repositories of a project.

**Comment by brightchuh** [comment]
I just tried  1.1-rc58, still the same. What's your command?

**Comment by brightchuh** [comment]
Sorry, forget my last reply, wrong issue.
