### ISSUE TITLE
consider adding logic to mirror.py to detect and indicate changes

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2399]
Currently `mirror.py` does not detect if any change to the project was actually done. This means `sync.py` will continue running subsequent commands like `reindex-project.py` unnecessarily. For at least some SCMs it might be possible to detect if any changes were received and `mirror.py` could then indicate this to `sync.py` via special exit code (similarly to what it currently does when a project is disabled).

**Comment by tulinkry** [comment]
+1
