### ISSUE TITLE
indexer.py should display stderr output from the Indexer continuously

### ISSUE THREAD

**Issue by brightchuh** [oracle/opengrok#2403]
Dear experts,

Detailed description as below:
**opengrok version:**
1.1-rc52
**command:**
```
./indexer.py \
	-a $OPENGROK/lib/opengrok.jar -- \
	-s $CODE -d $OPENGROK/data \
	-R $OPENGROK/etc/readonly_configuration.xml -W $OPENGROK/etc/configuration.xml \
	-U http://localhost:8080/opengrok \
	-H -P -S -G -v --progress -t 4
```
**Expact:**
print the progress of indexing
**Actuallity**
does not print any progress info

**Comment by vladak** [comment]
Works for me with the latest `master`, i.e. I can see log entries like:
```
Oct 10, 2018 10:38:04 AM org.opengrok.indexer.index.IndexDatabase getFileCount
INFO: Counting files in /universal-ctags ...
Oct 10, 2018 10:37:45 AM org.opengrok.indexer.index.IndexDatabase printProgress
INFO: Progress: 1 (100%)
```

**Comment by brightchuh** [comment]
I just tried 1.1-rc58, still the same. What's your command?

**Comment by vladak** [comment]
The options are:
```
-W
/var/opengrok/etc/configuration.xml
-c
/usr/local/bin/ctags
-s
/var/opengrok/src
-d
/var/opengrok/data
-P
-S
-H
-U
http://localhost:8080/source
--progress
```
The presence of other options is very likely not relevant.

**Comment by vladak** [comment]
I think the problem here is that no logger is specified and that `indexer.py` will not display the output of the Java program. If I use the same options and run the indexer with `java` directly, the output will get sent to `stderr`.

**Comment by vladak** [comment]
As the documentation (https://docs.oracle.com/javase/8/docs/api/java/util/logging/ConsoleHandler.html) says:
> This Handler publishes log records to System.err

**Comment by vladak** [comment]
In `indexer.py`, output written to `stderr` is only printed when the program fails. For continuous display of logs this would not work anyway because the output is only displayed after the program is done. So, the best would be to use `-J=java.util.logging.config.file=logging.properties` when the logging is configured to be written to a file (using `java.util.logging.FileHandler`) and `tail -f` the file during indexer run.

**Comment by vladak** [comment]
There is likely a way how to make the `Indexer` output continuously displayed on the console from `indexer.py`, marking as enhancement for now.
