### ISSUE TITLE
opengrok main page becomes outdated because of caching

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2405]
I figured out today that the main page (or other pages also maybe) send `Cache-Control: max-age=1800` which can make it

1. outdated for some time after the reindex
2. break the cookies (user search for projects, clicks on home, on homepage there is the cached set of cookie projects)
3. display messages that are no longer present in the system

only hitting full refresh (ctrl+shift+R) can fetch the updated version.

This must have been introduced to opengrok lately.

**Comment by tulinkry** [comment]
On related note, when there is a message on a project (or tag main) it is usually visible on the xref however sometimes the page is outdated to and the message is visible eventhough it's already gone.

**Comment by vladak** [comment]
That's the trade-off of caching I guess.

**Comment by vladak** [comment]
The caching directives were added to `web.xml` via #1842.

**Comment by tulinkry** [comment]
But for the main page it’s to loose

10. 10. 2018 v 16:18, Vladimir Kotal <notifications@github.com>:

**Comment by vladak** [comment]
I think that depends on the deployment in question. I have not noticed the issue with the default 30 minutes interval.

**Comment by tulinkry** [comment]
It's not just about deployment. The interaction with the cookies is broken this way.

You select some projects, do a search (this should save the project to the cookie). And then navigate to home and you get the cached page with different set of project than you just searched.

**Comment by vladak** [comment]
What exactly happens in such a case ? Do no longer existing projects get removed or is some sort of error thrown ? If the former then I think it's okay.

**Comment by tulinkry** [comment]
### Like I said, you select some projects:
<img width="1100" alt="screen shot 2018-10-12 at 09 25 32" src="https://user-images.githubusercontent.com/6997160/46854339-d691c780-ce00-11e8-8071-2c8d0d82d906.png">
<hr />

### Do a search (see you have the correct set of projects from previous step):
<img width="1100" alt="screen shot 2018-10-12 at 09 25 42" src="https://user-images.githubusercontent.com/6997160/46854340-d72a5e00-ce00-11e8-8b77-36afc31873d4.png">
<hr />

### Click home, and the set of projects is different than what was searched:
<img width="805" alt="screen shot 2018-10-12 at 09 25 49" src="https://user-images.githubusercontent.com/6997160/46854341-d72a5e00-ce00-11e8-8112-ddc942a638c9.png">

**Comment by vladak** [comment]
Is this really related to caching ? Sounds more like #1447.

**Comment by tulinkry** [comment]
### I tried more. It seams that in the response the selected projects in the `<select>` elements are correct
<img width="579" alt="screen shot 2018-10-12 at 10 03 34" src="https://user-images.githubusercontent.com/6997160/46856255-30e15700-ce06-11e8-97f3-1c1a8b19919d.png">

### However the project picker displays different set of projects:
<img width="463" alt="screen shot 2018-10-12 at 10 03 39" src="https://user-images.githubusercontent.com/6997160/46856279-3fc80980-ce06-11e8-8291-a4d06ed80892.png">

**Comment by tulinkry** [comment]
But it must be related to caching because if I set `Cache-Control: no-cache` for the main page, it works as expected.

**Comment by vladak** [comment]
fixed in cset b3d4315.
