### ISSUE TITLE
The 'all' python scripts installed to top-level directory

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2413]
After `pip install` of the `opengrok-tools` Python package the scripts under `all` are installed to top-level directory, e.g. into `lib/python3.4/site-packages/all` under venv directory root. Instead, they should be under `opengrok_tools` directory therein I believe.

**Comment by tulinkry** [comment]
My problem with this was that I wanted:

1. be able to run the script in the env (`python src/..../deploy.py`), thus be able to develop the scripts
2. be able to run the entry points (after install `opengrok-deploy`)

This was the only way I achieved this. I didn't see that all is going to be a separate python package (not under opengrok-tools).

**Comment by vladak** [comment]
fixed by cset 394d7f3
