### ISSUE TITLE
How to ignore files and folders in version 1.1-rc68

### ISSUE THREAD

**Issue by peng6662001** [oracle/opengrok#2471]
I want to ignore some folders such as camera
Use commands like this:
export OPENGROK_IGNORE_PATTERNS="-i d:camera" 
opengrok-indexer -J=-Djava.util.logging.config.file=/WD/opengrok/logging.properties \
    -a /opt/opengrok/lib/opengrok.jar -- \
    -s /WD/Android/Source/aosp/frameworks/av -d /WD/opengrok/data/androidP -H -P -S -G \
    -W /WD/opengrok/etc/androidP/configuration.xml -U http://localhost:8080

After index the source,I find camera is still indexed in /WD/opengrok/data/androidP/xref.
Please help to exclude the folder.

**Comment by vladak** [comment]
The environment options are gone. You need to supply the -i option directly to the indexer.

For more info see `opengrok-indexer -a /opt/opengrok/lib/opengrok.jar -- -v -h`

**Comment by vladak** [comment]
Also see https://github.com/oracle/opengrok/wiki/Python-scripts-transition-guide
