### ISSUE TITLE
add README to distribution tarball with instructions on how to install and run opengrok-tools

### ISSUE THREAD

**Issue by jvaneck** [oracle/opengrok#2486]
Can someone please tell me how to execute the new opengrok-tools indexer? I was previously able to run this: /opengrok-1.1-rc58/bin/indexer.py 

But this folder is now in /opengrok-1.1-rc70/tools/opengrok-tools.tar.gz and if I extract those contents I seem to get an entirely new setup app??? Can I just run the indexer command like I was before in rc58? If not, what do I need to run?

Is there any documentation or manuals for this tar?

Thanks for any help you're able to provide

**Comment by vladak** [comment]
The tools tarball is actually a Python package. The command to install is on https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step1---install-management-tools-optional

Then it is possible to run the scripts using their Python *entry points*, e.g. `opengrok-indexer`.

That said, you do not need to run the indexer using the Python wrappers unless you need some of its functionality. In general it is sufficient to run the indexer using plain `java -jar opengrok.jar -- [indexer options]`.

**Comment by vladak** [comment]
Actually, let's ship a README file in the `tools` directory with simple instructions.

**Comment by tulinkry** [comment]
It is there also with https://github.com/oracle/opengrok/tree/master/opengrok-tools#installation

**Comment by tulinkry** [comment]
One thing is as I see `python3 -m pip install opengrok_tools-{version}.tar.gz` it is outdated. We dont have the version in it.

**Comment by tulinkry** [comment]
Second thing it might be confusing for the end user what is the installation (there is dev installation and prod installation)

**Comment by vladak** [comment]
I'd like to avoid shipping the current README since as you mention, it contains developer type info.

**Comment by tulinkry** [comment]
I misread your comment. Yes we should ship some readme in the tools dir (I misread in the tools package).

**Comment by vladak** [comment]
version fixed in cset ef9d63d

**Comment by jvaneck** [comment]
Thanks guys for the updates. 

Although I didn't say it specifically, this is exactly the kind of discussion I was looking for. Thanks for the clarification and helping the next person out as well. The one thing that was (originally) confusing to me was 'what is this tools thing and why is there an installer. Is this required?' and I think all your notes/comments/future plans seems to correct that for the next person
