### ISSUE TITLE
add sync.py option to drive on even if a command in sequence requests break

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2510]
Sometimes, I need `sync.py` to drive on even if one of the commands in the sequence requests break, e.g. `mirror.py` when run with -I and there is nothing to pull from the remote.

**Comment by tulinkry** [comment]
Why should `sync.py` continue with anything else then cleanup if there was no new data from the remote?

**Comment by vladak** [comment]
This is needed in case a project needs to be reindexed from scratch however sync.py config file runs mirror.py with -I.

**Comment by tulinkry** [comment]
wpuldn't it be worth it if we supported this particular case by default?

**Comment by vladak** [comment]
which one do you mean ? The -I option for `mirror.py` or change the logic of the termination in `CommandSequence` so that it breaks the cycle only if explicitly specified in the init function ?
