### ISSUE TITLE
JDK9+ support

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2513]
This will need some workaround for the `coveralls-maven-plugin` as described in #2255.

**Comment by vladak** [comment]
Once solved, this will make it possible to broaden the build matrix in Travis (`jdk: oraclejdk9` for Linux builds and bumping `xcode` version for macOS builds)

**Comment by tulinkry** [comment]
How about to skip the coverall for jdk9?

**Comment by vladak** [comment]
Well, I'm worried that it will be forgotten forever then. Maybe there is a
way how to compile patched version during the build of the plugin and use
that.

pá 16. 11. 2018 17:53 odesílatel Kryštof Tulinger <notifications@github.com>
napsal:

**Comment by vladak** [comment]
Maybe you're right. It's not our problem that external dependency is broken. Maybe the Coveralls guys will realize that this is a problem as people will stop using the service.

**Comment by tulinkry** [comment]
Personally, I'd drop it for newer jdk. It's not like our life depend on it so there is not a problem I think.
