### ISSUE TITLE
When a file has been changed in the source tree I get “Failed to get xref file” in the web browser.

### ISSUE THREAD

**Issue by mattievanotten** [oracle/opengrok#2514]
I am setting up an opengrok system and find the following problem:
When update the file assoc.c in the source tree I get “Failed to get xref file” in the web browser
http://130.139.165.42:8080/source/xref/memcached-master/assoc.c
I expect that the web browser shows same as before the update but, with the update.
It can be that I have a wrong expiation of OpenGrok!
The file can be opened in Raw mode.
Is there a command to fix these errors, or is this normal behavior?

Tool versions:
opengrok-1.1-rc41
apache-tomcat-9.0.13
entos-release-7-5.1804.5.el7.centos.x86_64
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
Web browser IE 11, chrome 70.0, Firefox 63.0.1 
Index command:
```
java -Xms5G -Xmx10G -jar /opt/opengrok_stuff/opengrok-1.1-rc41/lib/opengrok.jar -m 128 \
    -H \
    -W /opt/opengrok_stuff/result/etc/configuration.xml \
    -c /usr/local/bin/ctags \
    -T 7 \
    -P \
    -S \
    -v \
    -s /opt/opengrok_stuff/searchdata \
    -d /opt/opengrok_stuff/result/data \
    --depth 10
```
PS On windows 7 I have the same issue.

**Comment by vladak** [comment]
You mean that the file was updated without reindex ?

**Comment by vladak** [comment]
Also, how exactly was the file updated ?

**Comment by mattievanotten** [comment]
Hi Vladimit,

I have the file updated buy an editor.
Added a comment * M van Otten 2018-11-15

Regards,
                Mattie

Mattie van Otten
Senior CADE Application engineer, IT I2M Technical Applications and IT for R&D
Philips

Veenpluis 4-6, Building QJ0-104-G, 5684 PC Best, The Netherlands
Tel +31 6 11732813, Email mattie.van.otten@philips.com<mailto:mattie.van.otten@philips.com>

**Comment by mattievanotten** [comment]
Hi Vladimir,

When the index is done do I have it to run it again when the data has been changed?
Run again = reindex


Regards,
                Mattie

Mattie van Otten
Senior CADE Application engineer, IT I2M Technical Applications and IT for R&D
Philips

Veenpluis 4-6, Building QJ0-104-G, 5684 PC Best, The Netherlands
Tel +31 6 11732813, Email mattie.van.otten@philips.com<mailto:mattie.van.otten@philips.com>

**Comment by vladak** [comment]
Yes, once data is changed on disk you need to reindex so that index becomes consistent again (this could lead to even more strange behaviour esp. if files were removed). As for the failure, I am not sure whether this is a bug or feature :-)

**Comment by vladak** [comment]
added https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step4---setting-up-periodic-reindex as a result.

**Comment by mattievanotten** [comment]
Hi Vladimir,

Thanks for the answer.

At the link you send they are talking about ‘python3 -m pip install opengrok-tools.tar.gz’
Where can I download the file opengrok-tools.tar.gz?

Regards,
                Mattie

Mattie van Otten
Senior CADE Application engineer, IT I2M Technical Applications and IT for R&D
Philips

Veenpluis 4-6, Building QJ0-104-G, 5684 PC Best, The Netherlands
Tel +31 6 11732813, Email mattie.van.otten@philips.com<mailto:mattie.van.otten@philips.com>

**Comment by tulinkry** [comment]
It's written there https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step1---install-management-tools-optional. It's a part of the release tarball.

**Comment by mattievanotten** [comment]
I am get lost.
OpenGrop is running okay after the first index.
https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok
I have also installed: python3.6 -m pip install opengrok-tools.tar.gz
I didn’t use the opengrok-indexer command but the java version direct.
So far okay.
After updating the source code which has been indexed I want to periodic reindex the current project.
See https://github.com/oracle/opengrok/wiki/Repository-synchronization
There you find the command opengrok-sync
$ opengrok-sync -c /scripts/sync.conf -d /ws-local/

I haven’t an idea what should be in the sync.conf!
I have tried the first part which is on previous script.
[nly17943@NLYBSTQVP4CADE003 scripts]$ more sync.config 
- command:
  - http://localhost:8080/source/api/v1/messages
  - POST
  - cssClass: info
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
[nly17943@NLYBSTQVP4CADE003 scripts]$ opengrok-sync -c ./sync.config -d ./
cannot open './sync.config'
Cannot read config file from ./sync.config
[nly17943@NLYBSTQVP4CADE003 scripts]$
Opengrok can’t open the sync.config!!! It can be wrong but it compliance that the file can’t be opened!
 Or should I use opengrok-reindex-project?? How.
Is there some more explanation of the commands and are the some basic examples?

**Comment by vladak** [comment]
There are several options (actually one more if you do not want to use projects but let's leave it aside for now):
  - synchronize your repositories by hand (e.g. by running `git pull` and such) and run the indexer directly with `java -jar ...`.
  - use `opengrok-mirror` together with the way how you run the indexer now, e.g. something like:
```shell
    opengrok-mirror -c mirror.yml ... && \
        java -jar opengrok.jar -s ... -d ...
```
  - same as previous except the indexer is run via `opengrok-index` which is handy if you have JRE installed in some non-default location.
  - use `opengrok-sync`,  `opengrok-mirror`, `opengrok-projadm`, `opengrok-reindex-project` to achieve both parallel (on project level) mirroring and reindex.

The first 3 options are really pretty much the same and they are recommended if you have limited number of projects which are similar w.r.t. mirroring time. The last one is more complicated and requires to use special workflow - add/remove a project via `opengrok-projadm` and then perform repository syncing and project reindex via `opengrok-sync` which will run a sequence of commands to facilitate this.

**Comment by vladak** [comment]
As for the `opengrok-sync` failing to read the config file, this is the consequence of it using `chdir("/")` before the config file is read in. You need to specify the path as absolute.

**Comment by vladak** [comment]
Examples of configuration files for both `opengrok-sync` and `opengrok-mirror` can be found on https://github.com/oracle/opengrok/wiki/Repository-synchronization
