### ISSUE TITLE
TLS failures when running setup.py on newer macOS builds in Travis due to missing CA bundle

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2528]
Newer xcode environments in Travis fail with TLS failures due to missing CA bundles when running `setup.py`.

**Comment by vladak** [comment]
This is blocking transition of the macOS builds to newer JDK.

**Comment by vladak** [comment]
Example of the failure:
```
[INFO] --- exec-maven-plugin:1.6.0:exec (Install python package for tests/pylint) @ opengrok-tools ---

Download error on https://pypi.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051) -- Some packages may not be found!

Couldn't find index page for 'pytest-runner' (maybe misspelled?)
```

**Comment by vladak** [comment]
This failure is described in pypa/pip#4205

Installing `certifi` Python package (globally or in the venv) did not help.

The Linux builds succeed so the Python there has to access to a CA bundle.

**Comment by vladak** [comment]
Looks like macOS also needs to run `Install Certificates.command` after the `certifi` installation: https://stackoverflow.com/a/56031239/11582827

**Comment by vladak** [comment]
I think https://github.com/pypa/pip/issues/4205#issuecomment-290587840 is the closest to what is happening as it is the setuptools based installation that is failing.

**Comment by vladak** [comment]
> Looks like macOS also needs to run `Install Certificates.command` after the `certifi` installation: https://stackoverflow.com/a/56031239/11582827

This only works if using official Python distribution, not the one from HomeBrew like the macOS build uses.

**Comment by vladak** [comment]
Tried to reproduce the problem in https://github.com/vladak/setuptools_certs however failed so far.

**Comment by tulinkry** [comment]
I am not able to reproduce the error. I took your setup, added maven, did some small changes to match it to the current situation in opengrok: https://github.com/tulinkry/setuptools_certs

```
mvn verify
```
executes just fine

**Comment by tulinkry** [comment]
I think I got it, the commit which broke it is https://github.com/tulinkry/setuptools_certs/commit/a683be89d00966ccab52df19416bc4c4e10af65e.

**Comment by tulinkry** [comment]
After series of tries this addon
```
  coverity_scan:
    project:
      name: OpenGrok/OpenGrok
      description: Build submitted via Travis CI
      branch_pattern: coverity_scan
      build_command: ./mvnw -DskipTests=true -Dmaven.javadoc.skip=false -B -V compile
```

seems to fail the build always with the TSL errors.

**Comment by vladak** [comment]
Good job ! It would never occur to me this could be caused by one of the plugins. The plugin overwrites all CA certs by per host cert.

I am all for disabling Coverity for good, there is Sonar and LGTM.

**Comment by vladak** [comment]
There does not seem to be a way how to create issue for https://github.com/travis-ci/travis-build so I sent them an e-mail.
