### ISSUE TITLE
support file encoding detection

### ISSUE THREAD

**Issue by sslvjun** [oracle/opengrok#2532]
Is it possible to support file encoding detection when reading files? File encoding garbled is  very troublesome while reading code.

**Comment by sslvjun** [comment]
May be GBK, Unicode and so on. Multiple encodes may exist in a project at the same time.  Before index is built, convert file encoding to such as UTF-8，this is a very terrible thing.

**Comment by vladak** [comment]
Well, introducing additional complexity by having to support multiple
encodings, let alone adding complicated and unreliable heuristics would be
bad for OpenGrok too. We can mark this as an enhancement however the
probability of it to be implemented is very low unless you want to step up
and do the work yourself. I think most of the world is moving towards UTF-8.

so 24. 11. 2018 3:16 odesílatel sslvjun <notifications@github.com> napsal:

**Comment by sslvjun** [comment]
Eh, thank you for your response.
