### ISSUE TITLE
Find the same line in the same file multiple times after running indexing again on Windows

### ISSUE THREAD

**Issue by mattievanotten** [oracle/opengrok#2565]
When the repository has been updated I run the index command.
`java -Xms5G -Xmx10G -jar lib\opengrok.jar -m 128  -H -W d:\grokresults\source\etc\configuration.xml -T 6  -c C:\opengrok\ctags\ctags.exe - P -S -v -s d:\searchdata\source -d d:\grokresults\source\data –depth10`
If I have done that three time I get the following result in the web browser:
Searched full:bugfix (Results 1 – 3 of 3) sorted by relevance

/memcached-master/
H A D	ChangeLog	11 * *critical bugfix*. In 1.2.7 under multithreaded mode, memcached
H A D	ChangeLog	11 * *critical bugfix*. In 1.2.7 under multithreaded mode, memcached
H A D	ChangeLog	11 * *critical bugfix*. In 1.2.7 under multithreaded mode, memcached
Completed in 234 milliseconds
I don’t understand why I find three times the same result! 
This is in Windows 7.
If I do the same is Linux Centos 7, then it works okay.
Why does Linux work okay and Windows 7 not?
We prefer Windows because the data which must be indexed is available on a windows platform.
Versions:
opengrok-1.1-rc41
apache-tomcat-9.0.13

We use the same versions on windows and linux.

Windows Java:
```
C:\opengrok\opengrok-1.1-rc41>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
```
![opengrokweb](https://user-images.githubusercontent.com/41118389/49236521-93190a00-f3fc-11e8-88ca-c5f49c6b436a.png)

Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
 Linux Java
```
 openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by vladak** [comment]
I vaguely remember similar issue. Firstly, could you check with the latest 1.1 RC ?

**Comment by mattievanotten** [comment]
I have tested 1.1-rc76  and the problem is solved!
