### ISSUE TITLE
Files with .e suffix do not display properly in OpenGrok UI

### ISSUE THREAD

**Issue by nd-krieg** [oracle/opengrok#2577]
Another team at my company has been using OpenGrok with our software for almost 2 years.  They are using release 0.13 and are not having issues with the display of .e files.  But their server is not reliable and is down frequently, so I installed the latest version (1.1-rc70 and then 1.1-rc76) on a different machine.  It parses the .e files properly and gives the same search result line numbers as the older version.  However, when the .e file is displayed on the screen, it sometimes doesn't detect end of line, and sometimes it skips part of the file, so the line numbers it gave don't resolve properly.

I will attach photos of the same code being shown in both versions of OpenGrok. 
Here is the file incorrectly rendered on a server running 1.1-rc76

![image](https://user-images.githubusercontent.com/12236779/49400821-05def980-f70b-11e8-8495-d88c199a6e1e.png)

Here is the file correctly rendered on a server running 0.13.
![image](https://user-images.githubusercontent.com/12236779/49400836-0ecfcb00-f70b-11e8-89ff-2c07b8ac85ec.png)

I used a Hex editor to look at the files in question.  I don't think the file type has anything to do with it.  The places in the file where the UI gets messed up have double line feeds (0A 0A).

Here is a section of the code from what is displayed in the images. Line 00004B8C  shows the first double line feed where the display starts to get messed up.

00004A9C  61 6E 73 21 20 54 68 69 73 20 61 6C 73 6F 20 63 61 75 73 65 ans! This also cause
00004AB0  64 20 54 61 72 64 69 73 20 63 72 61 73 68 65 73 2E 0A 0A 31 d Tardis crashes...1
00004AC4  30 20 4D 61 79 20 32 30 30 31 20 4A 41 48 20 20 4D 52 49 67 0 May 2001 JAH  MRIg
00004AD8  65 36 36 30 32 39 3A 20 52 6F 75 6E 64 69 6E 67 20 6F 66 20 e66029: Rounding of 
00004AEC  61 76 6D 69 6E 73 6C 73 70 61 63 65 20 63 61 75 73 65 64 20 avminslspace caused 
00004B00  72 6F 75 6E 64 69 6E 67 0A 20 20 20 20 20 20 20 20 20 20 20 rounding.
00004B14  20 20 20 20 20 20 65 72 72 6F 72 73 20 74 6F 20 74 68 72 6F       errors to thro
00004B28  77 20 72 65 70 65 74 69 74 69 76 65 20 65 72 72 6F 72 20 6D w repetitive error m
00004B3C  65 73 73 61 67 65 73 2E 20 44 6F 6E 27 74 0A 20 20 20 20 20 essages. Don't.
00004B50  20 20 20 20 20 20 20 20 20 20 20 20 72 6F 75 6E 64 20 2D 2D             round --
00004B64  20 6D 75 6C 74 69 70 6C 79 20 75 70 20 61 6E 64 20 63 61 73  multiply up and cas
00004B78  74 20 74 6F 20 69 6E 74 65 67 65 72 20 61 74 20 65 72 72 6F t to integer at erro
00004B8C  72 20 63 68 65 63 6B 2E 0A 0A 31 30 20 4D 61 79 20 32 30 30 r check...10 May 200
00004BA0  31 20 4A 41 48 20 20 4D 52 49 67 65 36 36 31 35 30 3A 20 41 1 JAH  MRIge66150: A
00004BB4  64 64 65 64 20 32 44 2F 33 44 20 63 68 61 6E 67 65 73 20 66 dded 2D/3D changes f
00004BC8  6F 72 20 6D 61 78 69 6D 75 6D 20 43 53 49 0A 20 20 20 20 20 or maximum CSI.
00004BDC  20 20 20 20 20 20 20 20 20 20 20 20 65 6E 63 6F 64 69 6E 67             encoding
00004BF0  20 72 65 73 6F 6C 75 74 69 6F 6E 73 20 74 6F 20 6D 61 6B 65  resolutions to make
00004C04  20 74 68 65 6D 20 6C 69 6B 65 20 6E 65 75 72 6F 20 53 49 2E  them like neuro SI.
00004C18  0A 0A 31 35 20 4D 61 79 20 32 30 30 31 20 4A 41 48 20 20 4D ..15 May 2001 JAH  M
00004C2C  52 49 67 65 36 36 33 32 32 3A 20 43 68 65 63 6B 20 65 78 69 RIge66322: Check exi
00004C40  73 74 65 6E 63 65 20 6F 66 20 6F 70 73 6C 71 75 61 6E 74 20 stence of opslquant 
00004C54  62 65 66 6F 72 65 20 64 65 63 69 64 69 6E 67 0A 20 20 20 20 before deciding.
00004C68  20 20 20 20 20 20 20 20 20 20 20 20 20 74 6F 20 75 73 65 20              to use 
00004C7C  32 44 20 6F 72 20 33 44 20 43 53 49 20 72 65 73 6F 6C 75 74 2D or 3D CSI resolut
00004C90  69 6F 6E 20 6C 69 6D 69 74 73 2E 0A 0A 31 38 20 4D 61 79 20 ion limits...18 May
00004CA4  32 30 30 31 20 4A 41 48 20 20 4D 52 49 67 65 36 36 33 39 33 2001 JAH  MRIge66393
00004CB8  3A 20 52 65 64 75 63 65 20 74 68 65 20 66 6C 69 70 20 61 6E : Reduce the flip an
00004CCC  67 6C 65 20 73 74 65 70 20 77 68 65 6E 20 64 6F 69 6E 67 0A gle step when doing.
00004CE0  20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 6D 75 6C                  mul
00004CF4  74 69 70 6C 65 2D 68 69 74 20 73 61 74 73 2E 0A 0A 32 35 20 tiple-hit sats...25 
00004D08  4D 61 79 20 32 30 30 31 20 4A 41 48 20 20 4D 52 49 67 65 36 May 2001 JAH  MRIge6
00004D1C  36 35 30 38 3A 20 54 52 5F 50 41 53 53 20 77 61 73 20 6D 6F 6508: TR_PASS was mo
00004D30  76 65 64 20 66 72 6F 6D 20 74 6D 69 6E 5F 74 6F 74 61 6C 20 ved from tmin_total 
00004D44  74 6F 20 74 6D 69 6E 2E 0A 20 20 20 20 20 20 20 20 20 20 20 to tmin..
00004D58  20 20 20 20 20 20 62 65 63 61 75 73 65 20 61 6E 79 20 6F 74       because any ot
00004D6C  68 65 72 20 74 69 6D 69 6E 67 20 6C 69 6D 69 74 61 74 69 6F her timing limitatio
00004D80  6E 20 61 6C 72 65 61 64 79 20 61 6C 6C 6F 77 73 0A 20 20 20 n already allows.   
00004D94  20 20 20 20 20 20 20 20 20 20 20 20 20 20 65 6E 6F 75 67 68               enough
00004DA8  20 64 65 61 64 20 74 69 6D 65 20 66 6F 72 20 74 68 65 20 53  dead time for the S
00004DBC  70 65 63 74 72 6F 50 72 65 73 63 61 6E 20 73 63 72 65 65 6E pectroPrescan screen
00004DD0  0A 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 70 61 .                 pa
00004DE4  73 73 20 70 61 63 6B 65 74 73 2E 20 41 64 64 65 64 20 74 68 ss packets. Added th
00004DF8  65 20 54 52 5F 50 41 53 53 20 61 63 63 6F 75 6E 74 69 6E 67 e TR_PASS accounting
```

**Comment by vladak** [comment]
Could you attach the file to the issue pls ?

**Comment by vladak** [comment]
So, perhaps using something like `-A .e:org.opengrok.indexer.analysis.c.CxxAnalyzerFactory` would help given that it was mentioned on Slack that the contents of the .e files actually resemble C ?

**Comment by nd-krieg** [comment]
I will try your suggestion above.

I cannot supply the file since it contains proprietary information.

You don't think it is a significant that the parts which display incorrectly match up with the double LF characters?

**Comment by nd-krieg** [comment]
Using the CxxAnalyzerFactory worked!  Thanks for the support!

**Comment by idodeclare** [comment]
`Cxx` is actually for C++. `C` is for C.

OpenGrok also allows using just the prefix. E.g. the following are all equivalent:

`-A .e:org.opengrok.indexer.analysis.c.CAnalyzerFactory`
`-A .e:CAnalyzerFactory`
`-A .e:CAnalyzer`
`-A .e:C`

If you wanted explicitly to operate as does version 0.13, you would clear the mapping:

`-A .e:-`

so that the plain-text heuristic is active as a fallback for `.e` files. Or you could explicitly map the `PlainAnalyzerFactory`:

`-A .e:Plain`

(N.b. the case-sensitivity of the class name.)

**Comment by vladak** [comment]
Nice explanation, adding to https://github.com/oracle/opengrok/wiki/Indexer-configuration

I assume that there is no strong desire to add new analyzer for the proprietary E language, hence closing.
