### ISSUE TITLE
Feature Request:  Select multiple file types

### ISSUE THREAD

**Issue by gtoph** [oracle/opengrok#2580]
Would be nice if we could select multiple file types to search through, such as looking for a string in all "C" and "python" type files for example.

**Comment by vladak** [comment]
I think the underlying service can support multiple types just fine, it is just a matter of changing the UI.

**Comment by tulinkry** [comment]
Yes this is supported, but not selectable in the ui.

<img width="603" alt="screenshot 2019-02-17 at 14 06 26" src="https://user-images.githubusercontent.com/6997160/52913321-463b2600-32bd-11e9-8b64-e8f44c38de37.png">

**Comment by gtoph** [comment]
There was a 'multiple' option I found in one of the jsp files that turned the type list into a checkbox from radio and allowed multiple selections, but it needs a little work as far as ui behavior and actually sending those multiple selections to the searching framework.

**Comment by vladak** [comment]
The trouble with the UI is that the language selector is implemented via searchable-option-list (SOL) and therefore is supplemented by rectangles - just like the project picker. Having another rectangle "cloud" next to the search form si unwanted, I think.

**Comment by ahornace** [comment]
Closing as duplicate in favour of #1537
