### ISSUE TITLE
git pull --ff-only fails and does not synchronize the repository

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2583]
For one of my repositories (possible rewriten history, related to #2432)
`git pull --ff-only` fails:

```
bash-4.1$ /opt/git/git283/bin/git pull --ff-only
fatal: Not possible to fast-forward, aborting.
```

When I try to do `git pull`:
```
bash-4.1$ /opt/git/git283/bin/git pull

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident  <xxx> not allowed
```
it fails (I think when trying to do the merge commit).

The approach we used in company scripts before was:
```
git fetch
git reset --hard origin/master
```

which updates the repository correctly to the latest commit even when there was the mentioned problem.

**Comment by vladak** [comment]
How is this related to #2432 ?

**Comment by tulinkry** [comment]
I think with the modified history

**Comment by vladak** [comment]
I meant what is actually requested here.

When history is rewritten in remote, everything is in the air w.r.t. history index and therefore the Lucene index as well. Like you said, the cure is to revert the local to common point in history and reindex from scratch.

**Comment by tulinkry** [comment]
if we can handle the case or is it a side case?

**Comment by vladak** [comment]
It might be handy to have a means how to ***help***. Maybe the current tools are almost enough - detect/handle the repository and remove the index data in (universal/global) pre-mirroring hook and let the indexer do the job (assuming per-project setup and `opengrok-sync` script). Or, this could be a bit smarter by toggling the project's `indexed` flag and switching it on only after the reindex is done.

**Comment by tulinkry** [comment]
Ah yes.

Also what I had in mind was to allow users to specify the repository specific update command (instead of hard coded git pull ffonly).

There is already a section commands in mirror config.

**Comment by vladak** [comment]
This is maybe too flexible, i.e. giving users too much ammo to shoot themselves in the foot but that's just my opinion (in other words: having too much tunables is bad).

**Comment by vladak** [comment]
I mean the `-ff-only` was added so that it does not trigger merge and thus keep the syncing process non-interactive until something which needs intervention happens.

**Comment by 45hvnL** [comment]
Should this still be open?

**Comment by vladak** [comment]
Probably not. I don't think we want to `git reset --hard <branch>` as that would hide the original problem.

**Comment by vladak** [comment]
Also, I gather this is related to the Python tools since this is where the fetch/pull is done.

**Comment by 45hvnL** [comment]
> Probably not. I don't think we want to `git reset --hard <branch>` as that would hide the original problem.

Is the _original problem_ you refer to something like the occasionally (naughty!) developer changing history on the main branch? When this happens, we don't want mirroring, and therefore what's available in the web-app, to be stale for everyone until someone manually does a `git reset --hard <branch>` on the local repo. Maybe it should be an option, unless a better solution is available? 
In my case, I'm using the OpenGrok Docker image, and wondering how I can deal with the problem I described.
