### ISSUE TITLE
where can I disable suggester ?

### ISSUE THREAD

**Issue by alianZhen** [oracle/opengrok#2591]
![image](https://user-images.githubusercontent.com/27906971/50062655-3e8ad280-01e3-11e9-9fc1-2c24e30a26e1.png)
 I find the configuration,but I can not find out the configuration file or commands to disable it.

**Comment by vladak** [comment]
Put this into your [read-only configuration](https://github.com/oracle/opengrok/wiki/Read-only-configuration):

```xml
  <void property="suggesterConfig">
     <void property="enabled">
       <boolean>false</boolean>
     </void>
  </void>
```

**Comment by mohitgoyal2002** [comment]
This works Thanks @vladak !

**Comment by vladak** [comment]
You're welcome. I just looked at https://github.com/oracle/opengrok/wiki/Suggester and it's there, just not very obvious for any who has not used the read-only configuration yet.
