### ISSUE TITLE
"--symlink /path/to/symlink" option does not work for external (outside of source root) symlinks

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2594]
`--symlink` option does not work.  This option once worked with OPENGROK_SYMLINKS environment variable by OpenGrok wrapper shell script on 1.1-rc19.  It seems that this does not work after the shell script has changed to python script.

Also, the following option in read-only.xml also does not work.
```xml
  <void property="allowedSymlinks">
   <void method="add">
    <string>/path/to/symlink</string>
   </void>
  </void>
```
The symlinks directory under source root directory are processed correctly without this option.

**Comment by vladak** [comment]
Could you given an example of configuration where this does not work ? The conversion of the scripts did not change much, in the end the option is passed to `Indexer`.

**Comment by shyoshiz** [comment]
Please find attached sample test.sh in the test.zip.  I put 2 symlinks.  One is /src/test-branch/src and another is /src/test-branch/mtx/src.  When I index and deploy, both are listed in the directory list in the browser but I can not see the file contents.  It says 'Failed to get xref file'.  Under /data/xref, there is no entries for these 2 directories.

[test.zip](https://github.com/oracle/opengrok/files/2700028/test.zip)

**Comment by vladak** [comment]
The relevant options are:
```
   -s  /opt/pisces/opengrok-test/workspace/src \
    --symlink /opt/pisces/opengrok-test/workspace/src/test-branch/src/ \        
    --symlink /opt/pisces/opengrok-test/workspace/src/test-branch/mtx/src/ \    
```

What exactly is under `test-branch` directory ? Is this a respository ?

**Comment by shyoshiz** [comment]
Yes.  Several directories are under "test-branch" directory and I want "test-branch" is handled as a project.

**Comment by vladak** [comment]
It seems that I can reproduce this locally.

**Comment by vladak** [comment]
I have a layout like this under `/var/opengrok/src` which is my source root:
```
test-symlinks/
  sym -> /var/opengrok/src.repotest
```
and `/var/opengrok/src.repotest` is a directory:
```
/var/opengrok/src.repotest
└── one
    └── two
        └── three
            ├── file.txt
            └── four
                ├── file.txt
                └── five
                    └── file.txt
```
where `three` and `four` subdirs are Mercurial repositories.

The indexer is run with `--symlink /var/opengrok/src/test-symlinks/sym`.

After adjusting `--depth` indexer option to detect these repositories, they will show up in configuration and historyindex is actually generated for them however xrefs are not. `test-symlinks` is correctly recognized as a project.

**Comment by vladak** [comment]
When `/var/opengrok/src/test-symlinks/sym` is being evaluated in `IndexDatabase#indexDown` it reaches this branch:
```java
1061          String[] outLocalRelPath = new String[1];
1062          if (!accept(dir, outLocalRelPath)) {
1063              /**
1064               * If outLocalRelPath[0] is defined, then a local symlink was
1065               * detected but not "accepted" to avoid redundancy with its
1066               * canonical target. Set up for a deferred recreation of the symlink
1067               * for xref/.
1068               */
1069              if (outLocalRelPath[0] != null) {
1070                  File xrefPath = new File(xrefDir, parent);
1071                  PendingSymlinkage psym = new PendingSymlinkage(
1072                          xrefPath.getAbsolutePath(), outLocalRelPath[0]);
1073                  completer.add(psym);
1074              }
1075              return;
1076          }
```
however `outLocalRelPath[0]` is null on line 1069 so it is never added for deferred xref creation.

**Comment by vladak** [comment]
It seems to be the intention in the current code to skip symlinks to outside of the source root. I think we should allow that, esp. if it was allowed in the past.

**Comment by shyoshiz** [comment]
Yes, symlinks to outside of the source root were allowed at least 1.1-rc19.

**Comment by idodeclare** [comment]
> It seems to be the intention in the current code to skip symlinks to outside of the source root. I think we should allow that, esp. if it was allowed in the past.

No, symlinks to outside should be allowed.

@vladak, your test may have exposed that there might be an undesirable sensitivity to a trailing slash in an allowed symlink to a directory. E.g. if you use `--symlink /opt/pisces/opengrok-test/workspace/src/test-branch/src` (without trailing `/`) does that work for you?

**Comment by anlory** [comment]
so ,It doesn't work on newest version @vladak 1.2.23

**Comment by anlory** [comment]
please help, symlink is very useful  and convenient
