### ISSUE TITLE
-m option is ignored

### ISSUE THREAD

**Issue by kahatlen** [oracle/opengrok#26]
When Lucene was upgraded to 3.5, the -m option was made a no-op by commenting out the following line in IndexDatabase:

```
//writer.setMaxFieldLength(RuntimeEnvironment.getInstance().getIndexWordLimit());
```

It was presumably commented out because the setMaxFieldLength() method was deprecated in Lucene 3.5, and subsequently removed in Lucene 4.

The new way to limit the number of tokens is LimitTokenCountAnalyzer.

**Comment by tulinkry** [comment]
I think -m option now has completely different meaning, so a candidate for closing.
