### ISSUE TITLE
setup/install documentation suggestions

### ISSUE THREAD

**Issue by duaneellissd** [oracle/opengrok#2606]
for the most part the short "How to setup" documentation (link below) is good

This is a list of things that I found confusing that a sentence or two might help your victims installing for the first time, some context: I'm not that familiar with Tomcat or Java tools/techniques etc, the goal of these comments is to get rid of some assumed knowledge present in the docs.

https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok

Note that my install of Tomcat is verbatium from (link below), on a fresh Ubuntu 18 machine setup specific for this purpose.

     https://linuxize.com/post/how-to-install-tomcat-9-on-ubuntu-18-04/

**A) Step.2 - Deploy the web application**

Problem statement:  Never heard of a WAR file or how to deploy it, the existing instructions do not work and do not seem to work.

Result: I realized it was a ZIP file, used 'unzip source.war' - 

Suggestion: I would add the two parts below.

**Part 1.** For Tomcat installs, you find the "webapps' directory, 
 
      TOMCAT=/where/you/installed/tomcat

       cd ${TOMCAT}/webapps
       ls -l
       // note: on a fresh tomcat install you will find directories: ROOT, docs, manual, etc)
       total 24
       drwxr-xr-x 14 tomcat tomcat 4096 Dec 31 21:20 docs
       drwxr-xr-x  6 tomcat tomcat 4096 Dec 31 21:20 examples
       drwxr-xr-x  6 tomcat tomcat 4096 Jan  1 03:42 foobar
       drwxr-xr-x  5 tomcat tomcat 4096 Dec 31 21:20 host-manager
       drwxr-xr-x  5 tomcat tomcat 4096 Dec 31 21:20 manager
       drwxr-xr-x  3 tomcat tomcat 4096 Dec 31 21:20 ROOT

       # This directory name "opengrok" is the path on your tomcat server
       # ie:  If the name as  HappyBaby, the url would be: http://localhost:8080/HappyBaby
       
       # Here we use the name 'opengrok'
       # Thus the url will be: http://localhost:8080/opengrok

       sudo mkdir opengrok
       sudo chown tomcat.tomcat opengrok
       sudo chmod 0755 opengrok

**Part 2**

By default, opengrok uses the directory /var/opengrok for it data and configuration
Search for the string:  "CONFIGURATION" in this file:

                         ${TOMCAT}/webapps/opengrok/WEB-INF/web.xml

=====================

**STEP 3  Indexing**

PROBLEM STATEMENT: This was also confusing, and would benefit from a working example

SUGGESTION: I would add the following:

**Part 1**

OpenGrok's default data directory (per the file web.xml, on Linux ) is: /var/opengrok, you will require 3 sub-directories:

     sudo mkdir -m 0777 -p /var/opengrok/etc
     sudo mkdir -m 0777 -p /var/opengrok/data
     sudo mkdir -m 0777 -p /var/opengrok/src

Note, I believe the install instructions should address these security concerns

a) I'm not sure what the mode should be, I'm in a protected environment so 0777 is ok for me.
b) Users may also need to "chown" these in some way, for me with "chmod 0777" it did not matter

**Part 2**

PROBLEM STATEMENT:  How things are organized, projects, etc is confusing. A concrete example that indexes 2 or more projects would be a good addition, for example I would add this text:

ADD THIS:

Each directory under /var/opengrok/src is a separate project, below is simple sequence to load a few example projects for experimentation:

Step 1 - Populate the SRC directory.

      cd /var/opengrok/src

      # use one of the training modules at GitHub as an example small app.      
      git clone git@github.com:githubtraining/hellogitworld.git

      # use Git as an example large app
      git clone git@github.com:git/git.git

Step 2 - Index the code

      opengrok-indexer -a /path/to/your/opengrok.jar -- \
		 -c `which ctags` \
		 -s /var/opengrok/src \
		 -d /var/opengrok/data \
		 -H -P -S -G \
		 -U http://localhost:8080/opengrok

I would remind the user that the directories: /var/opengrok are set/configured via "web.xml"
And the URL used is dependent on the installation path in step 2.

**Comment by vladak** [comment]
I made best effort to update the wiki. Please take a look and feel free to add/change more.

**Comment by duaneellissd** [comment]
Looks good, thank you
