### ISSUE TITLE
Terraform analyzer

### ISSUE THREAD

**Issue by nitrocode** [oracle/opengrok#2613]
Would be nice to be able to filter on type: [terraform](https://www.terraform.io/) without having to set the filetype to `.tf`

**Comment by vladak** [comment]
That would probably mean to add Terraform analyzer first.

**Comment by tarzanek** [comment]
@nitrocode it should be easy to add in a simple way (just add lexical jflex parser, see other history commits on adding analyzers)
the tricky part however is that ctags doesn't support terraform, but that can be also easily fixed - by writing a regexp language definition for ctags, that will give at least basic semantic info
try to write it, it's fun (feel free to ask here or on slack)
