### ISSUE TITLE
Typo in wiki how to setup page

### ISSUE THREAD

**Issue by duaneellissd** [oracle/opengrok#2617]
See:  https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok

Scroll down to the configuration XML discussion, it shows:

```
    <context-param>
        <description>Full path to the configuration file where OpenGrok can read its configuration</description>
        <param-name>CONFIGURATION</param-name>
        <param-value>/opengrok/etc/configuration.xml</param-value>
    </context-param>
```
The `<param-value>` is incorrect, it should be: `/var/opengrok/etc/configuration.xml`

**Comment by vladak** [comment]
The wikis are open for everyone to edit, feel free to fix !

**Comment by duaneellissd** [comment]
I did not know it was open - Done.

**Comment by wy193777** [comment]
There is no edit button for me on wiki pages.

**Comment by tulinkry** [comment]
It's no longer open.
