### ISSUE TITLE
Java 11 builds fail due to javadoc error

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2629]
It seems that Travis started using Java 11.0.2 for its Java 11 builds. This lead to an error in javadoc surfacing. Now the build fails with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc (default) on project opengrok: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /home/travis/oraclejdk11/bin/javadoc @options @argfile
```
I found 2 related bugs:
  - https://bugs.openjdk.java.net/browse/JDK-8212233
  - https://issues.apache.org/jira/browse/MJAVADOC-555

however neither has a version out with the fix yet.

So far I have not found any workaround.

**Comment by vladak** [comment]
Tried using:
```XML
<configuration>
                    <additionalparam>--source 8</additionalparam>
```
but that did not help:
```
[ERROR] Exit code: 1 - javadoc: error - invalid flag: --source
```

**Comment by csaltos** [comment]
Adding `<detectJavaApiLink>false</detectJavaApiLink>` to the Maven javadoc pluging configuration also fix the error
