### ISSUE TITLE
SEVERE: Couldn't notify the webapp on https://.... HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by JustSong** [oracle/opengrok#2635]
Tomcat: apache-tomcat-8.5.37.tar.gz
Opengrok: opengrok-1.1.2.tar.gz

Hi Sir,

There is an error message need your help.

We will face this error after we process index command.
```
14:21:47 SEVERE: Couldn't notify the webapp on https://opengrok.system.com/source.
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1080)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at org.opengrok.indexer.index.IndexerUtil.enableProjects(IndexerUtil.java:60)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:308)

Couldn't notify the webapp on https://opengrok.system.com/source: HTTP 401 Unauthorized.
```

I have set tomcat connect with LDAP Auth. Maybe this error was cause by this setting ?!

Thanks

**Comment by vladak** [comment]
More details are needed about the setup to tell for sure however in order to perform admin actions on the webapp via RESTful API it is necessary to send the request through trusted channel such as via `localhost` and plain HTTP. In OpenGrok there is no concept of special authorization to perform admin actions yet.

For example, let's say https://opengrok.system.com/source is the user facing site that requires authentication and authorization while the Tomcat also listens on say port 8080 on localhost **only**. Then the indexer has to be run with `-U http://localhost:8080/source`.

**Comment by vladak** [comment]
There is `LocalhostFilter` class that should enforce certain RESTful API requests to come from `localhost` only however I fail to see how exactly it comes into action.

**Comment by JustSong** [comment]
Tomcat: apache-tomcat-8.5.37.tar.gz
Opengrok: opengrok-1.1.2.tar.gz
Specail Work: Connect with LDAP auth

Hi @vladak ,

Thanks a lot for your help! I have change `https://opengrok.system.com/source` to `http://localhost:8080/source`, but there is another error shown.

```
15:04:29 SEVERE: Couldn't notify the webapp on http://localhost:8080/source.
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
.....
```

Is this issuce cause by this <tomcat> server.xml setting ?
```
<Connector port="80" protocol="HTTP/1.1"
		   redirectPort="443"/>

<Connector port="443" protocol="HTTP/1.1" SSLEnabled="true"
		   maxThreads="150" scheme="https" secure="true"
		   clientAuth="false" sslProtocol="TLS"
		   sslEnabledProtocols="TLSv1.2"
		   connectionTimeout="20000"
		   keystoreFile="/var/lib/tomcat8/conf/opengrok.system.com.pfx"
		   keystoreType="PKCS12"
		   keystorePass="HU2Ue2Lq^zk^F6g*P"
		   compression="on"
		   compressableMimeType="text/html,text/xml,text/plain,text/css..."
		   />
```

**Comment by JustSong** [comment]
Hi @tulinkry ,

Yes , I have already tested with the following setting but not work for me...

- -U http://localhost:80/source
`javax.ws.rs.RedirectionException: HTTP 302 Found`

- -U http://localhost:443/source
javax.ws.rs.BadRequestException: HTTP 400 Bad Request

- -U https://localhost:443/source
`javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching localhost found. `

**Comment by vladak** [comment]
ad 1) there seems to be redirect in place
ad 2) it seems that there is only HTTPS (TLS based HTTP) being served on port 443 so plain HTTP requests cannot go through
ad 3) the X.509 certificate presented by the server does not have `localhost` in the list of hostnames, therefore the client failed to verify the certificate and terminated the connection

Really, you need to setup a plain HTTP port in Tomcat configuration.

**Comment by vladak** [comment]
Obviously, we need to document this better in the wikis.

**Comment by tulinkry** [comment]
And can't we follow redirects for
> -U http://localhost:80/source
javax.ws.rs.RedirectionException: HTTP 302 Found

**Comment by vladak** [comment]
It's a question where does the redirect lead to. My guess that it leads to a point which requires authorization and it would be back to square 1 :-)

**Comment by tulinkry** [comment]
I think it leads to

> `<Connector port="80" protocol="HTTP/1.1" redirectPort="443"/>`

but that wouldn't solve anything when the certificate is incorrect.

**Comment by vladak** [comment]
Technically, the certificate is correct. No certificate should ever contain localhost or localhost addresses (https://security.stackexchange.com/questions/35033/what-are-the-risks-of-a-localhost-signed-cerificate#35035)

**Comment by vladak** [comment]
https://serverfault.com/questions/218666/how-to-configure-tomcat-to-only-listen-to-127-0-0-1

**Comment by vladak** [comment]
You have to use the new port (8080) for communicating with the web app.

**Comment by vladak** [comment]
How do you run the indexer exactly ?

**Comment by JustSong** [comment]
Hi @vladak ,

Yes I have tried to use `-U http://localhost:8080/source/` but also get the same error:
`Couldn't notify the webapp on http://localhost:8080/source: HTTP 302 Found.`

My server.xml:
```
<Connector address="127.0.0.1" port="8080" protocol="HTTP/1.1"/>

<Connector port="80" protocol="HTTP/1.1"  redirectPort="443"/>

<Connector port="443" protocol="HTTP/1.1" SSLEnabled="true"
		   maxThreads="150" scheme="https" secure="true"
		   clientAuth="false" sslProtocol="TLS"
		   sslEnabledProtocols="TLSv1.2"
		   connectionTimeout="20000"
		   keystoreFile="/var/lib/tomcat8/conf/opengrok.system.com.pfx"
		   keystoreType="PKCS12"
		   keystorePass="HU2Ue2Lq^zk^F6g*P"
		   compression="on"
		   compressableMimeType="text/html,text/xml,text/plain,text/css..."
		   />
```

Indexer -U command:
-U http://localhost:8080/source/

**Comment by vladak** [comment]
Http 302 is redirection. Where does it redirect to ?

po 28. 1. 2019 9:00 odesílatel Dan Wang <notifications@github.com> napsal:

**Comment by JustSong** [comment]
I have no idea about this port redirection because of my server.xml not set redirection on 8080 port.
The settting on 8080 port is very simple : `<Connector address="127.0.0.1" port="8080" protocol="HTTP/1.1"/>`

**Comment by vladak** [comment]
Well, the redirection has to be configured **somewhere** and OpenGrok itself does not perform any redirections AFAIK. Again, if you query the address and display the HTTP headers, where does it tell it redirects to ? This might give a hint as to where this is configured.

**Comment by JustSong** [comment]
Hi @vladak ,

I tried to see what redirection on this 8080 port, but I found there is no redirection when I key in http://opengrok.system.com:8080/source in web browser. The web browser will show `ERR_CONNECTION_REFUSED` error.

I also tested other port setting like 8280, 8480 in `<tomcat8>/conf/server.xml`, .... and get the same error when I process index command so I don't think this error was cause by `port redirection`.

> - -U http://localhost:8280/source/
> Couldn't notify the webapp on http://localhost:8280/source: HTTP 302 Found.
> 
> - -U http://localhost:8480/source/
> Couldn't notify the webapp on http://localhost:8480/source: HTTP 302 Found.


I have checked the help doc again and found `-U` introduction:

> Send the current configuration to the specified webappURI

What is this -U command actual doing?

**Comment by JustSong** [comment]
I **tried to remove the LDAP auth feature** in tomcat and **all work smoothly**.
Only add setting `<Connector address="127.0.0.1" port="8080" protocol="HTTP/1.1"/>`  in `<tomcat8>/conf/server.xml` and process index command with `-U http://localhost:8080/source/`.


- Removed part in `<tomcat8>/conf/server.xml`:
```
<Realm className="org.apache.catalina.realm.JNDIRealm" debug="99"
	 referrals="follow"
	 connectionURL="ldap://ldaptw.ad.system.com"
	 connectionName="CN=systemsupport,OU=ConsoleLogon,OU=System Account,OU=Users,OU=Taiwan,OU=Asia,DC=ad,DC=system,DC=com"
	 connectionPassword="system@123"
	 userSearch="(sAMAccountName={0})"
	 userBase="ou=Asia,dc=ad,dc=system,dc=com"
	 userSubtree="true"
	 allRolesMode="strictAuthOnly"
/>
```

- Removed part in `<tomcat8>/conf/web.xml`:
```
<security-constraint>
	<web-resource-collection>
		<web-resource-name>Site</web-resource-name>
		<url-pattern>/*</url-pattern>
		<http-method>GET</http-method>
		<http-method>POST</http-method>
	</web-resource-collection>

	<user-data-constraint>
		<transport-guarantee>CONFIDENTIAL</transport-guarantee>
	</user-data-constraint>

	<auth-constraint>
		<role-name>*</role-name>
	</auth-constraint>
</security-constraint>

<login-config>
	<auth-method>BASIC</auth-method>
</login-config>

<security-role>
	<role-name>*</role-name>>
</security-role>
```

**Comment by JustSong** [comment]
I finally found out the correct setting and everything work smoothly too.

- According to following security setting in `<tomcat8>/conf/web.xml`, we **should modified the port with ssl setting**:

```
<user-data-constraint>
	<transport-guarantee>CONFIDENTIAL</transport-guarantee>
</user-data-constraint>
```

- Add specific port in `<tomcat8>/conf/server.xml` for `-U` command with SSL setting:
```
<Connector address="127.0.0.1" port="8080" protocol="HTTP/1.1"
		   SSLEnabled="true" scheme="https" secure="true"
		   clientAuth="false" sslProtocol="TLS"
		   sslEnabledProtocols="TLSv1.2"/>

```

**Comment by JustSong** [comment]
Although we have resolved HTTP 302 error, there are other problems ...

We found if process index command, the process will be stuck.
Log:

> 2019-03-18 17:42:29.823+0800 FINE t1 ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService: null
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.lookupManagedScheduledExecutorService(ClientExecutorProvidersConfigurator.java:198)
>         at org.glassfish.jersey.client.ClientExecutorProvidersConfigurator.init(ClientExecutorProvidersConfigurator.java:148)
>         at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:466)
>         at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
>         at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
>         at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
>         at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
>         at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
>         at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
>         at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
>         at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
>         at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
>         at org.opengrok.indexer.index.IndexerUtil.enableProjects(IndexerUtil.java:60)
>         at org.opengrok.indexer.index.Indexer.main(Indexer.java:308)
> Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
>         at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
>         at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
>         at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350)
>         at javax.naming.InitialContext.lookup(InitialContext.java:417)
>         ... 18 more
> 
> 2019-03-18 17:42:29.827+0800 CONFIG t1 ExtendedLogger.config: Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
> 2019-03-18 17:42:29.829+0800 CONFIG t1 ExtendedLogger.config: Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
> 2019-03-18 17:42:29.886+0800 CONFIG t1 HttpUrlConnector.<init>: Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
> 2019-03-18 17:42:29.993+0800 FINEST t1 HttpURLConnection.plainConnect0: ProxySelector Request for https://localhost:8080/source/api/v1/configuration/projectsEnabled
> 2019-03-18 17:42:29.994+0800 FINEST t1 HttpsClient.New: Looking for HttpClient for URL https://localhost:8080/source/api/v1/configuration/projectsEnabled and proxy value of DIRECT
> 2019-03-18 17:42:29.994+0800 FINEST t1 HttpsClient.<init>: Creating new HttpsClient with url:https://localhost:8080/source/api/v1/configuration/projectsEnabled and proxy:DIRECT with connect timeout:0
> 2019-03-18 17:42:30.005+0800 FINEST t1 HttpURLConnection.plainConnect0: Proxy used: DIRECT
>

**Comment by JustSong** [comment]
> Environment:
> - Tomcat: apache-tomcat-8.5.37.tar.gz
> - Opengrok: opengrok-1.1.2.tar.gz
> - LDAP Auth
> - SSL connection setting

Hi @vladak & @tulinkry ,

I think I finally found out the correct solution. Due to I have connected with the LDAP auth in my tomcat8, I should separate `api/*`  in tomcat `web.xml` setting like this issue https://github.com/oracle/opengrok/issues/2352.


If we connect with LDAP auth, we should add a specific port for -U command:
- server.xml:
`<Connector address="127.0.0.1" port="8080" protocol="HTTP/1.1"/>`

And we should set `api/*` without authorization form, so we need to add another `security-constraint` to separate `api/*` URL pattern:
- web.xml:
`<security-constraint>
	<web-resource-collection>
		<web-resource-name>API endpoints are checked separately by the web app</web-resource-name>
		<url-pattern>/api/*</url-pattern>
	</web-resource-collection>
</security-constraint>
`

Thanks again for your kindly help!
Maybe we can notify the user who connects the OpenGrok with LDAP auth.

**Comment by tulinkry** [comment]
The problem then is that `api/v1/search` is a public API (not only for localhost) and it would bypass your LDAP login.

**Comment by JustSong** [comment]
Hi @tulinkry 

Yes, that's right!! Thanks!!

**Comment by AKMFCJ** [comment]
-U http://localhost:8080/source
