### ISSUE TITLE
LocalhostFilter usage

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2636]
Follow up to discussion in #2635: it seems that `LocalhostFilter` is not used at all.

I can see it being added in c1a21bc08e5eef46541fa8cdb6754cb63090e387 by @Orviss as part of the REST API support (#2184) however I cannot see it being used anywhere.

**Comment by tulinkry** [comment]
It is used. As I wrote you on the slack, registered in http://demo.opengrok.org/xref/opengrok/opengrok-web/src/main/java/org/opengrok/web/api/v1/RestApp.java?r=1a2bb6b6#38.

Especially for the mentioned issue, it was in the action in the first comment.

**Comment by vladak** [comment]
I see, the `Provider` annotation (https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/Provider.html) combined with the `package()` call in `RestApp` makes this work.
