### ISSUE TITLE
Suggester needs to use PageConfig.getRequestedProjects() to get list of projects

### ISSUE THREAD

**Issue by mrashmiranjan** [oracle/opengrok#2640]
I am using version 1.1.2 on tomcat
Steps to re-produce
- Select multiple projects by clicking "Select All" button or by clicking on the group name containing multiple projects
- Start typing in any search box. We will see the error exclamation against Full Search text box and web server log will have NullPointerException 

Observation
If we select all those projects by clicking each one then there is no issue. 
Also if we refresh page after selecting the projects (by clicking select all or group name), suggester starts working.

**Comment by vladak** [comment]
full stack trace ?

**Comment by vladak** [comment]
This is a dup of #2587. Do you run with authorization framework enabled ?

**Comment by vladak** [comment]
`AuthorizationFramework.java#isAllowed()` calls `checkAll()`:
```java
204      public boolean isAllowed(HttpServletRequest request, Project project) {
205          return checkAll(
206                  request,
207                  "plugin_framework_project_cache",
208                  project,
209                  new AuthorizationEntity.PluginDecisionPredicate() {
210                      @Override
211                      public boolean decision(IAuthorizationPlugin plugin) {
212                          return plugin.isAllowed(request, project);
213                      }
```

which then calls `performCheck()`:
```java
758      private boolean checkAll(HttpServletRequest request, String cache, Nameable entity,
759              AuthorizationEntity.PluginDecisionPredicate pluginPredicate,
760              AuthorizationEntity.PluginSkippingPredicate skippingPredicate) {
...

796              overallDecision = performCheck(entity, pluginPredicate, skippingPredicate);
```

which is a wrapper:
```java
834      private boolean performCheck(Nameable entity,
835              AuthorizationEntity.PluginDecisionPredicate pluginPredicate,
836              AuthorizationEntity.PluginSkippingPredicate skippingPredicate) {
837  
838              return stack.isAllowed(entity, pluginPredicate, skippingPredicate);
839      }
```

and leads to `AuthorizationStack#isAllowed()` that hits the NPE on line 196:
```java
191      public boolean isAllowed(Nameable entity,
192              PluginDecisionPredicate pluginPredicate,
193              PluginSkippingPredicate skippingPredicate) {
194          boolean overallDecision = true;
195          LOGGER.log(Level.FINER, "Authorization for \"{0}\" in \"{1}\" [{2}]",
196                  new Object[]{entity.getName(), this.getName(), this.getFlag()});
```

The `entity` is thus the `project` that somehow became `null`.

**Comment by vladak** [comment]
Of course, this will only protect the authorization framework against null entities. The real root cause is yet to be determined.

**Comment by mrashmiranjan** [comment]
No, I don't have authorization framework enabled. However I debugged the code by attaching the IDE debugger. Found that this problem will happen if you have project groups defined. 

So if you have project groups defined, when you click "Select All" or click on a project group , UI sends the project group names along with the project name in the request.
The code at opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/filter/AuthorizationFilter.java line num 62 receives the project and group names as strings. Then when it tries to find the Project object for group name in line num 65, it gets null. Thats how entity becomes null and subsequent call throws NPE.

So as I originally suspected its an UI issues as the UI is sending project group names in the request.

**Comment by vladak** [comment]
Okay, it seems that the call to `Project p = Project.getByName(project);` in http://demo.opengrok.org/xref/opengrok/opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/filter/AuthorizationFilter.java?r=a55b429e returns `null`.

However I fail to see how group name can get there. Maybe related to the changes in #2518 ?

**Comment by vladak** [comment]
Could you send a sample of the request representation as it arrives to the `AuthorizationFilter` ?

**Comment by tulinkry** [comment]
> Okay, it seems that the call to Project p = Project.getByName(project); in http://demo.opengrok.org/xref/opengrok/opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/filter/AuthorizationFilter.java?r=a55b429e returns null.
 
yes. This should benefit from PageConfig.getProjects or how the method is called. It resolves the group parameter to projects.

**Comment by vladak** [comment]
you mean something like this ?
```
@@ -59,13 +60,11 @@ public class AuthorizationFilter implements ContainerRequestFilter {
         }
         AuthorizationFramework auth = env.getAuthorizationFramework();
         if (auth != null) {
-            String[] projects = request.getParameterValues(PROJECTS_PARAM);
-            if (projects != null) {
-                for (String project : projects) {
-                    Project p = Project.getByName(project);
-                    if (!auth.isAllowed(request, p)) {
-                        context.abortWith(Response.status(Response.Status.FORBIDDEN).build());
-                    }
+            PageConfig pageconfig = PageConfig.get(request);
+            for (String project : pageconfig.getRequestedProjects()) {
+                Project p = Project.getByName(project);
+                if (!auth.isAllowed(request, p)) {
+                    context.abortWith(Response.status(Response.Status.FORBIDDEN).build());
                 }
             }
         }
```

**Comment by vladak** [comment]
Still I don't see how group names could get into the `projects` param.

**Comment by mrashmiranjan** [comment]
> Could you send a sample of the request representation (mainly all its parameters) as it arrives to the `AuthorizationFilter` ?

I mentioned in my previous comment that the request that AuthorizationFilter receives contains projects as well as project group names.

**Comment by vladak** [comment]
Yes, however the group names should be under different parameter and suggester's `AuthorizationFilter` obtained the list via `request.getParameterValues(PROJECTS_PARAM)`.

**Comment by tulinkry** [comment]
> you mean something like this ?

yes

> Still I don't see how group names could get into the projects param.

me neither

**Comment by vladak** [comment]
This will need more intervention in the suggester code as the model for `SuggesterQueryData` relies on the project parameter:
```java
public final class SuggesterQueryData {

    @QueryParam(AuthorizationFilter.PROJECTS_PARAM)
    private List<String> projects;
```
