### ISSUE TITLE
Running old git version without iso8601-strict date format support

### ISSUE THREAD

**Issue by naveen0256** [oracle/opengrok#2641]
Hi,  my machine has been started recently.
While indexing the code, I am getting the same error as the [issue](https://github.com/oracle/opengrok/issues/1884) 
```
/mnt/codesearch1/git-2.16.2/git/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, --date=iso8601-strict] in directory /opengrok/project/qt/source: fatal: unknown date format iso8601-strict.
``` 
Do I need to update git to a newer version than 2.16.2?

I have my git as 2.16.2 version installed. 
Opengrok 1.1-rc17
Jdk as jdk1.8.0_171
Tomcat 9.0.10

**Comment by tulinkry** [comment]
Can you show us output of `/usr/bin/git --version`?

**Comment by naveen0256** [comment]
its pointing to 1.8.3.1. The old one. 
-bash-4.2$ git --version
git version 2.16.2
-bash-4.2$ /usr/bin/git --version
git version 1.8.3.1
-bash-4.2$

**Comment by tulinkry** [comment]
Then that's the problem. Use `-Dorg.opengrok.indexer.history.git=<path to the correct git>` as a parameter to java when running the indexer.

The correct path can be determined with `which git` I think.

**Comment by naveen0256** [comment]
which git is giving the correct path only
-bash-4.2$ which git
~/git-2.16.2/git/bin/git.

**Comment by vladak** [comment]
What happens if you run the `git log` as noted in the log on command line ?

**Comment by vladak** [comment]
https://github.com/git/git/commit/466fb6742d7fb7d3e6994b2d0d8db83a8786ebcf says August 2014 which is around Git 2.1.2 time frame.

**Comment by naveen0256** [comment]
Hi. 
Due to the system upgrade, some default provisions ran and which automatically set my jdk and git versions to some old default stable versions. It has been resolved. History is getting indexed.

Thanks for all the help.
