### ISSUE TITLE
Add additional CheckStyle rules

### ISSUE THREAD

**Issue by ahornace** [oracle/opengrok#2643]
List of checks: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml

I'm not saying that we need to use all but some of them are quite useful.

**Comment by vladak** [comment]
what else is needed after #2653 ?

**Comment by ahornace** [comment]
> what else is needed after #2653 ?

Well, that depends on what we want. I would add at least whitespace checks, javadoc style checks, line length check and a few others. But there was quite a lot of errors and I was lazy while doing #2653 :D

**Comment by tulinkry** [comment]
I'd be for some standard for javadoc definitelly. Line length is not a bad idea but keep it relaxed pls

**Comment by vladak** [comment]
Okay, sounds good to me. Adding checks (of any type) as an afterthought is
often painful.

čt 7. 2. 2019 15:11 odesílatel Adam Hornáček <notifications@github.com>
napsal:

**Comment by ahornace** [comment]
Fixed by #2896
