### ISSUE TITLE
Missing scrollbar in source view (Bugzilla #19187)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#265]
status CLOSED severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _i86pc/i386_
Assigned to: Lubos Kosco

Original attachment names and IDs:
- _grok-bug.jpg_ (ID 4632)
- _grok-expected.jpg_ (ID 4633)

On 2012-03-05 12:39:50 +0000, Tomas Kuthan wrote:

> Created attachment 4632
> Missing scrollbar
> 
> Right scrollbar is missing when displaying: 
> https://grok.cz.oracle.com/source/xref/on11u1-clone/usr/src/common/openssl/README.SUNW
> 
> The README file is much longer than one screen, and the remainder is not accessible due to the absence of scrollbar.
> 
> Browser: FF 8.0
> 
> Steps to reproduce:
> - just view https://grok.cz.oracle.com/source/xref/on11u1-clone/usr/src/common/openssl/README.SUNW
> 
> Workaround:
> - select a specific revision of the file, like:
>   https://grok.cz.oracle.com/source/xref/on11u1-clone/usr/src/common/openssl/README.SUNW?r=8545%3Aa1b3fd5884fd
> 
> Please, see attachment.

On 2012-03-05 12:41:20 +0000, Tomas Kuthan wrote:

> Created attachment 4633
> Expected behavior

On 2012-03-05 13:48:46 +0000, Lubos Kosco wrote:

> tried with FF 10.0.2 and couldn't reproduce :(

On 2012-03-05 13:49:38 +0000, Lubos Kosco wrote:

> can you actually force a refresh ? (CTRL+SHIFT+R)
> it might be css cache specific , I don't see any other obvious cause

On 2012-03-05 14:01:34 +0000, Tomas Kuthan wrote:

> Thanks Lubos, it probably was css-cache problem, and force refresh made it go away. Now I feel stupid.
> 
> Closing the bug, sorry for the bother...

On 2012-03-05 14:49:20 +0000, Lubos Kosco wrote:

> Well
> don't feel stupid
> 
> since I actually fixed this css cache problem some time ago (in 0.10)
> 
> but the web refactoring made the fix go away ... 
> and I was told not to put the code workaround back into the gate ...
> so ... don't feel like that, since the bug is in firefox and we opengrok doesn't workaround it anymore ...

On 2012-03-05 15:53:50 +0000, Jens Elkner wrote:

> (In reply to comment # 5)
> 
> > Well
> > don't feel stupid
> > 
> > since I actually fixed this css cache problem some time ago (in 0.10)
> > 
> > but the web refactoring made the fix go away ... 
> > and I was told not to put the code workaround back into the gate ...
> > so ... don't feel like that, since the bug is in firefox and we opengrok
> > doesn't workaround it anymore ...
> 
> Well, this isn't a caching problem. If the scrollbar does not appear, it is an indicator, that the resizeContent() method wasn't fired (initially via pageReadyMast()) or its execution has been stopped dueto an error ...
> 
> Haven't seen this with FF8, FF10, Safari 5.1.2 ...

On 2012-03-05 16:14:22 +0000, Lubos Kosco wrote:

> (In reply to comment # 6)
> 
> > (In reply to comment # 5)
> > 
> > > Well
> > > don't feel stupid
> > > 
> > > since I actually fixed this css cache problem some time ago (in 0.10)
> > > 
> > > but the web refactoring made the fix go away ... 
> > > and I was told not to put the code workaround back into the gate ...
> > > so ... don't feel like that, since the bug is in firefox and we opengrok
> > > doesn't workaround it anymore ...
> > 
> > Well, this isn't a caching problem. If the scrollbar does not appear, it is an
> > indicator, that the resizeContent() method wasn't fired (initially via
> > pageReadyMast()) or its execution has been stopped dueto an error ...
> > 
> > Haven't seen this with FF8, FF10, Safari 5.1.2 ...
> 
> hmm, then even better ... so this is a bug of firefox then (if I got it correctly)
> I just tried to reproduce with FF ... seems FF becomes crappy, time to switch to Chrome/Opera ?
> (and thanks chiming in Jens ;) )

On 2012-03-05 18:11:09 +0000, Jens Elkner wrote:

> (In reply to comment # 7)
> 
> > (In reply to comment # 6)
> > 
> > > (In reply to comment # 5)
> > > ...
> > > indicator, that the resizeContent() method wasn't fired (initially via
> > > pageReadyMast()) or its execution has been stopped dueto an error ...
> > > ...
> > > hmm, then even better ... so this is a bug of firefox then (if I got it
> > > correctly)
> > > I just tried to reproduce with FF ... seems FF becomes crappy, time to switch
> > > to Chrome/Opera ?
> 
> I don't think, it is an FF problem, but rather a server problem (if this actually happens at all): All pageReady\* methods are finally invoked via window.onload (i.e. when all components of the page have been loaded [and thus size calculations are safe]). So if the server doesn't answer a request (e.g. for an inlined image), hangs for some reason or e.g. sends wrong length param (value too big) the browser has to delay the window.onload as well ...
> 
> > (and thanks chiming in Jens ;) )
> 
> NP - that's an easy one ;-)

**Comment by jeremybarry** [comment]
I'm currently getting this issue in Firefox and Chrome. Any other users reporting this issue?

**Comment by tulinkry** [comment]
The problem is that a javascript on the page failed. Can you look in the firefox console to see what's there?

The javascript problem is tracked by #1488

**Comment by jeremybarry** [comment]
@tulinkry here's the errors.
<img width="843" alt="upload" src="https://user-images.githubusercontent.com/7319480/27610678-2e33476a-5b44-11e7-875a-cbbd97e565dd.png">

**Comment by abarash** [comment]
I work with Jeremy... To add on to his screenshot, when we look at where the 404 URLs are pointed, it looks like they're all relative URLs. We see, for example:

- http://[internal server]/[current folder]/js/jquery-3.2.0.min.js
instead of
- http://[internal server]/js/jquery-3.2.0.min.js

When I go to the first URL, I get a 404. The second works.
