### ISSUE TITLE
GitRepository isWorking should check git version

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2664]
As we are using features from newer git version (date format), the repository should report if it's working via the `isWorking()` method. Currently just return code is checked.

```
    @Override
    public boolean isWorking() {
        if (working == null) {
            ensureCommand(CMD_PROPERTY_KEY, CMD_FALLBACK);
            working = checkCmd(RepoCommand, "--help");
        }
        return working;
    }
```

**Comment by tulinkry** [comment]
The version is as mentioned in https://github.com/oracle/opengrok/issues/2641#issuecomment-457619314

**Comment by vladak** [comment]
Normally this would be a bug however Git versions with said date format support are largely prevalent today.
