### ISSUE TITLE
select all slow

### ISSUE THREAD

**Issue by dhireng** [oracle/opengrok#2669]
I'm migrating from opengrok v0.11.1 to  v1.1.2  and I have indexed my Subversion repository of 1550 projects. The project select box is considerably slow  (takes 5 seconds to load) in the new version and high CPU is seen on the browser when I select All projects or deselect all projects.
Is there a way to go back to the old style? Any other options to make things run faster?

**Comment by vladak** [comment]
closing as a dup of #1665
