### ISSUE TITLE
Inadequate indentation (Bugzilla #19198)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#267]
status RESOLVED severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Jan Friedel

Original attachment names and IDs:
- _misalignment.jpg_ (ID 4639)
- _irregular_indent.jpg_ (ID 4640)
- _diff.19198.patch_ (ID 4658)

On 2012-03-27 23:31:05 +0000, Jan Friedel wrote:

> C indentation seem to less readable on the recent version of OpenGrok.
> 
> Formerly: The first element on the line, the line number, was wrapped
> by an appropriate number of nbsp;s to form a 8 characters block.
> The subsequent TAB aligned the text on the next least multiple of 8,
> the 16th character.
> 
> Newly: The first element, the line number, is enclosed in
> the inline-block of defined width smaller than 8 (6); the subsequent
> TAB aligns the text on the next least multiple of 8, the 8th character.
> Note, that the tab width in this case is just 2 characters. That makes
> the text very hard to read, it makes difficult to quickly navigate
> through the source code.
> 
> Proposal:
> # src .l, #src .hl, .blame .r, .blame .a, #results .l, #more .l, #difftable i, del.d {
> 
> ```
> width: 8ex;
> ```
> 
> }

On 2012-03-28 08:28:34 +0000, Jan Friedel wrote:

> Created attachment 4639
> misalignment example

On 2012-03-28 08:30:56 +0000, Jan Friedel wrote:

> Created attachment 4640
> irregular indentation / alignment example

On 2012-03-28 08:49:02 +0000, Vladimir Kotal wrote:

> Is the "formerly" 0.10 and "newly" 0.11 ?

On 2012-03-28 09:11:13 +0000, Jan Friedel wrote:

> (In reply to comment # 3)
> 
> > Is the "formerly" 0.10 and "newly" 0.11 ?
> 
> Who knows, this an webapp/bui bug - I'm not sure how to determine
> the OpenGrok version from the BUI. Thanks for guidance.

On 2012-03-28 09:15:49 +0000, Lubos Kosco wrote:

> (In reply to comment # 4)
> 
> > (In reply to comment # 3)
> > 
> > > Is the "formerly" 0.10 and "newly" 0.11 ?
> > 
> > Who knows, this an webapp/bui bug - I'm not sure how to determine
> > the OpenGrok version from the BUI. Thanks for guidance.
> 
> view source of page
> search for meta generator
> (e.g. current grok.cz is:
> <meta name="generator" content="0.11.1rc1 (089f905e7a95+)" /> )

On 2012-03-28 09:17:07 +0000, Jan Friedel wrote:

> (In reply to comment # 4)
> 
> > (In reply to comment # 3)
> > 
> > > Is the "formerly" 0.10 and "newly" 0.11 ?
> > 
> > Who knows, this an webapp/bui bug - I'm not sure how to determine
> > the OpenGrok version from the BUI. Thanks for guidance.
> 
> Got it: Newly = 0.11.1rc1; Formerly = (eg) 0.9

On 2012-03-29 15:38:52 +0000, Jan Friedel wrote:

> Proposal:
> 
> diff -r 1684de046472 OpenGrok
> --- a/OpenGrok    Wed Mar 21 19:21:48 2012 +0100
> +++ b/OpenGrok    Thu Mar 29 17:37:17 2012 +0200
> @@ -242,7 +242,7 @@
>      # OPTIONAL: Web Site Look & Feel
>      #           (Options: default, offwhite and polished.
>      #            Note the quoting requirements)
> -    #SKIN='-L "default"'
> -    #SKIN='-L default'
>   
>    # OPTIONAL: Set Maximum Indexed Words Per File
>    # Note, that you might run out of memory, then either increase JVM memory
>   diff -r 1684de046472 web/default/style.css
>   --- a/web/default/style.css   Wed Mar 21 19:21:48 2012 +0100
>   +++ b/web/default/style.css   Thu Mar 29 17:37:17 2012 +0200
>   @@ -446,10 +446,10 @@
>   # results .l, #more .l,
>   # difftable i, del.d { /\* line number/annotation block */
>   
>   display: inline-block;
> - width: 5ex;
> - width: 6ex;
>   text-align: right;
> - padding-right: 1ex;
> - margin-right: 0.2em;
> - padding: 0 1ex;
> - margin-right: .5ex;
>   background-color: #dddddd;
>   color: # 666;
>   }
>   @@ -633,4 +633,4 @@
>   background-repeat: no-repeat;
>   background-position: -459px 0;
>   }
>   -/\* ############### end of footer ############## _/
>   \ No newline at end of file
>   +/_ ############### end of footer ############## */

On 2012-03-29 15:44:48 +0000, Lubos Kosco wrote:

> looks good, I am saying push :)

On 2012-03-29 16:36:39 +0000, Jens Elkner wrote:

> (In reply to comment # 8)
> 
> > looks good, I am saying push :)
> 
> Not really, since it is just a rough guess as well - depending on the font in use and browsers mind. One can use a workaround like http://src.iws.cs.ovgu.de/source/xref/opengrok-jel/web/list.jsp# 57 based on the biggest line numbers, which should usually work, but IIRC Knut has found out, that the browser has its own tab setting behavior, so that this kludge may not work for some files as well.
> 
> So IMHO the proper thing to do is, to let the browser determine the required width of those "columns" (linenumber, revision, author, source lines) and just decorate them as wanted. http://src.iws.cs.ovgu.de/source/ is already using this idea (beside major optimizations wrt. annotations/bandwidth saving) and seems to work as expected ;-)

On 2012-04-05 01:49:42 +0000, Jens Elkner wrote:

> see diffs fix # 19199

On 2012-04-25 13:24:06 +0000, Jan Friedel wrote:

> Since this is a small fix (patch) and will be integrated in a single
> changeset (thus easy to be backed out) I'll do the putback. For the time
> being the proposed solution saves a lot of pain while reading the code.
> Taking into account the size of the proposed fix, it should be fairly
> simple do a merge with any subsequent fix.

On 2012-04-25 14:50:29 +0000, Jan Friedel wrote:

> Created attachment 4658
> final patch

**Comment by liweitianux** [comment]
Hi @vladak ,

I'm browsing code in https://grok.dragonflybsd.org/ using Firefox (and Chrom) and have this issue: the first tab seems shown as a single space.  Checking the `style.css` shows `padding-right: 0`, and changing it to be `padding: 0 1ex` fix this problem, and everything looks much more pretty.

Cheers,
Aaron

**Comment by liweitianux** [comment]
Hi @vladak, I deployed OpenGrok 1.14.11 and I still see the indentation problem in both Firefox 150 and Chromium 142. Below are the screenshots (with Firefox; Chromium behaved the same):

<img width="1001" height="243" alt="Image" src="https://github.com/user-attachments/assets/6f27526d-fba7-46d0-97c5-6bcc9d866b48" />

<img width="1001" height="243" alt="Image" src="https://github.com/user-attachments/assets/517a5661-58b3-4648-899c-6cb780a4eb43" />

<img width="1001" height="246" alt="Image" src="https://github.com/user-attachments/assets/d44a1f93-1f0f-405f-9890-cd778da1e467" />

So it seems the [above patch](https://github.com/oracle/opengrok/issues/267#issuecomment-27952853) somehow got lost?  By the way, should we reopen this issue?

Thank you.
