### ISSUE TITLE
JavaScript regular expressions not handled

### ISSUE THREAD

**Issue by jordanbrown0** [oracle/opengrok#2670]
The expression
    `s.replace(/"/g, 'x')`
is treated as an unterminated string and causes the rest of the text (until a similar mismatch) to be colored as a string.

**Comment by vladak** [comment]
I can see the problem when browsing the JS code of OpenGrok:
![js-vs-regexp](https://user-images.githubusercontent.com/2934284/52416207-60b91680-2ae9-11e9-875d-be4558fd8944.png)
