### ISSUE TITLE
strict repository indentation

### ISSUE THREAD

**Issue by hseuming** [oracle/opengrok#2672]
Hi,
My computing env is as follows:
  
   OpenGrok:  1.1
   JDK:  openjdk version "1.8.0_191"
   OS:   Ubuntu 18.04.1 LTS
   browser: Google Chrome Version 72.0.3626.81 (Official Build) (64-bit)
 

In order to demonstrate the problem I ran into, I've set up the following repos with Apache being a directory on my Ubuntu 18.04 box:

    =================
    Apache
       Apache/ant
       Apache/ivy
       Apache/tomcat

    d3

    jwt-scala
    =================

However, I saw the following in {OpenGrok (PNG image attached):

    =================
    Apache   (linked to  --->  Apache/ant)
       Apache/ivy
       Apache/tomcat

    d3

    jwt-scala
    =================

Is that expected?

Thanks

![opengrok](https://user-images.githubusercontent.com/4443735/52374530-7c5de780-2a2b-11e9-8c94-b6c777b8e77c.png)

**Comment by tulinkry** [comment]
Not sure if I understood correctly but yes, it looks this is expected. When your project ("Apache") contains subrepositories ("Apache/ivy", ...) these are displayed with a little margin so you can distinguish on the main page which is the main project and which are subrepositories.

**Comment by tulinkry** [comment]
I believe this is not directly expected however works as designed - the first repository of the project is treated as the main repository and all other repositories in a project are treated as subrepositories and displayed with a little margin.

**Comment by tulinkry** [comment]
So I believe when the project has more repositories, maybe we should display all of them with the margin. @vladak thoughts?

**Comment by vladak** [comment]
I think this works as designed. If the project directory itself is a repository and has more than 1 sub-repositories, the alternative would be to display this as:
```
Apache        -- empty URI
  Apache      -- repo URI
  Apache/ivy  -- repo URI
  ...
```
Not sure I like this, though.

**Comment by ChristopheBordieu** [comment]
Hi,

An alternative could be too to display:
```
Apache               --empty URI
  Apache/ant         -- repo URI
  Apache/ivy         -- repo URI
...
``` 
I vote for this one :-D (cf. my comment [here](https://github.com/oracle/opengrok/issues/1478#issuecomment-313781013)).

**Comment by hseuming** [comment]
@tulinkry:
> the first repository of the project is treated as the main repository 
> and all other repositories in a project are treated as subrepositories

the "first" repo (in lexicographical order or whatnot) may not really be the "main" repo unless we tweak the original naming convention of some FLOSS projects when we clone them under SRC_ROOT

My personal preference is the same as that of @ChristopheBordieu:

   ```
   Apache                   -- empty URI
         Apache/ant         -- repo URI
         Apache/ivy         -- repo URI
         Apache/tomcat      -- repo URI
   ....
   ```

Anyway, thank you all for your input

**Comment by tulinkry** [comment]
I did a pull request for the new format.
