### ISSUE TITLE
SVN - History and Annotate "greyed out" but available from dir listing

### ISSUE THREAD

**Issue by pisek** [oracle/opengrok#2678]
After indexing:

    java -jar C:\OpenGrok\opengrok-1.2.1\lib\opengrok.jar -c C:\OpenGrok\ctags-2019-02-11_84dbaf52-x64\ctags.exe -s C:\OpenGrok\source -d C:\OpenGrok\data -H -P -S -G -W C:\OpenGrok\opengrok-1.2.1\configuration.xml -U http://localhost:8888/source

I am using SVN. Projects are checkedout using:

    svn co .../appname/trunk appname

(appname folder is mapped to trunk in svn)

Problems i found:

1. no link for _History_ text for current folder but showing correctly _H_ link when in parent folder:
![image](https://user-images.githubusercontent.com/1399479/52896856-d0a45c80-31cd-11e9-9a79-679215715619.png)
![image](https://user-images.githubusercontent.com/1399479/52896869-ec0f6780-31cd-11e9-835a-ddde3d8a34b3.png)
The history in _H_ link works fine.
2. no link for _History_ and _Annotate_ when inside file, but _H_ and _A_ links work in parent dir
![image](https://user-images.githubusercontent.com/1399479/52896939-97b8b780-31ce-11e9-9196-a81d06ffc0df.png)
![image](https://user-images.githubusercontent.com/1399479/52896956-cb93dd00-31ce-11e9-8659-000b3a116163.png)
3. It seems Annotate (_A_ link in parent dir) does not work - no annotation is shown, just simple source-code page
4. Is it possible to somehow be able to search through sourcecode-history? Eg. for parts of code that were removed i previous revisions etc?

**Comment by pisek** [comment]
1, 2, 3 points from above seems to be gone when reindexed with:

    java -jar C:\OpenGrok\opengrok-1.2.1\lib\opengrok.jar --writeConfig C:\OpenGrok\opengrok-1.2.1\configuration.xml --ctags C:\OpenGrok\ctags-2019-02-11_84dbaf52-x64\ctags.exe --source C:\OpenGrok\source --dataRoot C:\OpenGrok\data --uri http://localhost:8888/source --history --projects --search --assignTags --defaultProject __all__ --optimize on --quickScan off --renamedHistory on --remote on

**Comment by tulinkry** [comment]
I don't know much about svn but it seems that svn history is requested on demand from the remote rather then stored on the filesystem with the checkout. So I'm assuming the `--remote on` did the trick for it.

**Comment by tulinkry** [comment]
>     4\. Is it possible to somehow be able to search through sourcecode-history? Eg. for parts of code that were removed i previous revisions etc?

No, this isn't possible. Only searching through commit messages is supported.

**Comment by vladak** [comment]
This is a dup of #1498 I believe. The SVN checkout is using a `file` therefore repository `remote` flag will be OFF. Given that the remote suport in `Configuration` is off by default (which is strange) this leads to the observed behavior.

**Comment by elkin5** [comment]
Where is the anwer to this question?
