### ISSUE TITLE
CDDL compliance issues in changeset 57eefa4

### ISSUE THREAD

**Issue by idodeclare** [oracle/opengrok#2680]
Hello,

I'm writing to remind that CDDL compliance is mandatory for OpenGrok.

One type of CDDL contribution is specified in 1.9 ("Modifications") part B:

> Any new file that contains any part of the Original Software or previous Modifications.

"Covered Software" for CDDL is:

> (a) the Original Software, or (b) Modifications, or (c) the combination of files containing Original Software with files containing Modifications, in each case including portions thereof.

Furthermore CDDL has specific language in 3.3 ("Required Notices"):

> You may not remove or alter any copyright, patent or trademark notices contained within the Covered Software, or any notices of licensing or any descriptive text giving attribution to any Contributor or the Initial Developer [except your own attributions.]

New `AbstractAnalyzer` in 57eefa4791e1 contains parts copied from `FileAnalyzer`. 3.3 therefore requires including in the new file the following copyright and descriptive text giving attribution for the copied source:

>  * @&shy;author Chandan
>  * Copyright (c) 2005, 2019, Oracle and/or its affiliates. All rights reserved.
>  * Use is subject to license terms.
>  * Portions Copyright (c) 2017-2018, Chris Fraire <cfraire@&shy;me.com>.

Likewise `AnalyzerFactory` has code copied from `FileAnalyzerFactory` without including the copyright and descriptive text giving attribution.

Lastly, I remind that compliance is important ultimately because of the CDDL Termination clause 6.1:

> This License and the rights granted hereunder will terminate
    automatically if You fail to comply with terms herein and fail to
    cure such breach within 30 days of becoming aware of the breach.

Thank you.

**Comment by tulinkry** [comment]
You are very welcome to fix the issue. Thanks for reminding.
