### ISSUE TITLE
Is it possible recognizing the .ipp files as C++ ones in the indexer? (Bugzilla #19210)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#269]
status CLOSED severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2012-05-04 13:51:22 +0000, Adrian Nackov wrote:

> In the C++ Boost libraries there are implementation files with extension .ipp, #included as cpp files. Would it be possible having them recognized and processed by the indexer as C++ ones?

On 2012-05-04 15:03:41 +0000, Trond Norbye wrote:

> You can use the "-A extension:analyzer" to specify which analyzer to use for a given extension.
> 
> Please use the mailing list to ask questions

**Comment by binary-nerd** [comment]
@vladak 
How to know the name of the analyzer. I tried `-A ipp:cpp` and few other combinations but none seem to be correct.
Can you point me to a place where i can list or see the names of the analyzers.

**Comment by vladak** [comment]
If you run the indexer with `--help guru` it will provide the list of analyzers. For cases like this it would be nice to complement this with actual analyzer name.
