### ISSUE TITLE
IE10 js error

### ISSUE THREAD

**Issue by Teriand** [oracle/opengrok#2694]
opengrok 1.2.2
1. Object doesn't support property or method 'includes' -  utils-0.0.29.js:1787
2. Object doesn't support property or method "startsWith" -  utils-0.0.29.js:1868
3. Object doesn't support property or method "isInteger" - utils-0.0.29.js:1772

**Comment by ahornace** [comment]
Honestly, do we want to support IE?

**Comment by Teriand** [comment]
very small changes for support.
and in Enterprise IE10/11 its LTS

No one know when microsoft real change  engine to chrome.

**Comment by tulinkry** [comment]
I agree, this little change does not cost anything.

**Comment by ahornace** [comment]
I think this just prevents us from moving forward innovatively and we would sign up for something we don't really want.

https://mashable.com/article/microsoft-stop-using-internet-explorer-browser/?europe=true

**Comment by tulinkry** [comment]
This three line change does not prevent anything. Moving forward with our javascript is a whole another story.

**Comment by ahornace** [comment]
So if someone makes other JS changes and they break IE support then it's okay? 

IE is past.

**Comment by Teriand** [comment]
if break, we have chance fix it.

**Comment by ahornace** [comment]
But tell me a reason why. Why cannot we use something so trivial as `startsWith` and have a nice clean code just because some very very small percentage of people is still using obsolete software?

This just makes the maintaining harder.

How many Android developers support 2.x ?

**Comment by tulinkry** [comment]
Because it's costless to keep supporting this obsolete software at this point. If you were to develop a feature which violates this in many errors/warnings, then yeah, let's do it with a clean code.

**Comment by ahornace** [comment]
> If you were to develop a feature which violates it, then yeah, let's do it with a clean code.

That's what I wanted to hear.
