### ISSUE TITLE
History/Annotate links disabled for subversion projects 

### ISSUE THREAD

**Issue by mrashmiranjan** [oracle/opengrok#2696]
I am using version 1.2.0
I have both SVN and GIT projects. Indexer is also running with -H option. But in the UI History/Annotate links are disabled for subversion projects. They are enabled and working fine for GIT projects though.

When I checked the historycache inside data directory for the SVN projects, I could see the history files are generated fine, but still UI links are disabled.

Any other option or configuration I am missing ?

**Comment by vladak** [comment]
Check the logs of the application server.

čt 21. 2. 2019 7:16 odesílatel Rashmi Ranjan Mohanty <
notifications@github.com> napsal:

**Comment by mrashmiranjan** [comment]
Did not find anything related to history in the tomcat logs.

**Comment by tulinkry** [comment]
see #2678 if it's your case or not

**Comment by mrashmiranjan** [comment]
Yes its the same issue as #2678
