### ISSUE TITLE
Support of "git worktree"

### ISSUE THREAD

**Issue by Ramzec** [oracle/opengrok#2698]
apache-tomcat-8.5.35.tar.gz
jre-8u191-solaris-x64.tar.gz
opengrok-1.0.tar.gz

I created several source-trees with `git worktree`. Opengrok shows non-active Annotate and History links for them.

**Comment by idodeclare** [comment]
I raised a PR to relax the `.git` check being directory-strict so that a `.git` file can indicate a working tree.
