### ISSUE TITLE
Indexer docs for large repos out of date

### ISSUE THREAD

**Issue by amckenna-pinterest** [oracle/opengrok#2707]
https://github.com/oracle/opengrok/wiki/Tuning-for-large-code-bases

The indexer flags given here do not work:

`indexer.py -J=-Xmx8g -J=-d64 -J=-server -m 256`

Specifically, the -m 256 throws an error.  I think indexer.py was also changed to opengrok-indexer recently.

**Comment by vladak** [comment]
The indexer options need to be separated from the Java options using `--` when running via Python wrapper.

I fixed the wiki. Thanks !
