### ISSUE TITLE
Enable Cross Origin Requests for OpenGrok

### ISSUE THREAD

**Issue by wy193777** [oracle/opengrok#2710]
OpenGrok already has REST API provided for users. So cross origin requests should be enabled by default otherwise other services will not be able to take advantage of REST API.

**Comment by vladak** [comment]
I guess this is about adding a CORS filter to `web.xml` + make it configurable.

**Comment by tulinkry** [comment]
This should be part of the api only, so some filter for the REST API.
Currently public API is only:
 - SearchController.PATH
 - SuggesterController.PATH
 - SuggesterController.PATH + "/config"

other paths are available only for localhost so CORS filter does not make sense I think.

**Comment by vladak** [comment]
Good point.

Dne út 12. 3. 2019 13:04 uživatel Kryštof Tulinger <notifications@github.com>
napsal:

**Comment by wy193777** [comment]
Can we include this change to newest release? It's really hard to config the opengrok. I just want to run it with docker container.

**Comment by vladak** [comment]
Yep, will make a release soonish.

Dne st 20. 3. 2019 20:44 uživatel Shenghan Gao <notifications@github.com>
napsal:

**Comment by vladak** [comment]
Also, I wonder what makes it so hard for you to configure it ?

Dne st 20. 3. 2019 21:07 uživatel Vladimír Kotal <vlada@devnull.cz> napsal:

**Comment by wy193777** [comment]
1. To let OpenGrok run properly, first need to install several dependencies, such as ctags, tomcat. I already had them.
2. After installed those dependencies, I need to unzip the build result, copy paste the source.war to Tomcat path.
3. After the application is up and running, I also have to manually edit `web.xml` and a configuration file somewhere. 
4. I also have to manually run indexer to index code. 

None of them is hard, but all steps combined take at least one or two hours to setup. Also sometimes there are conditions on local machine, then the configuration might took someone forever(my experience with tomcat). As a developer spoiled by `npm`, `python` and other tools, I would expect apps can run with copy paste a few commands.

**Comment by wy193777** [comment]
Maybe we can add a Dockerfile for people to easily run the application from source code.

**Comment by vladak** [comment]
That will probably happen in some time by folding the OpenGrok/docker repo
onto the main OpenGrok repo.

Dne st 20. 3. 2019 22:21 uživatel Shenghan Gao <notifications@github.com>
napsal:
