### ISSUE TITLE
Move wiki pages to source code to let contributor make pull requests on wiki.

### ISSUE THREAD

**Issue by wy193777** [oracle/opengrok#2727]
I cannot find edit button on wiki pages. And even though I can clone wiki page, but I cannot find a way to make a pull request. Also it would be good if maintainer can also review wiki page changes.

**Comment by vladak** [comment]
The edits are restricted to maintainers only for internal reasons.

Just clone the wiki repo, do a commit, export the diff and attach it to
normal PR.

Dne čt 21. 3. 2019 0:10 uživatel Shenghan Gao <notifications@github.com>
napsal:
