### ISSUE TITLE
git ambigous argument

### ISSUE THREAD

**Issue by soleen** [oracle/opengrok#2755]
I am using opengrok for browsing linux source tree, and getting the following warnings during indexing:

Apr 19, 2019 3:00:29 AM org.opengrok.indexer.util.Executor exec
WARNING: Non-zero exit status 128 from command [/usr/bin/git, log, --format=commit:%H
Date:%at, -r, v2.6.12-rc2^..v2.6.12-rc2] in directory /opengrok/src/linux: fatal: ambiguous argument 'v2.6.12-rc2^..v2.6.12-rc2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

~$ which git
/usr/bin/git
~$ git --version
git version 2.19.1
Opengrok: opengrok-1.2.7
tomcat8
java 11

Running command:
opengrok-indexer -J="-Xmx8G" -a $OG/lib/opengrok.jar -- \
        -O on -s $SRC -d $DATA -H -P -S -G --renamedHistory off \
        -c /usr/bin/ctags-universal \
        -W $ETC/configuration.xml \
        -U http://localhost:80/source

**Comment by vladak** [comment]
The `git log` command in question originates from Git tag handling (triggered by the `-G` option).

I see this too in my Linux kernel repositories and also when indexing https://github.com/jenkinsci/mercurial-plugin.git which is better for debugging as it has limited set of tags. For that repo, I am seeing the errors for tags like `mercurial-1_X` where X is a number smaller than 9.

The `TagEntry` creation in `GitRepository.java#buildTagList()` works by getting the list of all tags in the repository and then finding a changeset ID and date for each tag. The `git log` command is used for the latter. Revision range (i.e. `REV^..REV`) is used to get the metadata for single commit only. For some commits it is not possible to get their parent:

```
/var/opengrok/src/mercurial-plugin (master)$ git log mercurial-1_0^..mercurial-1_0
fatal: ambiguous argument 'mercurial-1_0^..mercurial-1_0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/var/opengrok/src/mercurial-plugin (master)$ git log mercurial-1_0^
fatal: ambiguous argument 'mercurial-1_0^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/var/opengrok/src/mercurial-plugin (master)$ git log mercurial-1_0^ --
fatal: bad revision 'mercurial-1_0^'
```

hence the warning in the log.

The `git log` command can be fixed to avoid using the range which will make the warning go away however I am not sure whether the overall approach is sound. In this particular case `mercurial-1_0` is the tag of the first changeset in the repository so it cannot have any parent but the error happens for other tags, notably those that seem to be orphaned. `git log --graph --full-history --all` starts with:

```
* commit c368d9f5ccf4a1318dde404308b67b8e0d8c28d2
| Author: kohsuke <kohsuke@dev.java.net>
| Date:   Mon Jun 18 02:55:08 2007 +0000
| 
|     forgot to commit.
| 
* commit 03a634e3af3497b36b0e261498aea59b88dbc190
| Author: kohsuke <kohsuke@dev.java.net>
| Date:   Fri Apr 6 14:51:39 2007 +0000
| 
|     made the plugin self-contained.
| 
* commit 4a21cd92278cb436aa94e9c1ae518c71f0f1c38f
  Author: kohsuke <kohsuke@dev.java.net>
  Date:   Fri Apr 6 14:45:55 2007 +0000
  
      added skeleton for the mercurial plugin. Plan to work on this jointly with Jonathan Gibbons.
  
* commit 3a09c3377e194ac190d0baf10633757fa794dde6
  Author: null <null@dev.java.net>
  Date:   Sat Feb 9 03:34:56 2008 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_8'.
  
* commit 56c9178fc899bd6302bcaf88fd0f2e0eb2c6234c
  Author: null <null@dev.java.net>
  Date:   Wed Jan 16 17:25:55 2008 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_7'.
  
* commit f1ffd4c7c1ddf7ab0b317f1888a27563add93c0d
  Author: null <null@dev.java.net>
  Date:   Sat Jan 5 01:21:54 2008 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_6'.
  
* commit e91179041628ab2851b5813a24bc217872035df1
  Author: null <null@dev.java.net>
  Date:   Fri Nov 30 06:37:59 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_5'.
  
* commit 0d2c9ce0c3dd7334db11bf3cc084f87ad8985c30
  Author: null <null@dev.java.net>
  Date:   Mon Oct 15 22:11:45 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_4'.
  
* commit 8ec4f8fbb0cb9237a00e0910a884b3ba8727191d
  Author: null <null@dev.java.net>
  Date:   Tue Sep 18 16:52:34 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_3'.
  
* commit e10f342dd3e2e88ac1de326869e4bc83e46e368b
  Author: null <null@dev.java.net>
  Date:   Sat Sep 1 17:07:29 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_2'.
  
* commit ee658f64af6d702b29da7c49d5510ca9d6579141
  Author: null <null@dev.java.net>
  Date:   Wed Aug 15 06:20:36 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_1'.
  
* commit 08bfd3d13d923827c932a088137a0142ffcb6ed9
  Author: null <null@dev.java.net>
  Date:   Sat Aug 11 23:42:43 2007 +0000
  
      This commit was manufactured by cvs2svn to create tag
      'mercurial-1_0'.
```

If the `--all` option is omitted, these rogue changesets will not be displayed and the output will start with changeset `4a21cd92278cb436aa94e9c1ae518c71f0f1c38f`. So, they should not be used for tagging given that history parser will process the output from plain `git log`.

I will submit a PR that will provide immediate fix however this area clearly requires more work.
