### ISSUE TITLE
Incremental Indexing Taking Too Long

### ISSUE THREAD

**Issue by neerajbadlani** [oracle/opengrok#2759]
I  just migrated from 0.12 to latest and ran full index using folling command : 
```
[work] /auto/sw/licensed/sun/jdk/1.8.0_91-64/bin/java -Djava.util.logging.config.file=logging.properties -jar opengrok/lib/opengrok.jar --detailed --ctags /nobackup/nebadlan/binaries/bin/ctags  --dataRoot /nobackup/nebadlan/work/opengrok/data --source /nobackup/nebadlan/work/opengrok/src --depth 5 --assignTags --history --projects -m 8048 --verbose --writeConfig /nobackup/nebadlan/work/opengrok/etc/configuration.xml --renamedHistory on  --remote on --search --threads 16
```

After that , without updating repo , I ran same command again to check how quicly reindexing happens . Coming from 0.12 where if nothing has changed in repo , it finishes in less than a minute , here in latest , I see it taking more than 20 mins and still going . 

Am I doing something wrong ?

**Comment by gtoph** [comment]
Just taking a shot in the dark here, but because 0.12 is so old and lucerne has been updated multiple times since then, you may just want to completely wipe out your existing data files and start clean.  I've noticed that when it's updated, it doesn't always recognize the timestamping of an older database version.

**Comment by neerajbadlani** [comment]
Hi @gtoph  , 
Heres what I did, I created new source and data dirs and started indexing from scratch . So I dont think thats the issue here . 
[Update] : I removed assignTags option to see if it  increases the speed , unfortunately it doesnt .

**Comment by vladak** [comment]
I'd suggest bumping the log level, reindex and attach it.

Dne po 29. 4. 2019 20:50 uživatel Neeraj Badlani <notifications@github.com>
napsal:

**Comment by neerajbadlani** [comment]
Hi @vladak , Do you mind sharing exact steps I need to do , I am already passing --verbose switch on cmd line . And logging.properties file has .level=ALL already set . 
I also just looked at my server to see what the system is doing , apprently its re-making  entire history again , just guessing , since I see bunch of git log processes . 

I also have the old logs . Do you want me to look for something in the logs ? 
Thanks

**Comment by vladak** [comment]
You seem to be all set w.r.t. logging. Could you share the log ?

**Comment by neerajbadlani** [comment]
Just realized , after starting another run , logs are overwritten , will reproduce logs , scrub 'em of file names and dir structure and share . 

FYI , Below command line with couple of switches removed is faster , but I lose History and Annotation capabilities with this . 


 
[work] /auto/sw/licensed/sun/jdk/1.8.0_91-64/bin/java -Djava.util.logging.config.file=logging.properties -jar opengrok/lib/opengrok.jar --ctags /nobackup/nebadlan/binaries/bin/ctags --dataRoot /nobackup/nebadlan/work/opengrok/data --source /nobackup/nebadlan/work/opengrok/src --depth 5 --history --projects --writeCon
fig /nobackup/nebadlan/work/opengrok/etc/configuration.xml  --threads 16

**Comment by neerajbadlani** [comment]
Cant seem to repro the issue anymore . Incremental Indexing is fast now . 
However just see one issue though . "Last Index Update " doesnt update the time even though indexes and history is updated .

**Comment by vladak** [comment]
Ok, closing.

**Comment by vladak** [comment]
As for the time of last index update, there should be a file called `timestamp` right under the data root directory that is "touched" at the end of the indexing and the web app will then reload the time. I see that you do not use the -U option of the indexer which is probably the reason for why the time is not refreshed.
