### ISSUE TITLE
Monitoring opengrok index timestamp

### ISSUE THREAD

**Issue by pavanpenmetsa** [oracle/opengrok#2763]
Hi,
   I am using Opengrok 1.0 tomcat 8, Linux . 
   My opengrok UI is ldap auth.  I need to monitor opengrok last index timestamp. timestamp file seems to be empty. Is there a way for me to get the index timestamp.

**Comment by tulinkry** [comment]
It is the last modification date of the file, not the content.

**Comment by pavanpenmetsa** [comment]
Awesome !! thankyou
