### ISSUE TITLE
Perforce History cache not working

### ISSUE THREAD

**Issue by pavanpenmetsa** [oracle/opengrok#2764]
Hi All,

System confi: opengrok 1.0, tomcat 8, centos 7

opengrok is not able to generate hisory and annotations for perforce repo

i have created a .p4config under the root source directory and ran the following command:

/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx8g -d64 -server -Dorg.opensolaris.opengrok.history.Perforce=/usr/bin/p4 -Djava.util.logging.config.file=/grok/logging.properties -jar /opengrok/bin/../lib/opengrok.jar -vvv -r on -H -c /usr/bin/ctags-exuberant -a on  -W /grok/etc/configuration.xml -S -P -U localhost:2424 -s /grok/src -d /grok/data -H

The p4 source root is /home/centos/src with has symlink to /grok/src used in above command.  I am getting following errors. 
Also why is it detecting it as GIT repo

09:29:28 WARNING: Non-zero exit status 1 from command [/usr/bin/p4, dirs, *] in directory /src/app_218_freeze_core/app/218/freeze: Path '/src/app_218_freeze_core/app/218/freeze/*/...' is not under client's root '/home/centos/src'.

09:29:28 WARNING: Non-zero exit status 1 from command [/usr/bin/p4, files, *] in directory /src/app_218_freeze_core/app/218/freeze: Path '/src/app_218_freeze_core/app/218/freeze/*' is not under client's root '/home/centos/src'.

09:29:28 WARNING: Failed to determineCurrentVersion for /src/app_main_core/app/main/core: java.io.IOException: fatal: Not a git repository (or any parent up to mount point /src)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

09:29:28 WARNING: Non-zero exit status 128 from command [git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, --date=rfc] in directory /src/app_main_core/app/main/core: fatal: Not a git repository (or any parent up to mount point /src)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

09:29:28 WARNING: An error occured while creating cache for /src/app_main_core/app/main/core (GitRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/src/app_main_core/app/main/core" Exit code: 128
	at org.opensolaris.opengrok.history.GitHistoryParser.parse(GitHistoryParser.java:165)
	at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:513)

**Comment by vladak** [comment]
Firstly, try with the latest OpenGrok version. We do not have the capacity to provide support for old versions. Namely, this could be a problem with symlinks (judging by the `is not under client's root` message) which was I believe fixed post 1.0.

In general, people seem to be struggling with getting Perforce working with OpenGrok for some reason. Just recently, a discussion was re-initiated in (already closed) #926.

**Comment by kghariyal** [comment]
Hello,
I am experiencing the same issue. History view isn't available while the historycache has been generated. I can see the .gz file available in historycache folder as well but the history isn't showing up for that file.
Opengrok version-1.2.23
Apache Tomcat 8.0.28
