### ISSUE TITLE
Git tag parsing is sub-optimal

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2765]
When working on a fix for #2755 I noticed that Git tag parsing is sub-optimal performance wise  - to determine changeset/date for each tag a new command is spawned via `Executor` in `buildTagEntry()`. For repositories with large set of tags (e.g. Linux kernel) this could be taxing.

Either convert this to parallel execution (thread pool) or find a way how to get all the data in single command.

**Comment by swayamraina** [comment]
Hi @vladak,
I am interested in picking this up. 
I am thinking something like `ExecutorThreadPool` which accepts an `Executor` and returns a `CompletableFuture`.
Since the underlying process executed is `log -n 1`, I don't see an advantage of storing all the data.

**Comment by vladak** [comment]
Cool. It might be possible to use existing pool.

**Comment by vladak** [comment]
fixed via #3162
