### ISSUE TITLE
Reindex particular project

### ISSUE THREAD

**Issue by piladon** [oracle/opengrok#2767]
HI 

How can I reindex a particular BitBucket project in opengrok?

I normally reindex using 
/opt/opengrok/opengrok index

But this reindexes the whole instance.

**Comment by vladak** [comment]
Run the indexer directly just with the project path, plus -H with project path to generate the history. Something like:
```
java -jar opengrok.jar -s /source -d /data ... -H /project /project
```
For automated approach see https://github.com/oracle/opengrok/wiki/Repository-synchronization and https://github.com/oracle/opengrok/wiki/Per-project-management
