### ISSUE TITLE
Please can you publish a schema for the configuration.xml file

### ISSUE THREAD

**Issue by msillence** [oracle/opengrok#2768]
Feature request

Recently I was trying to configure the suggesterConfig to reduce the allowedFields and though I'm familiar with xml beans I had to look up the source code as this isn't documented on the opengrok site. For others I imagine it might help if there were a schema published as many tools can then aid them.

**Comment by vladak** [comment]
I am afraid there is no such a thing. Short term, the configuration tunables should be properly documented -  the suggester tunables are described in detail on https://github.com/oracle/opengrok/wiki/Suggester#configuration. Long term, we need to replace the XML format with something else (#2329).
