### ISSUE TITLE
Markdown does not show when running docker:latest

### ISSUE THREAD

**Issue by JozoVilcek** [oracle/opengrok#2776]
I was testing opengrok locally and used official docker run from 
https://github.com/OpenGrok/docker#how-to-run

So I did
`docker run -d -v <path/to/your/src>:/opengrok/src -p 8080:8080 opengrok/docker:latest`
waited for initial reindex to finish and then look at repo listing with README.md. The result was
![image](https://user-images.githubusercontent.com/3295033/58021696-e5192d80-7b0b-11e9-9f7a-716b377dd720.png)
without markdown rendered. Does it need to be enabled somehow?

**Comment by vladak** [comment]
I assume this is with OpenGrok 1.2.8 ("latest" will not mean much when someone revisits this issue in the future)

The README detection is done unconditionally in `src/main/java/org/opengrok/web/DirectoryListing.java#extraListTo()` (called from `list.jsp`):
```java

214          if (entries != null) {
215              for (DirectoryEntry entry : entries) {
216                  File child = entry.getFile();
217                  if (ignoredNames.ignore(child)) {
218                      continue;
219                  }
220                  String filename = child.getName();
221                  String filenameLower = filename.toLowerCase(Locale.ROOT);
222                  if (filenameLower.startsWith("readme") ||
223                          filenameLower.endsWith("readme")) {
224                      readMes.add(filename);
225                  }
```
So unless the README files are explicitly ignored they should be displayed.

**Comment by JozoVilcek** [comment]
Hm, I do not understand it, but after few refreshes or wait time, opengrok now shows readme rendered. I apologise for confusion

**Comment by vladak** [comment]
Well, this could be a bug related to timing/caching.
