### ISSUE TITLE
Lookup Commiter ID

### ISSUE THREAD

**Issue by jeasterling** [oracle/opengrok#2780]
Hello,
   I used to run a very old version of Opengrok, and it had a feature when you go to the history you could click on the commiter id and pull back information about that user (I had to write a lookup and some configuration) Does the current version of Opengrok have something like this?

**Comment by vladak** [comment]
Yes, this is configured with `userPage` and `userPageSuffix`

I added some info to https://github.com/oracle/opengrok/wiki/Webapp-configuration#configuration-tunables
