### ISSUE TITLE
Home page project links missing webapp name

### ISSUE THREAD

**Issue by cross** [oracle/opengrok#2802]
Running a fairly recent build from head (1.2.9), I have found that the links to projects at the top-level web  page do not include the web app name.

My app is reached at `http://localhost:8080/source/`, and there are two projects/repositories listed in the table below the search input fields.  Each of these links to `http://localhost:8080/xref/projectA`, which doesn't work.  The correct href should be `http://localhost:8080/source/xref/projectA`, which works when I manually adjust the URL.

I _think_ these links used to be correct, and that I have used them before, but I cannot verify that at the moment.

Is this a tomcat config issue, or something wrong in opengrok?

**Comment by vladak** [comment]
possibly related to #2719

**Comment by vladak** [comment]
I can confirm - seeing the same.

**Comment by IamTHEvilONE** [comment]
I'm still seeing this issue on 1.2.14 after upgrading, deploying the new WAR, and cleaning out the indexes and re-indexing (to push the new config).

The html code after generation looks like this:

<td class="name repository">
<a href="/xref/version"
 title="Xref for project version">
version
 </a>

so it's still not pulling the webapp name into it.

**Comment by vladak** [comment]
Looks like while `request` is implicit variable in JSP, it is not in JSTL: http://www.informit.com/articles/article.aspx?p=30946&seqNum=7

**Comment by cross** [comment]
Thank you @IamTHEvilONE .  I was also still seeing it, but hadn't gotten to verifying that I'd cleared and flushed everything until today.
This issue should be reopened, @vladak ?
Hmm.  I guess not if 3af6c7cd1802b84919948fd09d3622ecc50d9f17 fixes it?

**Comment by vladak** [comment]
Good question @cross, there does not seem to be established process for such case. Let's keep this simple for now.

**Comment by IamTHEvilONE** [comment]
Just commenting that this is fixed in release 1.2.16 when I was testing the build.
