### ISSUE TITLE
Request to include private in the regex for definitions (private def) for scala code

### ISSUE THREAD

**Issue by IamTHEvilONE** [oracle/opengrok#2804]
Can we add private the regex for scala definitions?

The current Scala regex (I think) is:

`--regex-scala=/^[[:space:]]*((abstract|final|sealed|implicit|lazy|)[[:space:]]*)*def[[:space:]]+([a-zA-Z0-9_]+)/\3/m,methods/` 

I would like to know if we could add private?

`--regex-scala=/^[[:space:]]*((private|abstract|final|sealed|implicit|lazy|)[[:space:]]*)*def[[:space:]]+([a-zA-Z0-9_]+)/\3/m,methods/` 

it just happens that the coding done where I am uses the term private a lot when doing a def statement.

I'm just not a coder, or else I'd try and do the commit myself for opengrok.

Here is the line of code to modify (assuming I got it correct):

https://github.com/oracle/opengrok/blob/81b586e651d9f2a40ab5a985d2b7080ae732dd83/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java#L332

OpenGrok Build: opengrok-1.2.9
U-Ctags build date:   Compiled: Jun 13 2019, 15:57:49
git version 2.22.0
Server version:        Apache Tomcat/8.5.42
Server built:          Jun 4 2019 20:29:04 UTC
Server number:         8.5.42.0
OS Name:               Linux
OS Version:            3.10.0-327.el7.x86_64
Architecture:          amd64
Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
JVM Version:           1.8.0_212-b04
JVM Vendor:            Oracle Corporation
CATALINA_BASE:         /opt/tomcat
CATALINA_HOME:         /opt/tomcat

**Comment by tarzanek** [comment]
you're really like 10mins from sending a PR and become a developer! :-D
quickly skim through: https://github.com/oracle/opengrok/wiki/Developer-intro
then 1) fork the repo (there is a button on https://github.com/oracle/opengrok top right "Fork" , clone it locally, create a branch as per above intro)
2) fix the file you've found
3) commit the fix and just push back the branch to github (github desktop should make all this easy)

4) if you go on github to your repo, just click on create pull request from the branch you've created, tests will happen on Travis (take cca 20mins) and then either me or @vladak will merge your change!

thank you in advance for the contribution!
Lubos

**Comment by IamTHEvilONE** [comment]
Hopefully I did that right on my private fork, then branch, then commit it back in, and pull from there.  I did it mostly via github.com without even using a local client since it's a single like of code to be edited.
