### ISSUE TITLE
add --release 8 arguments to JDK9+ build profiles

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2820]
To prevent regression of #2815 the build should add `--release 8` arguments to javac when building with JDK9+ as per https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495357838

e.g. `opengrok-indexer/pom.xml` contains the `java9plus` profile already that's used for surefire. It can be used for general compilation also. Similarly for other modules.

**Comment by tulinkry** [comment]
https://github.com/eclipse/jetty.project/blob/jetty-9.4.18.v20190429/pom.xml#L1843-L1858

**Comment by vladak** [comment]
Care to submit a PR ? :-)

**Comment by tulinkry** [comment]
sure, done
