### ISSUE TITLE
More control over repository table formatting

### ISSUE THREAD

**Issue by cross** [oracle/opengrok#2832]
I looked at #1478 which is about the same as this, but that had offshoots and was in the end closed.  But, check there for background.

I have a table, and would like to see more information in the "Current version" column for my repositories.  In `default/style.css`, that column is set to `width: 400px`, and if I increase that (I used `40%` which looked good to me), the text is still truncated as it was before.

This turns out to be due to the default value of `currentIndexedCollapseThreshold`, `27`.  This parameter seems to be configurable, and I can set it in my configuration.xml, but it will get overwritten when I index again with `-W configuration.xml`

So, the question part is how can I retain a value for that parameter.  Second, is there any way to make something either "smarter" or more configurable for the width of those table columns?

**Comment by vladak** [comment]
You need to use https://github.com/oracle/opengrok/wiki/Read-only-configuration to make extra tunables persistent.

**Comment by vladak** [comment]
As for smarter, we are open to suggestions. PRs, even :-)

**Comment by cross** [comment]
Okay.  Looking at that page, it describes a config file `read-only.xml` Which doesn't get read by the U/I. I created that, and paseds it to indexing, still specifying `-W /var/opengrok/etc/configuration.xml`.

I see now that it does what I want, that `-R` reads it into the indexers brain, and it gets written with `-W`.  I had trouble figuring that out from the documentation above though, perhaps this use case could be more clearly described there?

I'll close this now, although having the width of the column(s) also be a parameter may be an idea...
