### ISSUE TITLE
Support for .PKG extension files

### ISSUE THREAD

**Issue by OscarGelvez** [oracle/opengrok#2833]
What's up friend?
I would like to know if the .pkg extension files are supported? Or if it is possible to add support for this type of files.
I need it for a project that I'm doing where these types of files are worked.
These files have the following structure:

/ ********* Specification ************* /
Create or replace namePackage
Procedure1 ();
Procedure2 ();
Function ();
Procedure3 ();
END namePackage;

/ ********* Body ************* /
Create or replace namePackage
// Global Attributes
// Global variables

Procedure1 () Begin / * code * / End Procedure1;
Procedure1 () Begin / * code * / End Procedure2;
Function1 () Begin / * code * / End Function1;
Procedure4 () Begin / * code * / End Procedure3;

END namePackage;

The methods or functions that are in the block specification can be accessed publicly.

I appreciate your collaboration
regards

**Comment by vladak** [comment]
What language is the .pkg extension tied with ?

**Comment by OscarGelvez** [comment]
Hi friend
In PL / SQL.

**Comment by OscarGelvez** [comment]
I modified the opengrok-indexer / src / main / java / org / opengrok / indexer / analysis / Ctags.java class to support the extension of .PKG file and also modify the opengrok-indexer / src / main / java / org / opengrok / indexer / analysis / sql / plsql / PLSQLAnalyzerFactory class by adding the PKG suffix.

I would like to know how you could modify your own behavior when it comes to a file with this extension.

I need the syntactic analyzer to recognize that there can be 2 times the declaration of a method due to the structure of the files that I exposed previously.

**Comment by idodeclare** [comment]
@OscarGelvez , release 1.3.4 support dynamically reconfiguring `Ctags` operation when `-A,--analyzer` is used to map an extension. (Your private build statically maps SQL to .PKG already of course, but I was just informing.)

As to recognizing twice-declared methods, that would be a requirement of Universal Ctags. Please could you get the latest version of u-ctags, and run it on your file (making sure to map SQL to .PKG on the command-line) to see what tags it finds from your test file.

**Comment by vladak** [comment]
Closing since .pkg is too generic and a way how to configure indexer to provide the mapping exists.
