### ISSUE TITLE
Clustered indexes

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#2839]
Hi team,

Question.
Are you planning to support OpenGrok clustered indexes?

I mean: 
- several indexes would be generated via several source roots
- "merged" into single OpenGrok app
- meaning a search set from the app would target all indexes
- meaning all sources from all source roots would be available (with history) from the app
 
I took a quick look to Lucene Core pages and understand Lucene Core can not support this.
Elasticsearch would do.

Corollary question.
Are you planning to support Elasticsearch for indexes?

**Comment by vladak** [comment]
That will be pretty big project, perhaps a topic for another master thesis. The #779 tracks this.

**Comment by ChristopheBordieu** [comment]
So, should I consider short/mid term answer is no?

**Comment by vladak** [comment]
Yeah. This is definitely long term project that will have yet unidentified
impact on various subsystems (suggester, tooling).

Dne čt 27. 6. 2019 16:43 uživatel ChristopheBordieu <
notifications@github.com> napsal:

**Comment by ChristopheBordieu** [comment]
Ok. Thanks @vladak for quick answer.
