### ISSUE TITLE
Strange behaviour while scrolling.

### ISSUE THREAD

**Issue by sagarkhushalani** [oracle/opengrok#2841]
Related to https://github.com/oracle/opengrok/issues/1829, possible duplicate but slightly worse. This is a bug, since usability is hindered.

We are seeing some strange behaviour in the OpenGrok UI, specifically related to scrolling on the source page.

Things to note:
* opengrok version 1.2.8
* JDK 1.8
* OS: Fedora 29 (dockerized)
* Server: Jetty
* tried it using multiple browsers
* attempted to fix it by modifying the style.css file but failed

## Issue 1
1. Search for something (we used symbol) in a project
2. Click on a file name in the search results (not specific line)
    a. Expected results: file loads and line shown under header is line #1
    b. Actual: file loads, and line shown is line no. 7 or 8. The previous 6-7 lines are hidden behind the header and, since the header is transparent, appear as mangled text.
![file_click_error](https://user-images.githubusercontent.com/14348843/60361836-ed834480-99a4-11e9-916e-1415d9d25bf5.png)

## Issue 2
1. Click on a specific line in the file (on the search results page)
   a. Expected results: file loads, and takes you directly to the line corresponding to the result's line number.
   b. File loads, scrolls below the line (so it hides behind the header), and then scrolls back up to the correct line
![file_click_error_line](https://user-images.githubusercontent.com/14348843/60361840-ef4d0800-99a4-11e9-97d4-3814f8ff3928.png)

(note: the black lines in the pictures above are just hiding file names/paths)

Just wondering if there's a good way to fix this. What I tried (and I'm not good with CSS) is attached as a patch (zip file)
[style.zip](https://github.com/oracle/opengrok/files/3340337/style.zip)

file.

**Comment by sagarkhushalani** [comment]
Browsers tried:
* Chrome 75.0.3770.80 - 32bit
* Firefox 66.05 - 64bit
* Edge  41.16299.1004.0

**Comment by vladak** [comment]
Did you try from multiple distinct clients ?

**Comment by sagarkhushalani** [comment]
I have, and both Linux (Firefox 67.04 / Ubuntu 19.04)  and Windows 10.

**Comment by tulinkry** [comment]
Issue 2 is known and described in the ticket you mentioned.

**Comment by tulinkry** [comment]
Did you upgrade your opengrok version or have you just started with opengrok? I suggest clearing browser cache if you did the upgrade.

**Comment by sagarkhushalani** [comment]
@tulinkry 
This was a clean install. Also, though, because Chrome is famous for caching even not necessary, I cleared the cache for all the browsers I tried, and got the same result.

**Comment by vladak** [comment]
Could you try to run the official Docker image to see if the same problem happens there as well ?

**Comment by sagarkhushalani** [comment]
Tried the official image - it worked fine, so made some changes to our image:

- Removed _header_include_: we had some text in this file file (company name + a browse here link)
- Removed the -G option (shouldn't affect anything with this, though, I think)

It worked correctly with these changes. I'm assuming the page doesn't do well with the _header_include_ file, even though that is an official option, but I'm not sure why.

**Comment by vladak** [comment]
It seems you need to be careful with what you put inside the include.

Dne st 3. 7. 2019 21:22 uživatel Sagar Khushalani <notifications@github.com>
napsal:
