### ISSUE TITLE
python tools - --incoming check does not return the correct exit value

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2843]
```
ktulinger:opengrok ktulinger$ opengrok-mirror --loglevel INFO -c /var/opengrok/etc/mirror-config-generated.yml --incoming -U http://localhost:8080 project-x
output of ['/usr/local/bin/git', 'pull', '--dry-run']:

No incoming changes for repositories in project project-x
ktulinger:opengrok ktulinger$ echo $?
0
```

As I understood the return value should be 2, so the sync chain is skipped however this is never met.

**Comment by vladak** [comment]
dup of #2432 perhaps ?

**Comment by tulinkry** [comment]
No.

I mean that this code https://github.com/oracle/opengrok/blob/master/opengrok-tools/src/main/python/opengrok_tools/mirror.py never interprets the return value 2. So this process never exits with 2 to signal the sync to stop.

**Comment by vladak** [comment]
Oh, I only had sync.py in mind when thinking about retval of 2.

Dne po 1. 7. 2019 12:33 uživatel Kryštof Tulinger <notifications@github.com>
napsal:

**Comment by tulinkry** [comment]
So actually this `--incoming` check has never worked.

**Comment by vladak** [comment]
Actually, this worked before cset f3fa009afe46e8617c5ec667ce72c45dad6e84d4 so this is a regression.

**Comment by tulinkry** [comment]
Good job finding it!

**Comment by vladak** [comment]
Well, I know it is working because this works in our production instance running earlier version.

**Comment by tulinkry** [comment]
I also used it quite a lot, however I never tried to verify if it's actually working properly :-D

**Comment by vladak** [comment]
Time for unit test I think..
