### ISSUE TITLE
python tools --incoming check should check if the project has no index yet

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2844]
I'm not sure if this is implemented or not right now but I'm adding an issue to find this out.

When using the incoming check for mirror.py + sync.py combo (after #2843 is fixed), I suspect that for the first time the sync.py is run (projects are freshly clonned to src_root, no index exists for them), the incomming check would skip the indexing for all of the projects (=no changes as expected because it has just been clonned). So the check could be more robust and check the index presence and also the scm changes presence.

**Comment by vladak** [comment]
Not sure I understand the use case. Once all the projects are cloned for the first time, I'd like to index them all, no matter if there are incoming changes or not. Is this what you are proposing ?

For the opposite case: if you wanted to check for index presence (using RESful API call to retrieve the value of the `indexed` property for given project), I'd do it in separate script rather than making `mirror.py` smarter (or more bloated, depends on POV).

**Comment by tulinkry** [comment]
> Once all the projects are cloned for the first time, I'd like to index them all, no matter if there are incoming changes or not. Is this what you are proposing ?

Yes, exactly. With current setup the index would be skipped (= no new changes since the last clone few minutes ago).

The use case is that I don't want to update the sync-config.yml for the first index in a project. Why would it be necessary to use different config for the first-time index and second-time index? Of course, this is possible to check with a different script (which would include the call to mirror.py), it seems to me as this is exactly the job for mirror.py => skip the index when it's not needed.

Also, another use case is, when I add the projects dynamically to the running instance - I clone it to the src_root and run sync.py and I expect the sync.py to index it properly for the first time (and not to skip it with the `--incoming` check). This would essentially mean to update the sync-config to remove the `--incoming` check every time new project is clonned.

**Comment by vladak** [comment]
I work around it by stripping/resetting the repo in question by one changeset. Let's make `mirror.py` smarter then. After all, it already posts API requests to the web app to retrieve the source root value.
