### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [oracle/opengrok#2848]
Hi
The following lines have cryptographic API misuses. <br> File name => opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java: Line number => 215: API name => MessageDigest:<BR> File name => opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java: Line number => 211: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java: Line number => 215: API name => MessageDigest:<BR>

**Comment by vladak** [comment]
Could you expand on what is the problem exactly ?

**Comment by vladak** [comment]
The context: https://github.com/oracle/opengrok/blob/182742d5b8b24d0a98f0f088f820919f84737571/opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java#L209-L215
According to the somewhat terse problem description, it looks like the submitter considers all usages of SHA-1 to be a misuse and wants to replace by stronger variants of the message digest algorithm.
The string literal actually contains a comment: https://github.com/oracle/opengrok/blob/182742d5b8b24d0a98f0f088f820919f84737571/opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java#L77-L78 so this looks like a misunderstanding of the intention of the code.
