### ISSUE TITLE
Where is the configuration.xml file?

### ISSUE THREAD

**Issue by kiwidoggie** [oracle/opengrok#2855]
All I have found is: https://github.com/oracle/opengrok/issues/2771

No reply. I have extracted the binfiles from releases, they aren't there. Tried just copying the source.war to tomcat, and it complains that it can't find configuration.xml. I never had one to begin with? Is this something that was supposed to be automatically generated? The install instructions could use quite a bit of work.

**Comment by vladak** [comment]
https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step2---deploy-the-web-application says:
> This configuration file is created by the indexer when using the -W option and the web application reads the file on startup

**Comment by kiwidoggie** [comment]
Any particular reason that this wouldn't be created in that location? Or search paths for where it could be created? It does not work.

**Comment by vladak** [comment]
Could you share some details, i.e. how do you run the indexer, what it writes to the log, etc ?

**Comment by tulinkry** [comment]
This issue could be more appropriate (eventhough it uses old tools): 

https://github.com/oracle/opengrok/issues/1231
