### ISSUE TITLE
ignore dirs option -i did not work when use specified configuration

### ISSUE THREAD

**Issue by zhouhua852** [oracle/opengrok#2858]
Usage: java -jar opengrok.jar [options] [subDir1 [...]]

 -i, --ignore pattern
        Ignore the named files (prefixed with 'f:')
        or directories (prefixed with 'd:').
        Supports wildcards (example: -i *.so -i *.dll)

  -R /path/to/configuration
        Read configuration from the specified file.

When I first used opengrok.jar -i "ignoredirs" option, it worked very well. But when I used -R option to specified configuration file and I also want to ignore some dirs, I find -i option is not work。
What can I do to make these two options take effect at the same time?

**Comment by vladak** [comment]
how does your read only configuration file look like ?

**Comment by vladak** [comment]
I just tried with this read only configuration file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_121" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration">

  <void property="ignoredNames">
   <void property="ignoredDirs">
    <void property="items">
     <void method="add">
      <string>foobar</string>
     </void>
    </void>
   </void>
  </void>

 </object>
</java>
```

and ran the indexer like this:
```
-s
/var/opengrok/src
-d
/var/opengrok/data
-R
/var/opengrok/etc/readonly_config.xml
-i
d:barfoo
-W
/var/opengrok/etc/configuration.xml
-P
-H
-S
-G
-U
http://localhost:8080/source
```

Once the indexer finished, `/var/opengrok/etc/configuration.xml` contained this snippet:

```xml
  <void id="IgnoredNames0" property="ignoredNames">                             
   <void id="IgnoredDirs0" property="ignoredDirs">                              
    <void property="items">                                                     
     <void method="add">                                                        
      <string>foobar</string>                                                   
     </void>                                                                    
     <void method="add">                                                        
      <string>barfoo</string>                                                   
     </void> 
...
```

In my case `foobar` and `barfoo` are valid repositories under the source root. They are shown on the index page (which is a bug) however are ignored when displaying directory listing.

**Comment by zhouhua852** [comment]
thank you, I solve the problem by myself.

**Comment by vladak** [comment]
What was the issue specifically ?

Dne pá 19. 7. 2019 11:22 uživatel zhou <notifications@github.com> napsal:
