### ISSUE TITLE
Files not showing in webapp

### ISSUE THREAD

**Issue by momia42** [oracle/opengrok#2859]
OpenGrok version : 1.2.0
JDK: 1.8.0
Tomcat: 8.5.41
Running the Opengrok indexer appears to work all of my files are in the /data/index directory there are also in the /data/xref directory however an entire folder is missing on the web app. I have tried completely wiping the data directory and re-indexing but the same thing occurs. Any advice or anything to check? I've gone down many rabbit holes to no avail?

**Comment by vladak** [comment]
How do you run the indexer ? Is this specific just to some directories or all of them ? Does the webapp have rights to access the files ? Is there anything of interest in Tomcat logs ?

**Comment by momia42** [comment]
the indexer is run with opengrok-indexer wrapper. Some directories publish and are fine others do not though all directores appear in /data and in the configuration.xml 
I am seeing the following error in the tomcat logs
```
 SEVERE [http-nio-8080-exec-8] org.opengrok.indexer.configuration.RuntimeEnvironment.maybeRefreshSearcherManager maybeRefresh failed
        java.nio.file.NoSuchFileException: /opt/opengrok/data/index/[filedir]
```

**Comment by vladak** [comment]
What are the indexer options ?

**Comment by vladak** [comment]
And what is special about those directories that are not shown ?

**Comment by vladak** [comment]
Does `/opt/opengrok/data/index/[filedir]` actually exist on the file system ?

**Comment by momia42** [comment]
the commands that are are run 
`opengrok-indexer -l DEBUG \
    -a /grok/runtime/lib/opengrok.jar -- \
    -s /opengrok/src \
    -d /opengrok/data \
    -H -P -S -G -v \ 
    -W /var/opengrok/etc/configuration.xml -U http://localhost:8080 "$@"
`

The files are all in the directories just not showing up on the web application side. I have tried wiping out the entire /data directory and forcing a re-index but the same thing happens

**Comment by vladak** [comment]
There is a strange mismatch between the log entry that seems to reference data root as `/opt/opengrok/data` and you run the indexer with data root set to `/opengrok/data`. Is this a symlink perhaps ?

**Comment by momia42** [comment]
Yes sorry the filing path has changed they are both at /opt/opengrok/data

**Comment by vladak** [comment]
could you ask all of the questions ?

**Comment by momia42** [comment]
Yes apologies,
_What are the indexer options ?_
`opengrok-indexer -l DEBUG \ -a /grok/runtime/lib/opengrok.jar -- \ -s /opt/opengrok/src \ -d /opt/opengrok/data \ -H -P -S -G -v \ -W /var/opengrok/etc/configuration.xml -U http://localhost:8080 "$@"`

_Does /opt/opengrok/data/index/[filedir] actually exist on the file system ?_
Yes the files appear in the /data/index dir and in the /xref dir. They also appear to write into the configuration.xml after indexing

_And what is special about those directories that are not shown ?_
Nothing that I can discern, the file extensions are the same the file permissions on both the src and data are the same. The size of the files are roughly equivalent

_Does the webapp have rights to access the files ?_
Yes it does the files permission are identical across all directories 

I think I have answered all questions, apologies if I have missed any

**Comment by vladak** [comment]
What happens if you access the file directly using the xref link ? E.g. on my system the source root is `/var/opengrok/src` and underneat there is a subdirectory `foo-clone`, that has file `lcd.c`. I can access the file on the filesystem just fine:
```
$ file /var/opengrok/src/foo-clone/lcd.c 
/var/opengrok/src/foo-clone/lcd.c: c program text, UTF-8 Unicode text
```
The webapp is running with the same credentials so it should be able to access the file as well - 
http://localhost:8080/source/xref/foo-clone/lcd.c confirms.

What happens in your case when you repeat the same little exercise for one of the directories that is not visible in the listing in webapp ?

**Comment by vladak** [comment]
Also, do you run OpenGrok in Docker container ? Are you perhaps running on SELinux ?

**Comment by vladak** [comment]
Closing for lack of response; feel free to reopen.
