### ISSUE TITLE
Can or Will opengrok support to search symbol specificly when there are two symbol with same name?

### ISSUE THREAD

**Issue by yeleaveszi** [oracle/opengrok#2860]
Can or Will opengrok support to search symbol specificly when there are two symbol with same name?
Just like _IntelliJ IDEA_ and _Android Studio_ do(command + click).
For example:
Class A : /test/a/foo.class
Class B : /test/b/foo.class
When searching for symbol foo, opengrok now just return both.

**Comment by tulinkry** [comment]
OpenGrok can't do that. It's not just plaintext - you can search for symbol usage (the class) and not just any "foo" in your source code.

**Comment by vladak** [comment]
With the current architecture this is not really feasible to implement hence closing.
