### ISSUE TITLE
how to activate authorization

### ISSUE THREAD

**Issue by elkin5** [oracle/opengrok#2861]
I require have proyectos visibles for differents types of roles. I saw the documentation but it is not clear for me

**Comment by vladak** [comment]
Depends on what is your use case. From high level point of view: you need to supply authentication information to the OpenGrok authorization framework via HTTP headers. The rest is then very flexible.

The https://github.com/oracle/opengrok/wiki/Authorization has some examples.

You need to come up with set of concrete questions.

**Comment by vladak** [comment]
#2872 might be also of interest.

If you have more questions feel free to reopen.
