### ISSUE TITLE
.gitignore file should not be ignored by default

### ISSUE THREAD

**Issue by marceloavilaoliveira** [oracle/opengrok#2870]
In commit c5f6687acb814ebafdeee9698aa261d529893523 made in 12-Aug-17, Vladimir Kotal made OpenGrok ignore .gitignore file by default. I don't what was the goal with this action but I doesn't seem to be a good idea because someone could want to know, for example, if some file/directory is ignored in several repositories.

**Comment by vladak** [comment]
That's probably a bug. Feel free to submit a pull request - for such simple change this could be done completely from the the Github web interface.
