### ISSUE TITLE
'*' or '?' not allowed as first character in WildcardQuery

### ISSUE THREAD

**Issue by julytn** [oracle/opengrok#2886]
I upgraded my OpenGrok from version 1.2.8 to the latest version 1.3.0 in hope of being able to use a `*` as the first character in a search. But neither versions allow this when OpenGrok version 1.0 allows using `*` as the first character. 

For example, if I wanted to search `*hello`, currently it gives this error: 
```
Error
Unable to parse your query: 
You might try to enclose your search term in quotes, escape special characters with \, or read the Help on the query language. Error message from parser:
Cannot parse '*hello': '*' or '?' not allowed as first character in WildcardQuery
```

Version 1.0 does not give an error:
```
Your search full:*hello did not match any files. 
Suggestions:
Make sure all terms are spelled correctly.
Try different keywords.
Try more general keywords.
Use 'wil*' cards if you are looking for partial match.
```

**Comment by ahornace** [comment]
Hi,

can you please check your configuration file for `allowLeadingWildcard` option? If it is missing or is specified to `false`, then you can add it there. Also, it can be specified when running the indexer: https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java#L559

Maybe we should be enable it by default.

Regards,
Adam

**Comment by vladak** [comment]
Increased CPU usage is probably the reason why it is disabled by default. Not sure what is the extra load, though.
