### ISSUE TITLE
nested git repositories not found

### ISSUE THREAD

**Issue by Z4rc** [oracle/opengrok#2900]
I'm using the latest OpenGrok 1.3.1 release, and I have an issue with the repository detection for the history creation.

Our project is using repo for the file versioning, allowing to handle multiple Git repositories. The folder structure looks like:

```
baseDirectory/.repo
baseDirectory/anotherDirectory
baseDirectory/anotherDirectory/.git
```
The grok source dir has a symbolic link to the baseDirectory.

The problem is that the git repositories are not detected and therefore history is not working. Whereas it is working if I create a symlink in the grok source dir directly to the git repositories. But not as a subdir. The strange thing is that we used opengrok version 1.0 before and we had no problems with that. I've already played with parameter --depth but it didn't have any effect.
Indexing itself is working fine, only the history is missing.

**Comment by vladak** [comment]
There are similar issues: #2594, #1831

**Comment by vladak** [comment]
Does the problem happen if you avoid symlinks altogether ?

**Comment by jwehler** [comment]
I've observed the same behavior, but without the link. I was able to work around the problem by initializing an empty git repository at the project level (same level as .repo). Once I did that and re-indexed, the history for all the git projects below worked.

It worked fine before on the same release when I was running with --economical --optimize options, but that would leave me with other issues, like empty xref content when viewing files. Dropped those options then the content was back as expected, but lost history.

The other projects I have in the same opengrok src dir do not have this issue, only the AOSP-like projects that used 'repo' to sync. The other projects have similar layouts though, like:
OPENGROK_SRC_ROOT/project1/subdir1/.git
OPENGROK_SRC_ROOT/project1/subdir2/.git
vs the problematic one:
OPENGROK_SRC_ROOT/project2/.repo
OPENGROK_SRC_ROOT/project2/subdir1/.git
OPENGROK_SRC_ROOT/project2/subdir2/.git

The only thing I could think of that is unique is that repo sync can create local files in the root that are not part of an index, for example:
OPENGROK_SRC_ROOT/project2/somefile
which is the result of a manifest.xml rule like:
<copyfile dest="somefile" src="somefile"/>
which copies somefile from the project to the specified location, in this case the repo root.

**Comment by idodeclare** [comment]
This issue is not related to symlinks.

It seems to be an unintended effect of 32c956e ("add sub-repositories of the same type as parent ... [to fix] #1461") that is preventing `HistoryGuru` from searching under `RepoRepository` for @Z4rc's `GitRepository` children.

**Comment by vladak** [comment]
I thought this might be the problem. The `RepoRepository` class is odd beast.

**Comment by Z4rc** [comment]
You have already figured it out, but for completeness: The issue is not related to symlinks. As proposed by @vladak, I copied all sources to the grok source directory (to avoid symlinks) but got the same result:
```
INFO: Creating historycache for 1 repositories
Aug 19, 2019 2:08:13 PM org.opengrok.indexer.history.HistoryGuru createCache
INFO: Creating historycache for /grok/source/pilot-grok (RepoRepository) with renamed file handling
Aug 19, 2019 2:08:13 PM org.opengrok.indexer.history.Repository createCache
INFO: Skipping creation of history cache for /grok/source/pilot-grok, since retrieval of history for directories is not implemented for this repository type.
Aug 19, 2019 2:08:13 PM org.opengrok.indexer.util.Statistics report
INFO: Done historycache for /grok/source/pilot-grok (took 1 ms)
```
The workaround "creating an empty .git directory" by @jwehler is working, thank you!
