### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by chucksmash** [oracle/opengrok#2907]
On the older version of OpenGrok I have installed right now, TypeScript files are not analyzed. This prevents searching for definitions, linkification, and proper syntax highlighting. According to a conversation I've just had with @vladak and @tarzanek on the OpenGrok Slack channel, TypeScript is perhaps better supported by the JavaScript analyzer in later versions, but still not fully supported.

Adding full support for TypeScript source files would be an improvement for the people using it. I believe TypeScript has enough community adoption now to justify the enhancement effort. Based on the Slack conversation referenced earlier, it sounds like there is at least preliminary support for this from project maintainers as well.

My main reservation is that since I'm on a quite old release of OpenGrok, I've not had a chance to see what gaps still exist in JavaScript analyzer support for TypeScript. If more recent versions solve 90% of the issues I'm seeing now, it may not be worth the time and complexity of implementing the last 10%.

**Comment by tarzanek** [comment]
@chucksmash could you please install latest version and check how good is the support?
I'd like to see better typescript support, after all angular and ionic are nice things, so we should support them better
