### ISSUE TITLE
--symlink /path/to/symlink doesn't work for dir

### ISSUE THREAD

**Issue by skypx** [oracle/opengrok#2913]
**Describe the bug**
I want to use the opengrok deploy the Android Source code.
As you know. the source code has many symlink, for example

Android.bp -> build/soong/root.bp
bootstrap.bash -> build/soong/bootstrap.bash*

1. now the socus code already deploy success, And I can't check it for my opengrok. But I check the file  **Android.bp**. get the msg as below
Failed to get xref file

2. then I add the **--symlink ../../Android.bp** in the opengrok.sh. It works fine. And I can check
the file content. no error msg.

3.But I have some dir. And it is a symlink. for example
tools -> make/tools/
target -> make/target/

I add the **--symlink ../../tools** in my opengrok.sh. And I found it doesn't work.
tools(dir)
 ------test.mk       (Failed to get xref file)
 ------test1.mk     (Failed to get xref file)

Would you help check why it(symlink) doesn't work for the dir?
And maybe i lost some step?

My config as below.
![Screenshot from 2019-08-31 19-49-05](https://user-images.githubusercontent.com/5851854/64063625-35cf1500-cc29-11e9-8071-5285f5897faf.png)

**Comment by idodeclare** [comment]
@skypx, please would you try that directory —symlink without a trailing slash `/`

**Comment by idodeclare** [comment]
I can reproduce directory symlink issues when I chain allowed-symlinks. I’ll debug to see how that’s failing.

**Comment by skypx** [comment]
> @skypx, please would you try that directory —symlink without a trailing slash `/`

Hi @idodeclare Thanks for your support. This issue still reproduced even if without a trailing slash `/`
