### ISSUE TITLE
Cannot get the specified version of a file from SVN server

### ISSUE THREAD

**Issue by wjgong** [oracle/opengrok#2921]
I want to browser a specified version of file.
I clicked a Revision ID in History page. But the specified version was not opened successfully, the page shown error message "Error reading file".
I checked the logs of tomcat:
> 06-Sep-2019 17:33:18.178 WARNING [http-nio-8080-exec-6] org.opengrok.indexer.util.Executor.exec Non-zero exit status 1 from command [svn, cat, --non-interactive, -r, 10125, path_to_my_appr/user_gui.c@] in directory /home/xxx/opengrok/src/00_SW_DEV: svn: E170013: Unable to connect to a repository at URL 'https://svn-server.com/svn/XXX_SW/trunk/00_SW/00_SW_DEV/path_to_my_app/user_gui.c'
svn: E215004: No more credentials or we tried too many times.

OPENGROK_SUBVERSION_USERNAME and OPENGROK_SUBVERSION_PASSWORD are set.

OpenGrok Version: 1.3.1
I executed version.sh of tomcat, and got the information as below:
> Using CATALINA_BASE:   /opt/tomcat/latest
Using CATALINA_HOME:   /opt/tomcat/latest
Using CATALINA_TMPDIR: /opt/tomcat/latest/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/tomcat/latest/bin/bootstrap.jar:/opt/tomcat/latest/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Server version: Apache Tomcat/8.5.45
Server built:   Aug 14 2019 22:21:25 UTC
Server number:  8.5.45.0
OS Name:        Linux
OS Version:     4.15.0-60-generic
Architecture:   amd64
JVM Version:    11.0.4+11-post-Ubuntu-1ubuntu218.04.3
JVM Vendor:     Ubuntu

I have no idea how to investigate the issue further.
Thanks for your help!

**Comment by vladak** [comment]
The `svn log` command is missing the `--username` and `--password` options therefore somehow the environment variables did not get through.

**Comment by wjgong** [comment]
> The `svn log` command is missing the `--username` and `--password` options therefore somehow the environment variables did not get through.

Yes, opengrok didn't get username and password from the environment variables. I didn't find the rootcause. I made a workaround that uses a default username/password if not get them.

**Comment by vladak** [comment]
How do you set the env vars exactly ?

Dne po 9. 9. 2019 4:42 uživatel Wenjie Gong <notifications@github.com>
napsal:

**Comment by vladak** [comment]
Also, there is an enhancement somewhere to replace the env vars with per
project properties (although they have their own problems).

Dne po 9. 9. 2019 4:42 uživatel Wenjie Gong <notifications@github.com>
napsal:

**Comment by vladak** [comment]
The #1946 covers the per-project properties.

Also, the trouble is that user/pass are visible in process listing: #1561

**Comment by vladak** [comment]
Setting the environment variables in Tomcat via `setenv.sh` works for me. It is necessary to `export` the environment variables. Then they are present in the environment (verified by looking into `/proc/<TOMCAT_PID>/environ` on Linux or by running `pargs -e <TOMCAT_PID>` on Solaris).
