### ISSUE TITLE
opengrok-indexer no longer echoes Indexer output to the console after 1.3.2

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#2935]
**Describe the bug**
opengrok-indexer returns 1 on release 1.3.2 even finises successfully.
So, the opengrok-deploy works successfully after that and indexed data work.
This issue occurs on 1.3.2 only.

JDK: 11.0.2
Tomcat: 9.0.13
RHEL 7

**To Reproduce**
Just runs normally.

**Expected behavior**
Should be 0

**Comment by vladak** [comment]
How exactly do you run the indexer ? Are there any warnings in the log ?

**Comment by vladak** [comment]
Also, run the script with `-l DEBUG`, it will print the exit code of the Java command.

**Comment by shyoshiz** [comment]
Thank you for your response.

I usually suppress "clojure/rust/pascal/lambda" messages.
I tried with "-l DEBUG".  If I add this parameter, return code is 0 but if I don't use, return code is 1.
Please see attached output and sample script.

[output.txt](https://github.com/oracle/opengrok/files/3649476/output.txt)
[test.sh.txt](https://github.com/oracle/opengrok/files/3649485/test.sh.txt)

**Comment by vladak** [comment]
I don't see any problem in the debug output or the script. What happens if you replace `opengrok-indexer` with `java` ?

**Comment by shyoshiz** [comment]
If I run with java directly, I don't get the return code 1.  (I learned grep does not work for java.exe output.)  Please see the attached.

[output2.txt](https://github.com/oracle/opengrok/files/3652825/output2.txt)
[test2.sh.txt](https://github.com/oracle/opengrok/files/3652826/test2.sh.txt)

**Comment by vladak** [comment]
How does the original (failing) output look like ? The indexer should print out this error:
https://github.com/oracle/opengrok/blob/1cbb059775f0228e5c3bfdbf3d9a4fede0673642/opengrok-tools/src/main/python/opengrok_tools/indexer.py#L68-L72

**Comment by vladak** [comment]
Also, try to run `opengrok-indexer` with `--doprint` and post the output.

**Comment by shyoshiz** [comment]
HI Vladimir,

I found that this is my fault.  I realized that 1.3.2 actually does not output warning messages.
I was using several "grep -v "xxxx" at the last of opengrok-indexer to suppress these warning messages but these grep statements now generate return code "1" because of no output from opengrok-indexer.  Thank you very much for your help and sorry to bother you.

I just want to confirm that 1.3.2 changed not to issue these warning messages, correct?

**Comment by shyoshiz** [comment]
Just addition.  Very strange that if I add --doprint, it gets 1 like this.
But, I don't treat this as an issue because I don't use this parameter. ;-)

pisces@sjc-opengrok-11>./test3.sh
Indexer command failed (return code 1)
1

**Comment by vladak** [comment]
> I just want to confirm that 1.3.2 changed not to issue these warning messages, correct?

Well, yes. c9dff538 effectively disabled logging to the console from `opengrok-indexer`. Maybe this was not such a bright idea - cannot assume that the Indexer was run with logging configuration. Also, the option should allow toggling.
