### ISSUE TITLE
buildTagEntry() needs to disambiguate between tag and subdir with same name

### ISSUE THREAD

**Issue by louie0817** [oracle/opengrok#2936]
**Describe the bug**
during historycache when starting tomcat, if a github repo has a tag and subdir with same name, the "git log" command used in buildTagEntry() fails with:

fatal: ambiguous argument 'mytag': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

opengrok : 1.2.25
tomcat: 9.0.22
linux: redhat 6.8

**To Reproduce**
any github repo with tag and top-level subdir with same name.

**Expected behavior**
git log should generator data for tag, not the subdir

**Screenshots**

**Additional context**
fix is to change:
/opt/bb/bin/git log --format="commit:%H%nDate:%at" -n1 myTag

to

/opt/bb/bin/git log --format="commit:%H%nDate:%at" -n1 myTag --

**Comment by louie0817** [comment]
suggested fix:
change
    private TagEntry buildTagEntry(File directory, String tag, boolean interactive) {
        ArrayList<String> argv = new ArrayList<>();
        ensureCommand(CMD_PROPERTY_KEY, CMD_FALLBACK);
        argv.add(RepoCommand);
        argv.add("log");
        argv.add("--format=commit:%H%nDate:%at");
        argv.add("-n");
        argv.add("1");
        argv.add(tag);

to

    private TagEntry buildTagEntry(File directory, String tag, boolean interactive) {
        ArrayList<String> argv = new ArrayList<>();
        ensureCommand(CMD_PROPERTY_KEY, CMD_FALLBACK);
        argv.add(RepoCommand);
        argv.add("log");
        argv.add("--format=commit:%H%nDate:%at");
        argv.add("-n");
        argv.add("1");
        argv.add(tag);
        argv.add("--");

**Comment by vladak** [comment]
Feel free to submit a pull request.

**Comment by louie0817** [comment]
I am planning on it, but I am waiting on company approval to do so.

**Comment by louie0817** [comment]
submitted PR https://github.com/oracle/opengrok/pull/2941
