### ISSUE TITLE
ctags don't like space in kind name

### ISSUE THREAD

**Issue by dynofu** [oracle/opengrok#2942]
17:56:34 WARNING: File '/spark/sql/hive/src/test/resources/golden/timestamp_udf-13-51959036fd4ac4f1e24f4e06eb9b0b6' interrupted--tagLine == null
17:56:34 WARNING: Error from ctags: ctags: Non-alphanumeric char is used in kind name: 'case classes' in "--regex-scala" option
17:56:34 WARNING: ctags: Unexpected end of file!
17:56:34 WARNING: ctags exited with code: 1

and ctags think opengrok should not pass empty space.
https://github.com/universal-ctags/ctags/issues/2207

**Comment by dynofu** [comment]
probably here https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java#L357

**Comment by idodeclare** [comment]
Hi, @dynofu . Please see release 1.3.2 where this got fixed.

**Comment by tarzanek** [comment]
possible dup of https://github.com/oracle/opengrok/issues/2930 ?
@dynofu if it works for you with latest release, please close this ticket, tia. L

**Comment by dynofu** [comment]
confirmed 1.3.2 fixed the issue.
