### ISSUE TITLE
Desktop Chrome: Click local symbol doesn't scroll to its definition but top of the file

### ISSUE THREAD

**Issue by haiyanghaiyang** [oracle/opengrok#2943]
**Describe the bug**
When clicking a local symbol, it scrolls to top of the file instead of its definition position. It happens for desktop Chrome (Ubuntu and Windows7), but none of Microsoft IE, FireFox, Safari, iOS Chrome has such problem with the same server. I'm not sure whether there's some compatiblity issue with latest desktop Chrome.

OS: Ubuntu 18.04
OpenGrok: 1.3.1
JDK: 1.8.0_222
Webapp server: Tomcat8
Desktop Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**To Reproduce**
1. Index with this command:
sudo opengrok-indexer -J=-Djava.util.logging.config.file=/var/opengrok/logging.properties -a lib/opengrok.jar -- -c /usr/local/bin/ctags -s /sourcecode -d /var/opengrok/data -H -P -S -G  -W /var/opengrok/etc/configuration.xml -U http://localhost:8080/source
2. Restart tomcat
3. Browser code in desktop Chrome and click local symbol to scroll

**Expected behavior**
When clicking symbol, if it is defined in the same file, it should scroll to its definition.

**Screenshots**
N/A

**Additional context**
I also tried previous non-python version (1.1-rc34) and got the same issue. I do not remember there was such issue before, since I'm keeping using OpenGrok for years.

**Comment by tony-zhao** [comment]
This change will fix the issue:
diff --git a/opengrok-web/src/main/webapp/js/utils-0.0.32.js b/opengrok-web/src/main/webapp/js/utils-0.0.32.js
index eb6a615..8b0f475 100644
--- a/opengrok-web/src/main/webapp/js/utils-0.0.32.js
+++ b/opengrok-web/src/main/webapp/js/utils-0.0.32.js
@@ -212,7 +212,7 @@
             }
 
             if (match) {
-                anchorOffset = $(match).offset().top - this.getFixedOffset();
+                anchorOffset = $(match.nextElementSibling).offset().top - this.getFixedOffset();
                 $('html, body').animate({scrollTop: anchorOffset});
 
                 location.hash = href;

**Comment by vladak** [comment]
Cool, care to submit a PR ?

**Comment by tony-zhao** [comment]
Sorry, I'm unable to contribute to an Open Source project.

**Comment by vladak** [comment]
All right, someone from the regular contributors will check that change in.

**Comment by artbycrunk** [comment]
A simpler fix to this would be via css, 
```
a.xmb {
    color: #090;
    font-weight: bold;
    display: inline-block;
}
```
adding the display: inline-block, will correctly position the element.
Tested and working in Chrome and Firefox!

**Comment by vladak** [comment]
Cool, will you submit a PR ?
