### ISSUE TITLE
opengrok  jumps to the top of the page as opposed to going to that function in the file.

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#2944]
opengrok  jumps to the top of the page as opposed to going to that function in the file.

got an EXample  from online :
https://opengrok.libreoffice.org/xref/core/pyuno/source/module/unohelper.py?r=ca3ddcf2#createSingleServiceFactory

Function 'createSingleServiceFactory' defined at line 123

and the same function called at line 150 and if you click at line 150 of function call and it is going to starting of the page instead of pointing to the definition at line 123.

opengrok version:opengrok-1.1-rc27
java :1.8
 tomcat-8.5
Universal ctags

**Comment by sreehari83** [comment]
is this kown issue in opengrok

**Comment by vladak** [comment]
Does this happen with all different kinds/versions of browsers ? If yes, this is possibly a dup of #2943

**Comment by vladak** [comment]
Also, 1.1 is pretty old version. Could you try with the latest OpenGrok ?

**Comment by sreehari83** [comment]
Yes, this issue with only chrome browser

**Comment by vladak** [comment]
closing as a dup then.
