### ISSUE TITLE
Need help on using Project groups

### ISSUE THREAD

**Issue by piladon** [oracle/opengrok#2948]
Hi ,

I want to implement project groups for the first time. I have below queries hopefully someone can help me. 
I went through below link and some doubts
https://github.com/oracle/opengrok/wiki/Project-groups

1: For the first time do I need to edit the configuration.xml manually or can be done using some command line?
2: Can I use groups for some of the projects only and rest can still be in list mode?
3: Is it necessary to use python wrapper?
4: readonly_configuration.xml will it be an extra configuration file along with configuration.xml.

Please help me clearing my doubts so that I can implement it.

**Comment by vladak** [comment]
1. `configuration.xml` (that is produced by the indexer when using the -w option) is never to be edited by hand because the changes will be lost on next reindex.
2. Projects that are not part of any group will be listed under 'Other' on the index page.
3. No
4. Yes, see https://github.com/oracle/opengrok/wiki/Read-only-configuration

**Comment by vladak** [comment]
Any other questions ?

**Comment by piladon** [comment]
Hey @vladak 

Thanks for your quick and guidance. Please close this ticket.

Just one small doubt so the group by configuration will be there in readonly_configuration.xml right?

and please close this request i will raise a new one when needed

**Comment by vladak** [comment]
The group config is to be added to read-only config and passed to Indexer via -R option always (assuming you are not running in basic mode, i.e. not indexing individual projects in parallel). The Indexer will then merge this configuration with whatever it discovers and stores the result into the file pointed to by the -W option. This location is then used by the web app. This way when web application is restarted the configuration is not lost. This is general principle of using read-only configuration.
