### ISSUE TITLE
how to integrate ldap authentication with opengrok?

### ISSUE THREAD

**Issue by piladon** [oracle/opengrok#2959]
how to integrate ldap authentication with opengrok?

can you please guide or are there any documents

**Comment by vladak** [comment]
Not sure what you mean specifically but see the wiki: https://github.com/oracle/opengrok/wiki/Authorization-based-on-HTTP-Basic-Authentication

There should not be much difference setting up Tomcat to perform LDAP auth instead of Basic HTTP auth.

Fingers crossed.

**Comment by vladak** [comment]
Also see https://ldapwiki.com/wiki/Tomcat%20And%20LDAP

It might be as simple as following the above mentioned OpenGrok wiki and setting up a Realm using LDAP in Tomcat (https://tomcat.apache.org/tomcat-8.0-doc/realm-howto.html) - assuming this is what you are using.

**Comment by Nurm78** [comment]
If you are running the Opengrok in an Windows environment, then you can use the IIS with Windows Authentication as an reverse proxy.

**Comment by piladon** [comment]
I am using unix. However, now I have created the authentication to use LDAP successfully. Thanks for all your help

**Comment by NicholasRiggs** [comment]
Hey @vladak!

I have gone through all these steps and I still am not able to get ldap to work with opengrok correctly. Do you have an email where we can get in touch and I can explain what I am doing and maybe you could help me?

All I literally want is for someone upon visiting localhost:8080/source to be prompted to authenticate with active directory to use opengrok, and decide which users can use it and which users cannot. Don't need anything fancy for just a form or anything like that, just to authenticate upon visiting the page and using the opengrok service.

Thanks!
