### ISSUE TITLE
bunch of results in given file is not shown when more hits than can be displayed are generated

### ISSUE THREAD

**Issue by kkarczew** [oracle/opengrok#2980]
**Describe the bug**
When the searched item is found too many times in given file and all results are not displayed the first matched line is removed. It seems the 'All' link causes it to be 'pushed off' the displayed list.

**To Reproduce**
Search for a term that will be found more times than the display can show.

**Expected behavior**
If it's necessary to drop one of the lines, then it should be the last one found.

**Comment by vladak** [comment]
I replicated the behavior on 1.3.3. If I index current Git repository of OpenGrok and search for `String` as full text, the first entry in my case looks like this:
![string-search](https://user-images.githubusercontent.com/2934284/69066802-4b7efa00-0a22-11ea-91f2-02d887d31028.png)
while the expanded results look like this:
![search-expanded](https://user-images.githubusercontent.com/2934284/69066884-7406f400-0a22-11ea-9ed1-6a7f7db3a9c0.png)

**Comment by idodeclare** [comment]
This is Lucene-driven. Unified Highlighter uses BM25 to score excerpts, and OpenGrok show the top N. For the “All” link, OpenGrok presents all excerpts in source-code order.

I liked this sampling when integrating uhighlight because it showed more widely across a file.

**Comment by vladak** [comment]
Hm, I never thought it works this way. Shall we call it a feature then ? :-)

**Comment by idodeclare** [comment]
> Hm, I never thought it works this way. Shall we call it a feature then ? :-)

Sounds good to me
