### ISSUE TITLE
pom.xml's checkstyle sourceDirectories syntax is not backwards-compatible with Maven 3.0.5

### ISSUE THREAD

**Issue by unhipzippo** [oracle/opengrok#2996]
When attempting build of 1.3.5 on Oracle Linux 7.7 (with OL7's default Maven 3.0.5 and AdoptOpenJDK 11). build fails with error:

```
Unable to parse configuration of mojo org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check for parameter sourceDirectories: Cannot assign configuration entry 'sourceDirectories' with value 'foo' of type java.lang.String to property of type java.util.List
```

I believe the issue is config parameter syntax in pom.xml that isn't backwards-compatible with Maven 3.0.x.

i.e. At https://github.com/oracle/opengrok/blob/master/pom.xml#L312 is:

```
                                <sourceDirectories>${project.build.sourceDirectory}</sourceDirectories>
```

I can't find a canonical source (e.g. Maven release notes), but I see mentions online that support for this (comma-separated) syntax may only have been added in recent versions of Maven (3.3.9 was mentioned, but it may have been earlier), and that in the older Maven 3.0, each source directory needs to be enclosed in its own **sourceDirectory** tag:

```
                                <sourceDirectories>
                                    <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
                                </sourceDirectories>
```

When I locally modify pom.xml as per the above, build works fine with both the OS Maven 3.0.5 as well as a separate Maven 3.6.2 install I have access to.

Although I can use 3.6.2 to get it to work without source modifications, it may be better to tweak the sources to be backwards-compatible with 3.0.5, given that enterprise/LTS releases may still default to the older Maven for a bit longer.

**To Reproduce**
* Install OL 7.7
* Install OS-default Maven via "yum install maven") (3.0.5 in my case)
* Build OpenGrok as normal (e.g. **mvn package**)

**Comment by vladak** [comment]
I wonder if the `sourceDirectory` is the only problem. If such cases are limited it might be worth changing this. Feel free to submit a PR.

**Comment by ahornace** [comment]
Why can't you use `mvnw`? It is provided exactly for cases like these.

**Comment by ahornace** [comment]
Maven 3.0.5 was released in 2013. Please use provided `mvnw` to build the project.
