### ISSUE TITLE
Encountered `Cannot call sendRedirect() after the response has been committed` when navigate search result

### ISSUE THREAD

**Issue by sammyhk** [oracle/opengrok#2997]
****
Encountered `Cannot call sendRedirect() after the response has been committed` when navigate to the search result after perform a search. check the list.jsp, seems it is performing a `response.sendRedirect()` but the JSP generated content before that statement is exceeded 8kb default JSP buffer size and got flushed to the client, so cannot perform `response.sendRedirect()` call.

**To Reproduce**
Setup brand new OpenGrok, index some source, perform a search, navigate into the search result.
Encountered this error.

**Expected behavior**
Can access the search result

**Screenshots**
![opengrok-1 3 5](https://user-images.githubusercontent.com/1185214/70110166-106b0080-1689-11ea-9f9d-a16cea6575c7.png)

**Environment**
- Ubuntu 18.04.3 LTS
- opengrok-1.3.5
- apache-tomcat-9.0.29 & apache-tomcat-8.5.49 (tested in those application servers, got same result)
- project source code using SVN (1.9.7)

**Comment by sammyhk** [comment]
Oh, I think I found the root cause, when added `header_include` with inline image (e.g. OpenGrok logo), it will have a very high chance to exceeded 8kb default JSP buffer size and the response got flushed automatically, so causing this issue.

Now my workaround is modify list.jsp, set `buffer="1024kb" autoFlush="false"` to workaround this issue, seek your help to do the permanent fix.

**Comment by idodeclare** [comment]
Yes those conditionals for redirect should be able to relocate much earlier in list.jsp, well before any response has been partially constructed and possibly sent. Let me try ....
