### ISSUE TITLE
PSA: Chrome bug with large files on OpenGrok caused by LayoutNG

### ISSUE THREAD

**Issue by louie0817** [oracle/opengrok#3003]
If you use the latest version of Chrome, Version 79.0.3945.79 (Official Build) (64-bit), which was released last week (around 12/12/19) and you notice issues with loading large files in opengrok gui, here is a workaround until addressed in Chrome, which was found by a coworker when we starting experiencing this problem last week:

"This performance regression seems to be caused by LayoutNG. You can disable this by visiting the url chrome://flags, searching for 'Enable LayoutNG' and then marking it 'Disabled'. This will restart Chrome with the feature disabled. (i.e, hit Relaunch button at the bottom)

**Comment by louie0817** [comment]
fyi, see https://developers.google.com/web/updates/2019/06/layoutNG about this Chrome feature. I guess it is possible that down the road, a change may be needed in opengrok.

**Comment by vladak** [comment]
The claim is that rendering should be faster, not slower :-) I wonder what elements make the pages slow then.

**Comment by ymn1k** [comment]
If anyone has an OpenGrok instance with some open-source code, you can file a bug report for LayoutNG at https://bugs.chromium.org/p/chromium/issues/entry?summary=%5BLayoutNG%5D+Enter+one-line+summary&labels=LayoutNG&components=Blink%3ELayout

**Comment by deeparora29** [comment]
I am also facing the same issue with version 0.9 , although I cannot share my instance/snapshots as it does not contain any open source code.  Do the authors/developers plan to follow this up extensively with chromium.

**Comment by mmmarq** [comment]
There is a public link to reproduce the issue:
http://androidxref.com/9.0.0_r3/xref/frameworks/opt/telephony/src/java/com/android/internal/telephony/Phone.java

**Comment by deeparora29** [comment]
I am not observing this behavior in Chrome version (80.0.3987.16). Seems like they have changed something recently

**Comment by unhipzippo** [comment]
They also appear to have fixed it in the recently-released Chrome 79.0.3945.130.

**Comment by vladak** [comment]
Cool, closing then. (not that large files are not a problem)
