### ISSUE TITLE
History content of subdirectories (git repos) of a repoRepo Project is empty

### ISSUE THREAD

**Issue by sirisan** [oracle/opengrok#3010]
History content of subdirectories (git repos) of a repoRepo Project is empty

Tested with both opengrok 1.3.3 and 1.3.6
OS: Ubuntu 16
tomcat 8.0.32
java-1.8.0-openjdk-amd64
git version 2.7.4

Reference: fix for bug https://github.com/oracle/opengrok/issues/2937 in 1.3.3. 
Though the history cache is now getting created for the repoRepository, the sub directories which are git repositories are getting empty History content.

I have a repoRepository project with below directory structure:
```
<SRC_ROOT>/project/
<SRC_ROOT>/project/folder1
<SRC_ROOT>/project/folder1/.git
<SRC_ROOT>/project/folder1/folder2/folder3/.git
<SRC_ROOT>/project/folder1/folder2/folder4/.git
<SRC_ROOT>/project/folder1/folder5/folder6/.git
<SRC_ROOT>/project/.repo
```
When I browse to folder1, I see History content correctly but when i click on History link on folder3, folder4, folder 6, it shows empty tables.
Added the option `--depth 6` as well but no luck.

Kindly suggest if there are additional options for nested repositories.
Indexer command used: 
```
opengrok-indexer \
    -J=-Djava.util.logging.config.file=/opengrok_1.3.6/etc/logging.properties \
    -a /opengrok_1.3.6/dist/lib/opengrok.jar -- \
    -c /usr/local/bin/ctags \
    -s /opengrok_1.3.6/src -d /opengrok_1.3.6/data -H -P -S -G \
    -W /opengrok_1.3.6/etc/configuration.xml -U http://localhost:8080/source_1.3.6 \
	--depth 6
```
![image](https://user-images.githubusercontent.com/55794016/71616254-45f90000-2bdb-11ea-9327-8fb057abb891.png)

**Comment by sirisan** [comment]
Hi there, any suggestions on how to get around this?

**Comment by idodeclare** [comment]
I created the sample structure and had no problem.

Does your log show anything remarkable for `HistoryGuru` activity?

**Comment by sirisan** [comment]
In the log, I find the below activities logged by HistoryGuru,
1. basically adds repositories for the projects which come under the folder1 category (as in git repositories inside a RepoRepository folder )
 2020-03-19 01:01:59.270+0530 CONFIG t1 HistoryGuru.addRepositories: Adding <org.opengrok.indexer.history.GitRepository> repository: <SRC_ROOT>/project/folder1
2. creates the History cache for all the identified Repositories ( all immediate git repos similar to folder1 above are identified correctly). But the ones that fall under folder3, folder4 or folder6 category do not get identified.
2020-03-19 01:01:59.318+0530 INFO t126 HistoryGuru.createCache: Creating historycache for <SRC_ROOT>/project/folder1 (GitRepository) without renamed file handling


Hope this helps. Kindly let me know if any further information is required.

**Comment by sirisan** [comment]
Also, thanks for looking into this issue.

**Comment by idodeclare** [comment]
After fixing my mistake in following your example, I reproduced the behavior you're seeing.

It's deliberate by way of f355b12765bfb139082f88a0fce2a9455119c4a1 as a performance optimization to prevent searching through full `--depth` below a nested repo. For your example, OpenGrok does not search below folder1, which is a nested `GitRepository` in a `RepoRepository`.

A switch would have to be added to let the user choose to circumvent that performance optimization to search full `--depth`.

**Comment by sirisan** [comment]
Hi, is the switch added to enable user to search full depth?

**Comment by idodeclare** [comment]
I don't believe so. I'm taking a stab at it.

**Comment by sirisan** [comment]
thanks

**Comment by sirisan** [comment]
Is this a part of 1.3.16 release?

**Comment by vladak** [comment]
Will be part of 1.4.1.
