### ISSUE TITLE
Be able to check the OpenGrok release version

### ISSUE THREAD

**Issue by jbaek7023** [oracle/opengrok#3023]
**Is your feature request related to a problem? Please describe.**
We can't find out the OpenGrok version from the command line or the source.

**Describe the solution you'd like**
we can see it from the code level

**Describe alternatives you've considered**
Run `opengrok --version`command

THANKS

**Comment by vladak** [comment]
There are multiple possibilities:
  - use the jar file directly: `java -jar -V`
  - use one of the Python tools, e.g.: `opengrok-indexer --version`

Also, the version is visible in indexer and web application logs.
