### ISSUE TITLE
Need to see indexer return code info

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#3024]
Hi,

This is simple question. I get "Indexer command failed" with return code 1 and/or -9.  Where (docs, source code, and/or web sites) can I see the return code information?

**Comment by vladak** [comment]
how do you run the indexer exactly ?

**Comment by shyoshiz** [comment]
I'm using the following parameters:

  ${opengrok_home}/${OPENGROK_BIN}/opengrok-indexer -C \
    -j ${OPENGROK_JAVA_HOME}/bin/java \
    -J=-Djava.util.logging.config.file=${logger_config_path} \
    -J=-Djava.io.tmpdir=/opt/pisces/tmp \
    -J=-Xmx40960m -J=-Xms20480m ${server_64_opt} \
    -a ${opengrok_home}/lib/opengrok.jar \
    -- \
    --verbose --depth 24 -r off -m 256 ${OPENGROK_SYMLINKS} \
    -H -S -G -U http://localhost:2424/${webname} \
    -c ${UNIVERSAL_CTAGS} \
    -s ${work_dir_src} \
    -d ${work_dir_data} \
    -R ${work_dir_etc}/${READONLY_XML}.${RO_CONF}.xml \
    -W ${work_dir_etc}/configuration.xml \
    | grep -v "clojure" \
    | grep -v "rust" \
    | grep -v "pascal" \
    | grep -v "WARNING:" \
    | grep -v "Warning:" \
    | grep -v "SEVERE:" \
    | grep -v "Exception:" \
    | grep -v "at java." \
    | grep -v "at org." \
    | grep -v "^$"

**Comment by vladak** [comment]
`-Djava.util.logging.config.file` points to file with logging configuration so that's one place to look at for paths to indexer logs.

**Comment by vladak** [comment]
In overall the exit code should be 0 or 1 - see `Indexer.java` code. I don't think the command can actually return negative return code.

**Comment by vladak** [comment]
Also, if you actually leave out the `grep` command you might see what is going on straight on the console.

**Comment by shyoshiz** [comment]
Thank you for the info! I'll look into these info and will come back if I have any updates.

**Comment by shyoshiz** [comment]
Thank you very much for your valuable advice.  I found that return code 1 was caused by blocked communication about -U.  I corrected it and the return code 1 was gone.  I don't know why I had return code -9 but that was also gone .  (It simply took time because of huge repository size.)
Thank you so much for your help and please close this issue.
