### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by ronsensei** [oracle/opengrok#3027]
We would like Kotlin files (with a 'kt' extension) added to the list of types to search from.

**Comment by tarzanek** [comment]
that should already be there, I think OpenGrok supports kotlin (in base form)

**Comment by ronsensei** [comment]
Thanks for replying, but in the Type dropdown I don't see Kotlin listed.  It goes from JavaScript to Lisp.

**Comment by tarzanek** [comment]
which version of OpenGrok do you have?
latest version definitely shows Kotlin in drop down

**Comment by vladak** [comment]
definitely see Kotlin in the list in 1.3.7 thus closing. If you need a specific Kotlin related feature feel free to reopen.
