### ISSUE TITLE
clear button does not clear file type field

### ISSUE THREAD

**Issue by seanclarkgithub** [oracle/opengrok#3028]
When clicking clear, all search fields are cleared but not the file type drop down.  Should clear not also reset that?

**Comment by tulinkry** [comment]
Definitely should. This should be a bug.

**Comment by tulinkry** [comment]
The code indicates there's been some effort

https://github.com/oracle/opengrok/blob/73a3b0f802a4baa7c19488351a497644d9b9842e/opengrok-web/src/main/webapp/js/utils-0.0.34.js#L2165-L2170

however it looks like it does not interact well with the type-picker.
