### ISSUE TITLE
web page rendering is slow on large files using Firefox

### ISSUE THREAD

**Issue by Z4rc** [oracle/opengrok#3030]
I am using the latest OpenGrok 1.3.7 release and I have a problem with large source files using Firefox.
The problem occurs when a large file (like 20.000 lines of code) is opened and I start scrolling. Then Firefox is hanging for 10-30 seconds before I can continue scrolling.
In the Firefox console log I see the following error message:
`Failed to download "/grok/js/jquery-ui-1.12.1-draggable.min.js" module (utils-0.0.34.min.js:1:5517)`
This message appears directly when the freeze is over. So it looks like the problem is at this point.
I am currently using Firefox 72.0.2 but I had the same problem with older Firefox releases. I reinstalled Firefox and deleted the cache, but that didn't help.
The problem does not appear with Google Chrome and the problem does not appear with Firefox + OpenGrok 1.0.

**Comment by vladak** [comment]
Is the `jquery-ui-1.12.1-draggable.min.js` accessible in your web app when you try to download it directly ? E.g. my web app is running on http://localhost:8080/source/ and I can `GET` http://localhost:8080/source/js/jquery-ui-1.12.1-draggable.min.js just fine.

**Comment by Z4rc** [comment]
Yes, it is accessible. Everything is working fine for smaller files or if I use Google Chrome.

**Comment by vladak** [comment]
okay. closing as dup of #3032.

It would help if you could provide the data requested therein.
