### ISSUE TITLE
Slow Loading of long file (>10000 Lines)

### ISSUE THREAD

**Issue by moshenis** [oracle/opengrok#3032]
**Describe the bug**

Slow load for files indexed with more than 10000 lines (FireFox or Chrome)

I am using the following tools:
1. opengrok-1.3.7
2. ctags-2019-12-17_e216bb44-x64 (From CoCo)
3. apache-tomcat-8.5.15-windows-x64
4. jre1.8.0_241 

Command line used for Indexing
java -jar C:\opengrok\opengrok-1.3.7\lib\opengrok.jar -R C:\opengrok\opengrok-1.3.7\WCD_readonly_configuration.xml -W C:\opengrok\opengrok-1.3.7\WCD_configuration.xml -c C:\opengrok\universal-ctags\tools\ctags.exe -P -S -v -s . -d C:\opengrok\opengrok-1.3.7\grokdata\WCD   -I *.py -I *.cs -I *.xml -I *.sln -I *.csproj -I *.c -I *.h -I *.cpp --progress

**To Reproduce**
Use files indexed with more than 10000 lines

**Expected behavior**
Expect page to be loaded less than 2Sec (10000 lines is loaded after 10sec)

**Screenshots**

**Additional context**

**Comment by idodeclare** [comment]
Example slow behavior with e.g. [Perl DBI.pm](https://metacpan.org/source/TIMB/DBI-1.643) which has >8500 lines

**Comment by vladak** [comment]
What are the load times you are seeing ? Could you attach a screenshot of Tools -> Web console -> Network pane capturing the page load ? (better to reload with Ctrl+Shift+R)

**Comment by vladak** [comment]
Also, it would be nice if you can supply the recording from the Tools -> Web console -> Performance pane (again the recording being done while the page is being loaded) and attach it to this issue.

**Comment by vladak** [comment]
For the record, I don't see this problem on FF 72.0.2 running on my laptop (Ubuntu, i7-8665U).

**Comment by Z4rc** [comment]
Since I have the same issue, I can also provide the data.
I am using Firefox 72.0.2 on my laptop (Win 10 Version 1809, i7-7600U).

Web console -> Network:
![image](https://user-images.githubusercontent.com/10116005/73735816-2146f980-4740-11ea-8961-2d46df3aee8c.png)

Web console -> Performance: [profile.zip](https://github.com/oracle/opengrok/files/4152661/profile.zip)
![image](https://user-images.githubusercontent.com/10116005/73735949-4dfb1100-4740-11ea-82ce-981d9f0418db.png)

**Comment by vladak** [comment]
On the metacpan.org site the slowdown is clearly caused by long executing JavaScript code, in particular their `findLines` function. How about providing the data from OpenGrok instance ?

**Comment by Z4rc** [comment]
Ok, here is the data I created for https://github.com/oracle/opengrok/issues/3030:

Web console -> Performance: [profile.zip](https://github.com/oracle/opengrok/files/4153372/profile.zip)

![image](https://user-images.githubusercontent.com/10116005/73746682-0b443380-4756-11ea-952f-6fdc4be02b3d.png)

**Comment by vladak** [comment]
Loading the profile into my browser, I can see most of time was spent in Layout/Gecko:

![grok-profile-FF-72 0 2](https://user-images.githubusercontent.com/2934284/73752312-03d65780-4761-11ea-80d2-3f0da4834458.png)

so it looks like this is not a JS problem.

It would be nice to isolate this to particular version of OpenGrok or browser - assuming this used to be faster.

**Comment by Z4rc** [comment]
This is the data for the same source file, using the same browser (Firefox 72.0.2), on the same machine, but with OpenGrok version 1.0:

Web console -> Performance: [profile.grok.1.0.json.zip](https://github.com/oracle/opengrok/files/4153992/profile.grok.1.0.json.zip)

![image](https://user-images.githubusercontent.com/10116005/73754056-0d14f380-4764-11ea-86ac-687b8c7e046d.png)

**Comment by tulinkry** [comment]
I strongly believe that this is cause by the javascript code which adds an artifitial "space" symbol at the beginning of each line in a file. Although it is originally optimised to do it for lines in the view only, it may misbehave.

**Comment by vladak** [comment]
> I strongly believe that this is cause by the javascript code which adds an artifitial "space" symbol at the beginning of each line in a file. Although it is originally optimised to do it for lines in the view only, it may misbehave. Just giving pointers for potential cause on our side.

I assume you mean the changes in #1020.

**Comment by moshenis** [comment]
See my profile


Regards,

   Moshe Nissim
   Mobile: +972542493492

**Comment by vladak** [comment]
> See my profile

which one ?

**Comment by vladak** [comment]
One idea: it might be worth comparing the page generated by 1.0 and 1.3.7 (for the same source file).

**Comment by moshenis** [comment]
[profile.zip](https://github.com/oracle/opengrok/files/4155826/profile.zip)
File added
This profile retrieved during loading of a file of 20000 lines

**Comment by vladak** [comment]
> [profile.zip](https://github.com/oracle/opengrok/files/4155826/profile.zip)
> File added
> This profile retrieved during loading of a file of 20000 lines

That is also interesting and actually points towards the `spaces` plugin mentioned by @tulinkry:

![moshenis-profile-call_tree](https://user-images.githubusercontent.com/2934284/73846483-e8cd1b80-4824-11ea-92de-df9b8de1725a.png)
![moshenis-profile-flame_graph](https://user-images.githubusercontent.com/2934284/73846486-e965b200-4824-11ea-8aa1-24fd543e2ebf.png)

This is because the `handleScrollEvent` is present only in this piece of JS code.

That said, the time spent with processing of the JS is only smaller part of the time spent in Layout - some 10 seconds out of 42 seconds if I am interpreting this correctly. The bulk of the time seems to be spent rendering the page.

**Comment by vladak** [comment]
Could someone try the [Firefox profiler plugin](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) ?

**Comment by vladak** [comment]
Another thing to try is to disable the `spaces` plugin as in https://github.com/oracle/opengrok/pull/1107/files (in the minified version just remove the call completely).

**Comment by moshenis** [comment]
[Firefox 2020-02-05 22.17 profile.json.gz](https://github.com/oracle/opengrok/files/4161896/Firefox.2020-02-05.22.17.profile.json.gz)
This is the with FireFox Profiler

**Comment by vladak** [comment]
Nice one. I am impressed by the FF Profiler.

![firefox-profiler-iil](https://user-images.githubusercontent.com/2934284/73922922-436c8300-48ca-11ea-8711-100921115280.png)

I think there is certainly some correlation between the `spaces` JS plugin and the rendering - the `handleScrollEvent` stack bubbles down to layout stack.

Could you try removing the `$.spaces.init()` call from `js/utils-0.0.34.min.js` (no need to redeploy I think) and shift-reloading the page while capturing the FF Profiler data ?

**Comment by vladak** [comment]
Also, could you guys try this on FF instance that does not have any plugins (besides the Profiler) installed ?

**Comment by vladak** [comment]
more on the most recent profiler data: the bulk of the time in the left most purple area (5 sec out of 10 secs) was spent in the JS `utils` stack that had a call to `CoalesceMutationEvents()` at the bottom. The name of the function would hint towards DOM being modified by the JS and then Gecko has to deal with that. The same is true for the right most purple area, again the call to `CoalesceMutationEvents()` takes 2 sec out of 4.3 secs, just that is no clear correlation to JS processing.

**Comment by vladak** [comment]
A bit more detail on how the code flow ends up in `CoalesceMutationEvents()`:
  - `handleScrollEvent()` in `spaces` plugin from `utils-0.0.34.js` calls the `callback`:
https://github.com/oracle/opengrok/blob/cf1700cdb9b464f38055f898107a40ed92ddc04a/opengrok-web/src/main/webapp/js/utils-0.0.34.js#L114-L117
    - that is defined in the beginning of the `spaces` plugin like so:
https://github.com/oracle/opengrok/blob/cf1700cdb9b464f38055f898107a40ed92ddc04a/opengrok-web/src/main/webapp/js/utils-0.0.34.js#L48-L53
  - the `callback` performs the jQuery [text](https://api.jquery.com/text/) call to add the space into the `"selected"` lines
  - this triggers the jQuery [empty](https://api.jquery.com/empty/) call for some reason
  - this triggers the [DOM mutation event](https://en.wikipedia.org/wiki/DOM_events) which jQuery subscribes to somehow (there is a banch of `addEventListener()` calls in jQuery, some with variable arguments but none that would contain the [mutation events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events))
  - `CoalesceMutationEvents()` does event manipulation and potentially reordering

It is worth noting that the values in the "Self" column (for the "bulk" stack) are mostly handful of milliseconds and the value of `CoalesceMutationEvents()` is in thousands. Even if there was thousands of events and the algorithm was exponential it should not take bunch of seconds. Smells like a Firefox bug to me. (not that the dealing with spaces could not be made better)

**Comment by vladak** [comment]
filed a bug against Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1613634

**Comment by vladak** [comment]
Here's another profile exhibiting the same problem (loading the `mac.c` code from Solaris code base, has some 11K LOC) from a colleague (Jon Anderson): 
![Screenshot from 2020-02-18 13-49-50](https://user-images.githubusercontent.com/2934284/74737716-b3c5bd80-5255-11ea-8ce2-f06d062107b3.png)

[Firefox 2020-02-18 11.48 profile.json.gz](https://github.com/oracle/opengrok/files/4219261/Firefox.2020-02-18.11.48.profile.json.gz)

**Comment by vladak** [comment]
The Firefox bug has been just fixed. Looks like this fix will be delivered in Firefox 97.
