### ISSUE TITLE
malformed URI sequence getting cookies

### ISSUE THREAD

**Issue by danielviorreta** [oracle/opengrok#3035]
Hello,

We have grok configured in a subdomain so it has access to rest of domain cookies.
We get this error when it tries to decode any cookie from the main domain:

```
jQuery.Deferred exception: URI malformed URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at getCookie (https://dviorreta.nw.dev.tripadvisor.com/js/utils-0.0.34.min.js:1:38643)
    at domReadyMenu (https://dviorreta.nw.dev.tripadvisor.com/js/utils-0.0.34.min.js:1:28080)
    at Array.<anonymous> (https://dviorreta.nw.dev.tripadvisor.com/:39:37)
    at HTMLDocument.<anonymous> (https://dviorreta.nw.dev.tripadvisor.com/js/utils-0.0.34.min.js:1:26130)
    at e (https://dviorreta.nw.dev.tripadvisor.com/js/jquery-3.4.1.min.js:2:29453)
    at t (https://dviorreta.nw.dev.tripadvisor.com/js/jquery-3.4.1.min.js:2:29755) undefined
k.Deferred.exceptionHook @ jquery-3.4.1.min.js:2
t @ jquery-3.4.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1.min.js:2
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
fire @ jquery-3.4.1.min.js:2
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
ready @ jquery-3.4.1.min.js:2
B @ jquery-3.4.1.min.js:2
jquery-3.4.1.min.js:2 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at getCookie (utils-0.0.34.min.js:1)
    at domReadyMenu (utils-0.0.34.min.js:1)
    at Array.<anonymous> ((index):39)
    at HTMLDocument.<anonymous> (utils-0.0.34.min.js:1)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
```

Any way to fix this? The problem was created in https://github.com/oracle/opengrok/pull/2237/
Thanks,
Daniel

**Comment by vladak** [comment]
So, what's the value of `document.cookie` in `getCookie()` ?

**Comment by danielviorreta** [comment]
I added this in the getCookie method:
`console.log(document.cookie);`

And it prints this in the console before failing:
`ServerPool=B; TATravelInfo=V2*A.2*MG.-1*HP.2*FL.3*RS.1; CM=%1%PremiumMobSess%2C%2C-1%7Ct4b-pc%2C%2C-1%7CRestAds%2FRPers%2C%2C-1%7CRCPers%2C%2C-1%7CWShadeSeen%2C%2C-1%7CTheForkMCCPers%2C%2C-1%7CHomeASess%2C1%2C-1%7CPremiumSURPers%2C%2C-1%7CPremiumMCSess%2C%2C-1%7CRestPremRSess%2C%2C-1%7CRepTarMCSess%2C%2C-1%7CCCSess%2C%2C-1%7CCYLSess%2C%2C-1%7CPremRetPers%2C%2C-1%7CViatorMCPers%2C%2C-1%7Csesssticker%2C%2C-1%7CPremiumORSess%2C%2C-1%7Ct4b-sc%2C%2C-1%7CRestAdsPers%2C%2C-1%7CMC_IB_UPSELL_IB_LOGOS2%2C%2C-1%7Cb2bmcpers%2C%2C-1%7CPremMCBtmSess%2C%2C-1%7CPremiumSURSess%2C%2C-1%7CMC_IB_UPSELL_IB_LOGOS%2C%2C-1%7CLaFourchette+Banners%2C%2C-1%7Csess_rev%2C%2C-1%7Csessamex%2C%2C-1%7CPremiumRRSess%2C%2C-1%7CTADORSess%2C%2C-1%7CAdsRetPers%2C%2C-1%7CTARSWBPers%2C%2C-1%7CSPMCSess%2C%2C-1%7CTheForkORSess%2C%2C-1%7CTheForkRRSess%2C%2C-1%7Cpers_rev%2C%2C-1%7CSPMCWBPers%2C%2C-1%7CRBAPers%2C%2C-1%7CRestAds%2FRSess%2C%2C-1%7CHomeAPers%2C%2C-1%7CPremiumMobPers%2C%2C-1%7CRCSess%2C%2C-1%7CLaFourchette+MC+Banners%2C%2C-1%7CRestAdsCCSess%2C%2C-1%7CRestPremRPers%2C%2C-1%7CRevHubRMPers%2C%2C-1%7Csh%2C%2C-1%7Cpssamex%2C%2C-1%7CTheForkMCCSess%2C%2C-1%7CCYLPers%2C%2C-1%7CCCPers%2C%2C-1%7CRepTarMCPers%2C%2C-1%7Cb2bmcsess%2C%2C-1%7CSPMCPers%2C%2C-1%7CRevHubRMSess%2C%2C-1%7CPremRetSess%2C%2C-1%7CViatorMCSess%2C%2C-1%7CPremiumMCPers%2C%2C-1%7CAdsRetSess%2C%2C-1%7CPremiumRRPers%2C%2C-1%7CRestAdsCCPers%2C%2C-1%7CTADORPers%2C%2C-1%7CTheForkORPers%2C%2C-1%7CPremMCBtmPers%2C%2C-1%7CTheForkRRPers%2C%2C-1%7CTARSWBSess%2C%2C-1%7CPremiumORPers%2C%2C-1%7CRestAdsSess%2C%2C-1%7CRBASess%2C%2C-1%7CSPORPers%2C%2C-1%7Cperssticker%2C%2C-1%7CSPMCWBSess%2C%2C-1%7C; TAUD=LA-1580981090234-1*RDD-1-2020_02_06*LG-3623-2.1.F.*LD-3624-.....; TAReturnTo=%1%%2F; roybatty=TNI1625!AMGxtFn%2BgfU6E1IMvkJXo6PyCqn%2FIZAtv8IYA90eb%2BadJgwdC0CLSe1hUebZf%2FxVYW7SNwjxm3Crl8HeBz2FEPCrF4j0I%2FKL0ywzIwrF8T4Fsj%2FQXVjouPaSFCN6mh5zUQqy84XywZ6EtdwH%2F0%2BVex0UiyTH0hNl865%2BwRof4rI2%2C1; mp_tripadvisor_mixpanel=%7B%22distinct_id%22%3A%20%2217019cd7ba5596-0bd966c8a558088-4b516d-1aeaa0-17019cd7ba64c0%22%2C%22bc_persist_updated%22%3A%201580981090219%7D`

If I remove the cookie I have a similar error for each cookie in the higher domain.

**Comment by vladak** [comment]
It does not seem this has to do with OpenGrok running in subdomain - there are no OpenGrok cookies in `document.cookie`. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI there is some encoding error in one of the cookies.

**Comment by vladak** [comment]
Calling `decodeURIComponent()` on the individual verbatim values of cookies, it turns out the cookies `CM` and `TAReturnTo` have invalid encoding. So, this is not a problem of cookies generated by OpenGrok. I'd say acting as RFC1122 would be wrong thing to do here.
