### ISSUE TITLE
Indexer Command Failed: Return code -9 from java.lang.IllegalStateException: TokenStream contract violation: close() call missing

### ISSUE THREAD

**Issue by Me4791** [oracle/opengrok#3036]
**Describe the bug**
Hello Contributors,
We have deployed the OpenGrok 1.3.3 in test environment and we are getting below error while indexing the source:
![image](https://user-images.githubusercontent.com/52797307/73994923-24e7a580-4925-11ea-87b6-fc897f128caf.png)

Environment:
Git - 2.17.1
OS -Ubuntu 18.04
Can you please help? Is this known issue? Is the indexing get failed in between or completed?
Is Analyzer part come in workflow after indexing?
Any help would be appreciated as we are close to production deployment date.

IS there any way I can skip this analyzer.
Thanks!

**Comment by idodeclare** [comment]
> IS there any way I can skip this analyzer.

For `JarAnalyzerFactory` which is enlisted either by file extension (.jar, .war, .ear) or by format magic string (`PK\{3}\{4}` with `0xCAFE` Extra Field ID), there are no switches to entirely disable `JarAnalyzer`.

You could ignore the file extensions though with the `-i, --ignore` switch:

`-i '*.jar' -i '*.war' -i '*.ear'`

(Ignored files may still show up in repo history though. See PR #1386.)

**Comment by tarzanek** [comment]
seems to be a dup of https://github.com/oracle/opengrok/issues/2030
