### ISSUE TITLE
Setting up OPENGROK_WEBAPP_CONTEXT doesn't change the root directory

### ISSUE THREAD

**Issue by jbaek7023** [oracle/opengrok#3054]
I made a change to the Dockerfile to server OpenGrok on `/source` instead of `/`. But it doesn't work.

```
# environment variables
ENV SRC_ROOT /opengrok/src
ENV DATA_ROOT /opengrok/data
ENV OPENGROK_WEBAPP_CONTEXT /source <<<<<<<<<<<<<<<<<<<<<<<<<My change here
ENV OPENGROK_TOMCAT_BASE /usr/local/tomcat
ENV CATALINA_HOME /usr/local/tomcat
ENV CATALINA_BASE /usr/local/tomcat
ENV CATALINA_TMPDIR /usr/local/tomcat/temp
ENV PATH $CATALINA_HOME/bin:$PATH
ENV JRE_HOME /usr
ENV CLASSPATH /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar

# custom deployment to / with redirect from /source
# RUN rm -rf /usr/local/tomcat/webapps/* && \
#    opengrok-deploy -c /opengrok/etc/configuration.xml \
#        /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war && \
#    mkdir "/usr/local/tomcat/webapps/source" && \
#    echo '<% response.sendRedirect("/"); %>' > "/usr/local/tomcat/webapps/source/index.jsp"
```

I changed `ENV OPENGROK_WEBAPP_CONTEXT /` to `ENV OPENGROK_WEBAPP_CONTEXT /source`. But it's still redirecting to `/` and the default URL is still `/`

I commented out the `RUN rm -rf ... opengrok-deploy` but it's now showing 404.

**Comment by jbaek7023** [comment]
Here is the change I made to the Dockerfile

```
# environment variables
ENV SRC_ROOT /opengrok/src
ENV DATA_ROOT /opengrok/data
ENV OPENGROK_WEBAPP_CONTEXT /source
ENV OPENGROK_TOMCAT_BASE /usr/local/tomcat
ENV CATALINA_HOME /usr/local/tomcat
ENV CATALINA_BASE /usr/local/tomcat
ENV CATALINA_TMPDIR /usr/local/tomcat/temp
ENV PATH $CATALINA_HOME/bin:$PATH
ENV JRE_HOME /usr
ENV CLASSPATH /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar

# custom deployment to / with redirect from /source
RUN rm -rf /usr/local/tomcat/webapps/* && \
    opengrok-deploy -c /opengrok/etc/configuration.xml \
        /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war && \
    mkdir "/usr/local/tomcat/webapps/source" && \
#    echo '<% response.sendRedirect("/"); %>' > "/usr/local/tomcat/webapps/source/index.jsp"
```

**Comment by jbaek7023** [comment]
@vladak Do you mind if you share some knowledge here..? Thank you so much

**Comment by jbaek7023** [comment]
I edited to:
`RUN opengrok-deploy -c /opengrok/etc/configuration.xml \
       /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war`

Now I'm getting this error:

> There was an error!
CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.
Unable to determine source root path. Missing configuration?
java.io.FileNotFoundException: Unable to determine source root path. Missing configuration?

**Comment by vladak** [comment]
The `OPENGROK_WEBAPP_CONTEXT` environment variable used to work with the `OpenGrok` shell script. With the conversion to Python based tools this environment variable is no longer used.

The webapp path is defined based on the name of the `war` file in the Tomcat webapps directory. If it is `ROOT.war` the webapp will be deployed to `/`. If t is `foo.war` the webapp will be deployed to `/foo`.

**Comment by vladak** [comment]
> I edited to:
> `RUN opengrok-deploy -c /opengrok/etc/configuration.xml \ /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war`
> 
> Now I'm getting this error:
> 
> > There was an error!
> > CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.
> > Unable to determine source root path. Missing configuration?
> > java.io.FileNotFoundException: Unable to determine source root path. Missing configuration?

Does the `/opengrok/etc/configuration.xml` file actually exist ? You need to run the indexer first (with `-W /opengrok/etc/configuration.xml`) so it can be created.

**Comment by vladak** [comment]
The `CONFIGURATION parameter has not been configured in web.xml` error message emitted from `error.jsp` is actually pretty misleading. It is printed when configuration object has merely no source root path, which could happen not necessarily only when the `CONFIGURATION` parameter is missing in `web.xml`.

**Comment by vladak** [comment]
`WebappListener#contextInitialized()` actually contains a check for the missing `CONFIGURATION` option in `web.xml`. It merely emits a log message in such case: https://github.com/oracle/opengrok/blob/d7648fcc198f443679eeca5076358753b7641a5a/opengrok-web/src/main/java/org/opengrok/web/WebappListener.java#L69-L71

I am not sure if it is worth the flexibility in continuing (as opposed to fail the deployment completely in such case), basically making it possible to upload the configuration later on.

**Comment by jbaek7023** [comment]
> > I edited to:
> > `RUN opengrok-deploy -c /opengrok/etc/configuration.xml \ /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war`
> > Now I'm getting this error:
> > > There was an error!
> > > CONFIGURATION parameter has not been configured in web.xml! Please configure your webapp.
> > > Unable to determine source root path. Missing configuration?
> > > java.io.FileNotFoundException: Unable to determine source root path. Missing configuration?
> 
> Does the `/opengrok/etc/configuration.xml` file actually exist ? You need to run the indexer first (with `-W /opengrok/etc/configuration.xml`) so it can be created.

You mean `opengrok-deploy -W /opengrok/etc/configuration.xml` before?
I'm using the exact same Dockerfile with yours and added a couple of new lines; But it's showing the Configuration error. Here is the code snippet: https://gist.github.com/jbaek7023/a050a659e1a856bb2824ab5883c14632

**Comment by jbaek7023** [comment]
I tried a couple of options and here are the errors:
(1) RUN opengrok-deploy -W /opengrok/etc/configuration.xml \
       /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war
```usage: opengrok-deploy [-h] [-l LOGLEVEL] [-v] [-c CONFIG] [-i INSERT]
                       source_war target_war
opengrok-deploy: error: unrecognized arguments: -W /usr/local/tomcat/webapps/source.war
ERROR: Service 'opengrok_docker' failed to build: The command '/bin/sh -c opengrok-deploy -W /opengrok/etc/configuration.xml        /opengrok/lib/source.war /usr/local/tomcat/webapps/source.war' returned a non-zero code: 2```

(2) opengrok-indexer: error: unrecognized arguments: -W /usr/local/tomcat/webapps/source.war

....
How do I push the configuration.xml file first..?

**Comment by jbaek7023** [comment]
@vladak Do you know how I can add CONFIGURATION section in web.xml? I don't see any example. :(

**Comment by jbaek7023** [comment]
@vladak Do you have any practice to change the root source path?
ex) from / to /source.

Do you have any branch for that..??

**Comment by jbaek7023** [comment]
This is my edited Dockerfile and it's still having web.xml error...

**Comment by vladak** [comment]
The -W is Indexer option, not deploy option.

**Comment by vladak** [comment]
It is there by default. See 
https://github.com/oracle/opengrok/blob/d7648fcc198f443679eeca5076358753b7641a5a/opengrok-web/src/main/webapp/WEB-INF/web.xml#L10-L14

The only thing that is required is that the path in CONFIGURATION needs 
to match the path used by the indexer (with -W). If the indexer does not 
use the default path (/var/opengrok/etc/configuration.xml) it is 
necessary to modify it (e.g. using the -c option of the opengrok-deploy 
script).

**Comment by vladak** [comment]
> @vladak Do you have any practice to change the root source path?
> ex) from / to /source.
> 
> Do you have any branch for that..??

In general this is easy - just copy the `source.war` file to the webapp directory of the application server.

I assume you mean how to change the default Dockerfile to achieve that. Should be easy as:
```diff
diff --git a/Dockerfile b/Dockerfile
index 59a0950746..cbc527a522 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -70,12 +70,9 @@ ENV PATH $CATALINA_HOME/bin:$PATH
 ENV JRE_HOME /usr
 ENV CLASSPATH /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
 
-# custom deployment to / with redirect from /source
 RUN rm -rf /usr/local/tomcat/webapps/* && \
     opengrok-deploy -c /opengrok/etc/configuration.xml \
-        /opengrok/lib/source.war /usr/local/tomcat/webapps/ROOT.war && \
-    mkdir "/usr/local/tomcat/webapps/source" && \
-    echo '<% response.sendRedirect("/"); %>' > "/usr/local/tomcat/webapps/source/index.jsp"
+        /opengrok/lib/source.war /usr/local/tomcat/webapps/
 
 # disable all file logging
 ADD docker/logging.properties /usr/local/tomcat/conf/logging.properties
diff --git a/docker/index.sh b/docker/index.sh
index efada94fdc..f11ece325d 100644
--- a/docker/index.sh
+++ b/docker/index.sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 LOCKFILE=/var/run/opengrok-indexer
-URI="http://localhost:8080"
+URI="http://localhost:8080/source"
 # $OPS can be overwritten by environment variable
 OPS=${INDEXER_FLAGS:='-H -P -S -G'}
 
```

**Comment by jbaek7023** [comment]
This worked!!! Thanks a lot @vladak

**Comment by vladak** [comment]
You're welcome.
