### ISSUE TITLE
Is there a CLI for search in the latest release?

### ISSUE THREAD

**Issue by AsCatgz** [oracle/opengrok#3062]
Hello 
In the previous release, I can use a CLI to search, which is very use full when I want to refilter the search result by grep or other tool.
But in the opengrok-1.3.8, I can't use the previous CLI, is there any way to do the search in CLI ?

The CLI in previous release, we search all "word_to_search" and exclude all .o and .ko file:
```
java -cp opengrok.jar org.opensolaris.opengrok.search.Search -R /myproject/etc/configuration.xml -f word_to_search | grep -vE "\.o|\.ko"
```

**Comment by AsCatgz** [comment]
I know the restful api, but  it's very hard to filter the search result.

**Comment by vladak** [comment]
Firstly, there is no plan to resurrect the CLI. Processing the results from the search RESTful API endpoint should be possible with programs like e.g. `jq`.

**Comment by AsCatgz** [comment]
ok Thanks.

**Comment by vladak** [comment]
Now, as for the path filtering using logical expressions within the webapp, this is not possible due to parameter escaping (`&` collides with request separator).

**Comment by vladak** [comment]
Here's basic example for simple path filtering:
```json
$ curl -s 'http://localhost:8080/source/api/v1/search?full=foobar' | jq '.results | to_entries | .[] | select(.key | contains(".so"))'
{
  "key": "/opengrok-1.0/testdata/sources/c/i386/libfoobar.so",
  "value": [
    {
      "line": ".so crti.s values-Xa.c ",
      "lineNumber": ""
    },
    {
      "line": "<b>foobar</b>",
      "lineNumber": ""
    },
    {
      "line": ".c crtn.s _PROCEDURE_LINKAGE_TABLE_ _fini _etext _init _end",
      "lineNumber": ""
    }
  ]
}
{
  "key": "/opengrok/testdata/sources/c/i386/libfoobar.so",
  "value": [
    {
      "line": ".so crti.s values-Xa.c ",
      "lineNumber": ""
    },
    {
      "line": "<b>foobar</b>",
      "lineNumber": ""
    },
    {
      "line": ".c crtn.s _PROCEDURE_LINKAGE_TABLE_ _fini _etext _init _end",
      "lineNumber": ""
    }
  ]
}
```

**Comment by idodeclare** [comment]
In the web app we would just enter a path expression to filter extensions: -py -ksh. Would the REST API accept `&path=-py%20-ksh`?

**Comment by AsCatgz** [comment]
> Here's basic example for simple path filtering using logical expressions:
> 
> ```json
> $ curl -s 'http://localhost:8080/source/api/v1/search?full=foobar&projects=opengrok' | jq '.results | to_entries | .[] | select(.key | contains(".so") or contains("Makefile"))'
> {
>   "key": "/opengrok/testdata/sources/c/i386/libfoobar.so",
>   "value": [
>     {
>       "line": ".so crti.s values-Xa.c ",
>       "lineNumber": ""
>     },
>     {
>       "line": "<b>foobar</b>",
>       "lineNumber": ""
>     },
>     {
>       "line": ".c crtn.s _PROCEDURE_LINKAGE_TABLE_ _fini _etext _init _end",
>       "lineNumber": ""
>     }
>   ]
> }
> {
>   "key": "/opengrok/testdata/sources/c/Makefile",
>   "value": [
>     {
>       "line": "$(DIR)/libfoobar.so: $(DIR)/<b>foobar</b>.o",
>       "lineNumber": "5"
>     },
>     {
>       "line": "\t$(LINK.c) -o $(DIR)/libfoobar.so -G $(DIR)/<b>foobar</b>.o",
>       "lineNumber": "6"
>     },
>     {
>       "line": "$(DIR)/<b>foobar</b>.o: $(DIR) <b>foobar</b>.c",
>       "lineNumber": "17"
>     },
>     {
>       "line": "\t$(COMPILE.c) -o $(DIR)/<b>foobar</b>.o -Kpic <b>foobar</b>.c",
>       "lineNumber": "18"
>     }
>   ]
> }
> ```

I get result which is similar as the result of CLI by: 
curl http://localhost:8080/source/api/v1/search?full=word_to_search 2>/dev/null | jq -r '.results|to_entries[]|(.key + " : " + (.value[]|(.lineNumber + .line)))'

Thanks.

**Comment by vladak** [comment]
You're welcome. Glad you found a way.

**Comment by vladak** [comment]
> In the web app we would just enter a path expression to filter extensions: -py -ksh. Would the REST API accept `&path=-py%20-ksh`?

The contents of the `path` arrive to the `SearchController` stripped of the `-` or `+` so it looks not.
