### ISSUE TITLE
OpenGrok Java Version and Framework

### ISSUE THREAD

**Issue by CodeCrimson00** [oracle/opengrok#3087]
We're trying to find out which version of Java OpenGrok is written for and if it's written with a specific framework.

I think I found out it's written in and for Java 8 based on the pom.xml file, but if that can be confirmed that'd be great. Thanks!

**Comment by vladak** [comment]
yep.

**Comment by CodeCrimson00** [comment]
Thanks. Is it written with a specific framework? Like Struts, Spring, etc...

**Comment by vladak** [comment]
Nope. Clear Java. We also try to avoid using stuff like Apache Commons, Guava, etc. as much as possible.

Now, some (@tarzanek) would like to use other high level language however that should remain constrained to plugins (depends on #2660).

**Comment by vladak** [comment]
why do you ask actually ?

**Comment by CodeCrimson00** [comment]
Oh we're just looking for an authentication method to work for the tool and was trying to figure out some options. Thanks.
