### ISSUE TITLE
ctagsTimeout in readonly_configuration.xml causes error

### ISSUE THREAD

**Issue by saltuser16** [oracle/opengrok#3092]
**Describe the bug**
ctagsTimeout in readonly_configuration.xml causes error.  

Here is the error:
```
['Mar 25, 2020 10:57:44 AM org.opengrok.indexer.configuration.Configuration read\n', 'INFO: Reading configuration from /opengrok/etc/readonly_configuration.xml\n', 'An error occurred - this may mean that the input file is not well-formated.\n', '\n', 'java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0\n', '\tat java.desktop/java.beans.XMLDecoder.readObject(XMLDecoder.java:251)\n', '\tat org.opengrok.indexer.configuration.Configuration.decodeObject(Configuration.java:1331)\n', '\tat org.opengrok.indexer.configuration.Configuration.read(Configuration.java:1309)\n', '\tat org.opengrok.indexer.configuration.Groups.main(Groups.java:100)\n']
command failed (return code 3)
```
This errors happen to:

OpenGrok: 1.3.8, 1.3.10
JDK: JDK 13.0.2
OS: CentOS 8.1 ( 8.1.1911)  4.18.0-147.5.1.el8_1.x86_64
Tomcat: 9.0.30
SCM: git 2.25.1

**To Reproduce**
1. Create /opengrok/etc/readonly_configuration.xml with:
```xml
`<?xml version="1.0" encoding="UTF-8"?>
<java version="13.0.2" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration">

  <void property="sourceRoot"> 
   <string>/opengrok/src</string> 
  </void>
  <void property="ctags"> 
   <string>/usr/local/ctags/bin/ctags</string> 
  </void>
  <void property="ctagsTimeout"> 
   <number>60</number> 
  </void>

 </object>
</java>`
```

2. Run this command:
`/opengrok/opengrok-tools/bin/opengrok-groups -a /opengrok/dist/opengrok-1.3.10/lib/opengrok.jar -- -i /opengrok/etc/readonly_configuration.xml -l`

or run this command:
`/opengrok/opengrok-tools/bin/opengrok-indexer \
    -J=-Djava.util.logging.config.file=/opengrok/etc/logging.properties \
    -a /opengrok/dist/opengrok-1.3.10/lib/opengrok.jar -- \
    -c /usr/local/ctags/bin/ctags \
    -s /opengrok/src -d /opengrok/data -H -P -S -G \
    -i "*.tar" -i "*.gz" \
    -R /opengrok/etc/readonly_configuration.xml \
    -W /opengrok/etc/configuration.xml \
    -U http://localhost:8080`

**Expected behavior**
The above commands should return no error

**Screenshots**
See attached screenshots

**Additional context**
Tried with JDK 8, same issue.

**Comment by saltuser16** [comment]
![opengrok_error12](https://user-images.githubusercontent.com/21090290/77571307-5e9b4e00-6e8a-11ea-881e-726bc62d7e50.png)
![opengrok_error22](https://user-images.githubusercontent.com/21090290/77571309-5f33e480-6e8a-11ea-984f-46cb7ddfbbaa.png)

[readonly_configuration.xml.txt](https://github.com/oracle/opengrok/files/4382721/readonly_configuration.xml.txt)

**Comment by idodeclare** [comment]
Try a slightly different element in the `<Configuration>`:

```
  <!-- Sample for setCtagsTimeout. Default is 10 -->
  <void property="ctagsTimeout">
   <long>11</long>
  </void>
```

**Comment by vladak** [comment]
guess I should document the types properly on https://github.com/oracle/opengrok/wiki/Indexer-configuration

**Comment by vladak** [comment]
fix in documentation.
