### ISSUE TITLE
 Indentation in OpenGrok

### ISSUE THREAD

**Issue by sreehari83** [oracle/opengrok#3136]
OpenGrok does not properly indent code
Even i have tried with tabSize in config file and it is not working

opengrok-1.3.9.tar.gz
jdk 1.8
apache-tomcat-9

**Comment by ray590ll** [comment]
Hi you getting this

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ray590ll** [comment]
This me

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by idodeclare** [comment]
I reported this user to Github support

**Comment by idodeclare** [comment]
@sreehari83 , did you re-index as required after changing `tabSize`? Were you using global `tabSize` or project-specific `tabSize`?

**Comment by sreehari83** [comment]
I have used at project specific and did not re-indexed the project.

is re-index required for tabSize changes?

**Comment by idodeclare** [comment]
Yes an incremental reindex is required so xref are rewritten with tabs as spaces

**Comment by vladak** [comment]
closing, feel free to reopen if reindex did not help.
