### ISSUE TITLE
Correct typo in plugins/README.md file 

### ISSUE THREAD

**Issue by tarangchikhalia** [oracle/opengrok#3150]
**Documentation bug**
The Readme file at https://github.com/oracle/opengrok/tree/master/plugins#example-configuration has a typo in the example xml snippet.

![image](https://user-images.githubusercontent.com/61030908/81545595-1c996f00-9347-11ea-9b2c-7250f13ef2de.png)

The below xml code should be inside `<object></object>` tag.

`<void property="setup">
   <void method="put">
     <string>objectclass</string>
     <string>posixAccount</string>
   </void>
</void>`

**Comment by vladak** [comment]
fixed via a3682d6, thanks !
