### ISSUE TITLE
Workaround comments exist in opengrok-indexer/pom.xml file while the related issues are already fixed.

### ISSUE THREAD

**Issue by markxiaotao** [oracle/opengrok#3172]
**Describe the bug**
In a research project, we analyzed the build file of repositories looking for comments with ready-to-be-addressed SATDs (self-admitted technical debt) that could be addressed. If the underlying issue is already resolved, the related code or comment can be removed or fixed. As we found an instance of this kind of asynchrony in pengrok-indexer/pom.xml, we decided to report the issue to contribute community.
Comments in pengrok-indexer/pom.xml file claim that it is workaround for https://github.com/jflex-de/jflex/issues/534, and this issue has been closed long ago, they have fixed in https://github.com/jflex-de/jflex/pull/705#issue-358917220.

Comment location:
https://github.com/oracle/opengrok/blob/cff3e28ce296696b5b7f53f503a11e868121f6b5/opengrok-indexer/pom.xml#L311-L314
https://github.com/oracle/opengrok/blob/cff3e28ce296696b5b7f53f503a11e868121f6b5/opengrok-indexer/pom.xml#L353-L356

**Expected behavior**
This workaround should be removed or updated.

**Comment by vladak** [comment]
Yes, this is something that needs to be changed however not right now - I tried switching to Jflex 1.8.2 however this fails with Java 11 (see https://github.com/jflex-de/jflex/issues/774).

**Comment by vladak** [comment]
fixed in PR #3063.
