### ISSUE TITLE
mirror private organization repos

### ISSUE THREAD

**Issue by nitrocode** [oracle/opengrok#3178]
Is there a way to setup opengrok to mirror private organization repos ? We use a github token to do our clones at the moment.

**Comment by idodeclare** [comment]
If you're meaning a GitHub Personal Access Token, then I believe you need to enlist an OS-specific credential helper (e.g. a Git [credential helper](https://git-scm.com/docs/gitcredentials)) for your local service account that is running your OpenGrok-related SCM command (e.g. `git pull` or `opengrok-mirror`).

Alternatively and more straight-forward (if your org permits) is to generate an SSH key-pair for your local service account, and upload the SSH public key to the GitHub repository to allow read-access for that key-pair. (You then use the SSH version of the remote-url.)

**Comment by vladak** [comment]
When using SSH keys to access a repository, I often set up an alias in `ssh_config` (either for the user performing the mirror or even globally) that looks like this:
```
Host whatever-gate
  User hg
  Hostname whatever.us.example.com
  IdentityFile /sshkeys/id_rsa_grok-hg_whatever
```
The advantage is that if the repository moves to another location, it is not necessary to change the origin in the local clone. This is especially helpful in case of nested repositories.

**Comment by nitrocode** [comment]
I did not know that we can create read only ssh keys.

https://superuser.com/questions/1314064/read-only-access-to-github-repo-via-ssh-key/1314090

I'll look into this more. Thank you.
