### ISSUE TITLE
Slack invitation link on Discussions Wiki page is expired

### ISSUE THREAD

**Issue by oacnhpkqxjhufwumkkqnshvlmheokqv** [oracle/opengrok#3179]
**Describe the bug**
Hello, I'd like to join the conversation on Slack, but it appears that the invitation link in the Wiki has expired on https://github.com/oracle/opengrok/wiki/Discussions#Slack

Would it be possible to have an updated invitation link? Thanks!

**To Reproduce**
Click the link under "use shared invite:"

**Expected behavior**
Get an invitation to join the Slack workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/68922586/88711017-bd8d0000-d0d4-11ea-9e61-abf6ef9b49cd.png)

**Additional context**
Previous occurrence: #2029

**Comment by tarzanek** [comment]
fixed by using https://join.slack.com/t/opengrok/shared_invite/zt-45h3yul2-BToDmBmAE3nN~ImJspCCFA
it seems Slack changed the way how they generate links

**Comment by tarzanek** [comment]
(and thank you for the report! :-) )
