### ISSUE TITLE
LdapFilterPlugin returning true for each ldap filter.

### ISSUE THREAD

**Issue by tarangchikhalia** [oracle/opengrok#3181]
I am using OpenGrok 1.13.16 and openjdk version 1.8.0. I am implementing project level Opengrok authorization in my organization which uses Git. I created the readonly_configuration.xml file which I have tagged below. I have implemented LdapAttrPlugin as well as LdapFilterPlugin in the .xml file. After the reindexing, I am seeing the LdapAttrPlugin is working file but the LdapFilterPlugin is returning true even if the filter blocks the user.

**To Reproduce**
`<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.6" class="java.beans.XMLDecoder">

  
  <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">

    <void property="pluginDirectory">
      <string>/var/opt/opengrok/main/share/lib</string>
    </void>

    <void property="pluginStack">
      
      <void property="setup">
        <void method="put">
          <string>configuration</string>
          <string>/var/opt/opengrok/main/auth/ldap_auth_plugin.xml</string>
        </void>
      </void>

      <void property="stack">

        
        <void method="add">
          <object class="org.opengrok.indexer.authorization.AuthorizationPlugin">
            <void property="name">
              <string>opengrok.auth.plugin.UserPlugin</string>
            </void>
            <void property="flag">
              <string>REQUISITE</string>
            </void>
            <void property="setup">
              <void method="put">
                <string>decoder</string>
                <string>opengrok.auth.plugin.decoders.UserPrincipalDecoder</string>
              </void>
            </void>
          </object>
        </void>

        
        <void method="add">
          <object class="org.opengrok.indexer.authorization.AuthorizationPlugin">
            <void property="name">
              <string>opengrok.auth.plugin.LdapUserPlugin</string>
            </void>
            <void property="flag">
              <string>REQUISITE</string>
            </void>
            <void property="setup">
              <void method="put">
                <string>filter</string>
                <string>(&amp;(objectclass=person)(uid=%username%))</string>
              </void>
              <void method="put">
                <string>attributes</string>
                <string>mail,uid</string>
              </void>
            </void>
          </object>
        </void>

        
        <void method="add">
          <object class="org.opengrok.indexer.authorization.AuthorizationStack">
            <void property="forProjects">
              <void method="add">
                <string>foo</string>
              </void>
            </void>
            <void property="flag">
              <string>REQUISITE</string>
            </void>
            <void property="stack">

              <void method="add">
                <object class="org.opengrok.indexer.authorization.AuthorizationPlugin">
                  <void property="name">
                    <string>opengrok.auth.plugin.LdapFilterPlugin</string>
                  </void>
                  <void property="flag">
                    <string>REQUIRED</string>
                  </void>
                  <void property="setup">
                    <void method="put">
                      <string>filter</string>
                      <string>(&amp;(objectclass=person)(uid=user_foo))</string>
                    </void>
                  </void>
                </object>
              </void>

            </void>
          </object>
        </void>

        <void method="add">
          <object class="org.opengrok.indexer.authorization.AuthorizationStack">
            <void property="forProjects">
              <void method="add">
                <string>bar</string>
              </void>
            </void>
            <void property="flag">
              <string>REQUISITE</string>
            </void>
            <void property="stack">

              <void method="add">
                <object class="org.opengrok.indexer.authorization.AuthorizationPlugin">
                  <void property="name">
                    <string>opengrok.auth.plugin.LdapAttrPlugin</string>
                  </void>
                  <void property="flag">
                    <string>REQUISITE</string>
                  </void>
                  <void property="setup">
                    <void method="put">
                      <string>attribute</string>
                      <string>uid</string>
                    </void>
                    <void method="put">
                      <string>file</string>
                      <string>/var/opt/opengrok/main/auth/whitelist.txt</string>
                    </void>
                  </void>
                </object>
              </void>

            </void>
          </object>
        </void>

      </void>
    </void>
    
  </object>
</java>
`

**Expected behavior**
LdapFilterPlugin should block unauthorized users.

Let me know if any other details are required.

**Comment by vladak** [comment]
How do you know that `LdapFilterPlugin` returns true ?

**Comment by vladak** [comment]
Also, I am not sure if it is related but the sub-stacks for projects `foo` and `bar` should probably have all the flags (i.e. both `AuthorizationStack` and `AuthorizationPlugin`) set to `REQUIRED`.

**Comment by vladak** [comment]
Looking at the filter in question:
```
(&(objectclass=person)(uid=user_foo))
```
this will yield "true" (i.e. allowed) basically _iff_ the user exists in the LDAP directory. Perhaps more fine grained filter is needed ?

In our deployment we use filters like this:
```
(&(objectclass=posixGroup)(cn=developers)(memberUid=%uid%))
```

**Comment by vladak** [comment]
In the source code you can see the behavior here: https://github.com/oracle/opengrok/blob/b05a93f1d75adafe320d94e94f050fafa9b495ff/plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java#L132-L141

The code assumes that if the filter does not match the search will fail, otherwise it updates the session with `true` = allowed.

**Comment by vladak** [comment]
As for debugging, first thing to try is to perform the lookup using the server(s) defined in `/var/opt/opengrok/main/auth/ldap_auth_plugin.xml` from command line, e.g. using `ldapsearch`.

Next, you can try raising the log level for the plugins in the server logging configuration. In this case it might not provide sufficient amount of info as the authnz decisions are logged however it might emit some light on some other problem. In case of Tomcat, try adding
```
opengrok.auth.level = FINE
```
to the `logging.properties` file in the Tomcat configuration directory.

Also, I had various levels of luck with raising the log level for the plugins. My guess it has something to do with class loaders employed by Tomcat and OpenGrok authnz framework.

**Comment by tarangchikhalia** [comment]
I have performed the `ldapsearch` lookup from command line with the same ldap configuration and ldap filter in command line. The filter is returning the user successfully.

Also, I set `opengrok.auth.levle = Fine`. That's where I know that LdapFilterPlugin is returning `true` for all the users.

**Comment by tarangchikhalia** [comment]
Here is the snippet of the logs

`05-Aug-2020 11:41:31.820 FINER [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "foo" in "default stack" [required]
05-Aug-2020 11:41:31.821 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserPlugin" [requisite] testing a name "foo"
05-Aug-2020 11:41:31.821 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.UserPlugin" [requisite] testing a name "foo" => true
05-Aug-2020 11:41:31.821 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapUserPlugin" [requisite] testing a name "foo"
05-Aug-2020 11:41:31.832 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapUserPlugin" [requisite] testing a name "foo" => true
05-Aug-2020 11:41:31.832 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "null" [requisite] testing a name "foo"
05-Aug-2020 11:41:31.832 FINER [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "foo" in "null" [requisite]
05-Aug-2020 11:41:31.832 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapFilterPlugin" [required] testing a name "foo"
05-Aug-2020 11:41:31.836 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "opengrok.auth.plugin.LdapFilterPlugin" [required] testing a name "foo" => true
05-Aug-2020 11:41:31.837 FINER [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "foo" in "null" [requisite] => true
05-Aug-2020 11:41:31.837 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "null" [requisite] testing a name "foo" => true
05-Aug-2020 11:41:31.837 FINEST [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.processStack AuthEntity "null" [requisite] skipping testing of name "foo"
05-Aug-2020 11:41:31.837 FINER [http-nio-127.0.0.1-8080-exec-12] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "foo" in "default stack" [required] => true`

**Comment by vladak** [comment]
> I have performed the `ldapsearch` lookup from command line with the same ldap configuration and ldap filter in command line. The filter is returning the user successfully.

That's the problem - if the filter query returns non-empty output this is interpreted as success. There has to be some matching done in the filter. Do you really have the filter in the config with hard-coded user or is it just an example ?

If you had e.g.
```
(&amp;(objectclass=person)(uid=%uid%))
```
that would mean: as long as the authenticated user (represented by the `%uid`) is present in the LDAP directory he is authorized for that paricular sub-stack.

**Comment by vladak** [comment]
The question is what exactly do you want to achieve with the LdapFilter plugin.

**Comment by tarangchikhalia** [comment]
Ok. I get what you mean. For testing purpose, I have hardcoded the user in the .xml file. This will be later replaced by LDAP group. What I want is to allow Project access to users present in specific LDAP group. 

Right now, user_foo (who can access the project) can access the project as the user is authorized. But the project can be also be accessed by some other user (let's say user_bar) who is not authorized.

**Comment by vladak** [comment]
Then you need a filter that will only match if the user in question is member of this group. This will work then as long as the filter in the configuration has a wildcard representing the user. Of course, given the nature of LDAP filters one can match multiple groups at once either with `&` or `|` logical operators. The available wildcards are set in the attributes in the `LdapUser` configuration.

**Comment by tarangchikhalia** [comment]
Thanks for the information. It is working with your recommendation.

**Comment by vladak** [comment]
Cool !

**Comment by diaojunxian** [comment]
@tarangchikhalia 

Hi, I  encountered the same problem, can you show me the sample file readonly_configuration.xml again?

the work fine file example, thanks a lot.
