### ISSUE TITLE
remove CTag temp files at the end of indexing

### ISSUE THREAD

**Issue by gtoph** [oracle/opengrok#3183]
For whatever reason I get a lot of Ctag failures in the builds I"m indexing.   That is something I eventually need to look into, but the real issue is that my temp folder ends up overflowing with remnants of the failed index.  

Looking in users\....\appdata\local\temp there are a TON of large Ctags temp files from the failed files it tried to look at.  I don't know if there is a built in option to Ctags to have it auto remove (kinda doubt it since it looks like OpenGrok is actually killing the process on a timeout).

Assuming not, is there a way OpenGrok can auto remove them all.. maybe at the end of indexing do a removal of any tags.* file in the temp directory?

**Comment by vladak** [comment]
Is this a actual failure or crash ? Any relevant log messages ? How big are the temp files ?

**Comment by vladak** [comment]
The idea of the auto removal is interesting. Need to see what is the life cycle of the temp files first.

**Comment by gtoph** [comment]
It's certainly not a crash in OpenGrok, if anything it's a failure in CTags.  Like I say, I'm not sure why Ctags chokes on it yet, but OpenGrok hits the timeout handler:

```
22:07:04.665 WARNING [org.opengrok.indexer.analysis] - Terminating ctags process for file '<blah>' due to timeout 10 seconds
22:07:04.667    FINE [org.opengrok.indexer.analysis] - Destroying ctags command
```

Looking at my temp folder... tags.xxxxx type files are variable, but I see some up to 300+ megs.   As it was indexing, I noticed these tag files coming and going, so Ctags is obviously just using them as temporary files, but my guess is that when OpenGrok kills Ctags, the temp would stay and just fill up my drive.

FWIW, I also increased the timeout value (to 20s I think) thinking well maybe ctags just didn't have enough time, but that didn't help it.

**Comment by vladak** [comment]
Thanks for the additional info. The ctags process is likely in endless loop. The indexer should perform the cleanup after it terminates the process.

**Comment by vladak** [comment]
Here's how ctags creates temp files in main/routines.c?r=50540afd#896:
```C
902  #if defined(HAVE_MKSTEMP)
903  	const char *const pattern = "tags.XXXXXX";
904  	const char *tmpdir = NULL;
905  	fileStatus *file = eStat (ExecutableProgram);
906  # ifdef WIN32
907  	tmpdir = getenv ("TMP");
908  # else
909  	if (! file->isSetuid)
910  		tmpdir = getenv ("TMPDIR");
911  # endif
912  	if (tmpdir == NULL)
913  		tmpdir = TMPDIR;
914  	name = xMalloc (strlen (tmpdir) + 1 + strlen (pattern) + 1, char);
915  	sprintf (name, "%s%c%s", tmpdir, OUTPUT_PATH_SEPARATOR, pattern);
916  	fd = mkstemp (name);
```
Basically the indexer will need to search for any files matching the `tags.??????` pattern in the directories stored in the `TMP` or `TMPDIR` environment variables.

**Comment by vladak** [comment]
Better yet, it should also try searching in `System.getProperty("java.io.tmpdir")`.

**Comment by ChristopheBordieu** [comment]
Hi OG team,

I am currently facing the exact same issue while trying to reindex our code (30k repos into 2k projects): my root disk was filled by /tmp/tags.* files. Indexing crashed because of this.
I am using OG 1.5.11.

What are my options to get rid of this issue?

**Comment by vladak** [comment]
That's strange, the workaround in cset 823830a9 was delivered in 1.4.1.

**Comment by vladak** [comment]
@ChristopheBordieu could you list some of your `tags.*` temporary file names ? The `CtagsUtil#deleteTempFiles()` matches just the `tags\\.\\S{6}` regexp.

**Comment by ChristopheBordieu** [comment]
Yep.
```
-rw-------. 1 opengrok opengrok 1707589632 Feb 24 16:36 tags.qbrBvb
-rw-------. 1 opengrok opengrok 1664610304 Feb 24 16:36 tags.8RtqbE
-rw-------. 1 opengrok opengrok 1663066112 Feb 24 16:36 tags.2u4mhq
-rw-------. 1 opengrok opengrok 1722843136 Feb 24 16:36 tags.BO8rdT
-rw-------. 1 opengrok opengrok 1731420160 Feb 24 16:36 tags.OEImwu
-rw-------. 1 opengrok opengrok 1695989760 Feb 24 16:36 tags.7vr1Kn
-rw-------. 1 opengrok opengrok 1733816320 Feb 24 16:37 tags.SY8dOG
-rw-------. 1 opengrok opengrok  911085568 Feb 24 16:37 tags.M8hwap

```

**Comment by ChristopheBordieu** [comment]
Are files deleted only at the very end of indexing?
Or each time ctags is killed or is crashing and so restarted by OG indexer?

I plan to watch my /tmp (TMPDIR soon) and rm all ctags files older than 5 minutes. Some of them are close to 2G. Any risk according to you to do that as a workaround?

**Comment by vladak** [comment]
Yes, the files are deleted at the very end of indexing. The indexer has no way to tell if a particular `tags.*` file belongs to running ctags process or not.

**Comment by ChristopheBordieu** [comment]
Arg... So, apparently, not so many solutions except to remove them quickly as soon as they are created then no more used.
Is my workaround risky according to you?
What is the duration of these files? I mean, when ctags creates it, it is a temporary file that should be used within the next minutes?

**Comment by vladak** [comment]
As for adjusting the workaround to be time based that's certainly doable however not something I'd like to tackle right now. I wonder how exactly the temporary files are used by ctags. The ctags processes used by the indexer are kept around until they are no longer needed so a single ctags process gets to chew many input files. If a single ctags process uses the temporary file for all of the input files then this might be a problem. Or it could just be some giant files causing problems.

**Comment by ChristopheBordieu** [comment]
My current watch shows very often ctags file(s) are created then almost instantaneously deleted. Watch is running with default 2s sleep on my VM (Linux RHEL 8.3; 10 CPUs so 10 ctags processes).

**Comment by vladak** [comment]
As for the adjusted workaround being more risky: it does not pass my gut test :-)

Firstly, the time would need to be bigger than the ctags timeout. Secondly, removing the temporary file would not help w.r.t. file system space reclamation on Unix systems unless the ctags process is killed as well.

**Comment by ChristopheBordieu** [comment]
I was planning, yes, to use at least 10s (ctags timeout) before to remove files.
As reported, many temp files are created then deleted. I have not 10 ctags files max (like the number of ctags processes) but many more (around 30) when it crashed the first time.

**Comment by vladak** [comment]
Strangely, looking at my production machine running 1.5.9, I can see number of `tags.*` files under `/tmp`, most of them older than one day. I don't see any `cannot delete file` log entries in indexer logs so likely the `.java.io.tmpdir` is different. The machine is running the indexer per project however I don't think it's related.

**Comment by vladak** [comment]
Looks like the `java.io.tmpdir` on that machine is set to `/var/tmp`, will need to address this somehow.
