### ISSUE TITLE
1.4.0 release issue

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#3184]
This is not code issue.

New 1.4.0 is half released not full in the release page.
Please correct.
Thank you.

**Comment by vladak** [comment]
I am aware of the issue. This is caused by #3176.

**Comment by vladak** [comment]
We need to publish a release with the recently integrated Lucene 8.6.1 anyway so once I fix the above mentioned bug I will trigger new release.

**Comment by vladak** [comment]
I was tempted to remove the Maven `verify` step when creating a release however that might lead to a situation where long standing test failures are not solved (which might cause actual problems in the longer run). It is better to keep this self regulation in place.

**Comment by vladak** [comment]
fixed by releasing 1.4.1
