### ISSUE TITLE
Opengrok SSO configuration

### ISSUE THREAD

**Issue by pavanbhattiprolu** [oracle/opengrok#3189]
Please point me any steps/procedures which we need to follow to enable SSO configuration to opengrok.

**Comment by vladak** [comment]
In general, OpenGrok is just a consumer of data which are passed from authentication (as described on https://github.com/oracle/opengrok/wiki/Authorization). This means that any authentication configuration has to be performed outside of OpenGrok configuration.

That said, I've been running an OpenGrok instance internally that uses SAML based SSO using the [mod_auth_mellon](https://github.com/latchset/mod_auth_mellon) Apache module where Apache provides the data to Tomcat via HTTP headers and is setup to act as a reverse proxy for Tomcat.

Let me know if you are interested in more details of this particular setup.

**Comment by vladak** [comment]
Closing for lack of response, feel free to reopen.
