### ISSUE TITLE
Unable to use the definition search after installing OpenGrok

### ISSUE THREAD

**Issue by RAgarwal57** [oracle/opengrok#3199]
I've installed OpenGrok running on a Tomcat server using instructions from the following links

https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok
https://www.mulesoft.com/tcat/tomcat-linux

I've managed to link opengrok to my source code and browse normally, but the definition search is not working. No matter what I search, it always returns no results. Has anyone seen this problem before and have any ideas on how to fix it?

**Comment by idodeclare** [comment]
What programming language is your code?

**Comment by RAgarwal57** [comment]
> What programming language is your code?

C and Python

**Comment by idodeclare** [comment]
Do logs show anything about the ctags runs?

You might also check the ctags function. Run the OpenGrok indexer with `--help ctags` to get the command-line, and then run it. If successful ctags will start up and wait for file names. You can enter a source code path and see what is produced.

**Comment by vladak** [comment]
This is stale, closing.
