### ISSUE TITLE
Limit user access to repo searches

### ISSUE THREAD

**Issue by sanjay-crypto** [oracle/opengrok#3201]
This is just a question not a feature request. 
Is there any way to restrict or limit user to search in particular repositories only?
I have 5 repositories and 5 users who access grok to search code. 
user1 to be allowed search repo1 and repo2. User2 to be allowed to search in repo2 and repo3, user3 to be allowed to search in repo1, repo3 and repo5.

**Comment by vladak** [comment]
See https://github.com/oracle/opengrok/wiki/Authorization
