### ISSUE TITLE
Configuration files Help

### ISSUE THREAD

**Issue by rmshnair** [oracle/opengrok#3220]
I am trying to setup the environment for my Java and Javascript projects. trying to find a help with configuration files that helps to setup my GIT and SVN repos synced with open grok. There are several configuration files and slightly confused with their formats, and locations, especially with docker container environment.
> sync config
> fresh_config.xml
> ctags.config
> reso sync configuration.yml

any help is much appreciated

**Comment by vladak** [comment]
For repository synchronization config using the `opengrok-mirror` script see https://github.com/oracle/opengrok/wiki/Repository-synchronization

The execution of the `opengrok-mirror` script should go into https://github.com/oracle/opengrok/blob/112419ef444792539909442eac238b1293734d71/docker/start.sh#L41-L44

Using the `sync` script in the Docker container is certainly possible.

It would be nice if the `opengrok-sync` and `opengrok-mirror` were running in the Docker container, created #3221.

**Comment by rmshnair** [comment]
Thanks, i see a YAML configuration in [https://github.com/oracle/opengrok/wiki/Repository-synchronization], it looks like a per project configuration, but different format, what should be the filename for this YAML and where do i put in docker container?

**Comment by vladak** [comment]
The config file can be placed anywhere in the Docker image I think. It does not matter what is the name of the config file, just pass it to the `opengrok-mirror` script with `--config` option.

**Comment by vladak** [comment]
The username/password for Subversion repositories is set via environment variables:
  - `OPENGROK_SUBVERSION_USERNAME`
  - `OPENGROK_SUBVERSION_PASSWORD`

**Comment by vladak** [comment]
Actually, the `opengrok-mirror` is already part of the Docker image and runs before every reindex.

**Comment by vladak** [comment]
The limitation of performing repository synchronization via `opengrok-mirror` is that it does not accept username/password. Perhaps this can be part of the Subversion configuration ?

**Comment by vladak** [comment]
In general I'd say that if you need mirroring configuration, then this is outside of intended use scope for the official Docker image. Better run the mirroring externally and disable it via the `NOMIRROR` environment variable.

**Comment by rmshnair** [comment]
Thanks. i was able to configure. however i see a problem. i have a svn repo with multiple trunks at different level. i checked out each trunk separately, however organized as same folder structure inside a single opengrok project. my observation is, indexer ran and able to figure out all the trunk that are with in 4 levels deep from the project folder. all other are not found and added to configuration.xml. is this 4 levels deep is a limitation? if so, can we overcome this?

**Comment by vladak** [comment]
See the `--depth` indexer option.
