### ISSUE TITLE
introduce API tokens

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3222]
It would be more convenient to be able to access all of the API remotely.

This would complement `LocalhostFilter` - the token would be required only when not coming from localhost.

**Comment by vladak** [comment]
Couple of notes:
  - the token filter should make sure that the request is going through HTTPS (i.e. `isSecure()` is true) in order to perform the check
  - the `LocalhostFilter` can be brought into `web.xml` (currently it is implicit via `@PreMatching`) so that it can be configured/disabled or it can be made aware of the authentication header used by the token filter (if the header is present, break out)

**Comment by vladak** [comment]
As for the general approach I'd like to keep this simple (i.e. no JWTs):
  - have a simple way to generate the API tokens (e.g. using `UUID.randomUUID()`) (if any)
  - add the tokens to the `Configuration` via read-only config
  - the token filter will compare the `Authorization` header contents (if present) to the tokens in the configuration

**Comment by Laeffe** [comment]
Hi @vladak.
I saw your patches related to this and it looked promising and exactly what we have been in need of for a while.
However I'm not able to get it working, not sure if I'm setting the token in the right way.
I'm currently via -R to the indexer adding this to the config:
```
<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.6" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void property="authenticationTokens">
   <void method="add">
    <string>the-token</string>
   </void>
  </void>
 </object>
</java>
```

**Comment by vladak** [comment]
How do you run the indexer exactly ? The configuration needs to be made active in the web application. Is there anything interesting in Tomcat logs ?

**Comment by Laeffe** [comment]
Thanks for you quick response @vladak.

After managing to verify with Postman and curl that the token does work, I guess the issue I'm facing is that the indexer isn't using the token it self while accessing the webapp.

Unless I missunderstand something, it's in these places the indexer tries to call the webapp:
org/opengrok/indexer/index/IndexDatabase.java:371
org/opengrok/indexer/index/IndexerUtil.java:53
org/opengrok/indexer/index/IndexDatabase.java:371
org/opengrok/indexer/configuration/RuntimeEnvironment.java:1440

Are we trying to use this feature in a completely wrong way? Or is this just a new use-case?

**Comment by vladak** [comment]
Oh, that's something I forgot - I considered only external API calls. Filed as #3398

**Comment by Laeffe** [comment]
@vladak, thanks <3
