### ISSUE TITLE
How can I access the javadoc?

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#3287]
I saw the build publishing javadoc but I don't seem to find a way to access it.

After a while, I deduced from the source code that the uri is https://oracle.github.io/opengrok/javadoc/, but I don't see it mentioned on the main page or else.

**Comment by vladak** [comment]
It's linked from https://github.com/oracle/opengrok/wiki/Developer-intro

**Comment by tulinkry** [comment]
Fair enough, thanks.
