### ISSUE TITLE
add OPTIONAL verb to authorization framework

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3289]
This is needed to support the change described in #3288. In the example authorization stack given there the `LdapUserPlugin` can be made `OPTIONAL` so the failure to lookup LDAP user is not fatal.

**Comment by tulinkry** [comment]
Why is marking the auth branch as SUFFICIENT not enough?

```
UserPlugin (REQUISITE)
LdapUserPlugin (SUFFICIENT)
  - substack
    LdapAttrPlugin (SUFFICIENT) // checks whitelist against mail attribute from LDAP
    LdapFilterPlugin (REQUIRED)

**Comment by vladak** [comment]
In the stack above it is undesirable to return immediately in case of success.

**Comment by tulinkry** [comment]
Then something like this?

```
UserPlugin (REQUISITE)
  - substack (SUFFICIENT)
     LdapUserPlugin (REQUISITE)
     LdapAttrPlugin (SUFFICIENT) // checks whitelist against mail attribute from LDAP
     LdapFilterPlugin (REQUIRED)
  - substack (REQUIRED)
     whitelistplugin from file (REQUIRED)

**Comment by vladak** [comment]
That would do however the added flexibility won't hurt.

**Comment by tulinkry** [comment]
If we stick to the PAM framework, where we implemented parts of the ideas, we have:

> Optional – Success in meeting an optional module's requirements is not necessary for using the service. Failure causes an optional failure to be recorded.

(from https://docs.oracle.com/cd/E26502_01/html/E29015/pam-32.html#SYSADV6pam-32)

I understood it that actually it's not really useful, as you shouldn't treat success anyhow and failure does not fail the authorization. More like a "execute action on a side".

**Comment by vladak** [comment]
Right, I think Linux PAM implementation interprets the result of OPTIONAL plugin only in case it is the only plugin in the stack.

**Comment by vladak** [comment]
My point is that this will allow for flat stack. If OPTIONAL `LdapUserPlugin` does not fill in the `LdapUser` the traversal will be stopped by the first LDAP plugin.

**Comment by vladak** [comment]
> Then something like this?
> 
> ```
> UserPlugin (REQUISITE)
>   - substack (SUFFICIENT)
>      LdapUserPlugin (REQUISITE)
>      LdapAttrPlugin (SUFFICIENT) // checks whitelist against mail attribute from LDAP
>      LdapFilterPlugin (REQUIRED)
>   - substack (REQUIRED)
>      whitelistplugin from file (REQUIRED)
> ```

The downside of this approach is that if you have multiple substacks relying on the `LdapUserPlugin` then you'd have to copy the plugin to each of them. For instance:

```
UserPlugin (REQUISITE)
LdapUserPlugin (REQUISITE)
- substack // per project/group
  LdapAttrPlugin (SUFFICIENT)
  LdapFilterPlugin (REQUIRED)
- substack // per project/group
  LdapAttrPlugin (SUFFICIENT)
  UserWhiteListPlugin (REQUIRED)
- substack // per project/group
  ... 
... //more LDAP based stacks
```

would turn into something like this:

```
UserPlugin (REQUISITE)
- substack // per project/group
  - subsubstack (SUFFICIENT)
    LdapUserPlugin (REQUISITE)
    LdapAttrPlugin (SUFFICIENT)
    LdapFilterPlugin (REQUIRED)
  - subsubstack (REQUIRED)
    UserWhiteListPlugin (REQUIRED)
- substack // per project/group
  - subsubstack (SUFFICIENT)
    LdapUserPlugin (REQUISITE)
    LdapAttrPlugin (SUFFICIENT)
  - subsubstack (REQUIRED)
    UserWhiteListPlugin (REQUIRED)
- substack
  ... 
... //more LDAP based stacks
```

while with `OPTIONAL` the overall structure would remain almost the same:

```
UserPlugin (REQUISITE)
LdapUserPlugin (OPTIONAL)
- substack // per project/group
  LdapAttrPlugin (SUFFICIENT)
  LdapFilterPlugin (REQUIRED)
- substack // per project/group
  UserWhiteListPlugin (SUFFICIENT) // swapped
  LdapAttrPlugin (REQUIRED) // swapped
- substack // per project/group
  ... 
... //more LDAP based stacks
```

**Comment by tulinkry** [comment]
I don't like this change for reasons:

1. it does not align with the PAM framework definition of OPTIONAL and we copied the parts of PAM framework for this authorization framework
2. the solution for the problem is possible and is just a matter of configuration
3. moving the responsibility of "ensure there is ldap user" to other plugins than LdapUserPlugin

**Comment by vladak** [comment]
> I don't like this change for reasons:
> 
>     1. it does not align with the PAM framework definition of OPTIONAL and we copied the parts of PAM framework for this authorization framework

Do you mean it has different semantics than in usual PAM implementation ?
 
>     2. the solution for the problem is possible and is just a matter of configuration

I consider adding another layer to the stack merely as a workaround.
 
>     3. moving the responsibility of "ensure there is ldap user" to other plugins than LdapUserPlugin

It depends on how you configure it. The LDAP plugins are certainly ready for this and this change does not force anyone to specify the control flags of `LdapUserPlugin` as `OPTIONAL`. It is true that configuring a PAM framework in Unix system is sometimes an art. On the other hand it allows for lots of flexibility. The logging employed by the framework and plugins is helpful enough to debug any kind of problem caused by the configuration I believe.

In sum, adding more flexibilty by introducing new control flag should not hurt as long as it does not break pre-existing functionality.  I consider the argument nr. 1 as the only viable out of these 3. Hopefully we can clarify that.

**Comment by tulinkry** [comment]
> Do you mean it has different semantics than in usual PAM implementation ?

I saw the code and it looks like you implemented it the way it is described in PAM - sice action which only fails the stack when no other non-optional plugins are present.

I'm not using these features so, at the end of the day, when it makes it really easier to configure with this new flag, it's worth considering it.

Plugins which are inherently dependent on some other plugins (like LdapAttrPlugin on LdapUserPlugin) must consider the fact that they can be used in a combination with OPTIONAL and thus be prepared that the dependency they require may not be met. I think the set of plugins in OpenGrok code is prepared for that.

**Comment by vladak** [comment]
> Plugins which are inherently dependent on some other plugins (like LdapAttrPlugin on LdapUserPlugin) must consider the fact that they can be used in a combination with OPTIONAL and thus be prepared that the dependency they require may not be met. I think the set of plugins in OpenGrok code is prepared for that.

Right. It gives the user more ammunition to shoot himself into his foot (or feet). The trade-off is the added flexibility. If we want to draw analogies with common PAM framework implementations in Unix it is just about the same. The plugins may pass data to one another using `pam_set_item(3PAM)` and be reasonably resilient w.r.t. this input data.
