### ISSUE TITLE
copyright format checker

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3300]
There should be copyright format checker run alongside the maven checkstyle checker that would enforce format of the copyright notes to be in the format of `{Portions ,}Copyright (c) <year>{, <year>}, comment`.

**Comment by tulinkry** [comment]
I remember writing a test for this back in oracle, though I left it in the company laptop :/

**Comment by tulinkry** [comment]
But it was more about checking if the year in the copyright corresponds to the modification date (for the files I was about to push to upstream)

**Comment by vladak** [comment]
> I remember writing a test for this back in oracle, though I left it in the company laptop :/

Well, that's an opportunity to produce even better version :-)

**Comment by vladak** [comment]
> But it was more about checking if the year in the copyright corresponds to the modification date (for the files I was about to push to upstream)

That would be nice to have too.
