### ISSUE TITLE
Couldn't notify the webapp on http://xxx:10309/source. javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by ivan511** [oracle/opengrok#3305]
Hi all,

I am trying to setup newest version of OpenGrok (1.4.9). I have deployed .war file, cloned test repo.
The next step is to get indexes but when I run command for it, I keep getting 401 ERROR:

seliius27570: /proj/cpp_opengrok  > java -Djava.util.logging.config.file=/proj/cpp_opengrok/etc/logging.properties -jar /proj/cpp_opengrok/dist/lib/opengrok.jar -c /usr/bin/ctags -s /proj/cpp_opengrok/src -d /proj/cpp_opengrok/data -H -P -S -G -W /proj/cpp_opengrok/etc/configuration.xml -U http://xxx:10309/source
15:46:18 SEVERE: Couldn't notify the webapp on http://xxx:10309/source.
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
    at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:936)
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:739)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:623)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:621)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)
    at org.opengrok.indexer.index.IndexerUtil.enableProjects(IndexerUtil.java:60)
    at org.opengrok.indexer.index.Indexer.main(Indexer.java:331)

So opengrok is deployed to "xxx" webserver, but all the data is at localhost. I have edited web.xml under WEB-INF to look like this:

    <context-param>
        <description>Full path to the configuration file where OpenGrok can read its configuration</description>
        <param-name>CONFIGURATION</param-name>
        <param-value>/proj/cpp_opengrok/etc/configuration.xml</param-value>
    </context-param>
    <context-param>
        <param-name>ConfigAddress</param-name>
        <param-value>xxx:10309</param-value>
        <description>An address where OpenGrok can receive new configuration</description>
    </context-param>

JDK used for indexing: 11.0.1-1
Tomcat version:  Apache Tomcat/8.5.42

Any suggestion on what needs to be done to be able to execute indexing properly ?

Hope someone could help.
Regards

**Comment by vladak** [comment]
If `xxx` is not `localhost` then this will not work due to `LocalhostFilter` - this is preventing anyone from sending arbitrary configuration to the web app. Is there a particular reason for that in your setup ?

Also see #3222

**Comment by ivan511** [comment]
Hi, xxx is not localhost, its other machine running webserver. So, #3222 is the only solution to be able to run it ?
Is there any example on how to set it up correctly with some more details maybe ?
Thanks in advance.

**Comment by vladak** [comment]
There is simply no authentication for the management APIs yet. Once #3222 is implemented it would also force HTTPS for the obvious reasons.

A workaround might be to tunnel the connection through SSH or such.

**Comment by vladak** [comment]
Out of curiosity - how do you share the data between the indexer machine and web app machine ?

**Comment by ivan511** [comment]
Thanks for fast response, 

Would some older version of opengrok help maybe ? (if LocalhostFilter is not in).

To answer your question on how do I share data.
So, I have edited web.xml to point out to indexer machine where all the data is. It worked when I had an older instance of opengrok installed. I saw /xref and could go through the source code, but had some "EROR EOF" while trying to search. Thats the reason I wanted to use newest version.

**Comment by vladak** [comment]
I really hope there is no version of OpenGrok without the `LocalhostFilter` as that would mean a security vulnerability (in older version but still).

My question about data sharing was about the actual data consumed and created by the indexer. Do you use NFS or something else ?

Another workaround would be to omit the -U option, copy the generated configuration XML file to the web app machine and upload its contents using the RESTful API (see https://opengrok.docs.apiary.io/reference/0/configuration/sets-configuration-from-xml-representation).

**Comment by vladak** [comment]
The API tokens are now available in 1.5.9.

**Comment by mamh2021** [comment]
I also met this issue.
I start tomcat with docker like this
`docker run --restart always -d -p 80:8080 -p 8080:8080 --name tomcat9 tomcat9-jdk11`
but the indexer run another docker like this
`docker run -t -d -u 1000:1000 --network host`
I start tomcat like this `docker run --restart always -d   --network host  --name tomcat9 tomcat9-jdk11`
maybe this option   --network host. is different.

**Comment by vladak** [comment]
Running with `-network host` should work as long as you run both containers with it and the indexer is run with the `-U` option pointing to `localhost`.

**Comment by vladak** [comment]
Actually, the Docker `host` driver does not seem to work that way. A network service running in container with this driver can be accessed from outside only as long as the request comes from the host itself, i.e. not another container.
