### ISSUE TITLE
HistoryGuru.getRepository(File f) is inefficient with many Repositories with many files (and deep directory structures)

### ISSUE THREAD

**Issue by azakkerman** [oracle/opengrok#3306]
**Is your feature request related to a problem? Please describe.**
getRepository(File) method is very frequently used in the code to discover mapping of File to its enclosing Repository. It is called for every crawled file during indexing as well.

https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java#L731-L763

The method performs O(N*M) invocations of PathUtils.getRelativeToCanonical(), where
  * N = number of Repositories
  * M = depth of the File path being examined

This gets extremely expensive when indexing ~10k Repos with deep directory structures.

**Describe the solution you'd like**
It appears that code can be optimized a bit:
 1. the code is being a bit overly conservative w.r.t. always wanting to compute canonical paths
     1. e.g. the code can assume that path is canonical and filter Repositories to only one(s) that match the beginning (prefix) of the File's path
     1. fallback to checking all Repositories if no match found in previous step (slow path, unlikely)
 1. the code can cache directory -> enclosing Repository in the HistoryGuru instance. This way lookups for all files in that directory will immediately find the Repository w/o any additional computations. Additionally, one should backfill all parent directories of a given dir -> Repository, up to the Repository root on first cache miss to speed up subsequent lookups. The cache should be cleared on HistoryGuru invalidation.

I have a working prototype of this using simple ConcurrentMap as a cache, but it requires some work to get past our corporate process for submitting OSS patches. It reduced indexing time by orders of magnitude in our setup.

**Comment by vladak** [comment]
Sounds awesome, looking forward to the PR !

**Comment by vladak** [comment]
fixed in 6d9d3df
