### ISSUE TITLE
Add git submodule support to indexer

### ISSUE THREAD

**Issue by azakkerman** [oracle/opengrok#3315]
**Is your feature request related to a problem? Please describe.**
When using git with many submodules, instead of crawling, the indexer should just run git submodule commands to discover the repositories. 

**Describe alternatives you've considered**
Passing in an explicit list of repositories to index via -s flag, preferably via a file, so as not to run into command line length limits

**Comment by vladak** [comment]
Fixed via #3677, hence closing.
