### ISSUE TITLE
Rapid growth in disk space usage in /tmp dir, with tags.xxxxxx files

### ISSUE THREAD

**Issue by oacnhpkqxjhufwumkkqnshvlmheokqv** [oracle/opengrok#3380]
**Describe the bug**
The disks on my VMs are filling up rapidly this week, and I've noticed that the /tmp folder inside the OpenGrok Docker container has a lot of "tags.xxxxxx" files. 
My test instance has 109 of these files, totalling 67 GB
My prod instance has 395 of these files, totalling 264 GB
All in the past 4 days

How are these created, and are they safe to delete? Thanks!!

$ docker exec -i opengrok-docker bash
$ du -ah --threshold=1G /
1.1G    /tmp/tags.mxhftj
1.1G    /tmp/tags.8ONX9G
1.1G    /tmp/tags.LTmOVG
1.1G    /tmp/tags.4z5eDl
1.1G    /tmp/tags.zQutQg
1.1G    /tmp/tags.fld24o
1.1G    /tmp/tags.dqlmsM
1.1G    /tmp/tags.DutIT8
1.1G    /tmp/tags.H0SMnb
1.1G    /tmp/tags.HQGLog
...
67G     /tmp

OpenGrok v1.3.8
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
OS: Debian GNU/Linux 9 (stretch)

Server version: Apache Tomcat/9.0.20
OS Version: 3.10.0-1127.el7.x86_64
JVM Version: 1.8.0_212-8u212-b01-1~deb9u1-b01

**To Reproduce**
Not sure.

**Expected behavior**
Temp files are automatically cleaned.

**Comment by vladak** [comment]
Sounds like a dup of #3183. Upgrade to the latest version.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Thank you!

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Hacky workaround until we upgrade to the latest version, is to cron this to run every ~24 hours:
`find /var/lib/docker/overlay2/*/merged/tmp/ -name "tags.*" -type f -mmin +120 -delete`
