### ISSUE TITLE
size of the thread pool created in HistoryGuru#invalidateRepositories() should be controllable

### ISSUE THREAD

**Issue by louie0817** [oracle/opengrok#3391]
**Describe the bug**

opengrok version 1.5.8
tomcat 9.0.39
jdk-11.0.9
running on Red Hat 7.6
28 cores , 512 GB RAM

We do our opengrok processing in two steps.
1: update source and run indexing.
 1a. swap yesterdays src/data tree with today's src/data
2. Push new config to Tomcat to point to new tree

I have observed that my setting for historyThreads is being ignored and a full 56 (i.e. 2 x 28 cores) threads are active during the run of step 2.

contrasted with step 1 that uses the requested 16 threads

notable opengrok.jar arguments:

step 1: `-G -S -H -P -T 16 --historythreads 16 -W conf.xml`

step 2: `-T 2 --historyThreads 2 -n -H -R conf.xml -U MYURI`
Note: I have tried lowering -T and --historyThreads each day from 16 -> 8 -> 4 -> 2, with no effect.

BTW, I am raising issue as our SAs are flagging our test machine with excessive PIDs (ranging from 3-7 k) during step 2. every night

Final piece of info. Originally step 2 did not have -H args, but that resulted in no "History box" on the gui. Seems although the generated conf.xml file shows HistoryEnabled as true, dumping the config from tomcat after uploading, returned HistoryEnabled as false. So this could be an underlying issue. as without the -H, I still see 56 threads, but less commands are executed per thread.

btw, I am getting the thread counts I mentioned ( 16 vs 56) from the logs with the command
`grep "Executor.exec: Executing command" log`
and then noting the unique thread ids

**Comment by louie0817** [comment]
btw, I am getting the thread counts I mentioned ( 16 vs 56) from the logs with the command
grep "Executor.exec: Executing command" log
and then noting the unique thread ids

**Comment by vladak** [comment]
Instead of running the indexer to upload the config to the web application, you can use the RESTful API, in particular the `/configuration` end point.

**Comment by vladak** [comment]
The threads that you are seeing in step 2 likely come from `HistoryGuru#invalidateRepositories()` that creates as many threads as there are CPUs in the system: https://github.com/oracle/opengrok/blob/e2dc7a488d0141a4a75e92800b263057abea5d5b/opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java#L819-L828

This is called from `RuntimeEnvironment#setConfiguration()` via: https://github.com/oracle/opengrok/blob/e2dc7a488d0141a4a75e92800b263057abea5d5b/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java#L251-L252

The `newFixedThreadPool` should honor some of the thread tunables.

**Comment by vladak** [comment]
As for whether to avoid calling `invalidateRepositories()` with `-n` I am bit torn. There seem to be too many places where `-n` has to be taken into consideration. Perhaps it's time to revisit whether `-n` is needed at all.

**Comment by louie0817** [comment]
Hi Vlad,

Thanks for the API suggestion.

I used the API to send the new configuration using:
curl -vi --header "Content-Type:application/xml" -X PUT --data-binary @conf.xml http://localhost:58080/source/api/v1/configuration

I have tried several times with various outcomes
After each attempt, I immediately get the configuration right back with GET to compare. As that seems the only way to verify the PUT worked.

First observation the index timestamp is not updated from our nightly job. :-(

Second, if I change a system tunable in the large conf.xml file, like ctagsTimeout the GET returns the new value, but if I change the branch string of the first repo listed, the data that comes back does not show my change. Also, the project listing on the main page of the GUI does not show my change in the 2nd column (SCM Type: Parent(branch)

Note that we normally disable the project listing at the bottom of the main page. We have over 100k GitHub enterprise repos and it takes too long to completely load. but I did re-enable it to see if my test change was visible. 

As an aside, I noticed that the 3rd column "Current version" has a "Show more" link, that does not work with our large list of repos, it has no effect. (it does work correctly in my docker image for a small number of repos)

So I am not sure replacing the 2nd call of openwork.jar with "-n" to pass the config to Tomcat with the "configuration" endpoint is suitable at the moment.

**Comment by vladak** [comment]
> First observation the index timestamp is not updated from our nightly job. :-(

For that to happen you have to set the `reindex` parameter in the query URL.
 
> Second, if I change a system tunable in the large conf.xml file, like ctagsTimeout the GET returns the new value, but if I change the branch string of the first repo listed, the data that comes back does not show my change. Also, the project listing on the main page of the GUI does not show my change in the 2nd column (SCM Type: Parent(branch)

Setting repository data was never supported. The repositories are re-evaluated when the new configuration is processed in the web app (that's called repository invalidation) which basically means they are re-scanned using the relevant SCM commands. This basically overrides any changes to the repository metadata.

**Comment by vladak** [comment]
The thread pool size fix is in 1.5.11.

**Comment by vladak** [comment]
What happens in step 2 is that the indexer will do repository invalidation (pretty heavy procedure with large number of repositories) and will upload the configuration (containing the list of the repositories) to the web application that will do the same repository invalidation. The RESTful API call is better because it skips the first invalidation.
