### ISSUE TITLE
random "Failed to move file" error for tmp *.org_opengrok files

### ISSUE THREAD

**Issue by louie0817** [oracle/opengrok#3397]
**Describe the bug**
opengrok version 1.5.10
tomcat 9.0.39
jdk-11.0.9
running on Red Hat 7.6
28 cores , 512 GB RAM

I am getting random rename errors during renames of the *.org_opengrok files in xref dir and this results in a SEVERE error in writing the index for this particular project. I looked at the code and only saw one file , PendingFileCompleter.java when teh rename is done, so not sure what would have happened to the *.org_opengrok file.

Every nightly run of the indexer results in 0 or more of these errors. When it does fail and I rerun just the indexing part of our nigthl job (i.e, no source update), the reported could be different files.
yesterday had 4 errors, then rerun had 0. Today's job had 1 error initially, then 3 in a rerun, and doing another indexing now

**SEVERE error is:**
```
2020-12-08 11:52:09.390-0500 SEVERE t1453803 IndexDatabase$1.run: Problem updating index database in directory /PATH/new/opengrok/index/ghe:
7312279 java.io.IOException: 3 failures (0.0%) while renaming pending files
```
**line from SEVERE error stack trace:**
```
Caused by: java.nio.file.NoSuchFileException: /PATH/new/opengrok/xref/ghe/MOREPATH/foo.t.js.gz.org_opengrok
```
**and this was the first WARNING of the failed rename:**
```
2020-12-08 11:52:08.428-0500 WARNING t1454018 PendingFileCompleter.doRename: Failed to move file: /PATH/new/opengrok/xref/ghe/MOREPATH/foo.t.js.gz.org_opengrok -> /PATH/new/opengrok/xref/ghe/MOREPATH/foo.t.js.gz
```

**Comment by louie0817** [comment]
One other note, I am pretty sure I did not see these errors in 1.5.8, but I cannot verify as I deleted the 1.5.8 logs a couple of days ago, thinking I would not need them. :-(

**Comment by louie0817** [comment]
So upon further investigation of the log based on filenames and not the error messages, I see the file was update since last run of nightly jobs, so it is removed from index with fileRemoved(), added back with fileAdd(), then a Statistics.logIt() and then two doDelete() calls, one for I presume the old *.gz file and another for the .org_opengrok, then I see to doRename and its failure. All of the is in different thread ids, so perhaps there is a race condition

Here is what each thread does in chronological order:

t1 fileRemove
t1 fileRemoved
t2 AnaylzerGuru.find()
t2 fileAdd
t3 ctags
t2 fileAdded
t2 statistics.logIt()
t4 doDelete(*.gz)
t4 doDelete(*.gz_org_opengrok)
t2 doRename failure

**Comment by ChristopheBordieu** [comment]
I think I have plenty of such errors too in my latest indexing runs. Incremental runs (with no update of SRC directory) seem to remove them little by little.

**Comment by vladak** [comment]
This seems to be happening for larger projects when there is large amount of updates. The problem is that these failures may lead to index being dirty.

**Comment by vladak** [comment]
> So upon further investigation of the log based on filenames and not the error messages, I see the file was update since last run of nightly jobs, so it is removed from index with fileRemoved(), added back with fileAdd(), then a Statistics.logIt() and then two doDelete() calls, one for I presume the old *.gz file and another for the .org_opengrok, then I see to doRename and its failure. All of this is in different thread ids, so perhaps there is a race condition
> 
> Here is what each thread does in chronological order:
> 
> t1 fileRemove
> t1 fileRemoved
> t2 AnaylzerGuru.find()
> t2 fileAdd
> t3 ctags
> t2 fileAdded
> t2 statistics.logIt()
> t4 doDelete(_.gz) 
> t4 doDelete(_.gz_org_opengrok)
> t2 doRename failure

Thanks for the analysis. I arrived to the same result using the "prepped" version (tarballs extracted and patches applied) of https://github.com/oracle/solaris-userland/ :
```
$ grep 'components/gnome/libsecret/test/results-32.master' opengrok0.0.log 
2021-08-10 21:46:11.005+0000 FINE t36 DefaultIndexChangedListener.fileRemove: Remove file:/solaris-userland/components/gnome/libsecret/test/results-32.master
2021-08-10 21:46:11.005+0000 FINER t36 DefaultIndexChangedListener.fileRemoved: Removed file:/solaris-userland/components/gnome/libsecret/test/results-32.master
2021-08-10 21:49:14.100+0000 FINEST t45 AnalyzerGuru.find: /solaris-userland/components/gnome/libsecret/test/results-32.master: chosen by suffix: XMLAnalyzerFactory
2021-08-10 21:49:14.101+0000 FINE t45 DefaultIndexChangedListener.fileAdd: Add: /solaris-userland/components/gnome/libsecret/test/results-32.master (XMLAnalyzer)
2021-08-10 21:49:14.105+0000 FINER t45 DefaultIndexChangedListener.fileAdded: Added: /solaris-userland/components/gnome/libsecret/test/results-32.master (XMLAnalyzer)
2021-08-10 21:49:14.107+0000 FINEST t45 Statistics.logIt: file '/ws-local/solaris-userland/components/gnome/libsecret/test/results-32.master' indexed (took 7 ms)
2021-08-10 21:52:21.570+0000 FINER t123 PendingFileCompleter.doDelete: Deleted obsolete file: /opengrok/data/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz.org_opengrok
2021-08-10 21:52:21.570+0000 FINER t123 PendingFileCompleter.doDelete: Deleted obsolete file: /opengrok/data/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz
2021-08-10 21:57:25.039+0000 WARNING t132 PendingFileCompleter.doRename: Failed to move file: /opengrok/data/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz.org_opengrok -> /opengrok/d
ata/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz
Caused by: java.nio.file.NoSuchFileException: /opengrok/data/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz.org_opengrok
Caused by: java.nio.file.NoSuchFileException: /opengrok/data/xref/solaris-userland/components/gnome/libsecret/test/results-32.master.gz.org_opengrok
```
[opengrok-failed-to-move.log.gz](https://github.com/oracle/opengrok/files/6966950/opengrok-failed-to-move.log.gz)

**Comment by vladak** [comment]
I asked @ahornace for help and he took a more direct approach - added a set of debug prints to the `add()` methods:

```patch
Index: opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java b/opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
--- a/opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java	(revision 5ec8ffa72a713acaec59e16e0d9caa82dc92d0c4)
+++ b/opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java	(date 1631676243918)
@@ -75,6 +75,10 @@
  */
 class PendingFileCompleter {
 
+    private static int instanceId;
+
+    private int id;
+
     /**
      * An extension that should be used as the suffix of files for
      * {@link PendingFileRenaming} actions.
@@ -89,6 +93,10 @@
 
     private volatile boolean completing;
 
+    public PendingFileCompleter() {
+        id = instanceId++;
+    }
+
     /**
      * Descending path segment length comparator.
      */
@@ -125,6 +133,7 @@
      * @throws IllegalStateException if {@link #complete()} is running
      */
     public boolean add(PendingFileDeletion e) {
+        System.out.println(id + " Calling add deletion " + System.currentTimeMillis() + " from " + Thread.currentThread().getName());
         if (completing) {
             throw new IllegalStateException("complete() is running");
         }
@@ -140,6 +149,7 @@
      * @throws IllegalStateException if {@link #complete()} is running
      */
     public boolean add(PendingSymlinkage e) {
+        System.out.println(id + " Calling add linkage " + System.currentTimeMillis() + " from " + Thread.currentThread().getName());
         if (completing) {
             throw new IllegalStateException("complete() is running");
         }
@@ -161,6 +171,7 @@
             throw new IllegalStateException("complete() is running");
         }
         synchronized (INSTANCE_LOCK) {
+            System.out.println(id + " Calling add rename " + System.currentTimeMillis() + " from " + Thread.currentThread().getName());
             boolean rc = renames.add(e);
             deletions.remove(new PendingFileDeletion(e.getAbsolutePath()));
             return rc;
```

that shows that the deletion `HashSet` is modified during the parallel phase of indexing:

```
1 Calling add rename 1631676263543 from ForkJoinPool-1-worker-31
1 Calling add rename 1631676263551 from ForkJoinPool-1-worker-25
1 Calling add rename 1631676263551 from ForkJoinPool-1-worker-23
1 Calling add rename 1631676263551 from ForkJoinPool-1-worker-27
1 Calling add rename 1631676263554 from ForkJoinPool-1-worker-5
1 Calling add deletion 1631676263554 from ForkJoinPool-1-worker-31
1 Calling add rename 1631676263561 from ForkJoinPool-1-worker-9
1 Calling add rename 1631676263561 from ForkJoinPool-1-worker-13
1 Calling add rename 1631676263561 from ForkJoinPool-1-worker-3
1 Calling add rename 1631676263561 from ForkJoinPool-1-worker-27
```

This means that the assumption https://github.com/oracle/opengrok/blob/5ec8ffa72a713acaec59e16e0d9caa82dc92d0c4/opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java#L70-L71
does not hold.

Augmenting the debug print in `add(PendingFileDeletion e)` with stack trace print (`org.apache.commons.lang3.StringUtils.join(Thread.currentThread().getStackTrace(), "\n")`) it is possible to pinpoint the culprit in `IndexDatabase#addFile()` that gets executed in parallel: https://github.com/oracle/opengrok/blob/5ec8ffa72a713acaec59e16e0d9caa82dc92d0c4/opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java#L828-L831

Funny how I was looking at this piece in the previous update and missed that.

**Comment by louie0817** [comment]
THANK YOU ADAM AND VLAD
