### ISSUE TITLE
Question: Is the supported languages list up-to-date?

### ISSUE THREAD

**Issue by Gilwe** [oracle/opengrok#3406]
This list is almost from 2 years ago:
https://github.com/oracle/opengrok/wiki/Supported-Languages-and-Formats

I guess that some languages were added in that last 2 years, e.g typescript.

Can someone please update it if any new languages were added?

Thank you.

**Comment by vladak** [comment]
I'd rather replace it with something like #2637.

**Comment by vladak** [comment]
added Typescript to the table.

**Comment by vladak** [comment]
and thanks for noticing !

**Comment by vladak** [comment]
replaced the table with command reference.
