### ISSUE TITLE
Which is the syntax for an indexing duration message?

### ISSUE THREAD

**Issue by jetm** [oracle/opengrok#3407]
This is more of a question than an issue.

Which is the syntax for an indexing duration message?

On [opengrok-sync wiki](https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow#opengrok-sync), there is an example the indexing will take one hour **PT1H**. How could I express the duration will take two hours with thirty minutes? **PT1H30M**?

**Comment by vladak** [comment]
This is the syntax of `java.time.Duration`. The explanation of the syntax can be found on https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-

**Comment by vladak** [comment]
And yes, `PT1H30M` is `Duration.ofMinutes(90).toString()`.

**Comment by jetm** [comment]
@vladak great! Thank you for the information and confirmation. It is useful

**Comment by vladak** [comment]
Verified that API documentation for the messages endpoint https://opengrok.docs.apiary.io/#reference/0/messages/adds-message-to-a-system contains the `Duration` reference.
