### ISSUE TITLE
Adding LDAP authentication to OpenGrok

### ISSUE THREAD

**Issue by baselz324** [oracle/opengrok#3408]
Hello, 
I would like to add to OpenGrok(Tomcat9) LDAP authentication,

I have followed this https://tomcat.apache.org/tomcat-9.0-doc/realm-howto.html 
But it didn't really help me, Is there's anything else I could do?

Best Regards

**Comment by ahornace** [comment]
Hi,
have you looked at the wiki?

https://github.com/oracle/opengrok/wiki/Authorization
https://github.com/oracle/opengrok/wiki/Authorization-plugins
