### ISSUE TITLE
A way to reduce index db size

### ISSUE THREAD

**Issue by dpilin** [oracle/opengrok#3416]
Hello!

Could you please advise is there any way to reduce index db files' size? I was indexing a very large SVN repo this week (each project ~ 200 Gb of size) and stumbled upon high disc space usage. After investigation I found out that for each project indexer had created index db files with almost same size as the project itself.

For example, there is a project directory which is 191 Gb of size, the indexer created a group of files which are 149 Gb of size. Is it an expected behaviour? If so, is there a way to reduce these files' size?

Thanks in advance

**Comment by vladak** [comment]
It really depends on the input data. In general the index size / input data size ratio is way less than 1. Examining the contents of the index might help, e.g. using [Luke](https://github.com/apache/lucene-solr/tree/master/lucene/luke).

**Comment by vladak** [comment]
Also, in case history is enabled the index will contain entries from the history of the repository. That could contribute to the index size significantly if the history is long/rich.

**Comment by dpilin** [comment]
It seems to be the case, we have a large amount of historical data in our repository. Thank you, we'll try tuning the indexer's configuration to avoid not-necessary files indexing.
