### ISSUE TITLE
Question: How to get rid of localhost only api requests

### ISSUE THREAD

**Issue by liamwarfield** [oracle/opengrok#3417]
**Setup**
I have 2 containers for running opengrok, one container for indexing and another for hosting tomcat. They share a volume mount for `.../opengrok/src`, `.../opengrok/data`, `.../opengrok/etc`, `.../opengrok/log`. It seems like the POST request for giving configuration and telling tomcat that indexing is done is only allowed to come from local host.

**Question**
Is there a way to disable the localhost only POST requests?

**Ideal Setup**
have normal GET requests come from in from port 8080 (mapped to port 80 on the host), and POSTs allowed on port 2424 (not exposed to the outside world) from non localhost origin ( `-U ogtomcat:2424/source`)

**Comment by vladak** [comment]
Hi Liam, the proper way to solve this (without bending the API rules which is precarious) is to use an API token. Just set up the web app side with a token (see https://github.com/oracle/opengrok/wiki/Webapp-configuration#configuration-tunables) and then use the token in the indexer container. That said, I need to finish #3399 first.

**Comment by liamwarfield** [comment]
In the end I just ended up using nginx to proxy traffic to localhost.
