### ISSUE TITLE
Indexer lock file not cleared when host rebooted while the indexer is running

### ISSUE THREAD

**Issue by oacnhpkqxjhufwumkkqnshvlmheokqv** [oracle/opengrok#3428]
**Describe the bug**
I'm running OpenGrok in a Docker container, on a virtual machine. If the VM is rebooted while the indexer is running, then the lock file is left in place, so when the VM comes back up and the container starts up, the indexer starts, checks for the lock file, finds it in place, and stops. 

OpenGrok - 1.5.10
OS - Debian GNU/Linux 10 (buster) in the Docker container, CentOS 7 host VM
Tomcat - 9.0.40
JDK - openjdk 11.0.9.1

**To Reproduce**
Let the indexer run
Reboot the host VM

**Expected behavior**
The Docker container startup script checks for an old lock file and deletes it

Thank you!

**Comment by vladak** [comment]
This is going to be solved by #3402 - it removes the lock file. The Python tools used after that change use different locking scheme, at least on Linux, that takes care of such cases.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Thank you so much @vladak! Is there a target release version or date for the PR?

**Comment by vladak** [comment]
The next one :-) Still waiting on review from someone.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
Awesome! I'm looking forward to it. Thank you for all your work on this project, it's moving quickly!

**Comment by vladak** [comment]
The above mentioned PR was merged in, hence closing.
