### ISSUE TITLE
Observing an increased heap growth after upgrading the opengrok version.

### ISSUE THREAD

**Issue by viri** [oracle/opengrok#3430]
I host around 104 projects that are indexed using opengrok and hosted on Apache tomcat.

Prior to the migration, the setup looked like below

```
opengrok on version 0.12.1.2.  

ctags version:
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 20 2015, 09:48:22
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

tomcat version:

Server version: Apache Tomcat/7.0.63
Server built:   Jun 30 2015 08:08:33 UTC
Server number:  7.0.63.0
OS Name:        Linux
OS Version:     2.6.32-754.35.1.el6.x86_64
Architecture:   amd64


java version:

JVM Version:    1.8.0_144-b01
JVM Vendor:     Oracle Corporation

Maximum heap memory allocated to Tomcat server(Xmx)  - 8GB

```

The current setup has the configuration like below:

```
opengrok version: 1.3.16

universal ctags version:

Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 22 2020, 17:47:52
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc


tomcat version:
Server version: Apache Tomcat/9.0.21
Server built:   Jun 4 2019 20:19:36 UTC
Server number:  9.0.21.0
OS Name:        Linux
OS Version:     2.6.32-754.35.1.el6.x86_64
Architecture:   amd64
JVM Version:    11.0.9.1+1-LTS
JVM Vendor:     Azul Systems, Inc.


java version:

openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)

Maximum heap memory allocated to Tomcat server(Xmx)  - 25GB

```
I believe the most significant change between the versions could be the suggester feature that is documented here:

https://github.com/oracle/opengrok/wiki/Suggester

What I noticed is that the heap memory requirement after the upgrade has significantly gone up.  I was alerted recently of an issue where the tomcat server was not responding, and I noticed that the allocated maximum heap size of 25GB was exhausted. 

So I took a heap dump on the tomcat process and generated a leak suspects report looking for potential memory leaks or to see if it genuinely needed more memory. 

From the report,  the largest objects are attributed to `org.opengrok.suggest.SuggesterProjectData` instances.

![image](https://user-images.githubusercontent.com/2963954/108884754-cd61b980-75bb-11eb-8d1c-39f8ad4701a0.png)

However, the memory analyzer doesn't seem to indicate that there are any leaks. 

I was looking for what `org.opengrok.suggest.SuggesterProjectData` represents and from the link below I see that it holds the indexed data for a given project - https://github.com/oracle/opengrok/blob/748d69c7ce0c716a7535e75a3134190445030208/suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java

Would this mean that for the number of projects I have hosted on the server, the memory would have to be allocated proportionally to accommodate these objects into the memory?

Would there be some kind of eviction mechanism on these objects that can be triggered based on the least used project with a certain timeout that will help with the memory that is required to keep the server alive?

I am attaching the generated leak suspects report, which I took from the heap snapshot of the tomcat JVM when the server became unresponsive.  If there is any specific information you needed, please do let me know so I can look into it.

Thanks!

[heap_Leak_Suspects.zip](https://github.com/oracle/opengrok/files/6031339/heap_Leak_Suspects.zip)

**Comment by ahornace** [comment]
We are using WFST in-memory data structure for quick prefix suggestions. It is quite memory efficient, e.g. storing ca. 9 million terms (Linux repo) takes only ca. 60MB. However, there is one WFST for each term type (full, definition, ...) times the number of projects. So this can theoretically cause the usage that you see if your projects are big enough.

Currently, there are no optimizations for this case. Our long term plan is to distribute OpenGrok to multiple hosts for big deployments but this not on our roadmap in the near future.

> Would there be some kind of eviction mechanism on these objects that can be triggered based on the least used project with a certain timeout that will help with the memory that is required to keep the server alive?

There is no such feature in OpenGrok yet and I'm not sure we would like to go down that road. It would require some discussion if it's feasible.

What you can do is to disable the suggester functionality entirely. You can also specify the subset of projects for which suggester should be enabled or you can disable most popular completion which could improve the memory usage a bit (depends on OpenGrok usage).

Do you have any other suggestions on what we could do to improve it?

Thanks.

**Comment by vladak** [comment]
> Would this mean that for the number of projects I have hosted on the server, the memory would have to be allocated proportionally to accommodate these objects into the memory?

Yep. From https://github.com/oracle/opengrok/wiki/Tuning-for-large-code-bases#web-application :

> For Suggester data, it should be sufficient to compute the sum of lengths of all *.wfst files under the data root and bump the heap limit by that value.

**Comment by vladak** [comment]
Also, #3378 jumps to mind.

**Comment by vladak** [comment]
In suml, the heap size requirements have indeed shot up due to the added suggester feature.

**Comment by viri** [comment]
Adam, Vladimir thank you for the insights into this.  

Given the suggester data is large for certain codebases, I am thinking to distribute these out to multiple tomcat instances and use a proxy to route the requests based on the application context.  That way if one tomcat server would go down or become unresponsive, I would still have other codebases up for use before I can resuscitate the downed service.  Plus the memory required to keep each tomcat server alive would be reduced greatly. 

The idea of having a separate process manage the suggester data works pretty well for cases like here for example, where the functionality can be offloaded to a different process altogether and thus keeping the tomcat server lightweight.  

I will close this one out for now.
