### ISSUE TITLE
Question : what is scopes?

### ISSUE THREAD

**Issue by baselz324** [oracle/opengrok#3457]
![image](https://user-images.githubusercontent.com/77238449/110440499-65ce6280-80c1-11eb-888b-8cc13fe5af4a.png)
it only opens this window 
![image](https://user-images.githubusercontent.com/77238449/110440523-6d8e0700-80c1-11eb-93b9-e69969d91753.png)

**Comment by vladak** [comment]
Shows the function you're in. Depends on whether function definitions are recognized for given file.
