### ISSUE TITLE
Missing History, Annotate when running in Docker

### ISSUE THREAD

**Issue by soleen** [oracle/opengrok#3462]
I am trying to switch to docker version of opengrok, and encountered this issue with opengrok/docker:latest.

I am starting docker like this:
```
sudo docker run -d							\
	-e SYNC_PERIOD_MINUTES="600"					\
	-e INDEXER_FLAGS="-H -P -S -G --renamedHistory off"		\
	-p 443:8443							\
	-p 8080:8080							\
	-v /etc/letsencrypt/live/soleen.com/privkey.pem:/privkey.pem	\
	-v /etc/letsencrypt/live/soleen.com/cert.pem:/cert.pem		\
	-v /etc/letsencrypt/live/soleen.com/chain.pem:/chain.pem 	\
	-v /home/soleen/opengrok/src/:/opengrok/src			\
	-v /home/soleen/opengrok/data/:/opengrok/data			\
	-v /home/soleen/opengrok/10.server.xml:/usr/local/tomcat/conf/server.xml	\
	opengrok/docker:latest
```

The only file in docker that is modified is server.xml, which is only to enable https access:

```
soleen ~/opengrok$ diff 10.server.xml 10.server.xml.bk 
85a86
>     <!--
89,91c90
<             <Certificate certificateKeyFile="/privkey.pem"
<                          certificateFile="/cert.pem"
<                          certificateChainFile="/chain.pem"
---
>             <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
94a94
>     -->
```

The directory "/home/soleen/opengrok/src/" contains several git repositires (they are cloned from https, so not authorisations issues for root access from container).

When I go to opengrok page, I see History, Annotate disabled. Any suggestion what is missing, or what should I check?

**Comment by vladak** [comment]
The indexer logs should tell you however they are only displayed if the indexing fails. Need to introduce a way how to display them.

Also, `INDEXER_FLAGS` no longer works.

**Comment by soleen** [comment]
Thank you for your reply, I realized, that INDEXER_FLAGS is gone by reading through resent commits after posting my bug report, and I already replaced it with INDEXER_OPT, unfortunatly, history, and annodate are still missing.

There is no historycache directory created:

```
~/opengrok/data$ ls 
index  suggester  timestamp  xref
```
here logs: [logs.txt](https://github.com/oracle/opengrok/files/6110953/logs.txt)

**Comment by vladak** [comment]
Here's the relevant piece:
```
2021-03-09T18:22:24.405858432Z INFO: Indexer options: [-R, /tmp/tmp2sdq6hj5, -r, dirbased, -G, -m, 256, --leadingWildCards, on, -c, /usr/local/bin/ctags, -U, http://localhost:8080/, -H, vmm-fast-restart-qemu, -H, -P, -S, -G, --renamedHistory, off]
2021-03-09T18:22:24.405890632Z The path /-H does not correspond to a project
2021-03-09T18:22:24.405894832Z The path /-P does not correspond to a project
2021-03-09T18:22:24.405898032Z The path /-S does not correspond to a project
2021-03-09T18:22:24.405901332Z The path /-G does not correspond to a project
2021-03-09T18:22:24.405904532Z The path /--renamedHistory does not correspond to a project
2021-03-09T18:22:24.405907732Z The path /off does not correspond to a project
```
The options following the name of the project are extraneous. Running without the `INDEXER_OPT` will solve this for now.

**Comment by soleen** [comment]
Hm, yes; what you found is a bug, but I removed INDEXER_OPT, deleted everything from data, and re-created the container, and still no History or Annodate for a small git repo.

Is this relavent?
2021-03-09T20:29:55.647714402Z 09-Mar-2021 20:29:55.640 WARNING [ForkJoinPool-1-worker-3] org.opengrok.suggest.SuggesterProjectData.initFields Fields [defs, path, hist, refs, type, full] will be ignored because they were not found in index directory MMapDirectory@/opengrok/data/index/kvm-hello-world lockFactory=org.apache.lucene.store.NativeFSLockFactory@16eac477

**Comment by vladak** [comment]
The suggester warning is not relevant. What does the indexer log say now ?

**Comment by soleen** [comment]
Here is new log:
[logs.txt](https://github.com/oracle/opengrok/files/6111539/logs.txt)

**Comment by vladak** [comment]
```
2021-03-09T20:46:53.185057466Z Output from 'opengrok-mirror -I -U http://localhost:8080/ linux':
2021-03-09T20:46:53.185060666Z No repositories for project linux

...

2021-03-09T20:46:53.184192960Z INFO: Creating historycache for 0 repositories
```
is the symptom. This means that the web app does not know about the repositories.

**Comment by vladak** [comment]
This means that the initial project add (that also adds repositories) did not discover the repositories for some reason. Could you remove the configuration file `/opengrok/etc/configuration.xml` and restart the container ?

**Comment by soleen** [comment]
Done, here is the content of new log: [logs.txt](https://github.com/oracle/opengrok/files/6111808/logs.txt)

This looks suspicious: 
```
 126 2021-03-09T20:46:53.179452330Z Output from 'opengrok-mirror -I -U http://localhost:8080/ vmm-fast-restart-qemu':
 127 2021-03-09T20:46:53.184073560Z No repositories for project vmm-fast-restart-qemu
```


The diff between original configuration.xml vs. the re-created one after restart of container:
```
soleen ~/opengrok$ diff bk.configuration.xml src/configuration.xml 
86d85
<   <void id="Boolean0" method="isAllowLeadingWildcard"/>
92c91
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
95c94
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
109c108
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
112c111
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
126c125
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
129c128
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
143c142
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
146c145
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
160c159
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
163c162
<       <object idref="Boolean0"/>
---
>       <boolean>true</boolean>
175c174
<    <object idref="Boolean0"/>
---
>    <boolean>true</boolean>

```

**Comment by soleen** [comment]
May be there is some command that I could run inside container to see how repositories are discovered?

**Comment by vladak** [comment]
It seems to me that the initial project addition does not discover the repositories. Now tracked by #3465.
