### ISSUE TITLE
indexer directory log messages should state the directory more clearly

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3464]
When indexing in project less configuration (in Docker) I noticed these log entries:
```
opengrok-dev | INFO: Starting traversal of directory
...
opengrok-dev | INFO: Starting indexing of directory
```
In a setup with projects enabled this looks like this:
```
opengrok-dev | INFO: Starting traversal of directory /foo
...
opengrok-dev | INFO: Starting indexing of directory /foo
```
The directory in the log message is determined to be relative to the source root. In case of project less setup this becomes empty. Either the message in project less setup should be adjusted to say something like `... directory '/'` or `... source root directory`.

Also, the directory should be perhaps enclosed in single quotes.

**Comment by sushant3kumar** [comment]
@vladak can you please elaborate on what do you mean by project less setup and how to replicate it. Thanks

**Comment by vladak** [comment]
> @vladak can you please elaborate on what do you mean by project less setup and how to replicate it. Thanks

means projects are disabled. This is what happens by default if you run the indexer without the -P option.

**Comment by Souvik-223** [comment]
@vladak Can you please assign this issue to me ? i would like to work on it.

**Comment by vladak** [comment]
This is addressed in the code by various changes, hence closing.
