### ISSUE TITLE
mvnw test failing at OpenGrok Indexer 

### ISSUE THREAD

**Issue by adityamathur97** [oracle/opengrok#3467]
I have tried to set up project as told in building instructions and tried to run the mvnw test command and ended with the error shown in the picture. I am using windows 10. Any help is appreciated.

![image](https://user-images.githubusercontent.com/15976450/110744871-09259180-8200-11eb-940f-e39ec66ba78f.png)

**Comment by vladak** [comment]
You need to have Subversion installed, see https://github.com/oracle/opengrok/wiki/Developer-intro
