### ISSUE TITLE
History missing in Docker with Projects and repo

### ISSUE THREAD

**Issue by jwehler** [oracle/opengrok#3474]
Running the latest version, 1.6.3, of Opengrok in Docker. 

I have a repo based project containing .git projects at various depths under it. I found the git projects greater than 4 levels deep were not showing history or being reflected in the main page under the corresponding project.

I added _INDEXER_OPT="--depth 6"_ in my options, but this did not help. I removed configuration.xml to force recreation and this did not help either. Next I wiped all of the data, same result.

However, once I manually edited start.py's new create_bare_config function in the container to also honor the depth option I supplied for the indexer_options for this --noIndex pass, this **fixed** the problem (after removing configuration.xml to force create_bare_config to run of course). Now the full project content appears on the main page and I have history options for those projects that were deeper than whatever the default is (4 it appeared).

I see there were several similar issues recently in https://github.com/oracle/opengrok/issues/3462 and https://github.com/oracle/opengrok/issues/3465 though I'm not sure if it is exactly the same.

**Comment by vladak** [comment]
Thanks for the diagnosis. The`create_bare_config` needs to honor `INDEXER_OPT`.
