### ISSUE TITLE
Minimal OpenGrok version to use Tomcat 10?

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#3477]
Hello,

What is the minimal version of OpenGrok to use with Tomcat 10?

**Comment by vladak** [comment]
1.6.0 is the first release to require Tomcat 10. Normally the minor version is bumped only for major Lucene upgrades (sic!) however in this case we wanted to signify this change.

As for older releases I am not sure whether it is possible to deploy them to Tomcat 10.

**Comment by ChristopheBordieu** [comment]
Ok. Thanks!

> As for older releases I am not sure whether it is possible to deploy them to Tomcat 10.

Nop. Tomcat 10 failed starting OG 1.5.11.
