### ISSUE TITLE
Question - How to index new project 

### ISSUE THREAD

**Issue by baselz324** [oracle/opengrok#3480]
Hey, I have add a new project under src folder and would like to index
`java -Djava.util.logging.config.file=/opengrok/etc/logging.properties -jar /opengrok/dist/lib/opengrok.jar --ctags /usr/local/bin/ctags -s /opengrok/src -d /opengrok/data -H -P -G -W /opengrok/etc/configuration.xml -U http://localhost:8080/source/  VERSION_NAME`

not working

**Comment by vladak** [comment]
Seems like you are trying per project indexing. If that's the case see https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow

Basically, you need to add the project first. Avoid writing the configuration to a file when indexing single project. Instead, get fresh configuration from the web app and use it as [read-only configuration](https://github.com/oracle/opengrok/wiki/Read-only-configuration). Also, you might want to have separate logging settings for the project.
