### ISSUE TITLE
How launch unit test single in intellij Idea

### ISSUE THREAD

**Issue by elkin5** [oracle/opengrok#3493]
I need to launch this ```testScopeAnalyzer()``` unit test, but I can't for this error 
![Captura de Pantalla 2021-03-23 a la(s) 5 50 02 p  m](https://user-images.githubusercontent.com/4118198/112229615-4ecf5a80-8c01-11eb-89ee-8472736e8a5a.png)

**Comment by ahornace** [comment]
I believe it's still due to https://github.com/oracle/opengrok/issues/2244 and that it can be resolved by running `ant -post-compile-test` in the indexer subproject. I'll take a look and provide you with exact steps soon :)

**Comment by ahornace** [comment]
Hmm, so it seems that ant does not allow to run targets starting with `-` from the command line. You can try modifying the `build.xml` by removing the leading `-` from the target name and running `ant post-compile-test`.

Alternatively, just running `mvn package` should be sufficient as it will run the `-post-compile-test` target.

@vladak how do you go around this problem?

**Comment by elkin5** [comment]
Thanks!

**Comment by ahornace** [comment]
You are welcome! :) What approach did you use in the end?

**Comment by vladak** [comment]
> @vladak how do you go around this problem?

This fails because the input bundle is not created. It needs the Subversion to perform the repository creation. What I usually do is to run `mvn verify` by hand and terminate it once it starts executing the tests and then run the unit tests from IDEA.

**Comment by elkin5** [comment]
> You are welcome! :) What approach did you use in the end?

the first solve, running ```ant post-compile-test```
