### ISSUE TITLE
indexing with https

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3517]
Hey, how could I index with https website?
I though to change it into this, looks like it's doing some issues
`java     -Djava.util.logging.config.file=/opengrok/etc/logging.properties     -jar /opengrok/dist/lib/opengrok.jar     --ctags  /usr/local/bin/ctags     -s /opengrok/src -d /opengrok/data -H -P -S -G     -W /opengrok/etc/configuration.xml -U https://opengrok02:8443/source/`

the change in server.xml is 
`<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true"
        keystoreFile="jks" keystorePass="tomcat9"
               maxThreads="150" scheme="https" secure="true"
               clientAuth="false" sslProtocol="TLS" keyalias="tomca"/>`

**Comment by vladak** [comment]
Looks like you are trying to run the indexer on different machine than the web app is running on. If that's the case, see https://github.com/oracle/opengrok/wiki/Web-services#authenticationauthorization

**Comment by chkp-baselz** [comment]
@vladak I don't think this is the case, indexing a specific version works good
`java -Djava.util.logging.config.file=/opengrok/etc/logging.properties -jar /opengrok/dist/lib/opengrok.jar --ctags /usr/local/bin/ctags -s /opengrok/src -d /opengrok/data -H -P -G -R /opengrok/etc/configuration.xml -U  https://opengrok02:8443/source/ VERSION`

**Comment by chkp-baselz** [comment]
indexing with localhost gives this error
![image](https://user-images.githubusercontent.com/77238449/113168344-3ee0f780-924d-11eb-9d18-0d1a09edac3e.png)

also the opengrok on the same machine

**Comment by vladak** [comment]
Yes, the -U option has to have a URL where the web app is reachable.

**Comment by chkp-baselz** [comment]
@vladak so I didn't understand how to fix this?

**Comment by vladak** [comment]
Basically, the web app has to be running on the URI you are supplying with the `-U` indexer option. For example, if you run the indexer with `-U http://localhost:8080/source`, the web app has to be accepting TCP connections on port 8080 on `localhost` via plain HTTP.

If you specify non-localhost URI then you need to use the Bearer token (see the link above) so that the API requests issued by the indexer can go through.

**Comment by chkp-baselz** [comment]
@vladak okay thank you, on a diffrent topic, should src folder contain gz files or only data? the indexer looks like he left gz files in src folder is that fine or should I remove them?

**Comment by vladak** [comment]
I don't think the indexer writes to the source root directory at all.

**Comment by chkp-baselz** [comment]
@vladak I don't know how but the src folder has gz files, so I need to delete them right?

**Comment by vladak** [comment]
My advice would be to carefully inspect these files first (names, time stamps, contents). Again, the indexer should not create anything under the source root. In fact, it should run perfectly fine even if the source root is read only.
