### ISSUE TITLE
Interpret .cu/.cuh files as .cxx files in opengrok for syntax highlighting

### ISSUE THREAD

**Issue by saltuser16** [oracle/opengrok#3518]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saltuser16** [comment]
Please add CU, CUH to SUFFIXES in CxxAnalyzerFactory.java 

https://github.com/oracle/opengrok/blob/34eac45c074573f8b090012e6c2fb3b0f72cc381/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/c/CxxAnalyzerFactory.java

**Comment by vladak** [comment]
Are these "standard" suffixes ? If yes, care to submit a PR ?

**Comment by saltuser16** [comment]
They are for CUDA code files and are widely used now.
