### ISSUE TITLE
Failed to get xref file

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3523]
Hey,
![image](https://user-images.githubusercontent.com/77238449/113573407-c601e700-9622-11eb-9a80-f29247e056ff.png)

 I had this issue before([3444](https://github.com/oracle/opengrok/issues/3444)) and fixed it by removing the gz files from the data folder and re-indexing the version, now I have only gz.org_opengrok extension file, no gz file, **removing it and touching the src file re-index won't solve the problem**
![image](https://user-images.githubusercontent.com/77238449/113573423-d0bc7c00-9622-11eb-892c-85859838c40f.png)

**Comment by vladak** [comment]
This is indeed different than #3444 where the xref file was present but stale. Here the indexer did not finish the move from temporary location to final destination.

As a workaround you can try moving the `globals.cc.gz.org_opengrok` to `globals.cc.gz` and touching it.

**Comment by chkp-baselz** [comment]
@vladak it worked, thank you
