### ISSUE TITLE
make it possible to use read-only configuration again in Docker

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3531]
As mentioned in https://github.com/oracle/opengrok/issues/3522#issuecomment-815081302 it should be possible to pass read-only configuration to Docker. This got broken with the transition to the `sync.py`. It should still be possible to use it when projects are disabled.

**Comment by Teriand** [comment]
I use this command to use RO config:
```OG_DOCKER="docker exec opengrok opengrok-indexer  -C -a /opengrok/lib/opengrok.jar -- -c /usr/local/bin/ctags -s /opengrok/src/ -d /opengrok/data -H -P -S -G -W /opengrok/etc/configuration.xml -U http://localhost:8080/ -R /opengrok/etc/readonly_configuration.xml"```
