### ISSUE TITLE
Question, what files are readable by OpenGrok

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3532]
Or what files are not, for example, gif/png/jpeg... I wan't to prevent copying these files to save space

**Comment by chkp-baselz** [comment]
@vladak thank you for your fast answer, I don't know how to run indexer could you assist? I index using the command java and running opengrok.jar file

**Comment by vladak** [comment]
see https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok#step3---indexing

**Comment by chkp-baselz** [comment]
@vladak it dosen't work for me tho I have already installed the tools
`opengrok-indexer
bash: opengrok-indexer: command not found...
`

**Comment by vladak** [comment]
just run the indexer directly: `java -jar opengrok.jar --help ...`

**Comment by chkp-baselz** [comment]
@vladak great working thank you, what do magic matches and magic strings mean?

**Comment by vladak** [comment]
They help with assignment of given file to an analyzer by matching part of the file contents. For example, some Java classes begin with 4 bytes `ca fe ba be` (hexadecimal).

**Comment by chkp-baselz** [comment]
okay thank you
