### ISSUE TITLE
Add manual reindex trigger in Docker

### ISSUE THREAD

**Issue by jwehler** [oracle/opengrok#3535]
Prior to the conversion to python scripts for the Docker image, it was trivial to force trigger a re-index by just calling index.sh while the container was already running:
`docker exec -it opengrok /scripts/index.sh
`

This allowed setting the periodic sync time to something much longer (2x per day, for example) and then you could update the code manually out-of-band and then trigger the re-index operation. Useful when something important is merged and you want it to be reflected in OG asap.

I don't see an obvious way to do the same thing now, aside from a stop/start of the container which is not ideal.

**Comment by vladak** [comment]
To fix this I'd like to avoid running a command using `docker exec`. Maybe introduce API endpoint via Flask ? (the `start.py` is running permanently anyway)

**Comment by dhose** [comment]
Didn't know Flask was used. But yes, that sounds like a good solution. :)

**Comment by vladak** [comment]
It's not used yet :-) It would mean exposing yet another port for the container.

**Comment by dhose** [comment]
I see, but I'm fine with exposing another port. It's always possible to bind it to localhost...
