### ISSUE TITLE
Rename Opengrok Project by restoring contents

### ISSUE THREAD

**Issue by maestropandy** [oracle/opengrok#3548]
I would like to rename existing repo and keep their contents after rename. I have included new name in re-index script and performed index. It has created a new repo without their contents ? Is there way to achieve that ?

opengrok version: 1.0-v3

**Comment by vladak** [comment]
Do you mean a project ? Do you run with projects enabled ?

**Comment by maestropandy** [comment]
Yes, I want to change Project named A to A_old.  May I know how to achieve ?

**Comment by vladak** [comment]
The process would be something like this:
1. move the project source and data to the new location
  - assuming Unix shell and `/opengrok/data` is data root and `/opengrok/src` is source root:
```
  for dir in /opengrok/data/{xref,historycache,index,suggester} /opengrok/src; do mv "$dir/A" "$dir/A_old"; done
```
2. remove the project from the configuration (assuming the web app is running on http://localhost:8080/source)
  - use the API endpoint like so: `curl -X DELETE http://localhost:8080/source/api/v1/projects/A`
    - next to removing project metadata, this will try to remove the sources and data for this project however they were moved already in the previous step; should be fine, might produce some warnings.
3. add the new project
  - use the API endpoint like so: `curl -H 'Content-Type: text/plain' -X POST http://localhost:8080/source/api/v1/projects/A_old`

I have not tested this.

Not sure the above mentioned API endpoints are present in 1.0. If they are not, you'd have to edit the XML configuration by hand (backup first) and restart the web application.

Also, I'd recommend to try this process on staging service instance first.
