### ISSUE TITLE
Opengrok in docker fails to index if project is versioned in git

### ISSUE THREAD

**Issue by Lazaruspl** [oracle/opengrok#3565]
There is something wrong with new opengrok image for docker. Current version I believe is 1.7.2.

This works:
```
mkdir /tmp/test1
cd /tmp/test1/
mkdir foo
echo bar > foo/bar.cpp
docker run -d --name opengrokTest1 -v /tmp/test1/:/opengrok/src -p 9876:8080 opengrok/docker:latest
```

This doesn't work:
```
cd /tmp/
cp -R test1/ test2/
cd test2/
git init
git add foo/
git commit -m "foo commit"
docker run -d --name opengrokTest2 -v /tmp/test2/:/opengrok/src -p 9877:8080 opengrok/docker:latest
```

Basically the only difference is that in second case there is git directory.
By works and doesn't work I mean this:
![opengrok](https://user-images.githubusercontent.com/918385/116557967-40aae300-a8ff-11eb-9c9d-4f70adb22b73.png)

**Comment by Lazaruspl** [comment]
If instead of: **opengrok/docker:latest**
I use: **opengrok/docker:1.2**
Then it works, so this is some degrade which was introduced in some update.

**Comment by vladak** [comment]
A project has to be a sub-directory of source root. With `-v /tmp/test2/:/opengrok/src` the Git repository becomes source root so it is not detected as a project.

**Comment by vladak** [comment]
This is visible on the console as:
```
Adding project .git
Sync starting
29-Apr-2021 14:37:56.062 INFO [ForkJoinPool.commonPool-worker-3] org.opengrok.suggest.Suggester.rebuild Rebuilding the following suggesters: [.git]
29-Apr-2021 14:37:56.101 WARNING [ForkJoinPool-2-worker-3] org.opengrok.suggest.SuggesterProjectData.initFields Fields [defs, path, hist, refs, type, full] will be ignored because they were not found in index directory MMapDirectory@/opengrok/data/index/.git lockFactory=org.apache.lucene.store.NativeFSLockFactory@7d1e75f7
29-Apr-2021 14:37:56.120 INFO [ForkJoinPool.commonPool-worker-3] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggesters for [.git] were successfully rebuilt (took 0 seconds)
29-Apr-2021 14:37:56.215 INFO [ForkJoinPool.commonPool-worker-3] org.opengrok.suggest.Suggester.rebuild Rebuilding the following suggesters: [.git]
Output from 'opengrok-mirror -I -U http://localhost:8080/ .git':
No repositories for project .git

Output from 'opengrok-reindex-project --printoutput --jar /opengrok/lib/opengrok.jar -U http://localhost:8080/ -P .git -- -r dirbased -G -m 256 --leadingWildCards on -c /usr/local/bin/ctags -U http://localhost:8080/ -H .git':
...
```
The solution is to move the `/tmp/test2` directory underneath different directory and use that as source root.

**Comment by vladak** [comment]
OpenGrok 1.5 still had the main Docker program implemented as a shell script. It ran the indexer with -P so there should not be any change in how projects are discovered. I just tried that and it did not detect any projects:
```
$ docker exec  opengrokTest1.5 curl --silent http://localhost:8080/api/v1/projects | jq
[]
```
