### ISSUE TITLE
Support for indexing bare GIT repositories.

### ISSUE THREAD

**Issue by systemmonkey42** [oracle/opengrok#3573]
Hi,

I need to index a git server containing many repositories, however all repositories are bare, as you would expect on the server.

Can OpenGrok index bare repositories?  All my reading so far says I need to check out each repostory into a directory per branch prior to indexing.  Is that correct?

Thanks

**Comment by vladak** [comment]
Currently it cannot. Yes, you need to checkout each and every branch so that it has files on disk.
