### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3590]
Hey, 

I faced an issue in searching, it can be found in files, 
I'm searching for example "wgetTls1_2Client" it can be found in file and project, 
![image](https://user-images.githubusercontent.com/77238449/118685157-86c2da80-b80b-11eb-95f2-a7ebde20f07b.png)

But when I search it does not found it 
![image](https://user-images.githubusercontent.com/77238449/118685277-a35f1280-b80b-11eb-8c08-487c9d18fdfc.png)

The file is indexed

**Comment by vladak** [comment]
Does the search produce any results for other terms in the same file ?

**Comment by chkp-baselz** [comment]
@vladak looks not, tried with a couple searches

**Comment by ahornace** [comment]
> @vladak looks not, tried with a couple searches

In that case the index is probably not in sync with the actual codebase.  Can you retry running the indexer?

**Comment by chkp-baselz** [comment]
@ahornace Hey Adam, I have tried, it didn't help

**Comment by ahornace** [comment]
Can you check if the zipped file `{opengrok_data_dir}/xref/{path_to_file}` contains the term ? Maybe the indexer was rerun with different data directory or did not finish properly.

Theoretically, you might try to search for `"wgetTls1_2Client"` with the quotes, maybe the file was not interpreted as Java and `_` is considered to be a term delimiter but I don't think this is the case.

As a last resort, you might try to reindex from scratch. If the problem still persists, then I'll try to replicate :)

**Comment by chkp-baselz** [comment]
@ahornace I run index from scratch daily using this command
`java     -Djava.util.logging.config.file=/opengrok/etc/logging.properties     -jar /opengrok/dist/lib/opengrok.jar     --ctags  /usr/local/bin/ctags     -s /opengrok/src -d /opengrok/data -H -P -S -G     -W /opengrok/etc/configuration.xml -U  URL`

I have checked if the` {opengrok_data_dir}/xref/{path_to_file}.gz` file contains the term, it does
![image](https://user-images.githubusercontent.com/77238449/118696861-626cfb00-b817-11eb-8aad-5e01a63d1821.png)

about searching with the quotes, I have tried also, it failed

**Comment by ahornace** [comment]
What version are you on? Does search work for some projects/files or not at all? Did it work before? Do you see anything weird in the logs?

**Comment by chkp-baselz** [comment]
@ahornace version 1-5-11
Search works very well for other files/projects
Nothing weird in indexing logs, should I check any other log?

**Comment by ahornace** [comment]
It worked fine on my machine so there does not seem to be anything wrong with the code snippet you provided. 

You could check all the terms in your index by using Luke or https://github.com/javasoze/clue - if the term is missing (which I suspect), then indexer did not index it properly but to find out why is next to impossible without any error from the logs.

So all the help I can provide now is to suggest to update to the newest version (it has newer lucene which might have some bugfixes) or reindex from scratch.

Please reopen with a reproducible case.

**Comment by chkp-baselz** [comment]
@ahornace what do you reindex from scratch?

**Comment by ahornace** [comment]
`rm -rf {opengrok_data}` - if you have too many projects and it would take too long, then try to remove only the index data for that problematic project

**Comment by chkp-baselz** [comment]
@ahornace to rm only "/opengrok/data/index/PROJECT" or also "/opengrok/data/xref/PROJECT"?

**Comment by ahornace** [comment]
Just `/opengrok/data/index/PROJECT` should be enough :)

**Comment by chkp-baselz** [comment]
@ahornace FYI, that fixed it
a million thnx man :)

**Comment by ahornace** [comment]
Awesome, you are welcome!
