### ISSUE TITLE
What exactly does --webappCtags do?

### ISSUE THREAD

**Issue by liamwarfield** [oracle/opengrok#3591]
When I look at the help it just gives me:
```
  --webappCtags on|off
        Web application should run ctags when necessary. Default is off.
```
I tried searching online, but I could not find a description that was more specific. What is this setting and why/when would you use this setting?

**Comment by ahornace** [comment]
The only places that it's used at the moment is during the "on-the-fly" xref generation.

Usually, OpenGrok creates these files during indexing. However, if it's not present (e.g. it was deleted from data directory), then OpenGrok will try to generate it when `--webappCtags` is `on`.

**Comment by vladak** [comment]
was documented here: https://github.com/oracle/opengrok/wiki/Webapp-configuration#configuration-tunables

**Comment by vladak** [comment]
> Usually, OpenGrok creates these files during indexing. However, if it's not present (e.g. it was deleted from data directory), then OpenGrok will execute ctags to get the definitions when `--webappCtags` is `on`.

The other case when xref is generated on the fly is when it is stale (i.e. when its time stamp is older than the time stamp of the pre image file).
