### ISSUE TITLE
History and Annotate not visible in some paths/repos

### ISSUE THREAD

**Issue by oliver-mx** [oracle/opengrok#3593]
Hi everyone,

I've been working with Opengrok the past few months and everything was looking really good, but suddenly I discovered that some of the files were not showing the "History" and "Annotate" links (They are grayed out) in some specific paths, but in others, they seem to work perfectly.

My code is made of multiple git repositories in different levels, lets say I have the following structure;
```
-folder1\
`-a\
`-b\
   `.git
   `file1.txt
-folder2\
`....
-folder3\
`-a\
`-b\
   `-c
     `d
        `-.git
        `-file6.txt
     `-e    <- 'e' it's at the same level than 'd'
       `-f
          `.git
          `filez.txt
```

The problem here is that Opengrok seems to not be able to detect that the directory 'f' is under version control, or at least not at all, but it detects that 'd' is. 

Let me fully explain the problem in the following lines along with the command that I use to index the project.
Command used to index the project:
```
opengrok-indexer -a /var/opengrok/dist/lib/opengrok.jar -- \
                        --depth 8 \
                        --optimize off \
                        --progress \
                        -c /usr/local/bin/ctags \
                        -U $OPENGROK_URL \
                        -R /opengrok/etc/readonly_configuration.xml \
                        -H -G $PROJECT_NAME \
                        $PROJECT_NAME
```

When I run this command, If I check the logs that the command generates one of the things to highlight is:

> INFO: Creating historycache for 0 repositories

Apparently Opengrok is not generating any history for any of the repos inside my project, but if I go to the web app I'm able to see the "History" and "Annotate" links without any problem, or at least that's what I thought at the beginning, because now I see that they are not generated for all the repos.

I've been trying to work around this issue changing the indexing command and so far I would like to mention the following two alternatives:

1.-
``` 
opengrok-indexer -a /var/opengrok/dist/lib/opengrok.jar -- \
                        --depth 8 \
                        --optimize off \
                        --progress \
                        -c /usr/local/bin/ctags \
                        -U $OPENGROK_URL \
                        -R /opengrok/etc/readonly_configuration.xml \
                        -H -P -S $PROJECT_NAME \
                        $PROJECT_NAME
```

2.-
```
curl -s -X GET $OPENGROK_URL/api/v1/configuration -o fresh_config.xml
       opengrok-indexer -a /var/opengrok/dist/lib/opengrok.jar -- \
                        --depth 10 \
                        --optimize off \
                        --progress \
                        -c /usr/local/bin/ctags \
                        -U $OPENGROK_URL \
                        -R fresh_config.xml \
                        -H -G $PROJECT_NAME \
                        $PROJECT_NAME 
```

Basically in number 1, I added -S flag to scan all the repos in my project, with this I was not only able to see the following:

> INFO: Done scanning for repositories, found 207 repositories

but I also verified that the history was created for the project I was looking for (directory 'f'). I checked under '/opengrok/data/historycache/$PROJECT_NAME/folder3/b/e/f' and I was able to find some *.gz files, which I supposed contain the history generated.
Unfortunately when I go to the configuration.xml there is no entry for that path, only for some others (and of course, I can't see it either on the web app)

In Number 2, the index logs tells me right away what project will be taken to generate the history

> INFO: Generating history cache for repositories: <repo_path>, <repo_path>, <repo_path> .....

But the project 'f' is not in that list and it dosen't generate the history under /opengrok/data either.

I would appreciate all the help you could give me, thank you so much!

Opengrok version: 1.7.2
Tomcat version: 10.0.5
Git version: 2.17.1

**Comment by ahornace** [comment]
For option 1 drop the project names at the end of the command. If you provide the project name, then the indexer thinks it's a partial reindex and will only notify the webapp that it should refresh the specified project but it does basically nothing when that project does not exist in the first place. (it does not update the configuration)

Maybe we should return a different HTTP status for such a scenario - e.g. `404` and display a warning in the indexer.

For option 2, @vladak will be a better person to answer. I am not even sure the repositories should be found without the `-S`.

**Comment by oliver-mx** [comment]
> For option 1, drop the project names at the end of the command. If you provide the project name, then the indexer thinks it's a partial reindex and will only notify the webapp that it should refresh the specified project but it does basically nothing when that project does not exist in the first place. (it does not update the configuration)
> 
> Maybe we should return a different HTTP status for such a scenario - e.g. `404` and display a warning in the indexer.
> 
> For option 2, @vladak will be a better person to answer. I am not even sure the repositories should be found without the `-S` or `--repository` options.

Hi ahornace, 
Thank you for your answer.

About dropping out the project names at the end of the command, the documentation shows it in a very similar way on the "Per-project-management-and-workflow" page.
```
curl -s -X GET http://localhost:8080/source/api/v1/configuration -o fresh_config.xml
opengrok-indexer -a /opengrok/dist/lib/opengrok.jar -- \
    -c /usr/local/bin/ctags \
    -U 'http://localhost:8080/source' \
    -o /opengrok/etc/ctags.config \
    -R fresh_config.xml
    -H PROJECT_NAME \
    PROJECT_NAME
```
https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow

I'll run the command anyways to see the output.
- Thank you

**Comment by vladak** [comment]
So before I go into answering: seems like you are trying to follow per project management, correct ?

**Comment by oliver-mx** [comment]
Hi vladak,

yes, I'm trying to follow the per project management structure.
I have changed some parts, but yes, overall it follows the guide described in that section.

Just in case, I'll set in here my "complete" workflow.

1.- Add the project
```
opengrok-projadm -b $OPENGROK_PATH -a $PROJECT_NAME -U $OPENGROK_URL --jar /var/opengrok/lib/opengrok.jar
```

2.- Index the specific project
```
opengrok-indexer -a /var/opengrok/dist/lib/opengrok.jar -- \
                        --depth 8 \
                        --optimize off \
                        --progress \
                        -c /usr/local/bin/ctags \
                        -U $OPENGROK_URL \
                        -R /opengrok/etc/readonly_configuration.xml \
                        -H -P $PROJECT_NAME \
                        $PROJECT_NAME
```

3.- Reindex the the project (Recommended based on the documentation)
```
opengrok-reindex-project -J=-Xmx15g -J=-server \
                    -a /var/opengrok/dist/lib/opengrok.jar \
                    -t /var/opengrok/etc/logging.properties \
                    -p $PROJECT_NAME -d /var/opengrok/log/$PROJECT_NAME  \
                    -P $PROJECT_NAME -U $OPENGROK_URL \
                    -- -G -m 256 -c /usr/local/bin/ctags \
                    -U $OPENGROK_URL -H $PROJECT_NAME
```

4.- Save/Apply configuration to Webapp
```
opengrok-projadm -b $OPENGROK_PATH -U $OPENGROK_URL --jar /var/opengrok/dist/lib/opengrok.jar \
            -R $OPENGROK_PATH/etc/readonly_configuration.xml -r -u
```


I'm aware that the guide presented under "per project management" page does not tell us how to run the "opengrok-reindex-project" command, but I based my command on the one used on the Opengrok-sync section. 
This command seems to work as I expect, the only problem here is on the indexer command (I think).

-Thank you

**Comment by oliver-mx** [comment]
> For option 1, drop the project names at the end of the command. If you provide the project name, then the indexer thinks it's a partial reindex and will only notify the webapp that it should refresh the specified project but it does basically nothing when that project does not exist in the first place. (it does not update the configuration)
> 
> Maybe we should return a different HTTP status for such a scenario - e.g. `404` and display a warning in the indexer.
> 
> For option 2, @vladak will be a better person to answer. I am not even sure the repositories should be found without the `-S` or `--repository` options.

Hi ahornace,

Based on your recommendation, I executed the command and even when I'm now able to see the repo with "History" and "annotate" I think it might not be the right approach. I'm saying this because of the following:

- The projects are not visible on the Web app, I was able to verify that History and Annotate were working because I had the direct URL and I visited right away, but when I went to home, the projects indexed with this new command weren't visible.
I checked the configuration.xml and even when the repo information was there, some important lines were not.
```
<void method="put">
    <string>$PROJECT_NAME</string>
    <object class="org.opengrok.indexer.configuration.Project">
     <void property="historyEnabled">
      <boolean>true</boolean>
     </void>
     <void property="indexed">
      <boolean>true</boolean>
     </void>
     <void property="name">
      <string>$PROJECT_NAME</string>
     </void>
     <void property="path">
      <string>/$PROJECT_NAME</string>
     </void>
    </object>
   </void>
  </void>
```
If I'm not mistaken, these are the lines that tells Opengrok to show the project on the webapp, so these were not generated.

- When I indexed the first project everything seem normal, but when I tried to index the second one, the indexer command took all the projects I had and ran over those.

> INFO: Scanning for repositories in [<project_path>, <project_path>...

The command:
```
opengrok-indexer -a /var/opengrok/dist/lib/opengrok.jar -- \
                        --depth 8 \
                        --optimize off \
                        --progress \
                        -c /usr/local/bin/ctags \
                        -U $OPENGROK_URL \
                        -R /opengrok/etc/readonly_configuration.xml \
                        -H -G -S
```

-Thank you

**Comment by oliver-mx** [comment]
Sorry, I missed the click and hit "Close with comment" instead of just "Comment"

**Comment by vladak** [comment]
Okay, bonus points for using the per project workflow !

I think what may be happening is that the `f` repository is too deep in the directory structure to be discovered, at least w.r.t. the current maximum scanning depth setting at the time the project is added.

When `opengrok-projadm` is run with the `-a` option to add (or rediscover [1]) a project, it will basically call the `/api/v1/projects` API endpoint. This will perform repository scan, similar to what the indexer performs when run with the `-S` option, just in given directory. The repository scan traversal of the directory tree is governed by the `scanningDepth` property - the same that is set by the `--depth` indexer option. Given the API call does not have to set the value of this option, it is necessary to set it in the web application beforehand. This can be done e.g. API call before adding the project, e.g.:
```
curl -X PUT -d 8 -H 'Content-Type:application/text' \
    http://localhost:8080/source/api/v1/configuration/scanningDepth
```
or store it in the read-only configuration, merge with the current configuration and redeploy the web application.

As always when modifying some property in the web application configuration, it is usually necessary to make this change permanent.

[1] nice thing about adding already existing project is that it will be rescanned

**Comment by vladak** [comment]
You can always check whether the repository rescan was successful using the API call, e.g.:
```
curl http://localhost:8080/source/api/v1/projects/INSERT_PROJECT_NAME_HERE/repositories
```

**Comment by vladak** [comment]
As for running `opengrok-indexer` vs. `opengrok-reindex-project`, the latter is meant specifically to be run from `opengrok-sync` (because it handles various pattern replacements handful for per project logging etc.), not standalone even though it could be.

**Comment by oliver-mx** [comment]
Hi vladak,

Thank you so much for all the help provided, **it worked!**
**The issue was the Depth**, after setting the configuration given on the read_only.xml and merged it with the configuration.xml I was finally able to see the "History" and "Annotate" links for the project 'f'.

I even thought of adding this configuration myself when I was doing all my tests, but since we can specify the depth in the index command I thought this couldn't be the issue (but it was).

I just have some extra questions that I would like to ask you about Opengrok and some of the commands:

1. When I opened this question, I said that when I was running the index command it says:

> INFO: Creating historycache for 0 repositories

This stills happening, If I look under /opengrok/data/ I see that the Index command is not the one generating the history, in my case is the 'opengrok-reindex-project' command. (After executing this command, I was able to see the generated files in the mentioned data path), but I was able to see the paths/repos scanned by 'opengrok-projadm' in the configuration.xml when the index command was in progress.
**I guess my question is, is this expected?**

2. I ran two version of my workflow with the same project, and applying the depth configuration. In the first one the index command was like the one I commented before (Point 2, without the -S flag) and on the second one, I ran it with the -S and -P flag because in my previous test I checked that if you run it with the -S flag, the command will scan all the repos in your project and generate the history of all of them.
So the result was that the index command took longer and the 'opengrok-reindex-project' took only a few minutes.

So if I take the two workflows, both were xecuted successfully and both are showing the "History" and "Annotate" that I wanted. The difference here is the timing and the way that they work.

- On the first workflow, the index took 12min, reindex=30min. Total time=42 min
- On the second workflow, the index took 28min, reindex=5min. Total time = 33 min

**My question is, at the end both workflows are doing the same, right?** I'm asking this, because sometimes I work with big projects, and the 'opengrok-reindex-project' process could take even 1-3 days to be completed the first time (I guess this happens because it's generating the history). The only problem is that this command doesn't show any "progress" so I don't really know how much time could a big project take to be completely indexed for the first time (while the indexer command is able to show the progress).

3. **What's the difference of running the command I specified in the "4.- Save/Apply configuration to Webapp" with and without the -u flag?**
I know that -u is for "update" the webapp, but in my two workflows that I ran previously one of them was ran without this option and I still see everything normally, as I would expect.


Thank you so much in advance for all the help, I really appreciate it.

**Comment by vladak** [comment]
Let's go through these questions one by one:

>     1. **What's the difference of running the command I specified in the "4.- Save/Apply configuration to Webapp" with and without the -u flag?**
>        I know that -u is for "update" the webapp, but in my two workflows that I ran previously one of them was ran without this option and I still see everything normally, as I would expect.

If you run `opengrok-projadm` with the `-u` option, it will upload the new configuration to the web application at the end of the run (does not matter if it was adding or deleting a project or refreshing the configuration on disk). Running with `-u` is only useful if you changed something in the read-only configuration and want to apply the effect to the web app. Hence, in general this is only useful if you used it in conjunction with the `-R` and `-r` options.

Applying new configuration to the web app can take some time (it will perform repository invalidation etc. as a result) so run with `-u` only when needed.

The purpose of the last step (number 4) is to make the configuration persistent. It should be run only after all the per project reindex commands have finished or when you change read only configuration. In the former case, the reason to run it is that when reindex is done, the state of the repositories (metadata like the last indexed changeset - the stuff displayed on the index page in the UI for given repository) of given project is stored only in the web app, i.e. in memory. So if you redeployed the web app or restated the application server before the current configuration is saved to disk, after startup the web app would display old state. Now, the next reindex would fix it however for some users it might be confusing.

**Comment by vladak** [comment]
> For option 2, @vladak will be a better person to answer. I am not even sure the repositories should be found without the `-S` or `--repository` options.

The `-S` option takes optional argument - the path to scan. If the argument is not specified, it will perform repository scan under source root. In general, when running per project reindex this option should be avoided. I mean, it will do the job of discovering the repositories so that the history cache can be generated, however doing this for every reindex would be waste of resources.

The `--repository` option is for very specific use cases.

**Comment by vladak** [comment]
>     1. When I opened this question, I said that when I was running the index command it says:
> 
> 
> > INFO: Creating historycache for 0 repositories
> 
> This stills happening, If I look under /opengrok/data/ I see that the Index command is not the one generating the history, in my case is the 'opengrok-reindex-project' command. (After executing this command, I was able to see the generated files in the mentioned data path), but I was able to see the paths/repos scanned by 'opengrok-projadm' in the configuration.xml when the index command was in progress.
> **I guess my question is, is this expected?**

I think there is some confusion about the per project workflow in general. Firstly, it is important to realize that the `opengrok-indexer` and `opengrok-reindex-project` are very similar tools. At the end they will just run the `java -jar opengrok.jar ...` command with bunch of indexer options. If you want to reindex one specific project, choose one command and stick with it. Now, the `opengrok-reindex-project` command does some extra stuff:
  - notably, it retrieves fresh configuration from the web application (via RESTful API call), stores it in a temporary file and automatically appends the `-R` option with this temporary file to the indexer arguments. 
    - This way you do not have to make the configuration from the web app persistent on disk before running the indexer (with `-R`).
  - Also, it will perform logging template substitution.
    - This way the indexer logs for each project will be stored in separate file (as long as you pass the right logging template via the `-t` option and `-p` with the project pattern and `-P` with actual project name).

Assuming the project you are indexing indeed contains some repositories, the `Creating historycache for 0 repositories` might be expected but is probably unwanted :-) When you run the per project index and want history cache to be generated, it is necessary to supply the information of the repositories to the indexer somehow. This can be done in number of ways, e.g. by running it with `--repository` option or by scanning for the repositories by using the `-S` option. Or by adding the project to the configuration in the web app first (e.g. using `opengrok-projadm -a ...` or via appropriate RESTful API call directly), getting the fresh configuration from the web app and running the indexer with this configuration using the `-R` option.

The way you are running the `opengrok-indexer` command with `-R` (bullet 2 in https://github.com/oracle/opengrok/issues/3593#issuecomment-845167471) it looks like you are using the read only configuration file that usually contains just bunch of tunables, not project+repository information. Hence, the indexer will have no knowledge about the project and its repositories (it would have if you also specified `-S` or `--repository` however as explained above this is not recommended) so it will not generate history cache for them.

So, in sum, with the per project workflow it is recommended to add a project to the configuration in the web app first (which will also discover project's repositories if history cache is enabled), then run indexer in a way so it has the knowledge about the project+repository information. As explained above, the `opengrok-reindex-project` will that for you (after the project was added). If you wanted to do it yourself, the steps would look like this:
  1. add the project:
    `opengrok-projadm -a NEW_PROJECT ...` 
    - this will add also its repositories if history is enabled
  1. get the fresh configuration from the web app: 
   `curl -s -o /tmp/fresh.xml http://localhost:8080/source/api/v1/configuration` 
    - or use `opengrok-projadm -r ...`
  1. run the indexer with the fresh configuration so it knows about project's repositories:
  `opengrok-indexer ... -R /tmp/fresh.xml`

The important part is that however the configuration used to run the indexer was retrieved, it has to contain something both the `Project` object and `RepositoryInfo` object(s) for the history cache to be generated. Here is a snippet of configuration that contains a project and its 2 repositories:
```xml
   <void method="put">
    <string>foo</string>
    <object class="org.opengrok.indexer.configuration.Project">
     <void property="historyEnabled">
      <boolean>true</boolean>
     </void>
     <void property="mergeCommitsEnabled">
      <boolean>true</boolean>
     </void>
     <void property="name">
      <string>foo</string>
     </void>
     <void property="path">
      <string>/foo</string>
     </void>
    </object>
   </void>

...

   <void method="add">
    <object class="org.opengrok.indexer.history.RepositoryInfo">
     <void property="branch">
      <string>default</string>
     </void>
     <void property="currentVersion">
      <string>2019-12-03 09:39 +0100 194db2377782 Vladimir Kotal &lt;vlada@devnull.cz&gt; initial</string>
     </void>
     <void property="datePatterns">
      <array class="java.lang.String" length="1">
       <void index="0">
        <string>yyyy-MM-dd hh:mm ZZZZ</string>
       </void>
      </array>
     </void>
     <void property="directoryNameRelative">
      <string>/foo</string>
     </void>
     <void property="type">
      <string>Mercurial</string>
     </void>
    </object>
   </void>

   <void method="add">
    <object class="org.opengrok.indexer.history.RepositoryInfo">
     <void property="branch">
      <string>default</string>
     </void>
     <void property="currentVersion">
      <string>2020-08-21 09:19 +0200 ebbb094f60b3 Vladimir Kotal &lt;vlada@devnull.cz&gt; add</string>
     </void>
     <void property="datePatterns">
      <array class="java.lang.String" length="1">
       <void index="0">
        <string>yyyy-MM-dd hh:mm ZZZZ</string>
       </void>
      </array>
     </void>
     <void property="directoryNameRelative">
      <string>/foo/nested</string>
     </void>
     <void property="type">
      <string>Mercurial</string>
     </void>
    </object>
   </void>
```

**Comment by vladak** [comment]
> The only problem is that this command doesn't show any "progress" so I don't really know how much time could a big project take to be completely indexed for the first time (while the indexer command is able to show the progress).

It all depends on how logging is set up. The `opengrok-indexer` command in https://github.com/oracle/opengrok/issues/3593#issuecomment-845167471 is not run with any Java options that would specify the logging properties (one can do it with the `-J`/`--java_opts` option of `opengrok-indexer`) so the log entries produced by the indexer will be output to `stdout`/`stderr` (the default behavior of Java logging) and the `opengrok-indexer` will pass them through so you can actually see them. The `opengrok-reindex-project` is run with a logging properties file so the logging output will be directed according to the logging configuration therein, possibly to a file. You can watch the progress by `tail -f` on the file.

**Comment by oliver-mx** [comment]
Thank you so much for all the help and guidance.
Now I have a much better understanding about Opengrok, many thanks!

I'm closing this question since my original issue has been already resolved.

Saludos!
