### ISSUE TITLE
Meaningful error message when dataroot is not provided

### ISSUE THREAD

**Issue by arymangupta** [oracle/opengrok#3632]
PS C:\Users\agupta\Downloads\opengrok-1.7.10\lib> java -jar .\opengrok.jar -W .\configuration.xml -c C:\ctags\ctags.exe -P -S -v -s C:\opentest .\grokdata
Jun 11, 2021 2:50:43 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [-W, .\configuration.xml, -c, C:\ctags\ctags.exe, -P, -S, -v, -s, C:\opentest, .\grokdata]
Jun 11, 2021 2:50:43 PM org.opengrok.indexer.index.Indexer main
SEVERE: Unexpected Exception
java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at org.opengrok.indexer.index.Indexer.checkConfiguration(Indexer.java:881)
        at org.opengrok.indexer.index.Indexer.main(Indexer.java:191)

Exception: null
PS C:\Users\agupta\Downloads\opengrok-1.7.10\lib>

**Comment by arymangupta** [comment]
source of the tutorial https://medium.com/@kannaapandita/how-to-install-tomcat-and-opengrok-on-windows-e39f7f910348

**Comment by ahornace** [comment]
You are missing the `-d` option before `.\grokdata`. However, the output should be nicer and should not throw NPE.
