### ISSUE TITLE
what is tomcat.servlet.context.path for in the pom file?

### ISSUE THREAD

**Issue by cosmoJFH** [oracle/opengrok#3635]
What is purpose of the parameter 	

`<tomcat.servlet.context.path>/source</tomcat.servlet.context.path>`

in the pom file?

Could it be used in the the target

	<build>
		<finalName>source</finalName>

making the change

		<finalName>${tomcat.servlet.context.path}</finalName>
?

**Comment by vladak** [comment]
I think it used to be a property passed to the `tomcat7-maven-plugin`. It is certainly sensible to avoid duplication.

The first two were used in 65ec6718 , looks like the `tomcat.servlet.context.path` is still unused. Instead, the plugin uses `<path>/${project.build.finalName}</path>`.

**Comment by cosmoJFH** [comment]
Thanks for you quick answer. We really appreciate your effort to develop this project.

**Comment by vladak** [comment]
I think we should do something about this unused property.

**Comment by cosmoJFH** [comment]
Let me know whether I could contribute to solve this.

**Comment by vladak** [comment]
I think the `finalName` can be replaced with the Tomcat property, feel free to submit a PR for that (you'd need to sign Oracle Contributor Agreement).
