### ISSUE TITLE
avoid repository invalidation with --checkIndex

### ISSUE THREAD

**Issue by fstefanov** [oracle/opengrok#3645]
--checkIndex
	Check index, exit with 0 on success,
	with 1 on failure.

java -jar /home/ubuntu/bin/opengrok/dist/lib/opengrok.jar -R /home/ubuntu/fresh_config.xml --checkIndex

Jun 23, 2021 11:08:04 AM org.opengrok.indexer.configuration.Configuration read
INFO: Reading configuration from /home/ubuntu/fresh_config.xml
Jun 23, 2021 11:08:05 AM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [-R, /home/ubuntu/fresh_config.xml, --checkIndex]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 23, 2021 11:08:10 AM org.opengrok.indexer.util.Statistics logIt
INFO: done invalidating 1987 repositories (took 4.663 seconds)

ubuntu:~$ echo $?
0

Why 1987 gits are invalidated?

**Comment by ahornace** [comment]
I think the purpose of the check is to ensure that the current version of the application can work with the already existing index or if a complete reindex is necessary.

From javadoc of `checkVersion`:
```
Check if version of index(es) matches major Lucene version.
```

> Why 1987 gits are invalidated?
I think this is not relevant and is only a side-effect of the `checkIndex` method as it is called after configuration setup. Maybe it would be worth to move the `checkIndex` before that as it really does not need anything from the configuration but the data root.

**Comment by vladak** [comment]
> I think this is not relevant and is only a side-effect of the `checkIndex` method as it is called after configuration setup. Maybe it would be worth to move the `checkIndex` before that as it really does not need anything from the configuration but the data root.

Yes, the invalidation of the repositories is caused by the `setConfiguration()` call just before the index check: https://github.com/oracle/opengrok/blob/0dc20a000a49f8f3533eed6ff3eb66ae2eb5ed86/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java#L260-L271
