### ISSUE TITLE
org.apache.jasper.JasperException: Unable to compile class for JSP:

### ISSUE THREAD

**Issue by ashitoshghate** [oracle/opengrok#3656]
HTTP Status 500 – Internal Server Error

Type Exception Report

Message Unable to compile class for JSP:

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [12] in the jsp file: [/connect.jsp]
user cannot be resolved
9: try {	Class.forName("com.mysql.jdbc.Driver");
10: 	Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/?user=root","root","root");
11: 	PreparedStatement ps=conn.prepareStatement("select * from user whre user_id=? And password=?);");
12: 	ps.setString(user.getText());
13: 	ps.setString(pass.getText());
14: 		
15: 	int x=ps.executeUpdate();

An error occurred at line: [13] in the jsp file: [/connect.jsp]
pass cannot be resolved
10: 	Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/?user=root","root","root");
11: 	PreparedStatement ps=conn.prepareStatement("select * from user whre user_id=? And password=?);");
12: 	ps.setString(user.getText());
13: 	ps.setString(pass.getText());
14: 		
15: 	int x=ps.executeUpdate();
16: 	if(x>0) {

An error occurred at line: [19] in the jsp file: [/connect.jsp]
JOptionPane cannot be resolved
16: 	if(x>0) {
17: 			System.out.println("Registration is Succeful...");
18: 				
19: 			JOptionPane.showMessageDialog(submit,"You have succesfully register login now ");
20: 			home h1=new home();
21: 		
22: 			h1.show();

An error occurred at line: [19] in the jsp file: [/connect.jsp]
submit cannot be resolved to a variable
16: 	if(x>0) {
17: 			System.out.println("Registration is Succeful...");
18: 				
19: 			JOptionPane.showMessageDialog(submit,"You have succesfully register login now ");
20: 			home h1=new home();
21: 		
22: 			h1.show();

An error occurred at line: [20] in the jsp file: [/connect.jsp]
home cannot be resolved to a type
17: 			System.out.println("Registration is Succeful...");
18: 				
19: 			JOptionPane.showMessageDialog(submit,"You have succesfully register login now ");
20: 			home h1=new home();
21: 		
22: 			h1.show();
23: 			h1.setVisible(true);

An error occurred at line: [20] in the jsp file: [/connect.jsp]
home cannot be resolved to a type
17: 			System.out.println("Registration is Succeful...");
18: 				
19: 			JOptionPane.showMessageDialog(submit,"You have succesfully register login now ");
20: 			home h1=new home();
21: 		
22: 			h1.show();
23: 			h1.setVisible(true);

An error occurred at line: [24] in the jsp file: [/connect.jsp]
The method dispose() is undefined for the type connect_jsp
21: 		
22: 			h1.show();
23: 			h1.setVisible(true);
24: 			dispose();
25: 
26: 					
27: 			}else {

An error occurred at line: [28] in the jsp file: [/connect.jsp]
JOptionPane cannot be resolved
25: 
26: 					
27: 			}else {
28: 			JOptionPane.showMessageDialog(submit,"Registration Unsucceful");
29: 			}
30: 
31: 				}catch(Exception e1) {

An error occurred at line: [28] in the jsp file: [/connect.jsp]
submit cannot be resolved to a variable
25: 
26: 					
27: 			}else {
28: 			JOptionPane.showMessageDialog(submit,"Registration Unsucceful");
29: 			}
30: 
31: 				}catch(Exception e1) {

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:213)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:544)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:381)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:597)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:382)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

I am unable to solve this can anyone have the solution for this problem

**Comment by ashitoshghate** [comment]
this is my JSP code 
<%@page language="java" %>
<%@page import="java.sql.*" %>

<%
    String Username=request.getParameter("user");
    String Password=request.getParameter("pass");
  

try {	Class.forName("com.mysql.jdbc.Driver");
	Connection conn=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/?user=root","root","root");
	PreparedStatement ps=conn.prepareStatement("select * from user whre user_id=? And password=?);");
	ps.setString(user.getText());
	ps.setString(pass.getText());
		
	int x=ps.executeUpdate();
	if(x>0) {
			System.out.println("Registration is Succeful...");
				
			JOptionPane.showMessageDialog(submit,"You have succesfully register login now ");
			examsheet h1=new examsheet();
		
			h1.show();
			h1.setVisible(true);
			dispose();

					
			}else {
			JOptionPane.showMessageDialog(submit,"Registration Unsucceful");
			}

				}catch(Exception e1) {
					System.out.println(e1);
				}
			

 %>

**Comment by ahornace** [comment]
How is this relevant to OpenGrok? Please reopen with proper description.
