### ISSUE TITLE
initial indexing (creating historycache) extremely slow on 1.7.x

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#3657]
Description:
  One of our most popular branch took whole 2 days for initial indexing on 1.6.9.
  Now with 1.7.x, it is taking extremely too much time and we never get it finished yet.

  Here are the recent results;
    1.6.9: 2 days
    1.7.6: 22+ days, but not finished, then canceled
    1.7.13: 13+ days with adding some performance up options (see attached read-only config); still running

Expectation:
  1. We want the initial indexing (creating historycache) to be finished within reasonable time flame (less than one week?).
  or,
  2. We want to have the option to disable the feature which is introduced from 1.7.x and is taking too much time.
  or,
  3. We want to know the way to drastically improve the initial indexing performance with history enabled.

Spec:

  H/W (vm)
  CPU: 8 core
  Memory: 94G
  Free Storage: 900GB

  S/W
  RHEL 7.9
  Java: 11.0.2
  CTAGS: Universal Ctags compiled at 02/13/2020

Attachment:
  opengrok0.0.log
  read-only.99.xml (read-only config file)
[opengrok0.0.log](https://github.com/oracle/opengrok/files/6779574/opengrok0.0.log)
[read-only.99.xml.txt](https://github.com/oracle/opengrok/files/6779575/read-only.99.xml.txt)

**Comment by ahornace** [comment]
Have you tried increasing the chunk size to higher values? In https://github.com/oracle/opengrok/pull/3647 @vladak tried using `524288` chunk size and it seemed to take only quarter of the time compared to `8192`.

Furthermore, now the default value for git repositories is `65536` which is much higher than `640` in your config.

**Comment by shyoshiz** [comment]
Thanks for the info!
I'll definitely try the `524288`.

**Comment by vladak** [comment]
The attached read-only config has chunk size of 640. That's definitely too low even for smaller repositories. That's why it was bumped into tens of thousands in #3647. If you have lots of RAM and can assign this memory to the JVM heap, you can set the chunk size really high.

How many changesets are in your Git repository ?

**Comment by vladak** [comment]
Given that the count of commits is known in advance (design decision we debated over with @ahornace when the per partes history was introduced) maybe we can add some logic there. Something like: if the total changeset count for a repository is higher than say 500k and JVM heap size is bigger than say 16 GB then turn the per partes history cache generation off. This is getting complicated when indexing couple of these repositories so I'd rather not do that. Perhaps adding a tunable to disable it is in order.

**Comment by vladak** [comment]
How big is the JVM heap size you are running the indexer with ?

**Comment by shyoshiz** [comment]
Hi OpenGrok team,

"find | wc -l" command shows `530452`
java for tomcat: `-Xmx24g -Xms24g`
java for indexer: `-Xmx56g -Xms56g`
H/W memory: 94G

I'm now running with `524288`.
Can I increase more? How much is the most effective?

Thank you so much for your help!

**Comment by vladak** [comment]
This is not so much about the number of files in the current checkout of the repository (even though it also matters) rather than the size of the history of the repository. Something like `git log --stat | wc -l` or `git log --pretty=oneline |wc -l` would tell more. If you bump the check count to be greater than the latter number, the history cache creation performance should return to the previous state.

**Comment by shyoshiz** [comment]
I get the following numbers:

> pisces@sjc-opengrok-17>git log --stat | wc -l
> 5948997
> pisces@sjc-opengrok-17>git log --pretty=oneline | wc -l
> 188502

So, this means 524288 is too much?
Do you think what value would be most effective?

**Comment by vladak** [comment]
For reference, currently the Linux Git repo has 1027755 commits. 56 GB heap size should be probably enough even if you set the chunk size to value higher than 188502. Assuming single project is indexed at once.

**Comment by shyoshiz** [comment]
Yes, this is a single project. Ok, then I will leave it as 524288.
Thank you for your advice!

**Comment by shyoshiz** [comment]
The 524288 works fine!
Thank you very much for your help!
