### ISSUE TITLE
glassfish link on "how to setup opengrok" page has expired

### ISSUE THREAD

**Issue by dsdqmhsx** [oracle/opengrok#3681]
**Describe the bug**
Glassfish link (https://glassfish.dev.java.net/) on https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok redirects to "We're sorry the java.net site has closed." page (https://www.oracle.com/splash/java.net/maintenance/index.html).

**Comment by ahornace** [comment]
Fixed, thanks for reporting it :)
