### ISSUE TITLE
/configuration/authorization/reload API endpoint should be asynchronous

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3686]
This API call could take a lot of time due to reconnecting to LDAP servers etc. It should be asynchronous. Will use the infrastructure put in place by the change for #3678.

**Comment by manan-paneri-99** [comment]
Hi, I would like to contribute to this issue. Can you please share more details about the same?

**Comment by ahornace** [comment]
Take a look at https://github.com/oracle/opengrok/issues/3678 

I think it covers what needs to be done. If it's still unclear, then please ask more specific questions.
