### ISSUE TITLE
Clicking on revision in annotation mode returns 400 bad request

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#3689]
**Describe the bug**
Annotation seems to be broken on 1.7.15, clicking on a specific commit in annotation mode results in 400.

**To Reproduce**

1. Go to http://demo.opengrok.org/xref/OpenGrok/opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java?a=true&r=8ae5e262
2. click on any commit

**Expected behavior**
Load the file in the desired revision.

Results in this uri:
```
http://demo.opengrok.org/xref/OpenGrok/opengrok-indexer/src/main/java/org/opengrok/indexer/framework/opengrok-indexer%2Fsrc%2Fmain%2Fjava%2Forg%2Fopengrok%2Findexer%2Fframework%2FPluginClassLoader.java?a=true&r=0cdb674f
```
 which returns 400 bad request.

**Comment by ahornace** [comment]
Thanks! Could you please check the PR?
