### ISSUE TITLE
Update documentation for the "Path Descriptions"

### ISSUE THREAD

**Issue by cosmoJFH** [oracle/opengrok#3694]
We think that the documentation provided for the "Path Descriptions" in https://github.com/oracle/opengrok/wiki/Webapp-configuration#path-descriptions is out of date.

We have tried to use the RESTful API call as it is described in the documentation

```
curl -i -X POST -H "Content-Type: text/plain" \
    --data-binary "@/opengrok/etc/paths.tsv" \
    http://localhost:8080/source/api/v1/system/pathdesc
```

But it does not work.

Searching in the source code (SystemController.java), it looks like the service api/v1/system/pathdesc only accepts the media type "Content-Type: application/json"

We have checked that the following  RESTful API call would work

```
curl -i -X POST -H "Content-Type:  application/json" \
    --data-binary "@/opengrok/etc/paths.json" \
    http://localhost:8080/source/api/v1/system/pathdesc
```

where the paths.json file
```json
[
{"path": "/foo", "description" : "  source code for foo"},
{"/bar", "description" : "  source code for bar"},
{"/bar/blah", "description" : " source code for blah"}
]
```

**Comment by vladak** [comment]
Looks like I forgot to update the documentation for #3375.

Thanks for the report !
