### ISSUE TITLE
Possibility to configure the container's timezone

### ISSUE THREAD

**Issue by mishka81** [oracle/opengrok#3710]
By default, in the UI timezone is in UTC, for both latest index date and for latests commits on projects.

Would it be possible to pass it to the Docker container as an environment variable ?

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
I'd like to have this too, also for the Container's OS time zone, so that log event outputs are in the correct time zones.

**Comment by vladak** [comment]
Perhaps one of the solutions in https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container would help ?

**Comment by vladak** [comment]
Checking the Docker image, the `tzdata` package is installed so the `/usr/share/zoneinfo` directory is present.

**Comment by mishka81** [comment]
I can confirm TZ=Europe/Paris (in my case) works in docker-compose.yml.
Thank you very much.
