### ISSUE TITLE
Upgrade 1.6.6 -> 1.7.20

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#3734]
Hi team,

Not a bug report. Just a question.

Do you confirm that if I upgrade OG from 1.6.6 to 1.7.20, since I am indexing using -G argument, I only need to delete my historycache directory, despite newer Lucene version (from 8.8.0 for OG 1.6.6 to 8.10.0 for OG 1.7.20)?

**Comment by ahornace** [comment]
As far as I know, Lucene is following semantic versioning so there should be no issue at all regarding Lucene updates. If you are worried that something might go wrong, then always take a backup.

**Comment by ChristopheBordieu** [comment]
Thanks!
