### ISSUE TITLE
opengrok-indexer uses git log full history instead of git log without full history

### ISSUE THREAD

**Issue by ghost** [oracle/opengrok#3737]
**Describe the bug**
After upgrading to OpenGrok 1.6.8, git log full history is indexed instead of git log without full history.  This will display every single commits for a file history.  This history is way too much and includes many changes not interested to users.

Regular git log is `git log -- <file>`
Full git log history is `git log --full-history -- <file>`

OpenGrok 1.6.8
JDK: jdk-13.0.2-13.0.2-ga.x86_64
OS: CentOS 8.4 x86_64
Tomcat: apache-tomcat-10.0.2
Git: 2.25

**To Reproduce**

1. Clone repot files
2. Run this command:
```
/opengrok/opengrok-tools/bin/opengrok-indexer \
    -J=-Djava.util.logging.config.file=/opengrok/etc/logging.properties \
    -a /opengrok/dist/opengrok-1.6.8/lib/opengrok.jar -- \
    -c /usr/local/ctags/bin/ctags \
    -s /opengrok/src -d /opengrok/data -H -P -S -G \
    -i "*.tar" -i "*.gz" -i "*.jar" -i "*.sqlite" \
    -W /opengrok/etc/configuration.xml \
    -R /opengrok/etc/readonly_configuration.xml \
    -U http://localhost:8080
```
3. Check a file commit history

**Expected behavior**
Commit history only shows the changes as reported by `git log`, not by `git log --full-history`

**Screenshots**
N/A

**Additional context**

This issue seems started with OpenGrok 1.6.8.

**Comment by vladak** [comment]
The [git log documentation](https://www.git-scm.com/docs/git-log) does not really give too much detail on what `--full-history` does:
>    Same as the default mode, but does not prune some history.

Interestingly, I found https://stackoverflow.com/questions/49792793/how-do-i-get-git-log-full-history-file-in-jgit asking the opposite - how to get full history in JGit.

**Comment by vladak** [comment]
Seems like the difference is about merge commits and deleted files (https://stackoverflow.com/a/34755406/11582827). What sort of extra commits do you see in your case ?

**Comment by saltuser16** [comment]
The extra commits are Merge branch 'master',  Merge remote-tracking branch, Automatic merge of branch, Merge commit messages. 

One would not see the extra commits with "git log". The extra commits are displayed with "git log --full-history".

**Comment by vladak** [comment]
> The extra commits are Merge branch 'master', Merge remote-tracking branch, Automatic merge of branch, Merge commit messages.
> 
> One would not see the extra commits with "git log". The extra commits are displayed with "git log --full-history".

Could you share the output from `git log --pretty=short -n1 <INSERT_REVISION_ID_HERE>` for those revisions that appear extra in the history ? I'd like to see if these are indeed merge commits, i.e. how many parent changesets they have.

**Comment by saltuser16** [comment]
Here is readonly_configuration.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<java version="13.0.2" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration">

  <void property="sourceRoot">
   <string>/opengrok/src</string>
  </void>
  <void property="ctags">
   <string>/usr/local/ctags/bin/ctags</string>
  </void>

 </object>
</java>
`

**Comment by saltuser16** [comment]
The output of some 'git log --pretty=short' commands:

```$ git log --pretty=short -n1 69081ea79cc2a36df739101c233e46db03f9eaca
commit 69081ea79cc2a36df739101c233e46db03f9eaca
Merge: 7750d253c17 ec0fb0aafdd
Author: User One <user.one@corp.com>

    Merge branch 'master' of ssh://git.server.net/var/git/repos/example

$ git log --pretty=short -n1 16d19759cb7fd1f3b515f5cdadce9e3a4d719614
commit 16d19759cb7fd1f3b515f5cdadce9e3a4d719614
Merge: e3241a4f365 099447a0447
Author: User Two <usertwo@corp.com>

    Merge branch '2021-2'

$ git log --pretty=short -n1 3eb29896f2a895b189b872db60342e0f3e0d1bb5
commit 3eb29896f2a895b189b872db60342e0f3e0d1bb5
Merge: d28dd9d8e20 4d026091394
Author: User Two <usertwo@corp.com>

    Merge branch '2021-2'

$ git log --pretty=short -n1 9001c71ac57735c10152ab7fcb87b8ace9f2649d
commit 9001c71ac57735c10152ab7fcb87b8ace9f2649d
Merge: 7af4d4e49b1 928920e939e
Author: User Two <usertwo@corp.com>

    Merge branch '2021-2'```

**Comment by vladak** [comment]
> I tried 1.7.20 and still saw the same issue. I will check with disabling mergeCommitsEnabled.

It is necessary to recreate the history cache from scratch.
