### ISSUE TITLE
Issue running tests for  1.7.21

### ISSUE THREAD

**Issue by cosmoJFH** [oracle/opengrok#3750]
We have just changed from opengrok 1.7.20 to 1.7.21 and we have the following error running the tests.

Do you know whether we should change something in our system?

```
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ opengrok ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenGrok 1.7.21:
[INFO] 
[INFO] OpenGrok ........................................... SUCCESS [  0.737 s]
[INFO] OpenGrok Indexer ................................... FAILURE [ 25.583 s]
[INFO] OpenGrok authorization plugins ..................... SKIPPED
[INFO] OpenGrok Suggester ................................. SKIPPED
[INFO] OpenGrok Web ....................................... SKIPPED
[INFO] OpenGrok tools ..................................... SKIPPED
[INFO] Distribution ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.461 s
[INFO] Finished at: 2021-10-13T16:47:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project opengrok: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed: java.lang.NoClassDefFoundError: Main (wrong name: sources/java/Main) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :opengrok
```

**Comment by ahornace** [comment]
Could you please provide additional data like:
- operating system
- java version
- maven version (if not using `mvnw`)

**Comment by vladak** [comment]
I wonder what happens if you run this outside Jenkins.

**Comment by ahornace** [comment]
I don't see a change between 1.7.20 and 1.7.21 that should cause this (maybe https://github.com/oracle/opengrok/pull/3732 ?)

I personally would try running it with `mvnw` and `-X` option to get some insight into what is happening. Wondering where this `Main` class is actually coming from: 
> java.lang.NoClassDefFoundError: Main (wrong name: sources/java/Main)

**Comment by cosmoJFH** [comment]
We have changed the project and now we made use of the wrapper ./mvnw, but we had the same error

[SVNSearch_22.0] $ /bin/sh -xe /tmp/jenkins18100487676034827790.sh
+ ./mvnw clean test -Dorg.opengrok.indexer.analysis.Ctags=/jenkins/.xxxx120/workspace/CU1_AuxiliaryTools/SVNSearch_22.0/ctags-universal/bin/ctags '-Dtest=*,!HistoryGuruTest,!RCSRepositoryTest,!IndexDatabaseTest,!IndexerTest,!SearchHelperTest,!PageConfigTest,!SuggesterControllerTest' -DfailIfNoTests=false



.....



[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project opengrok: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed: java.lang.NoClassDefFoundError: Main (wrong name: sources/java/Main) -> [Help 1]

**Comment by ahornace** [comment]
I've tried to specify excludes in `pom.xml` but it seems the https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test is overriding the settings altogether. Closing for now as I don't think it's a bug.
