### ISSUE TITLE
Failed to initial search

### ISSUE THREAD

**Issue by sogoogos** [oracle/opengrok#3755]
Hello. I am getting the following search error.

![キャプチャ](https://user-images.githubusercontent.com/24484961/138656390-9a932641-3374-40a3-8484-28e89ab38d4a.PNG)

I followed [this wiki](https://github.com/oracle/opengrok/wiki/How-to-setup-OpenGrok) and ran:

``` 
java -Djava.util.logging.config.file=opengrok\etc\logging.properties -jar opengrok\dist\lib\opengrok.jar  -c ctags\ctags.exe -s opengrok\src -d opengrok\data -H -P -S -G -W opengrok\etc\configuration.xml -U http://localhost:8080/source
```

### Environment & packages 

* Windows 10 64 bit
* opengrok-1.7.21
* Java SE 11
* Tomcat 10.0
* [ctags (2021-10-25)](https://github.com/universal-ctags/ctags-win32/releases/tag/2021-10-25%2Fp5.9.20211024.0-2-g6f544dfc)

**Comment by ahornace** [comment]
The tomcat logs should contain at least these 2 errors:
```
LOGGER.log(Level.SEVERE, "cannot get IndexReader for project " + proj, ex);
LOGGER.log(Level.SEVERE, "cannot construct MultiReader for set of projects", ex);
```

I've tried to reproduce with the same project and options on my Win machine but everything worked well. Can you please reopen with the above mentioned stacktraces?
