### ISSUE TITLE
Some folders are not showing up in opengrok search.

### ISSUE THREAD

**Issue by viri** [oracle/opengrok#3759]
```
opengrok version: 1.3.16

universal ctags version:

Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 22 2020, 17:47:52
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc


tomcat version:
Server version: Apache Tomcat/9.0.21
Server built:   Jun 4 2019 20:19:36 UTC
Server number:  9.0.21.0
OS Name:        Linux
OS Version:     2.6.32-754.35.1.el6.x86_64
Architecture:   amd64
JVM Version:    11.0.9.1+1-LTS
JVM Vendor:     Azul Systems, Inc.


java version:

openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
```

The issue I am seeing is that for the same product, when I index using same command line parameters for the opengrok indexer, between two different versions of the product, some of the folders are missing from search in one version whereas I am able to see that folder in other version .

For example product A version 1 shows results for the search on a specific folder :

![image](https://user-images.githubusercontent.com/2963954/140543228-61cb9e8d-1138-4c7b-9465-3b848344c481.png)

Product A now has version 2, I pull the source code and index it, but I don't see results for the specific folder:

![image](https://user-images.githubusercontent.com/2963954/140543535-d6c81999-ef5f-4bd4-8545-df9efb0822d8.png)

It appears to me that the indexer is not indexing the same way between two different versions and something is prompting the indexer to drop the folders from indexing.

Is there any way I can isolate the cause from the opengrok side? Thanks!

**Comment by vladak** [comment]
I assume that the files in question are present in both version 1 and 2 of the product A.

Couple of questions first:
  - How do you run the indexer ?
  - Are these files indeed present in the source root directory ?
  - Does this happen if you reindex from scratch ?

First thing I'd do is to look at indexer logs of the instance that fails to show the expected content. Then take a look into the data root directory for xref files corresponding to the files that are expected to be seen in the search results.

**Comment by viri** [comment]
Thank you for your response.




> I assume that the files in question are present in both version 1 and 2 of the product A.

Yes both projects contain the files in version 1 and 2


> * How do you run the indexer ?

I run it using the following command line parameters
`
 java -Djava.util.logging.config.file=/opengrok/logging.properties -Xmx16G -jar /opengrok/lib/opengrok.jar -s /A/10.5/main/ -d /og1_5_11/1050/data -W /og1_5_11/10.5/configuration.xml -i '*.mbtest' -i '*.dll' -i '*.pdb' -i '*.jar' -i '*.class' -i '*.obj' -i '*.idb' -i '*.dep' -i '*.dsp' -i '*.dsw' -i '*.sln' -i '*.vcproj' -i '*.makefile' -i '*.pch' -i '*.lib' -i '*.exp' -i '*.o' -i '*.a' -i '*.so' -i '*.jar' -i '*.class' -i '*.war' -i '*.ear' -i '*.mrep' -i '*.dat' -r off -c /ctags/bin/ctags -P -S -v -q

`
> * Are these files indeed present in the source root directory ?

Yes the files are located in root folder

> * Does this happen if you reindex from scratch ?

I just reindexed and I am able to see the folders now. This was the same source code, and the command line to index the source code is same also.

> First thing I'd do is to look at indexer logs of the instance that fails to show the expected content. Then take a look into the data root directory for xref files corresponding to the files that are expected to be seen in the search results.

I will do this next time the issue happens again. Unfortunately  the indexing was done almost a year ago for this project and the logs were recycled after certain time. But I will retain them next time the issue should happen again.
