### ISSUE TITLE
tomcat open source 404

### ISSUE THREAD

**Issue by LeaoWinchester** [oracle/opengrok#3760]
HTTP status 404 - not found

localhost:8080 it's ok !

**Comment by vladak** [comment]
There is not enough data to tell what is going on, namely:
  - which URL does not work
  - OpenGrok version
  - web app logs
  - environment (Docker image or not)
  - how the web app was deployed
  - how the indexer was run
  - was it always like that

**Comment by ahornace** [comment]
Closing as not enough details were provided to do proper investigation. Please reopen if the issue persists by answering the questions posed by @vladak
