### ISSUE TITLE
Make grepping easier :-)

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#3768]
Hi team,

https://github.com/oracle/opengrok/blob/1a64b7d0f709c7f478e9e5bbc504ec1274488f4c/opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java#L857

Would it be possible to use _**D**one_ instead of _**d**one_ like for other messages?

It would help (avoiding usage of -i) when grepping OpenGrok indexer logs in debug mode.
Thanks!

Regards,
Christophe

**Comment by ahornace** [comment]
Hi,
sure, makes sense that logs should follow similar format (1st capital letter in this case).

Thanks!

**Comment by ChristopheBordieu** [comment]
Many thanks Adam for quick update! 
All these messages you put in place during various indexing operations help a lot maintainers to monitor and report the whole process. That's very useful!

**Comment by ahornace** [comment]
You are most welcome! Thanks for the good suggestions and review :)
