### ISSUE TITLE
OpenGrok 1.7.24 - Tomcat LDAP authentication - using incorrect password instantly leads to locked out account in AD

### ISSUE THREAD

**Issue by ncsctc** [oracle/opengrok#3829]
Wonder if I can get some help  with an issue with the LDAP authentication and if anyone has any idea how to debug/workaround/fix it. Much appreciated for any pointers. 

- I'm using OpenGrok 1.7.24 running in a container with Tomcat doing the authentication via secure LDAP with Microsoft AD. No OpenGrok authorization used at this stage. The connection to the main OpenGrok webpage is via HTTPS.

- When I open the OpenGrok main webpage, I am prompted for a username and password and if I insert these correctly then no issue at all: everything is working great.

- My problem comes when I am inserting an incorrect password: looks like Tomcat/OpenGrok is unforgiving and locks out my account in AD instantly. I discussed this with my internal infra team and they are saying that they only see one lockout attempt. My suspicion is that Tomcat/OpenGrok re-attempts ( or makes multiple attempts from different threads) automatically using the same username and incorrect password and that leads to my AD account getting locked out. Looking to check if my suspicion is correct/incorrect here but don't know how to prove that is the case, or not.

My Tomcat server.xml includes these realms:
```
      <Realm className="org.apache.catalina.realm.LockOutRealm" failureCount="3" lockOutTime="60" >
        <Realm className="org.apache.catalina.realm.JNDIRealm"
        ...
        />
      </Realm>
```
I'm not a Java developer but I should be able to add debug logging if someone has any suggestions for its location. Maybe to identify how many auth attempts and in what timeframe in the first instance and then trying to figure out where those attempts are generated from.

**Comment by vladak** [comment]
Overall, I think asking this sort of question on forums like stackoverflow.com would have higher chances of getting a useful response. That said, I will take a stab:

OpenGrok does not perform any sort of authentication as explained on https://github.com/oracle/opengrok/wiki/Authorization so should not have any role in the account lockout, unless there is some weird redirect loop that would case the authentication to be attempted in a cycle or such.

From the above it is is not clear to me what component actually performs the account lock. I doubt it is the client component as that would make no sense - anyone on a configured LDAP client instance could lock a random account like that, creating an avenue for a nice Denial Of Service possibility. More likely it is the server which locks the account so getting some debug/verbose data from the server side should explain what is going on, at least in terms of authentication requests. Also, dumping the traffic from the client to Tomcat (e.g. using Web developer console in a browser) and from Tomcat to the LDAP server might help (https://stackoverflow.com/a/30338381/11582827).

Anyhow, for starters I think it would be good to take OpenGrok out of the picture and use some dummy web app and observe the behavior there.

**Comment by vladak** [comment]
Closing for the lack of response, feel free to reopen with more data.
