### ISSUE TITLE
Question: How to add new project without indexing already existing projects?

### ISSUE THREAD

**Issue by Z4rc** [oracle/opengrok#3832]
Hi,

I use the following command for reindex:
`java opengrok.jar -H --depth 2 -T 48 --progress --renamedHistory on -r on -s source -d data -c ctags -R config.xml -U http://localhost:8080/grok <project list>
`

When adding a new project, I use the following command:
`java opengrok.jar -H --depth 2 -T 48 --progress --renamedHistory on -r on -S -P -W config.xml -s source -d data -c ctags -R read-only.xml -U http://localhost:8080/grok
`

In contrast to the reindex, I am using the options -S and -P and write the configuration file confix.xml instead of reading it.
The problem is that all existing projects are also indexed when using this command, including the generation of the history cache.
In my case, this takes a long time, although it would be enough if only the new project would be indexed + history cache generated.

Is there a more efficient way of adding new projects without indexing the already existing projects?

Thanks in advance!

**Comment by vladak** [comment]
Surely there is. You are looking for different workflow, see https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow
