### ISSUE TITLE
Multibyte character text files (Like Japanese) are recognized as a binary file.

### ISSUE THREAD

**Issue by ushiba0** [oracle/opengrok#3838]
Hi, 

I'm not sure if this is a bug or not, but I couldn't find the configuration file that controls this behavior, so I'm posting an this issue.

[Problem Description]
Certain Japanese files are recognized as binary files and cannot be viewed in the browser, and a download link is displayed.

[Reproduction Method]
1. In an Opengrok project directory, create a utf-8 text file.
$ echo "Hello from 日本" > hello-from-japan.txt
$ file hello-from-japan.txt
hello-from-japan.txt: UTF-8 Unicode text

2. Check hello-from-japan.txt in Opengrok browser page. This file will be recognized as text and can be read in a browser as expected.

3. In an Opengrok project directory, create a utf-8 text file. This time, I made the text only in Japanese.
$ echo "こんにちは" > hello-in-japanese.txt
$ file hello-in-japanese.txt
hello-in-japanese.txt: UTF-8 Unicode text

4. Check hello-in-japanese.txt in Opengrok browser page. This file will be recognized as binary. Only an download link is displayed.
The expected behavior is to be able to read the text in the browser.
![image](https://user-images.githubusercontent.com/24836241/146143361-f2123632-ae2d-48d5-97fe-55f1e67348ac.png)

[Environment]
Opengrok version : 1.7.25
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode)

Team, could you please check if this is a bug ?

**Comment by idodeclare** [comment]
Hi, @ushiba0. That is an old limitation of the plain-text heuristic that recognizes whether the initial bytes are "all ASCII graphic characters or ASCII whitespace." I have a patch which I'll raise to recognize UTF-8 instead.
