### ISSUE TITLE
Indexing time consuming problem

### ISSUE THREAD

**Issue by chenchuanliang** [oracle/opengrok#3865]
Version:Opengork1.7.24
Server:ubuntu 16.04    i7-2600 3.4GHz x 8   32G RAM
CMD:./opengrok-indexer -J=-Xmx16g -J=-server -a ~/opengrok/dist/lib/opengrok.jar -- -c /usr/local/bin/ctags -m 64.0 -s /workspace1 -d /opengrokData -i 'f:*.rar' -i 'f:*.zip' -i 'f:*.mbn' -i 'f:*.jar' -i 'f:*.gz' -i 'f:*.tar' -i 'f:*.elf' -i 'f:*.json' -i 'f:*.m' -i 'f:*.mm' -i 'f:*.js' -i 'f:*.lib' -i 'f:*.css' -i 'f:*.csl' -i 'f:*.acdb' -i 'f:*.exe' -i 'f:*.pp' -i 'f:*.o' -i 'f:*.a' -i 'f:*.bz2' -i 'f:*.kt' -i 'f:*.lsdump' -i 'f:*.so' -i 'zh.txt' -i 'zh.xml' -i 'f:*.rs' -i 'f:*.rb' -i 'f:*.cer' -i 'f:*.qwsp' -i 'f:*.obj' -i 'f:*.vblock' -i 'f:kernel-qemu' -i 'f:kernel-qemu2' -i 'f:*.b04' -i 'f:*.data' -i 'f:*.ts' -i 'f:*.cov' --progress -Q on -q -H -P -S -G -W ~/opengrok/etc/configuration.xml -U http://localhost:8080/source

We have about 27 Android projects. After the index is created, we maintain the synchronous index every day, but it takes more than 20 hours even without any modification. But we used opengrok0.3 version is very fast and can be completed in about 7-8 hours. In addition to increasing server performance, is there any opengrok parameter configuration that can shorten the time?

Thanks

**Comment by vladak** [comment]
> it takes more than 20 hours even without any modification

I assume this is a Git repository. Then #3077 would help.
