### ISSUE TITLE
opengrok-sync throws AttributeError exception due to command dictionary lacking the COMMAND_PROPERTY

### ISSUE THREAD

**Issue by chenchuanliang** [oracle/opengrok#3868]
I use the cmd:opengrok-mirror -a -I -U http://localhost:8080/source
But “No incoming changes for repositories in project xxx”
There are no source code updates and index changes.
Are there any errors in using the cmd?
Or use -c parameter ？
Look forward to receiving your reply.
Thank you.

**Comment by chenchuanliang** [comment]
When I use opengrok-sync ot openrok-mirror,There are some syntax errors about python：

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/unicair/opengrok/dist/tools/env/lib/python3.8/site-packages/opengrok_tools/sync.py", line 64, in worker
    x.run()
  File "/home/unicair/opengrok/dist/tools/env/lib/python3.8/site-packages/opengrok_tools/utils/commandsequence.py", line 131, in run
    cmd_value = command.get(COMMAND_PROPERTY)[0]
AttributeError: 'str' object has no attribute 'get'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./opengrok-sync", line 33, in <module>
    sys.exit(load_entry_point('opengrok-tools==1.7.24', 'console_scripts', 'opengrok-sync')())
  File "/home/unicair/opengrok/dist/tools/env/lib/python3.8/site-packages/opengrok_tools/sync.py", line 272, in main
    r = do_sync(args.loglevel, commands, config.get("cleanup"),
  File "/home/unicair/opengrok/dist/tools/env/lib/python3.8/site-packages/opengrok_tools/sync.py", line 105, in do_sync
    cmds_base_results = pool.map(worker, cmds_base, 1)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'str' object has no attribute 'get'

**Comment by vladak** [comment]
The exception comes from `opengrok-sync`, not `opengrok-mirror`. The exception was raised as a result of the configuration file not having the correct structure (which is a bug - the command should fail with an error instead).

What exactly are you trying to do ?

**Comment by chenchuanliang** [comment]
> The exception comes from `opengrok-sync`, not `opengrok-mirror`. The exception was raised as a result of the configuration file not having the correct structure (which is a bug - the command should fail with an error instead). See https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow#opengrok-sync for the syntax of the configuration file.
> 
> What exactly are you trying to do ?

Quick update index for about 60+ android projects.
Thanks

**Comment by vladak** [comment]
How does the `opengrok-sync` config file look like ?

**Comment by chenchuanliang** [comment]
> How does the `opengrok-sync` config file look like ?

Without setting, opengrok-sync reported a python error：AttributeError: 'str' object has no attribute 'get'

Previously, openrok-mirror reported a similar error, logger.error logger. info,the str method in Python cannot be found. I can execute it only after masking and modifying the python related files. Is there a problem with my Python version?
Thank you

**Comment by vladak** [comment]
I think this is a problem in the configuration file used for `opengrok-sync`.

**Comment by vladak** [comment]
Going back to the original comment: if you run `opengrok-mirror` with the `-a` option, it will make a RESTful API call to the web application (that's why it is usually accompanied with the `-U` option so that the tool know where to make the API call to) to get a list of all indexed projects. It will then try to update the source code for these projects by running the command appropriate for the repositories within each project (e.g. `git pull`). This should be followed by running the indexer for all projects.

Using `opengrok-sync` allows one to do the update and reindex for each project **in parallel**.

**Comment by chenchuanliang** [comment]
> Going back to the original comment: if you run `opengrok-mirror` with the `-a` option, it will make a RESTful API call to the web application (that's why it is usually accompanied with the `-U` option so that the tool know where to make the API call to) to get a list of all indexed projects. It will then try to update the source code for these projects by running the command appropriate for the repositories within each project (e.g. `git pull`). This should be followed by running the indexer for all projects.
> 
> Using `opengrok-sync` allows one to do the update and reindex for each project **in parallel**.

**Comment by chenchuanliang** [comment]
I guess : there is no git in the level 2 directory( such as E60/android ) of my project directory, which is not applicable to "git pull". Need to execute "repo forall - c git pull".

**Comment by chenchuanliang** [comment]
> Going back to the original comment: if you run `opengrok-mirror` with the `-a` option, it will make a RESTful API call to the web application (that's why it is usually accompanied with the `-U` option so that the tool know where to make the API call to) to get a list of all indexed projects. It will then try to update the source code for these projects by running the command appropriate for the repositories within each project (e.g. `git pull`). This should be followed by running the indexer for all projects.
> 
> Using `opengrok-sync` allows one to do the update and reindex for each project **in parallel**.

I check the project when I use "opengrok-mirror",Some level 2 directory( such as E60/ADSP )'s source code updated and reindex.But not all  level 2 directory can be updated.It's strange that I compared the upload record with the index. One file code and index have been updated, but some uploads have not been updated.
But If level 2 directory not have git( such as E60/android ,but  such as E60/android/package/apps/Settings have git) can not update source code.

**Comment by chenchuanliang** [comment]
> Going back to the original comment: if you run `opengrok-mirror` with the `-a` option, it will make a RESTful API call to the web application (that's why it is usually accompanied with the `-U` option so that the tool know where to make the API call to) to get a list of all indexed projects. It will then try to update the source code for these projects by running the command appropriate for the repositories within each project (e.g. `git pull`). This should be followed by running the indexer for all projects.
> 
> Using `opengrok-sync` allows one to do the update and reindex for each project **in parallel**.

I check the project when I use "opengrok-mirror",Some level 2 directory( such as E60/ADSP )'s source code updated and reindex.But not all  level 2 directory can be updated.It's strange that I compared the upload record with the index. One file code and index have been updated, but some uploads have not been updated.
But If level 2 directory not have git( such as E60/android ,but  such as E60/android/package/apps/Settings have git) can not update source code.

**Comment by chenchuanliang** [comment]
![2022-01-20 10-36-22屏幕截图](https://user-images.githubusercontent.com/20430797/150262307-86635c94-99c2-4218-8b6e-3904c48d6112.png)

**Comment by chenchuanliang** [comment]
![2022-01-20 10-36-22屏幕截图](https://user-images.githubusercontent.com/20430797/150263167-8166b86f-31c6-4753-b220-c1e440c4768e.png)
You can see:SQ53 no update,but the actual source code have changes.source code and index no changes when run "opengrok-mirror".
D50 only update 3 dir,but there are actually more directories that have changes.
![_20220120104601](https://user-images.githubusercontent.com/20430797/150263196-adf734f1-0ba7-47b1-8308-dac0090185b2.jpg)

you can see,TZ.XF.5.1 have changes,but no action when run "opengrok-mirror".

**Comment by chenchuanliang** [comment]
![2022-01-20 10-36-22屏幕截图](https://user-images.githubusercontent.com/20430797/150263318-54eab2de-7c83-4f00-b666-ab9987ef22ed.png)
You can see:SQ53 no update,but the actual source code have changes.source code and index no changes when run "opengrok-mirror".
