### ISSUE TITLE
Question about opengrok/docker on large source data

### ISSUE THREAD

**Issue by narugit** [oracle/opengrok#3874]
Hi, I'm new to OpenGrok. Could I ask a question about opengrok/docker?

As described in [README#when-not-to-use-it](https://github.com/oracle/opengrok/tree/05e3d405390e18994676ea934da43653fd2621ca/docker#when-not-to-use-it), what could happen when running the indexer on large source data?

> The indexer and the web container are not tuned for large workloads.

**Comment by ahornace** [comment]
> As described in README#when-not-to-use-it, what could happen when running the indexer on large source data?

Give it a shot and you will see :) the chances are that it will work properly for your needs. If you start experiencing slow indexing, crashes, or would need more fine-grained configuration, then it would be better to run OpenGrok the "old way".

**Comment by vladak** [comment]
I love the 'what could go wrong' questions :-) I guess the answer lies in https://github.com/oracle/opengrok/wiki/Tuning-for-large-code-bases 

Besides the obvious stuff like JVM heap (which is definitely addressable in Docker environment), you may run out of file descriptors or HTTP header space. Or simply you may find that the container does not give you enough flexibility w.r.t. configuration (in which case you might want to create your own image based on the official image).

**Comment by narugit** [comment]
@ahornace 
> Give it a shot and you will see

Yeah, that is the best way to learn. 

> slow indexing, crashes

I see. Thank you for the example :)

**Comment by narugit** [comment]
@vladak 
Thank you for accepting my question ;-)

> I guess the answer lies in https://github.com/oracle/opengrok/wiki/Tuning-for-large-code-bases

It's awesome. I'll read it.

> Besides the obvious stuff like JVM heap (which is definitely addressable in Docker environment), you may run out of file descriptors or HTTP header space. Or simply you may find that the container does not give you enough flexibility w.r.t. configuration

Thank you again for detailed example. 
It gave me an idea of what I needed to pay attention to. I will read the wiki and try to understand it better.
