### ISSUE TITLE
OpenGrok only "/source/xref/..." serves an old version of a file

### ISSUE THREAD

**Issue by liamwarfield** [oracle/opengrok#3887]
**Describe the bug**
Only when displaying a file, OpenGrok is showing an old version of the file. `https://opengrok/source/xref/path/to/file.cpp` shows an outdated version of a file. Strangely enough `/source/raw/path/to/file.cpp` shows the correct, newer file. The same goes for searching. When searching for a term thats only contained in the new version of `file.cpp`, the preview gives the correct and newer text.

`file.cpp` does not show up in any error/warning/info logs (on both the indexer and tomcat server) since it was updated 2 months ago. index is up to date, xref file timestamp is up to date inline with last change to the file. source is up to date, I have no idea where OG is picking the file from.

OG_VER=1.7.19
TOMCAT_VERSION="10.0.11"

Things that I have attempted to remedy the error:
1. Reindex the src files (no affect)
2. Restart the tomcat server (no affect)
3. Delete the xref file (waiting for a reindex, will post details later)

**To Reproduce**
Unknown

**Expected behavior**
`https://opengrok/source/xref/path/to/file.cpp` should show the up to date version after a reindex

**Screenshots**
Cannot share due to company policy, heres a more verbose example:

old version of file.cpp
```c++
int main() {
   cout << "hello world" << endl;
}
```

new version of file.cpp
```c++
int main() {
   cout << "hello everybody" << endl;
}
```

Searching for "everybody" shows this preview:
```
2  cout << "hello everybody" << endl;
```

going to `https://opengrok/source/xref/path/to/file.cpp` shows
```c++
int main() {
   cout << "hello world" << endl;
}
```

**Additional context**
I have an internal fork of OG that adds parsing support for an internal DSL. This fork only adds some lex files and an Analysis factory for the DSL. As far as I know, a fail parse shouldn't lead to an old file being displayed. As far as I can tell this is not the issue. As mentioned above no errors with ctags or indexing this file were observed. Searching for the contents of newer version of the file works correctly.

Sorry if this issue is a little vague, I acknowledge that it's hard without any logs to point at.

**Comment by vladak** [comment]
What is inside the xref file itself ? Say for example your data root is `/opengrok/data` what do you get if you display the decompressed contents of `/opengrok/data/xref/path/to/file.cpp.gz` ? Does it match what is presented by the browser ?

Is this file in question classified for processing by the DSL analyzer ?

**Comment by liamwarfield** [comment]
Update: 
Deleting the Xref file and reindexing did not fix the issue. Reindexing created the old version of `file.cpp`. `/var/opengrok/src/path/to/file.cpp` does contain the new version of file.cpp.

> Is this file in question classified for processing by the DSL analyzer ?

Yes. @vladak , do you know what happens if an analyzer factory fails?

> what do you get if you display the decompressed contents of /opengrok/data/xref/path/to/file.cpp.gz ?

The page for the old version of `file.cpp`

> Does it match what is presented by the browser ?

Yes

Where would OG be getting the old version of `file.cpp`  from?

**Comment by ChristopheBordieu** [comment]
Have you tried to remove too historycache directory for this repository? Or at least, into the historycache directory, the file dealing with file.cpp. Got same kind of issue and this fixed the problem.

**Comment by liamwarfield** [comment]
Where is the historycache directory?

**Comment by ChristopheBordieu** [comment]
Same level as xref, into your data root. If you do not see it, it is because you did not index enabling historycache.

**Comment by liamwarfield** [comment]
We disabled history on our OG instance because of performance and disk space considerations.

**Comment by liamwarfield** [comment]
Just RCed. It was a problem with our in house analyzerfactory. It wasn't building an import path properly, so it looked like the file wasn't changing. Thanks Y'all for your time and and help!
