### ISSUE TITLE
Allow to opt-out of redirecting on single search results

### ISSUE THREAD

**Issue by cesar-d2l** [oracle/opengrok#3900]
**Is your feature request related to a problem? Please describe.**
I had a few people ask me if they can prevent OpenGrok from redirecting when a single result is returned. Particularly people are looking to link to search results as opposed to the result itself

**Describe the solution you'd like**
I'd like it if this can be turned off at the user level (like suggestor) or at the webapp level.

**Describe alternatives you've considered**
People have been modifying the url and replacing `full=` (for full-text search) and setting a value for `xrd=`

**Comment by vladak** [comment]
`SearchHelper#executeQuery()` honors `noRedirect` if the "no redirect" query parameter is set. The name of the parameter is `xrd` (`QueryParameters.NO_REDIRECT_PARAM`) and if non empty the redirect will be short-circuited. This query parameter is hidden in the `menu.jspf`. This should be made properly toggleable via the `Settings` page.

**Comment by vladak** [comment]
This is actually a dup of #3582.
