### ISSUE TITLE
large file rendering is extremly slow.

### ISSUE THREAD

**Issue by amplengin2** [oracle/opengrok#3913]
When i use opengrok to open big files through web browser, it's take extremly long time. (over the x mins)
Sometimes stuck happened.
Could you let me know about is there any method for fast rendering ?

opengrok version: opengrok-1.3.11
tested web browser: IE, EDGE, firefox. chrome and so on. (all latest version)

**Comment by vladak** [comment]
closing as dup of #3209

In general, it is necessary to perform at least some sort of analysis w.r.t. transfer speed, ideally also browser profiling.
