### ISSUE TITLE
Incorrect sorting of CVS revisions in History on a branch

### ISSUE THREAD

**Issue by aerofeev2k** [oracle/opengrok#3925]
We've just jumped from 1.0.0 to 1.7.30 and noticed that the list of revisions in History for a file on branch is presented out of order. E.g. for one file the History shows this:

1.9
1.8
1.7
1.6
1.5
1.4
1.3
1.2
1.17.200.2
1.17.200.1
1.17
1.16
1.15
...

As far as I understand, this code may be the reason:

        // In case there is a branch, the log entries can be returned in
        // unsorted order (as a result of using '-r1.1:branch' for 'cvs log')
        // so they need to be sorted according to revision.
        if (cvsrepo.getBranch() != null && !cvsrepo.getBranch().isEmpty()) {
            List<HistoryEntry> entries = history.getHistoryEntries();
            entries.sort((o1, o2) -> o2.getRevision().compareTo(o1.getRevision()));
            history.setHistoryEntries(entries);
        }

AFAIK, 1.0.0 didn't do any sorting at all, and so we were intercepting "cvs log" and sorting ourselves, but now the sorting happens inside OpenGrok as well, and the revisions are getting reordered later anyway.

The consequences are not just in how the History is presented, but in how Annotate works as well. E.g. with the above file if I click Annotate, I end up fetching URL "https://server/...path.../file.cpp?r=1.9&a=true", and "r=1.9" is of course incorrect, it runs "cvs annotate -r1.9 file" and produces a totally wrong and not matching output.

**Comment by aerofeev2k** [comment]
Out of curiosity I disabled the above sorting code, recompiled OpenGrok, reinstated our "cvs log" sorting layer, reindexed the file in question (delete-reindex-update-reindex), and I can now see revisions in History in the correct order... but...

I still see incorrect revision "?r=1.9" in the URL when I either click the file or enter Annotate from xref screen. It's as if somewhere else OpenGrok too got a list of revisions, sorted them like strings and is now thinking that the tip of the branch is 1.9 (rather than 1.17.200.2).

**Comment by vladak** [comment]
The reason for the revisions to be specified in the URL is longevity - if a URL that contains a particular line (or line range), i.e. it has the line anchor (e.g. http://demo.opengrok.org/xref/OpenGrok/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java?r=741f2ca7#174-177), has also the revision, the URL will be valid forever (or until someone decides to rewrite the history of given repository which is not very frequent practice I'd say).

**Comment by vladak** [comment]
Interestingly, the above referenced change was done for #1633 which was actually filed by you.

**Comment by aerofeev2k** [comment]
> Interestingly, the above referenced change was done for #1633 which was actually filed by you.

True. At that time I didn't wait for the fix, I just added a wrapper around /usr/bin/cvs to sort revisions before feeding them into OpenGrok. This week we upgraded and hit the internal sorting.

I can continue with the wrapper (after disabling OpenGrok sorting), but the Annotations and opening files from xref are still wrong. They somehow pull rev. 1.9 instead of 1.17.200.2, and it's _after_ disabling internal sorting and reenabling the wrapper.

What may be the issue here? HistoryCache? Another sorter somewhere?

**Comment by aerofeev2k** [comment]
Btw, the comparator that we used looks like this. Basically, any revision with more fields (or dots) is newer than any revision with less fields. And if the number of fields in two revisions is the same, the fields are compared one by one as integers.

```
class Rev
{
public:
        Rev(const string & _rev) : rev(_rev)
        {
                dots=std::count(rev.begin(), rev.end(), '.');
        }
        friend int operator<(const Rev & r1, const Rev & r2)
        {
                if (r1.dots<r2.dots)
                        return 1;
                if (r1.dots>r2.dots)
                        return 0;
                const char * ptr1=r1.rev.c_str();
                const char * ptr2=r2.rev.c_str();
                while(*ptr1 && *ptr2)
                {
                        char * dot1, * dot2;
                        int num1=strtol(ptr1, &dot1, 10);
                        int num2=strtol(ptr2, &dot2, 10);
                        if (num1<num2)
                                return 1;
                        if (num1>num2)
                                return 0;
                        ptr1=*dot1 ? dot1+1 : dot1;
                        ptr2=*dot2 ? dot2+1 : dot2;
                }
                return 0;
        }
private:
        int dots=0;
        string rev;
};
```

**Comment by vladak** [comment]
> What may be the issue here? HistoryCache? Another sorter somewhere?

The latest revision for given file is pulled either from the index or history cache or history command itself (in this order) - see https://github.com/oracle/opengrok/blob/7626bae0f6e5cafadf9bedeb56ebdc5d31564565/opengrok-web/src/main/java/org/opengrok/web/PageConfig.java#L1292-L1306

**Comment by aerofeev2k** [comment]
Ah, I get it. When I disabled internal sorting, I've updated only opengrok.jar under Tomcat directory, so indexing part was still using opengrok.jar from the install directory, was still sorting revisions and pushing 1.9 as LASTREV into index. Now it's pulling the right rev.

Could you modify the internal sorter to use something similar to the c++ code above please? And then I would put the wrapper to rest.

In CVS when a new branch is created, two fields are added to the branch's root revision. First fields is a branch number, second one counts file revisions on the branch. Branches can also be branched, so potentially something like this is easily possible:

1.12.200.2.2.3.50.4
1.12.200.2.2.3.50.3
1.12.200.2.2.3.50.2
1.12.200.2.2.3.50.1
1.12.200.2.2.3
1.12.200.2.2.2
1.12.200.2.2.1
1.12.200.1
1.11
1.10
1.9
1.8
1.7
1.6
1.5
1.4
1.3
1.2
1.1

**Comment by vladak** [comment]
I am thinking about a way to approach this - create a numeric vector out of each compared version and compare them element by element. Perhaps some Java library out there has a semantic versioning comparator already. Pull requests are certainly welcome.

**Comment by vladak** [comment]
https://stackoverflow.com/questions/198431/how-do-you-compare-two-version-strings-in-java might be a good start.

**Comment by vladak** [comment]
And https://github.com/G00fY2/version-compare looks neat.
