### ISSUE TITLE
Triggered Suggester rebuilds do not obey rebuildThreadPoolSizeInNcpuPercent

### ISSUE THREAD

**Issue by aerofeev2k** [oracle/opengrok#3938]
It seems that Suggester rebuilds triggered via REST (either explicitly using Suggester entry points or as a result of marking a project indexed) are all serialized using a single future.

So, if I quickly rebuild a dozen of main project indices from a dozen of threads, in the end I end up with quite a few threads sitting in the webapp and waiting to rebuild Suggester DBs for the reindexed projects one by one.

All of the rebuilds are of course finished sooner or later, but they ironically end up taking more time than the main index rebuild, and (as described in another report) are blocking configuration from updating and can potentially block suggestion lookups as well.

It would be nice if Suggester DB rebuilds triggered in this manner would also use a thread pool and honor rebuildThreadPoolSizeInNcpuPercent setting.

**Comment by vladak** [comment]
Will be addressed by #3347.
