### ISSUE TITLE
allow admins and users to add labels/tags to xref pages (Bugzilla #1063)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#396]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2008-04-09 11:12:31 +0000, Hemang Lavana wrote:

> Provide the capability to label or add tags to various pages displayed under xref page. Then it can allow the users to search pages by tags (like youtube or flickr). I think this can be a very powerful feature addition to opengrok search tool.
> 
> Hemang.

**Comment by tulinkry** [comment]
I think we chose a different path so this doesn't seem much relevant anymore.
