### ISSUE TITLE
allow users to rate and provide comments for xref pages (Bugzilla #1064)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#397]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Trond Norbye

On 2008-04-09 11:14:45 +0000, Hemang Lavana wrote:

> Provide the capability for users to rate the various pages under xref as well as allow them to add comments/tags for each page. This can help improve code-search results by using appropriate weight from user-ratings.
> 
> Hemang.

**Comment by tulinkry** [comment]
I think we chose a different path than being a social network based on source code.
