### ISSUE TITLE
WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined

### ISSUE THREAD

**Issue by maestropandy** [oracle/opengrok#3974]
When running indexer with ctags, exit with below warnings

```
org.opensolaris.opengrok.analysis.Ctags$1 run
WARNING: Error from ctags: ctags: Warning: Language "pascal" already defined
```

Opengrok version: **opengrok-1.0-v3** 
ctags version : Exuberant **Ctags 5.8**

**Comment by maestropandy** [comment]
If its warning, there should be a way opengrok should ignore/skip and proceed indexing, but instead its exit.

**Comment by vladak** [comment]
If the indexer exited, it was because of something else, definitely not the above ctags related warning.

Anyhow, 1.0 is too old to deal with here. After all, new OpenGrok releases dropped the support for Exuberant ctags and only Universal ctags is supported.

**Comment by vladak** [comment]
also, dup of #1205
