### ISSUE TITLE
create an eclipse-plugin for opengrok search tool (Bugzilla #1066)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#399]
status NEW severity _enhancement_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2008-04-09 11:22:36 +0000, Hemang Lavana wrote:

> Provide an eclipse plugin for code search functionality so that developers using eclipse IDE can simply type in a code search bar and find results right in their IDE environment.
> 
> Hemang.

**Comment by ahornace** [comment]
This was implemented in https://github.com/OpenGrok/addons -> however, I think it is broken due to recent REST API changes. PRs are welcome to keep it up to date.
