### ISSUE TITLE
Docker image should have ssh client fot git ssh:// pull/fetch

### ISSUE THREAD

**Issue by rgroux** [oracle/opengrok#4005]
**Is your feature request related to a problem? Please describe.**
i try tu use git repo clone with ssh access, so i need to have **openssh-client** in the docker image

**Describe the solution you'd like**
i made a PR, but i ca nnot signe the OCA, so could you add openssh-client to the installed package inside the image ?

```diff
diff --git a/Dockerfile b/Dockerfile
index b2eb487498..6b00bf8a56 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -46,7 +46,7 @@ LABEL maintainer="https://github.com/oracle/opengrok"
 # hadolint ignore=DL3008,DL3009
 RUN apt-get update && \
     apt-get install --no-install-recommends -y git subversion mercurial unzip inotify-tools python3 python3-pip \
-    python3-venv python3-setuptools
+    python3-venv python3-setuptools openssh-client

 # compile and install universal-ctags
 # hadolint ignore=DL3003,DL3008
```

**Describe alternatives you've considered**
until now i pull the image, add the openssh-client inside and then pull this one

**Comment by vladak** [comment]
Will do; please close the PR.

**Comment by rgroux** [comment]
Thanks a lot 👍
