### ISSUE TITLE
OpenGrok will NULL def on SRC_ROOT when configure file is put in web.xml (Bugzilla #11007)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#402]
status NEW severity _normal_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-08-28 08:59:21 +0000, Edward OCallaghan wrote:

> Good day,
> 
> OpenGrok will NULL def on SRC_ROOT when configure file is put in web.xml
> 
> Fortunately I fixed the problem now and I don't have the trace at hand however I can explain how to recreate it.
> 
> If you don't comment out:
> 
>   ^M
> 
> Then OpenGrok will claim that:
> 
>   <context-param>^M
>     <param-name>SRC_ROOT</param-name>^M
>     <param-value>/sourcegate/aurorauxsource/sourcetree</param-value>^M
>     <description>REQUIRED: Full path to source tree</description>^M
>   </context-param>^M
> 
> Is not correct, even though it maybe correct and fine.
> 
> What OpenGrok _should_ do, is check that configuration.xml exists before using it.
> 
> Hope this is clear on what I mean.
> 
> Regards,
> Edward O'Callaghan.

**Comment by tulinkry** [comment]
I’m not sure what it’s reported here. Handling invalid source roots is already implemented.

**Comment by ahornace** [comment]
Closing as per @tulinkry 's comment
