### ISSUE TITLE
Automatic list symbols when input something in Definition or Symbol

### ISSUE THREAD

**Issue by zhaojh329** [oracle/opengrok#4025]
Automatic list symbols when input something in Definition or Symbol.

As show:
![image](https://user-images.githubusercontent.com/28673295/183893752-797ae453-4768-481e-8300-13a493486101.png)

**Comment by vladak** [comment]
Um, you mean [Suggester](https://github.com/oracle/opengrok/wiki/Suggester) ? That has been present in OpenGrok for quite some time.
