### ISSUE TITLE
Duplicate history entries due to merge commits

### ISSUE THREAD

**Issue by jwehler** [oracle/opengrok#4027]
**Describe the bug**
Clicking on History for a file shows duplicate commit entries (same hash) in a git based repository. This appears to be tied to merge commits from one branch (mainline) into the development branch that contains the actual commit. Each time the mainline is merged into the dev branch it results in another entry in OG history. This problem has been around for awhile. I believe it started after the switch to using JGit.

OpenGrok 1.7.35 (Docker)

**Screenshots**
![og_merge_commit_history](https://user-images.githubusercontent.com/54180433/184263225-a7058b2f-97f3-47c2-9e2d-ff3465b91cf7.PNG)

**Comment by vladak** [comment]
So, whenever a merge commit is done, even files that were not changed in that commit receive the extra entry in the history ?

**Comment by dpsi** [comment]
I have been seeing this (duplicate history) too for the past few releases. My workaround is to wipe the index/history/etc for the affected repo and reindex. 
I did not dig much further, but since you mention merge commits cause it I will keep an eye out.
