### ISSUE TITLE
foot.jspf not found

### ISSUE THREAD

**Issue by nitinpuranik** [oracle/opengrok#4048]
Long time Opengrok user here. Love it, use it everyday. Since opengrok installation isn't an easy process, I even wrote an installation guide ([Link](https://nitinpuranik.medium.com/how-to-install-tomcat-and-opengrok-on-windows-e39f7f910348)) for absolute dummies. Google search for opengrok installation ranks my post at the very top :)

So it feels like I've lost an arm with this "ChronicleMap" issue I've run into lately. Any help would greatly be appreciated.

OS: Windows 11 Home

java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

Apache Tomcat: 10.0.26

Ctags: 2022-09-29/p5.9.20220925.0-7-g9072199

Opengrok: 1.7.35

The indexer seems to run just fine. Here's a screenshot.
![Index](https://user-images.githubusercontent.com/3022225/193118769-65acbdde-bc17-4d10-a749-b3ac38cda074.png)

Then I make sure the web.xml file points to the right configuration.xml, and launch the Tomcat server with its provided startup.bat script. This is where I get the ChronicleMap "SEVERE" error. Here's the screenshot.
![Apache](https://user-images.githubusercontent.com/3022225/193119406-b621e2bf-1690-4e52-97e0-6f4637f2fc36.png)

Tomcat eventually comes up fine and I get the welcome page at localhost:8080. But localhost:8080/source throws this error:
![browser](https://user-images.githubusercontent.com/3022225/193119965-9e400bd1-1038-4d5d-a8e3-1e2d8b5906e9.png)

Please help! Browsing code sucks without Opengrok :(

**Comment by vladak** [comment]
The ChronicleMap log message is just a red herring. The inability to find `foot.jspf` is the main problem.

**Comment by vladak** [comment]
A dup of #4050

**Comment by nitinpuranik** [comment]
Thanks Vlad! Changing "foot.jspf" to "/foot.jspf" fixed the issue. So happy to have opengrok back :)
