### ISSUE TITLE
Can't run on Tomcat 10.1: JSP file [foot.jspf] not found

### ISSUE THREAD

**Issue by novikovag** [oracle/opengrok#4050]
Under Windows 10 I was getting the following error
```

There was an error!
The source root path has not been configured! Please configure your webapp.

/index.jsp (line: [66], column: [2]) JSP file [foot.jspf] not found
```

In file webapps\source\index.jsp I changed line 68

`include file="foot.jspf"`

to

`include file="/foot.jspf"
`

And seems all works fine

**Comment by vladak** [comment]
There has been another foot.jspf report lately, also on Windows.

**Comment by vladak** [comment]
This is also reproducible with Tomcat 10.1.0 on Linux.

**Comment by vladak** [comment]
When loading the index page, I can see a number of successful attempts to get `foot.jspf` and then bunch of these:
```
[pid 475749] stat(".../apache-tomcat-10.1.0/webapps/opengrok_web_war/WEB-INF/tags/foot.jspf",  <unfinished ...>
[pid 475617] <... gettid resumed>)      = 475617
[pid 475749] <... stat resumed>0x7f9ae38f5100) = -1 ENOENT (No such file or directory)
```
which likely cause the "not found" error.

The `WEB-INF/tags` directory is the location where various JSTL files reside. `index.jsp` includes these files and this seems to change the search directory in Tomcat, at least in the recent versions.
