### ISSUE TITLE
display real change time stamps in directory listing

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4087]
The problem with directory listing currently is that it uses file-system time stamps which can be a bit misleading. If the mirror of particular repository was around long enough, then the timestamps would reflect the changes in individual files, however for repositories reindexed from scratch, the time stamps of files will be initially the same. The file-system time stamps might reflect the history of the files or might not.

Code wise, this would change this: https://github.com/oracle/opengrok/blob/8a7aa08e2f11ac1acfba209e18a1444600fe18df/opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java#L685-L691

Once the file history cache is converted to use suitable serialization scheme is implemented for #3539, it would make it possible to address this limitation by manually decoding the part of serialized history that contains the latest changeset date (to avoid unnecessary I/O), similarly how this is done in `FileAnnotationCache` to retrieve the revision ID.

**Comment by vladak** [comment]
The limitation of this approach is that directory based timestamps will have to remain the same. A different approach would be to use the index documents - there are already per directory documents for the LOC counts.

**Comment by vladak** [comment]
The trouble with the per directory dates derived from changeset dates is that while the LOC documents can be used for file changes/additions (grab the date from the latest history entry in file history cache and register it with the count aggregator), if there is a single removed file in a directory tree and no other changes, there is no reasonable way how to extract the date of the changeset that removed that file and pass it on.

So, I am thinking about implementing this just for regular files and leave the directory dates reflect their file system time, however I am not sure if that would not be confusing.

**Comment by vladak** [comment]
One thing I like about the file dates coming from history cache is that it also allows to display information about the last commit in the file listing, say in the form of some hovering window when one passes mouse cursor over the file name.

**Comment by ChristopheBordieu** [comment]
> Another alternative would be to avoid displaying the directory dates and fetch the regular file dates from history cache.

I think it is a good idea, at least for Git repositories. For other SCMs, maybe different managements would be needed.
With Git, you commit files and not directories, so I would like knowing the commit dates for files. And I don't really care the date for directories.
The timestamp available in the OG homepage is enough to know when was run the last indexing (because it is run for all projects at once on our instances).
