### ISSUE TITLE
upgrade to jflex 1.9.1 and remove the workaround for lex scanners limits

### ISSUE THREAD

**Issue by tarzanek** [oracle/opengrok#4170]
jflex 1.9.0 is out and
https://github.com/jflex-de/jflex/issues/203
got fixed and jflex now introduces:
(https://github.com/jflex-de/jflex/issues/197 https://github.com/jflex-de/jflex/pull/1045 )
```
%token_size_limit (<identifier>|<number>)
```
which makes the workaround of manually patching generated lexical scanner obsolete, 
though I see @vladak removed it ?!?!?
https://github.com/oracle/opengrok/commit/d051e170ebfdcd5eaca944e0de2228fb2030f164
(I don't see 1.8 fixes it ... )
so it needs to be set where applicable so OpenGrok is in sync with lucene limits and their tokenizers

also https://github.com/jflex-de/jflex/issues/542 is fixed so https://github.com/oracle/opengrok/blob/master/pom.xml#L348
can be cleaned up

**Comment by sreenath-tm** [comment]
Hi I would like to work on this issue can you assign this issue to me

**Comment by vladak** [comment]
> Hi I would like to work on this issue can you assign this issue to me
> 

just submit a PR
