### ISSUE TITLE
provide RESTful or web-services (Bugzilla #12863)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#422]
status NEW severity _enhancement_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-11-24 18:15:53 +0000, Hemang Lavana wrote:

> It would be great to have RESTful or web-services provided by the backend for search, xref, etc so that this tool can be easily integrated into other applications.

On 2009-11-25 04:52:28 +0000, Lubos Kosco wrote:

> version 0.8 (or 0.8.1) have all the pages conforming to XHTML strict (I made sure they all pass validator.w3.org ...) ... meaning that you can easily parse the data from direct http requests, since they come back as xml valid documents (hence you can just consume it like it is ;) ). The structure is obvious and we plan to stick with it (if it will be changed, we will announce it) ...
> 
> what more would we gain by implementing REST or web service ?

**Comment by faywong** [comment]
@pombredanne What's the query syntax in detail?

**Comment by pombredanne** [comment]
@faywong No ide: You can check #799 and the commit https://github.com/OpenGrok/OpenGrok/pull/799/files
#978 tracks creating doc but nothing seems to have been done. I cannot find any test code either
@tarzanek @vladak would you have some doc or some samples?

@faywong the code is there: https://github.com/OpenGrok/OpenGrok/blob/8319a89aaa06ff36af7fb04086caf078421086cf/src/org/opensolaris/opengrok/web/JSONSearchServlet.java

**Comment by pombredanne** [comment]
@faywong if you figure it out, you could contribute a doc page ;)

**Comment by tarzanek** [comment]
nope, I don't have any docs :(
all reverse engineer or utsl, or @ralphmayr needs to come to the rescue here

**Comment by faywong** [comment]
@tarzanek The syntax is 
```bash
{host}/{webapp_name}/json?freetext={keyword}&maxresults=80...
```

{webapp_name} is the name of war archive, for example "source" in the default build configure.

the other query parameters are defined as:
```java
private static final String PARAM_DEF = "def";
private static final String PARAM_SYMBOL = "symbol";
private static final String PARAM_PATH = "path";
private static final String PARAM_HIST = "hist";
private static final String PARAM_MAXRESULTS = "maxresults";
private static final String ATTRIBUTE_DIRECTORY = "directory";
private static final String ATTRIBUTE_FILENAME = "filename";
private static final String ATTRIBUTE_LINENO = "lineno";
private static final String ATTRIBUTE_LINE = "line";
private static final String ATTRIBUTE_PATH = "path";
private static final String ATTRIBUTE_RESULTS = "results";
private static final String ATTRIBUTE_DURATION = "duration";
private static final String ATTRIBUTE_RESULT_COUNT = "resultcount";
```

**Comment by pombredanne** [comment]
Actually rather:
The following are the available query parameters: freetext, def, symbol, path and hist.

**Comment by faywong** [comment]
@pombredanne 
Yes, you're right. The fields prefixed with "ATTRIBUTE_" are attributes in the result json string.
 
Take this response for example:
![image](https://cloud.githubusercontent.com/assets/1934627/11387094/61a9758e-9362-11e5-901f-89a9b654ead7.png)

So the following are the available query parameters: **maxresults**, **freetext**, **def**, **symbol**, **path** and **hist**.

**Comment by tarzanek** [comment]
@faywong @pombredanne 
good stuff, can one of you create some doc around this and put it into doc directory?
I'll gladly review and merge such pull request! ;)

**Comment by tarzanek** [comment]
ev. a wiki could be created too, wondering if you can create wiki pages (or only edit?)

**Comment by faywong** [comment]
I have created a [wiki page](https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-web-services) around the query syntax, please review it(forgive my pool english).

**Comment by tarzanek** [comment]
lovely! thank you @faywong 
I will ideally take it into doc so it will be part of .zip distro too

**Comment by pombredanne** [comment]
@faywong your English is better any day that my Chinese!
That said, I wonder if you could post the JSON snippet example as text in triple quotes rather than an image?

**Comment by faywong** [comment]
@pombredanne I have refined it. Please review [it](https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-web-services#response-example).

**Comment by pombredanne** [comment]
On Tue, Dec 15, 2015 at 10:17 AM, faywong <notifications@github.com> wrote:
> @pombredanne I have refined it. Please review it.

It looks good to me!
I wonder if adding a list of the options/fields rather than just
listing the Java definition would be better?
With may some explanation of what each means?

**Comment by faywong** [comment]
What you propose is reasonable. I will try to add proper explanations when i am free.

**Comment by earonesty** [comment]
+1

**Comment by jjacobsson** [comment]
At the risk of committing a heinous act of necromancy in writing in this very old thread, would there be any chance of an &offset= or similar to allow for paging of the results? I would dig in there myself but I don't java.

**Comment by tarzanek** [comment]
@jjacobsson open a new issue for this enhancement ... fwiw implementation would be very easy and the needful java knowledge to implement it can be learned within few hours (challenge accepted? ;-) ?)
