### ISSUE TITLE
Default connectTimeout (3s) is too small for large database

### ISSUE THREAD

**Issue by ChristopheBordieu** [oracle/opengrok#4229]
Hi @vladak 

After I installed OG 1.9.1 on my UAT environment, I got severe error when starting indexing.
Debugging, I found the reason is: when you check the connection to webapp provided via `-U webappURL` argument, getting `webappURL/api//v1/configuration`, you use a default connect timeout of 3s ([here](https://github.com/oracle/opengrok/blob/26ea64252630c5ad81b398ac8b6ab6c4c679d2fd/opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java#L591)).
With huge number of projects and repositories, this default is too small.
With a curl command to get the configuration, I found I need at least ~15s to get the answer (+2100 projects, +37k repos).
Adding to the indexer options `--connectTimeout 60`, I was able to go on indexing from scratch my projects.

Would it be possible this default is increased to a longer value like 30 or 60s?

**Comment by vladak** [comment]
The `/configuration` endpoint is too heavy due to the locking etc. involved. I will introduce dedicated endpoint for pinging the webapp and also will raise the default timeout.

**Comment by ChristopheBordieu** [comment]
Many thanks @vladak for the quick enhancement!
It works ok now.
