### ISSUE TITLE
OpenGrok should be able to index all branches in a single copy of a repository (Bugzilla #13344)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#425]
status NEW severity _enhancement_ in component _scm_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-12-15 02:20:26 +0000, Kate Ebneter wrote:

> Currently, if you want to index multiple branches in a git repository, you have to have separate clones with the appropriate branch checked out in each one. While this works, it's clumsy, especially for repositories with lots of branches. It would be much better if OpenGrok could index all the branches in a single clone, perhaps even a bare clone (one with no working copy). This should be possible, but it would require using some of git's plumbing commands, or perhaps JGit (the pure-Java implementation of git).

**Comment by pomac303** [comment]
JGit should also improve the performance since all caches can be kept in memory - this is something that has been grinding-my-gears^tm while I've been setting up a OpenGrok server for some users

**Comment by vladak** [comment]
It would be good if someone proposed possible solutions. I guess there should be a option to enable the behavior. Should all branches be indexed or just some ? (selection, certain number of most recent branches , ...) Where would indexer keep these branches ? How the results would be presented ?  Should the branches be treated as separated projects or introduce concept of pseudo-sub-projects ?

Also, I am not sure I got the point about storing the caches in memory - would they have to be reindexed after each restart of the webapp ?

**Comment by vladak** [comment]
Also, this is not specific to git only. Similarly, one might want to do the same thing for tags withing each branch.

**Comment by jimklimov** [comment]
Is this a duplicate / another aspect of #923 ?

**Comment by vladak** [comment]
The JGit transition is in progress (#1113). For getting the history it is actually slower than executing `git log` (#3544).
