### ISSUE TITLE
easier configuration procedure (Bugzilla #13619)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#428]
status ACCEPTED severity _normal_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

On 2009-12-29 23:34:59 +0000, Cristi Măgherușan wrote:

> The current configuration procedure is cumbersome and error-prone.
> 
> Opengrok should have a more user-friendly configuration process, avoiding the manual editing of any of the scripts. 
> 
> The settings could be defined in an independent config file (like /etc/opengrok.conf), which would be sourced by all the scripts at runtime.
> 
> Optionally, an additional script may be created in order to modify the web.inf file inside the source WAR file at install time so that the users won't have to extract and then re-compress it themselves after main configuration file changes. The location to the source.war file could be specified in the main config so this could work even when updating opengrok.

On 2009-12-31 08:35:01 +0000, Lubos Kosco wrote:

> Can you please try:
> 
> http://hub.opensolaris.org/bin/view/Project+opengrok/installdescription
> 
> and let me know if it fixes your problem ? ;)
> 
> thnx
> Lubos

On 2010-01-01 21:53:47 +0000, Cristi Măgherușan wrote:

> Thanks Lubos,
> 
> Sorry for not reading the manual first. I installed it before when it was about at  version 0.6 and then it was different.
> 
> I tried it and it kinda worked (History is grayed out and I can't seem to fix it), but this approach is set to use /var/opengrok, or otherwise it expects variables from the environment or even editing the script. 
> 
> I still believe that an independent config file should be provided and it should contain all the stuff that may need to be set by the user, and heavily commented with instructions (the squid config is a good example :)
> 
> The WAR can already be handled as in my proposal, so that is fine as it is, IMHO.
> 
> Regards,
> Cristi

**Comment by tulinkry** [comment]
I think this is no longer relevant. A candidate for closing.

**Comment by vladak** [comment]
Yes, the Python scripts reworked the problem area.
