### ISSUE TITLE
DirectoryListingTest should use a repository data

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4292]
After PR #4275, the `DirectoryListingTest` deserves overhaul to properly cover the setup where directory listing dates come from history cache. The way this should be addressed, I think, is to get rid of the `FileEntry` and use a repository from test data instead.

**Comment by igmtz** [comment]
Hello @vladak I'm trying to understand this issue. As I understand, in the `DirectoryLisntingTest` doesn't have to create the class `FileEntry` inside the test so the solution would be create a repository and its implementation with the functions used there - create(), compareTo(), getHref(), getFilename(),  getDateValue(), getSize(), validateEntry() -  and use this repo in the test file. Is that correct?

**Comment by vladak** [comment]
> Hello @vladak I'm trying to understand this issue. As I understand, in the `DirectoryLisntingTest` doesn't have to create the class `FileEntry` inside the test so the solution would be create a repository and its implementation with the functions used there - create(), compareTo(), getHref(), getFilename(), getDateValue(), getSize(), validateEntry() - and use this repo in the test file. Is that correct?

Basically, the files/directories that are used to verify the listing behavior are created using the `FileEntry#create()`. Instead of using that, the tests should use files from one of the repositories so that history cache can be created. I have a fix in the works (PR #4295), however it could be improved even further.
