### ISSUE TITLE
option -w should die (Bugzilla #13985)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#431]
status NEW severity _minor_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-01-20 08:05:25 +0000, Lubos Kosco wrote:

> the price for getting rid of -w is bigger xrefs, which need to generate proper paths instead of just /source/<servlet> ....
> what we gain is, that we can name the webapp anyhow without the need to reindex the sources
> 
> fix is quite easy - adding a generator of proper URL path pointer for generated xref links ( ../../../ ), the question is, whether it will be worth it, since the webapp you just name once, but the xref index size increase for this will be like 10-20% (which means more traffic and more disk space usage)
> 
> I tried finding another solution, like generate a base meta header, but that will not help here

**Comment by idodeclare** [comment]
@tarzanek , I have a fix for this in 2eddb0822 in my PR queue which takes advantage of recent xref enhancements where all underlying source is XML-escaped. Thus any instances of `"href=\"/source/"` are actual OpenGrok links and thus can be easily revised to target the true `request.getContextPath()` without the need to re-index source (except for users formerly using `-w` who need to re-index back to the static `/source/`).

In fact you can have multiple servlet instances running and using the same `/var/opengrok/data`. You can also set the ROOT context to `source.war`, and it works correctly.

**Comment by tarzanek** [comment]
woa! @idodeclare RESPECT!
let me have a look at the changeset, but feel free to open a PR
btw. I'd really like to know how you manage to pull all this code together (any special recipe? or you have a Jarvis that helps you? ;-) )

**Comment by tarzanek** [comment]
@idodeclare only one concern - your change will break caching of xref, no?
and increase cpu usage of opengrok server, won't it?

**Comment by idodeclare** [comment]
Luckily it will be a deterministic transformation for a given URL (e.g., to `/source/s?`, `/s?`, or `/arbitrary/path/s?` depending on the `source.war` being served from different context paths) so if a caching mechanism is active it will not be thwarted.

The transformation is done by JFlex for a single static match — and its state machine is efficient — so I do not believe there should be a perceptible change in load.

**Comment by idodeclare** [comment]
>  I'd really like to know how you manage to pull all this code together (any special recipe? or you have a Jarvis that helps you? ;-) )

:-) — I'm just finding satisfaction in this project lately.

**Comment by tarzanek** [comment]
the concern is still valid, since a lot of generated urls can be found inside the xref itself ... (to defs/refs/...)
we cache xrefs on the disk, so they just can be sent like that
in such case they will always be sent anew - OR - as you said will be cached but by the application container, rather than by app itself (and I don't have a clue, if this scales ... )

**Comment by tarzanek** [comment]
(I am not saying it won't work, but I see a price there ... )

**Comment by tarzanek** [comment]
yeah - and the use case is - you generate the index, then you move webapp whether the cached file will regenerate ...

and I have a feeling that just changing  src/org/opensolaris/opengrok/web/Util.java
might not be enough ... webapp fetches the file from .gz-ed xref directly ...

**Comment by idodeclare** [comment]
Lubos, if you examine the .gz-ed xref, you'll see just HTML fragments: a `<script type="text/javascript">` element followed by the preformatted lines — i.e., lines like `<a class="l" name="1" href="#1">1</a>`....

So `list.jsp` currently is composing pages anyway. `list.jsp` has the HTML `!DOCTYPE` and the containing `<html>` and `<body>` elements (plus `<head>`); `list.jsp` reads the .gz-ed xref fragments and incorporates that content into the served result.

This patch adds a cheap, JFlex-based transformation of that incorporation. The .gz-ed xref fragments remain as-is on disk regardless of the context path at which you deploy `source.war`.

**Comment by tarzanek** [comment]
AH AAAH!
so I forgot that we made a change to dynamic links already ... OK, my bad ... then your patch will just work perfectly fine!
great, so let's get it merged

**Comment by tarzanek** [comment]
but then ... looking at gzipped xref I see:

```
<a class="l" name="101" href="#101">101</a><span class='fold-space'>&nbsp;</span>    <b>private</b> <a href="/source/s?defs=Filter&amp;project=OpenGrok" class="intelliWindow-symbol" data-definition-place="undefined-in-file">Filter</a> <a class="xfld" name="includedNames"/><a href="/source/s?refs=includedNames&amp;project=OpenGrok" class="xfld intelliWindow-symbol" data-definition-place="def">includedNames</a>&#59;
```
so I hope we're on the same page ... those "/source/s? ... " links will be fixed too?

**Comment by tarzanek** [comment]
the code that does that is:
https://github.com/oracle/opengrok/blob/master/web/list.jsp#L297

**Comment by tarzanek** [comment]
but then we're back to caching mechanism of application server ...

**Comment by idodeclare** [comment]
> let's go for it, it will be fun

This is blocked on `feature/LOC` too due to `list.jsp` changes there.

**Comment by tarzanek** [comment]
hmm, OK, I see where you're coming from with gunzip ... 
I still didn't speak to vlad or Krystof about the LOC changes ... (and I started to review them, bear with us please)
