### ISSUE TITLE
Linking about signing OCA is broken

### ISSUE THREAD

**Issue by davidd8663** [oracle/opengrok#4335]
**Describe the bug**
The link in CONTRIBUTING.md is not valid.  Should probably point to https://oca.opensource.oracle.com/ instead.

**To Reproduce**
[The current link](http://www.oracle.com/technetwork/community/oca-486395.html) returns a page that says "We can't find the page you were looking for."

**Expected behavior**
Link should actually arrive at details on how to sign the OCA.

**Comment by vladak** [comment]
Thanks for the report, will fix that.
