### ISSUE TITLE
using --noIndex hangs the indexer

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4374]
As identified on https://github.com/oracle/opengrok/discussions/4373, running indexer with the --noIndex option causes it to hang. This is because of the changes in 2af6dbcfa3babf9d3d0ca3506ebe41bb64e8c4f5. After these changes the `IndexParallelizer` is no longer bounced which results in a `OpenGrok-ctags-watcher` thread to stay around after `main()` is done. The thread appeared because ctags is run via `validateUniversalCtags()` in `prepareIndexer()`.

**Comment by tarzanek** [comment]
@vladak you have a typo in patch https://github.com/oracle/opengrok/commit/1ea5adf9c047598efd554ef1a9b516ab4f125621
"ctags" word got lost from
https://github.com/oracle/opengrok/blob/master/opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java#L1055
