### ISSUE TITLE
Java method calls incorrectly classified as definitions (Bugzilla #14924)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#440]
status CAUSEKNOWN severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

Original attachment names and IDs:
- _navigate.png_ (ID 4440)

On 2010-02-27 15:24:31 +0000, Knut Anders Hatlen wrote:

> Given this Java class (Test.java)
> 
> public class Test {
>   void f() {
>     synchronized (this) {
>       notifyAll();
>     }
>   }
> }
> 
> a definition search for notifyAll will list a match in Test.java. But there's no definition of notifyAll in that file, just a call to it.

On 2010-02-27 16:26:59 +0000, Knut Anders Hatlen wrote:

> This appears to be a ctags problem. Running ctags (5.8) on the file gives this output:
> 
> Test    src/Test.java   /^public class Test {$/;"       c
> f       src/Test.java   /^  void f() {$/;"      m       class:Test
> 
> Test is recognized as a class and f is recognized as a method, and those are the only definitions in the file. This looks correct.
> 
> When OpenGrok performs indexing, it runs ctags with --java-kinds=+l to enable tagging of local variables. Then the output is changed to this:
> 
> Test    src/Test.java   /^public class Test {$/;"       c
> f       src/Test.java   /^  void f() {$/;"      m       class:Test
> notifyAll       src/Test.java   /^      notifyAll();$/;"        m
> 
> For some reason, ctags now thinks notifyAll is a method definition.
> 
> Or maybe we are just misinterpreting the ctags output? The real method definition in the file (f) is marked as a method in class:Test, whereas notifyAll is just marked as a method. Perhaps we need to ignore those methods that are not associated with a class?

On 2010-02-27 17:12:08 +0000, Knut Anders Hatlen wrote:

> Could be this ctags bug: https://sourceforge.net/tracker/?func=detail&aid=2726391&group_id=6556&atid=106556

On 2011-01-03 09:28:27 +0000, Knut Anders Hatlen wrote:

> Filed a new bug against CTags (in case it's not the same problem as the C++ one): https://sourceforge.net/tracker/?func=detail&aid=3150230&group_id=6556&atid=106556

On 2011-01-03 09:34:50 +0000, Knut Anders Hatlen wrote:

> (In reply to comment # 1)
> 
> > Or maybe we are just misinterpreting the ctags output? The real method
> > definition in the file (f) is marked as a method in class:Test, whereas
> > notifyAll is just marked as a method. Perhaps we need to ignore those methods
> > that are not associated with a class?
> 
> I've tried this, but then some actual method definitions were left out.

On 2011-01-03 09:52:24 +0000, Knut Anders Hatlen wrote:

> Created attachment 4440
> Screenshot of the navigation panel
> 
> This bug is very visible in the new navigation panel. See the attached screenshot (navigation panel for src/org/opensolaris/opengrok/FileLogFormatter.java). All the methods marked with red are not really method definitions.

On 2011-01-03 09:58:17 +0000, Lubos Kosco wrote:

> so what about leaving the local vars out from ctags kinds?
> I'd rather miss stuff than have a LOT of false positives ...

On 2011-01-03 11:43:46 +0000, Knut Anders Hatlen wrote:

> (In reply to comment # 6)
> 
> > so what about leaving the local vars out from ctags kinds?
> > I'd rather miss stuff than have a LOT of false positives ...
> 
> I agree that the false positives in the method list is more annoying than missing local variables (at least the way I use OpenGrok). But, of course, it's not an ideal solution... If there are no objections, I'll disable local variables for Java files only. This bug should be kept open so that we remember to re-enable local variables when/if the upstream bug is fixed.

On 2011-01-03 13:10:19 +0000, Knut Anders Hatlen wrote:

> Checked in suggested workaround.
> changeset:   1148:b42a9515757a
> 
> Leaving bug open with status CAUSEKNOWN.

**Comment by tulinkry** [comment]
I tried this for the sample class and notifyAll is stored as a symbol rather than a definition. Navigate window shows only Test and f. So not relevant anymore.
