### ISSUE TITLE
Is there anyway to scale?

### ISSUE THREAD

**Issue by demonguy** [oracle/opengrok#4405]
We have multiple Big AOSP repostitories.
Now it's very large that we need multiple machines to hold them.
Is there anyway to use same domain for these different machines?

**Comment by vladak** [comment]
> We have multiple Big AOSP repostitories.
> Now it's very large that we need multiple machines to hold them.
> Is there anyway to use same domain for these different machines?

What is the limit you are bumping into ? Indexing time, memory constraint, storage space or something else ?
