### ISSUE TITLE
Support for YAML extension for file filtering

### ISSUE THREAD

**Issue by azizthanawala** [oracle/opengrok#4420]
**Is your feature request related to a problem? Please describe.**
I would like to understand if there .yaml support present in opengrok.

**Describe the solution you'd like**
.yaml to be available as a filtering option when selecting the "type" of file the search should be limited to.

I'll be happy to contribute if the support is not available, provided a little bit of guidance on getting started.
I know the ticket is bit stingy on the details but it's rather a simple query. 

Thank you,
Aziz.

**Comment by ginoaugustine** [comment]
Yaml support is already implemented through #4353, please try out with latest version of opengrok
