### ISSUE TITLE
replace direct invocation of setup.py

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#4429]
The tools builds started complaining not so recently about [`python setup.py install` being deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).  It is probably just a matter of time before the builds start failing.

https://github.com/oracle/opengrok/blob/a8851abcd9791357806af966e37f2323af2861d7/tools/pom.xml#L248-L249 should be replaced with something else.

Same goes for any direct invocation of `setup.py`, e.g. generating the Python package or running the tests.

**Comment by tarangchikhalia** [comment]
@vladak, I want to work on this Issue. Can you assign it to me?

**Comment by vladak** [comment]
> @vladak, I want to work on this Issue. Can you assign it to me?

just submit a PR.
