### ISSUE TITLE
Support retrieving function definitions for a project path

### ISSUE THREAD

**Issue by ronvgs** [oracle/opengrok#4508]
Im working on a project and one of the tasks requires getting all function definitions from all code(cpp) files in a project path.

**Describe the solution you'd like**
I would like opengrok api to take the project path as input and return the info(return type, name, params list, enclosing type name, namespace, etc) related to each function definition found in each source file in that path.

**Describe alternatives you've considered**
None.

**Additional context**
NA

**Comment by vladak** [comment]
Also, the above suggests the API endpoint would be limited to single file, i.e.be similar to the pre-existing [genre API](https://opengrok.docs.apiary.io/#reference/0/file-genre/get-file-genre), i.e. `api/v1/file/defs?path=`

**Comment by vladak** [comment]
Also, pagination should be considered as the "tags" data for some files can be significant. On the other hand, I don't want to complicate this API endpoint too much.

**Comment by vladak** [comment]
Speaking of simplicity, it would seem to me that the API should merely present the list of tags, i.e. the contents of `Definitions#tags` list. The items of the list, `Tag` objects, contain various interesting pieces of information: https://github.com/oracle/opengrok/blob/6fb5eeefacb6d6322a342cd458d2dca9f6273893/opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Definitions.java#L209-L242

If one needs the line to tag mapping, that could be reconstructed from the list.

Would that match your use case @ronvgs ?
