### ISSUE TITLE
`READONLY_CONFIG_FILE` doesn't work in docker containers

### ISSUE THREAD

**Issue by MasterAwesome** [oracle/opengrok#4523]
When READONLY_CONFIG_FILE is used, the file name passed to merge_config_files is the object as a string which is serialized and written into disk. This always results in a file named <tempfile._TemporaryFileWrapper object at 0x7fa12bf82350> on disk instead of the actual name and doesn't actually merge configs.

Bug is present in `master` branch of opengrok

**To Reproduce**
- Run the `docker` container built using the `Dockerfile`
- Set `-e READONLY_CONFIG_FILE` environment variable

**Expected behavior**
Merging configs succeeds

**Observed behavior**
Merging configs uses the object instead of the actual FS path `<tempfile._TemporaryFileWrapper object at 0x7fa12bf82350>` resulting in merge failure + read-only-config to not be applied.

**Comment by vladak** [comment]
This was introduced with the rework of how config merge is called (#4509).
