### ISSUE TITLE
check Dockerfile for vulnerability alerts periodically and automatically

### ISSUE THREAD

**Issue by dkr91** [oracle/opengrok#4598]
**Is your feature request related to a problem? Please describe.**
Hey, is it Possible to Update TomCat with Renovate

**Describe the solution you'd like**
Automatic new TomCat version if there are CVEs within TomCat via RenovateBot or Dependabot

**Describe alternatives you've considered**
Use Renovate or Dependabot

**Additional context**
https://github.com/oracle/opengrok/pull/4595
https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts
https://github.com/apps/renovate
https://github.com/dependabot

**Comment by vladak** [comment]
The Renovate app is 3rd party so I'd have to request permission to use it. On the other hand, it seems Dockerfile scanning can be performed by Dependabot (built into Github) so I will explore it.

For the record, there is a weekly CodeQL scan of the repo (enabled for the 3 main languages) is done via https://github.com/oracle/opengrok/blob/master/.github/workflows/codeql-analysis.yml.

**Comment by vladak** [comment]
There is also some automated tool scanning the repository for version updates, however I am not sure whether it is able to evaluate Dockerfiles.

**Comment by vladak** [comment]
The PR was merged. Now let's wait till next Monday when the next Dependabot scan should occur.

**Comment by vladak** [comment]
Seems to work fine: https://github.com/oracle/opengrok/network/updates/865389462 , specifically:
```
updater | 2024/08/05 18:36:47 INFO <job_865389462> Latest version is 10.1.26-jdk17
updater | 2024/08/05 18:36:47 INFO <job_865389462> No update needed for tomcat 10.1.26-jdk17
```
