### ISSUE TITLE
Thread strategy on File parsing is not optimal (Bugzilla #16137)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#460]
status NEW severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-06-02 09:50:13 +0000,  wrote:

> I have 16 svn-repositories
> 
> the history parsing of all repositories is parallel and I understand the strategy,
> one thread per repository.
> 
> But then, the files of all repositories are inspected and my repositories have a high difference in the amount of file. The result is, that the last 4 hours one thread is working on the last repository.
> 
> In my mind it would be better, to have for that step a pool of threads and a list of files to inspect and each thread takes the next file.

On 2011-11-17 22:54:17 +0000, sp wrote:

> While there is a command line option to limit the number of threads for indexing (-T n), the lack of a similar or shared option to limit the number of threads when generating the history cache is unfortunate. On a 24 core machine with with -T 4 and 20+ projects, this can bring the machine to its knees.  Please consider making the -T flag also apply to the history cache generation process.

**Comment by vladak** [comment]
The number of threads participating concurrently in creating history can be limited with the `org.opensolaris.opengrok.history.NumCacheThreads` system property (after the changes for #728). By default it is set to `availableProcessors()` in `getHistoryExecutor()`.

It's still a question whether it should be following the `-T` value.

**Comment by tulinkry** [comment]
The strategy was reworked with #1936. A candidate for closing.

**Comment by vladak** [comment]
Yes, the parallelism is not on project level anymore.
