### ISSUE TITLE
The ctags built in the Docker image doesn't support the XML language

### ISSUE THREAD

**Issue by gnustavo** [oracle/opengrok#4628]
**Describe the bug**

Using the [opengrok/docker](https://hub.docker.com/r/opengrok/docker) Docker image I see several log messages like the following during the indexing of a repository:

```
'Aug 02, 2024 4:51:48 PM org.opengrok.indexer.analysis.Ctags lambda$run$0', 'WARNING: Error from ctags: ctags: Warning: Unknown language "XML:+.asax.Asax.ASAX" in "langmap" option', 
'Aug 02, 2024 4:51:48 PM org.opengrok.indexer.analysis.Ctags lambda$run$0', 'WARNING: Error from ctags: ctags: Warning: Unknown language "XML:+.asax.Asax.ASAX" in "langmap" option', 
'Aug 02, 2024 4:51:48 PM org.opengrok.indexer.analysis.Ctags lambda$run$0', 'WARNING: Error from ctags: ctags: Warning: Unknown language "XML:+.ascx.Ascx.ASCX" in "langmap" option', 
'Aug 02, 2024 4:51:48 PM org.opengrok.indexer.analysis.Ctags lambda$run$0', 'WARNING: Error from ctags: ctags: Warning: Unknown language "XML:+.aspx.Aspx.ASPX" in "langmap" option', 
```

This means that the `ctags` command built into the image doesn't support the XML language.

**To Reproduce**
Instantiate a container with the latest image (I'm using tag 1.13.17) and watch its logs while it indexes a repository.

**Expected behavior**
I expect not to see those warnings and that `ctags` does support XML.

**Suggested solution**
Just install the `libxml2-dev` package in the Dockerfile before compiling `ctags`.

**Comment by vladak** [comment]
Thanks for very well formed issue ! care to submit a PR ?

**Comment by gnustavo** [comment]
Hi @vladak. I was going to submit a PR but the CONTRIBUTING document says that I need to sign a [OCA](https://oca.opensource.oracle.com/). Since my employer have claims to the IP I create I would have to work here to get an approval.

For such a tiny contribution I think it's too much of a hassle.

Would you be willing to recreate [this commit](https://github.com/gnustavo/opengrok/commit/8fa3b18f658fa6afdb21601ab9f7b9eefd708507) yourself?

**Comment by vladak** [comment]
> Hi @vladak. I was going to submit a PR but the CONTRIBUTING document says that I need to sign a [OCA](https://oca.opensource.oracle.com/). Since my employer have claims to the IP I create I would have to work here to get an approval.
> 
> For such a tiny contribution I think it's too much of a hassle.
> 
> Would you be willing to recreate [this commit](https://github.com/gnustavo/opengrok/commit/8fa3b18f658fa6afdb21601ab9f7b9eefd708507) yourself?

Absolutely, however I encourage external contributions whenever possible. The OCA process is pretty swift from my experience, at least on Oracle side.

**Comment by gnustavo** [comment]
Thank you!
