### ISSUE TITLE
Would like to be able to assemble a set of projects using symlinks (Bugzilla #16735)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#469]
status NEW severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-08-06 01:02:42 +0000, Dan Price wrote:

> I noticed that work is going on to provide some support for symlinks.
> 
> I would like to be able to assemble a group of projects together using
> symlinks.
> 
> For example, let's say I have
> 
> /blah/blah/foo-gui-1.0
> /blah/blah/foo-gui-2.0
> /blah/blah/foo-gui-3.0
> /bug/yub/foo-cli-1.0
> /bug/yub/foo-cli-2.0
> /bug/yub/foo-cli-3.0
> 
> I'd like to be able to group things together-- for example, I'd like
> to be able to do:
> 
> /opengrok/foo-1.0
> /opengrok/foo-1.0/foo-gui-1.0 -> /blah/blah/foo-gui-1.0
> /opengrok/foo-1.0/foo-cli-1.0 -> /bug/yub/foo-gui-1.0
> 
> Presently, doing this causes opengrok to complain that
> /opengrok/foo-1.0/foo-gui-1.0 and /opengrok/foo-1.0/foo-cli-1.0
> are non-local symlinks.

On 2010-08-06 08:13:20 +0000, Lubos Kosco wrote:

> Hi,
> I _think_ what you want to achieve below is already possible with latest trunk
> 
> option -N
> ( http://grok.czech.sun.com:8080/source/xref/opengrok-trunk/src/org/opensolaris/opengrok/index/CommandLineOptions.java# 81 )
> 
> should be able to make it explicit
> _but_ I think if the symlink is inside the source root or repository (don't remember from top of my head) it will be followed too by default ...
> 
> can you please test below with a trunk build ?
> (you can fetch a hourly build from : http://helius.sfbay.sun.com:7000/hudson/job/OGPackage/ws/dist/ )
> 
> cheers
> L

On 2010-08-09 18:58:22 +0000, Patrick Higgins wrote:

> (In reply to comment # 1)
> 
> > _but_ I think if the symlink is inside the source root or repository (don't
> > remember from top of my head) it will be followed too by default ...
> 
> The symlink will only be followed by default if it is in the source root directory (not a subdirectory of source root).
> 
> In Dan's example, if /opengrok was the source root and /opengrok/foo-1.0 is a directory in the source root, then all the symlinks that assemble the project will not be recognized without explict -N options for each.
> 
> If /opengrok/foo-1.0 is the source root, then they will be picked up automatically.

**Comment by lllama** [comment]
I have a similar requirement. I would like to be able to symlink a number of projects under the source root. However, it would be really useful to be able to put duplicate projects under different names. For example, I have a number of projects with third party libraries and would like to have these directories included in one version and excluded in another.

It would be great to be able to use `cp -as` to replicate a project and then go in manually and delete the directories.

At the moment, I can browse these with xref, but cannot view the file contents (get a `FileNotFoundException` due to the path not being relative to the source dir) and it doesn't look like an index is being generated either.

Hope that makes sense.

**Comment by lllama** [comment]
Looking into the `-N` option, I think I would have to generate a config where all files are listed as allowed symlinks. (which would be ~ 140,000 entries in the config in the current project). Would it possible to add a flag that allows all symlinks to be followed?

**Comment by Z4rc** [comment]
> Looking into the `-N` option, I think I would have to generate a config where all files are listed as allowed symlinks. (which would be ~ 140,000 entries in the config in the current project). Would it possible to add a flag that allows all symlinks to be followed?

I am also very interested in that. Is there any possibility to follow all symlinks?
