### ISSUE TITLE
Simplify browsing code by providing code folding (Bugzilla #16904)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#474]
status NEW severity _enhancement_ in component _analyzer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2010-08-24 09:27:53 +0000, Patrik Larsson wrote:

> I do not know if this enhancement request should be put on the indexer, analyzer or the webapp. In the end all three will be affected when this enhancement is implemented.
> 
> When browsing long files/functions it can shorten the time needed to understand code if it is folded as many IDEs can do.
> 
> Providing this enhancement would probably mean extending the language parsers to include information on where code blocks start and end in the specific language which are used to fold the code correctly.
> 
> I cannot tell at this point what version of HTML is required for this to work or if AJAX or similar must be used.
> 
> I did search this bugzilla but could not find anything similar to this enhancement request.
> 
> Thank you so much for an awesome tool!

On 2010-08-25 14:30:11 +0000, Lubos Kosco wrote:

> this is definitely a great idea
> I think even in current state one could implement a button which would collapse all comments (since they have a class, so css flip triggered by js to hide it will work)
> obviously for more functionality analyzer(xref generator) changes would be needed
> if you want you can start on adding a button for collapsing comments, I should be able to help with review of code and push to main trunk ...
> 
> thnx for your help
> Lubos

**Comment by tulinkry** [comment]
Collapsing is implemented with the scopes #897

**Comment by ahornace** [comment]
Closing as per @tulinkry 's comment
