### ISSUE TITLE
CSS problems when searching many projects at once (Bugzilla #18623)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#510]
status NEW severity _major_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

Original attachment names and IDs:
- _opengrok-CSS-corruption.png_ (ID 4552)

On 2011-06-27 12:23:28 +0000, Vladimir Kotal wrote:

> From internal bug report:
> ---
> 
> Do this search:
> - go to http://<opengrok-instance>:8080/source/index.jsp
> - 'select all' gates
> - run Filepath search for valid package name, for instance
> 
> You get to with a different links. If you click on the link, the page is empty (for me).
> 
> It's behaving strange, sometimes if I copy the URL to a new browser tab,
> it displays.
> ## It seems that the huge search somehow tires opengrok, who is then unwilling to serve any content :)
> 
> It seems like CSS corruption of sorts.

On 2011-06-27 12:26:52 +0000, Vladimir Kotal wrote:

> Sometimes I even get empty page as a result of the search.

On 2011-06-27 12:35:43 +0000, Vladimir Kotal wrote:

> Created attachment 4552
> screenshot demonstrating the problem
> 
> this is how it looks like when opengrok displays the result of all-project search.

On 2011-06-27 15:21:45 +0000, Jens Elkner wrote:

> Hmmm, works for me, but it may depend on the repos (I just got 7099 results).
> 
> I wonder whether you would get the same behavior with a recent opengrok-snapshot...
> 
> For now I would blame the browser ;-) If you don't think so, the html source of what you browser got would be interesting...
> 
> BTW: What version do you use.
> 
> Lubos/Knut/Trond: Is it possible to add the version fields in bugzilla, so that people can submit this info, when reporting a bug?

On 2011-06-27 15:39:51 +0000, Vladimir Kotal wrote:

> (In reply to comment # 3)
> 
> > Hmmm, works for me, but it may depend on the repos (I just got 7099 results).
> > 
> > I wonder whether you would get the same behavior with a recent
> > opengrok-snapshot...
> 
> Can't test unfortunately, since our deployment is sort of operationally critical.
> 
> > For now I would blame the browser ;-) If you don't think so, the html source of
> > what you browser got would be interesting...
> 
> I will try to gather and attach it.
> 
> > BTW: What version do you use.
> 
> We use 0.10:
> 
>    PKGINST:  OSOLopengrok
>       NAME:  OpenGrok
>   CATEGORY:  application
>       ARCH:  generic
>    VERSION:  0.10
>    BASEDIR:  /
>     VENDOR:  http://www.opensolaris.org/os/project/opengrok/
>     PSTAMP:  tecra20110105110109
>   INSTDATE:  Jan 05 2011 17:44
>      EMAIL:  opengrok[at]sun.com
>     STATUS:  completely installed
>      FILES:       46 installed pathnames
>                    1 shared pathnames
>                   23 directories
>                    3 executables
>                15308 blocks used (approx)

On 2011-06-27 15:42:27 +0000, Vladimir Kotal wrote:

> I saved the page produced by opengrok and it's missing header and footer:
> 
> $ tail -5 /Saved/search 
> 
> Served by OpenGrok http://www.opensolaris.org/os/project/opengrok/
> 
> Indexes created Mon Jun 27 14:26:51 CEST 2011
> 
> $ head -2 /Saved/search 
> </source/>
> Home </source/>   Sort by: _relevance_ | last modified time

On 2011-06-27 15:51:08 +0000, Vladimir Kotal wrote:

> (In reply to comment # 5)
> 
> snip
> 
> > $ head -2 /Saved/search 
> > </source/>
> > Home </source/>    Sort by: _relevance_ | last modified time
> 
> and then it goes like this:
> 
> <search?&path=Makefile&project=...
> 
> the same line in the normal results looks like this:
> 
> <table border="0" width="100%"><tr><td><a href="/source/" id="home">Home</a></td><td align="right">Sort by: <b>relevance</b> | <a href="search?&amp;q=path%3AMakefile&amp;project=...

**Comment by tulinkry** [comment]
I don't see this happening for 1.1.2.
