### ISSUE TITLE
Add a haltOnFailure property in indexer (Bugzilla #18658)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#512]
status NEW severity _normal_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2011-07-04 11:31:07 +0000, gaurav kochhar wrote:

> I had a huge file (456M) an XML file in my repository.
> While indexing the project the indexer stops execution when it encounters this file, and hence the indexing is incomplete.
> 
> Please add a variable/flag which can be set while running indexer to continue execution even on such failures.
> E.g. JUnit plugins have "haltOnFailure" attribute.

On 2011-07-04 15:31:22 +0000, Knut Anders Hatlen wrote:

> This may have been fixed by bug # 18618. Now the indexer should try to continue also if it encounters an OutOfMemoryError when processing a file (assuming an OOME was causing the issue you saw). It doesn't prevent the OOME from happening, though.

**Comment by tulinkry** [comment]
No longer relevant.

**Comment by vladak** [comment]
Actually, I think we want quite the opposite - stop the indexer on OOM. Kind a of dup of #2649.
