### ISSUE TITLE
Search should be able to look only on specific type of object (Bugzilla #19048)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#520]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

On 2011-11-04 11:41:24 +0000, Zdenek Kotala wrote:

> It would be nice if I could specify what kind of definition I'm looking for. For example when I try to find msg() function it shows me also bunch of char *msg; results and so on.

**Comment by tulinkry** [comment]
Duplicate of #685 and can be closed.
