### ISSUE TITLE
If a git repository does not have a valid HEAD indexing breaks (Bugzilla #19163)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#527]
status NEW severity _minor_ in component _scm_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2012-02-05 19:09:36 +0000, Johan wrote:

> phb@opengrok:/var/lib/opengrok/src/opstools-misc$ git log
> fatal: bad default revision 'HEAD'
> 
> java.lang.RuntimeException: Failed to acquire random test lock; please verify filesystem for lock directory '/var/opengrok/data/spellIndex/opstools-misc' supports locking
>   at org.apache.lucene.store.NativeFSLockFactory.acquireTestLock(NativeFSLockFactory.java:103)
>   at org.apache.lucene.store.NativeFSLockFactory.makeLock(NativeFSLockFactory.java:142)
>   at org.apache.lucene.store.Directory.makeLock(Directory.java:106)
>   at org.apache.lucene.index.IndexWriter.init(IndexWriter.java:1058)
>   at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:882)
>   at org.apache.lucene.search.spell.SpellChecker.setSpellIndex(SpellChecker.java:142)
>   at org.apache.lucene.search.spell.SpellChecker.<init>(SpellChecker.java:110)
>   at org.apache.lucene.search.spell.SpellChecker.<init>(SpellChecker.java:124)
>   at org.apache.jsp.search_jsp._jspService(search_jsp.java:689)
>   at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
>   at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
>   at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
>   at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
>   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
>   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
>   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
>   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
>   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
>   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
>   at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
>   at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
>   at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
>   at java.lang.Thread.run(Thread.java:662)
> Caused by: org.apache.lucene.store.LockReleaseFailedException: Cannot forcefully unlock a NativeFSLock which is held by another indexer component: /var/opengrok/data/spellIndex/opstools-misc/lucene-....--3y5zar-test.lock
>   at org.apache.lucene.store.NativeFSLock.release(NativeFSLockFactory.java:329)
>   at org.apache.lucene.store.NativeFSLockFactory.acquireTestLock(NativeFSLockFactory.java:95)
>   ... 26 more
> 
> phb@opengrok:~$ ls -al /var/opengrok/data/spellIndex/opstools-misc
> total 24
> drwxr-xr-x   2 opengrok opengrok  4096 Jan 31 02:33 .
> drwxr-xr-x 548 opengrok opengrok 20480 Feb  4 02:34 ..
> 
> Workaround is simple, ensure no repositories like that exist in the directory that is being indexed. (We use git show-ref -q --verify refs/remotes/origin/master )

On 2012-02-06 08:28:43 +0000, Lubos Kosco wrote:

> this is a bit weird
> I think it shouldn't happen with latest binaries
> 
> afaik our executors have a timeout on forked commands
> 
> below stack shows this: an indexer is stuck indexing "opstools-misc"
> and another indexer was started in between (within maybe the timeout of above)
> 
> so basically you have 2 indexers running on the same box and they seem to clash, check ps axf (or ptree) and let us know
> - locking on lucene is supposed to be automatic, I removed forced options on lock clean ups because of that (and no one complained, so you're the first one)
> 
> the other Q can be, whether you use latest opengrok ;)
> 
> hmm?
> L
> 
> note that current 0.11rc and 0.10 didn't have big changes in this area, so the locking should be the same, however older opengrok versions had old locking, which was problematic sometimes

On 2012-02-06 09:43:10 +0000, Johan wrote:

> (In reply to comment # 1)
> 
> > this is a bit weird
> > I think it shouldn't happen with latest binaries
> > 
> > It is using opengrok 0.11, or at the very least 0.10 if I failed the upgrade somehow (There seems to be no UI-visible version # to verify?)
> > 
> > afaik our executors have a timeout on forked commands
> > 
> > below stack shows this: an indexer is stuck indexing "opstools-misc"
> > and another indexer was started in between (within maybe the timeout of above)
> > 
> > so basically you have 2 indexers running on the same box and they seem to
> > clash, check ps axf (or ptree) and let us know
> > 
> > No indexers running at all. It happened for us on 5 repositories, all exhibiting the above problem, so I'm really suspecting something w.r.t the git scm history.
> 
> All the other directories under /var/opengrok/data/spellIndex has a couple of files (
> 672 -rw-r--r--   1 opengrok opengrok 684629 Nov 28 23:07 _0.cfs
> 128 -rw-r--r--   1 opengrok opengrok 130345 Nov 28 23:07 _0.cfx
>   4 -rw-r--r--   1 opengrok opengrok     20 Nov 28 23:07 segments.gen
>   4 -rw-r--r--   1 opengrok opengrok    246 Nov 28 23:07 segment)
> 
> > - locking on lucene is supposed to be automatic, I removed forced options on
> >   lock clean ups because of that (and no one complained, so you're the first one)
> > 
> > the other Q can be, whether you use latest opengrok ;)
> > Well, most probably 0.11rc2 unless my installation failed and then it would be running 0.10.
> > 
> > hmm?
> > L
> > 
> > note that current 0.11rc and 0.10 didn't have big changes in this area, so the
> > locking should be the same, however older opengrok versions had old locking,
> > which was problematic sometimes

**Comment by SreyasSultan** [comment]
Hi Vladak,
Were to download the latest opengrok bin for Linux.
Thanks!

**Comment by vladak** [comment]
See the downloads on https://java.net/projects/opengrok/downloads

**Comment by SreyasSultan** [comment]
Will it support Apache Tomcat/7.0.52 version..?
which is the stable latest version 0.12.1.2 or 0.12.1.5

**Comment by vladak** [comment]
The latest stable is always the one with highest number (see https://github.com/OpenGrok/OpenGrok/releases and http://semver.org/), I believe it should work with Tomcat7.

**Comment by SreyasSultan** [comment]
Thanks for your response
Is Ctags are same for all version of opengrok..?
how to update the opengrok from opengrok-0.11.1 to opengrok-0.12.1.5..?

**Comment by vladak** [comment]
Yes, exuberant ctags that is. The upgrade depends on your system. If using the binary distro, then:
  - replace the contents
  - redeploy to Tomcat
  - remove indexes
  - reindex from scratch

**Comment by SreyasSultan** [comment]
how to remove the indexes..? or will it be removed automatically if we reindex..?

**Comment by vladak** [comment]
Definitely, indexes are not removed upon reindex. Depends on where are the indexes stored. I will assume they are stored on disk in your case (the alternative would be JavaDB). Go to your DATA_ROOT directory and remove everything under `index` and `historycache` directories.

**Comment by SreyasSultan** [comment]
If we try to deploy opengrok  it shows a fatal error as below 
"FATAL ERROR: Unable to determine Deployment Directory for  Tomcat - Aborting!"
From OpenGrok file I could able to see that it has problem in fetching the "DetermineWarDirectoryTomcat". After installing tomcat 8 in Linux, I couldn't find OPENGROK_TOMCAT_BASE in /var/lib/ folder

**Comment by vladak** [comment]
There are 3 variables used by the `OpenGrok` shell script relevant to Tomcat install:
  - `OPENGROK_APP_SERVER`: should say "Tomcat"
  - `OPENGROK_WAR_TARGET_TOMCAT`: should contain the `webapps` directory within the Tomcat installation
  - `OPENGROK_TOMCAT_BASE` should point to top-level Tomcat installation directory. The shell script assumes the `webapps` directory is subdirectory of this one.

If the heuristics in the shell script cannot find tomcat, it is sufficient to use the first 2 variables.

E.g.
```
OPENGROK_APP_SERVER=Tomcat
OPENGROK_WAR_TARGET_TOMCAT=/foo/bar/mytomcat/webapps
```

So, your task is now to find out where was Tomcat installed on your system and set the variables accordingly when running the `OpenGrok` shell script.

**Comment by SreyasSultan** [comment]
Thanks for your response
Is opengrok (0.12.1.5) be supported in tomcat 8..? Bocz am trying to deploy the opengrok in tomcat 8
# Supported Deployment Engines:
#   - Tomcat 7
#   - Tomcat 6

**Comment by vladak** [comment]
You can give it a try, in theory it should work.

**Comment by SreyasSultan** [comment]
Thanks for your response.
I have downgraded the tomcat to 7. Now I could successfully host opengrok in tomcat server.
But when I tried to index my source it throws below error
[root@XeroxBuild04 bin]# ./OpenGrok index
Loading the default instance configuration ...
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/opensolaris/opengrok/index/Indexer : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.opensolaris.opengrok.index.Indexer. Program will exit.
[root@XeroxBuild04 bin]#

**Comment by vladak** [comment]
It seems that JRE on the system is not compatible with the class files in the OpenGrok distribution. According to http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error the class files require J2SE 7. What Java versions are installed on the system ?

**Comment by SreyasSultan** [comment]
We have Installed java version is 
[root@Build04 bin]# javac -version
javac 1.6.0_20
so we have to install JDK 1.7 to fix this problem..?

**Comment by vladak** [comment]
JRE 1.7, yes. Or rebuild the 0.12-stable branch with JDK 1.6 (I assume this will work).

**Comment by SreyasSultan** [comment]
Could you please tell how to rebuild 0.12 opengrok with JDK 1.6..?

**Comment by tarzanek** [comment]
Well
I'd stick with jdk8 and latest branch if you want to build. Also use universal ctags.
Jdk6 is dead as is jdk7 face it as a fact.

**Comment by SreyasSultan** [comment]
Thanks. I could able to host opengrok(0.12) successfully with tomcat 8 and jdk 1.8. 
But SAD news is am getting "java.lang.OutOfMemoryError: Java heap space" even with latest opengrok itself. We have hosted only 1 project (4GB size).

**Comment by tarzanek** [comment]
even with latest?
ok, so you must have some file that triggers this behaviour, can you check which file gets indexed when you get OOM ?

**Comment by SreyasSultan** [comment]
Yes, we are using opengrok 0.12 version only. 
We have also tried to increase the java heap space as per http://crunchify.com/how-to-change-jvm-heap-setting-xms-xmx-of-tomcat/ 
In Opengrok log also, we couldn't find from which file it triggers OOM
According to logs
2015-10-28 13:14:58.852+0530 SEVERE t4033 IndexDatabase$1.run: Problem updating lucene index database:
java.lang.OutOfMemoryError: Java heap space
2015-10-28 13:15:14.159+0530 SEVERE t4032 IndexDatabase$1.run: Problem updating lucene index database:
java.lang.OutOfMemoryError: Java heap space

**Comment by tarzanek** [comment]
There should be another more verbose log in /var/opengrok/log, which will hopefully point out the name of file that caused the prob
And by latest I mean latest build from source code, which has some fixes (but is missing some, check issues for .js issues, where minified .js files can break ctags and how opengrok handles ctags output)

**Comment by vladak** [comment]
This discussion should be moved elsewhere asit is not I believe related to the original bug description anymore.

**Comment by SreyasSultan** [comment]
All those logs which I shared are taken from /var/opengrok/log folder only.
As vladak said let take this discussion on a separate issue. Please follow the below link I have created a new issue
https://github.com/OpenGrok/OpenGrok/issues/1019

**Comment by satswami** [comment]
@SreyasSultan @tarzanek Do You have a step by step guide for setting this up Linux machine please?

**Comment by tarzanek** [comment]
That is a mismatch of java versions
Most likely your java is too old

**Comment by SreyasSultan** [comment]
@vladak  @tarzanek  Could you please tell us how to index files with .doc, .docx, .txt files extension
