### ISSUE TITLE
indexer reports null directories (Bugzilla #19165)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#528]
status NEW severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2012-02-09 16:23:16 +0000, Vladimir Kotal wrote:

> Running 0.11 indexer for the first time in my source repository. Lots of messages about 'null' directory:
> 
> 2012-02-09 16:44:43.965+0100 FINE t10 Executor.registerErrorHandler: Installing default uncaught exception handler
> 2012-02-09 16:44:44.795+0100 FINE t10 Executor.exec: Executing command [/usr/bin/exctags, --version] in directory null
> 2012-02-09 16:44:44.822+0100 INFO t10 Indexer.prepareIndexer: Scanning for repositories...
> 2012-02-09 16:44:44.831+0100 FINE t10 Executor.exec: Executing command [cleartool, ?version] in directory null
> 2012-02-09 16:44:44.847+0100 FINE t10 Executor.exec: Executing command [p4, help] in directory null
> 2012-02-09 16:44:44.868+0100 FINE t10 Executor.exec: Executing command [/usr/bin/sccs, help, help] in directory null
> 2012-02-09 16:44:44.906+0100 CONFIG t10 HistoryGuru.addRepositories: Adding <org.opensolaris.opengrok.history.SCCSRepository> repository: </ws-local/foo>
> 2012-02-09 16:44:44.908+0100 FINE t10 Executor.exec: Executing command [/usr/bin/git, --help] in directory null
> 2012-02-09 16:44:44.954+0100 CONFIG t10 HistoryGuru.addRepositories: Adding <org.opensolaris.opengrok.history.GitRepository> repository: </ws-local/bar>
> 2012-02-09 16:44:44.955+0100 FINE t10 Executor.exec: Executing command [/usr/bin/hg] in directory null
> 
> The commands must be run in some concrete directory so the 'null' value is confusing.

On 2012-02-13 06:03:44 +0000, Jens Elkner wrote:

> Messages with a severity <= CONFIG are primary targeting developers/troubleshooters and thus do not need to be perfect for several reasons. So just set your log level to INFO/WARNING and don't care ;-)

**Comment by tulinkry** [comment]
I believe this is no longer an issue in current master.
