### ISSUE TITLE
logging consolidation (Bugzilla #19170)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#530]
status NEW severity _minor_ in component _misc_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

Original attachment names and IDs:
- _logging.patch_ (ID 4625)

On 2012-02-13 06:44:16 +0000, Jens Elkner wrote:

> Created attachment 4625
> patch
> 
> patch provides:
> - stack traces are never logged at a level >= CONFIG to avoid user annoyance
>   with one exception: the UncaughtExceptionHandler ;-)
> - each class logs to its own logger (FQCN) to allow a more fine grained, selective logging;
>   OpenGrokLogger is just used as very simple Logging Configurator
> - file and path names are usually enclosed in single quotes
> - commands and contents of a line in brackets ([])
> - warnings+ are usually always logged: no need to use formatter for those msgs

On 2012-02-14 20:44:23 +0000, Trond Norbye wrote:

> Can you split the patch into  multiple patches that fix one thing? The current patch fix some formatting, some bugfixing etc..

On 2012-02-14 23:51:10 +0000, Jens Elkner wrote:

> (In reply to comment # 1)
> 
> > Can you split the patch into  multiple patches that fix one thing? The current
> > patch fix some formatting, some bugfixing etc..
> 
> Hmmm, doesn't make sense to me.

On 2012-02-16 06:05:56 +0000, Trond Norbye wrote:

> What doesn't make any senese? To have a patch only fix related stuff?? Patches that fix completely unrelated stuff makes it way harder to back it out again if there is some problems with the patch. Last time we did push one of these patches through, and it pretty much blocked the release process for a long period of time since we couldn't back out the thing we had a regression in. 
> 
> As a rule of thumb one should consider splitting up a patch into multiple patches whenever you start typing the word "and" or start listing stuff in the commit when one is writing the commit message.

**Comment by tulinkry** [comment]
Another patch which wouldn't make sense to merge it today.
