### ISSUE TITLE
misc enhancement (Bugzilla #19183)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#537]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

Original attachment names and IDs:
- _patchsets1330-1357.tgz_ (ID 4631)

On 2012-02-22 06:34:19 +0000, Jens Elkner wrote:

> Created attachment 4631
> patch bundle
> 
> The attached patch bundle provides several enhancements, most important one's wrt. the web app - see patchsets for a more detailed description or just ask:
> 
> changeset:   1330:a8850f7d7017
> summary:     - new command line option -Z (enable status page)
> 
> changeset:   1331:b2c98bfe4263
> summary:     make index_body.html an include like {header,footer}_include
> 
> changeset:   1333:713825d4426c
> summary:     mv eclipse stuff to separate dir, adjust JspC class libs glassfish 3.1.2
> 
> changeset:   1334:c6ff1fbcbff0
> summary:     remove single quotes around configdir value
> 
> changeset:   1344:54e0c6162b3f
> summary:     satisfy java 1.6
> 
> changeset:   1345:4d1ff765944c
> summary:     merge latest changes from origin
> 
> changeset:   1346:b43d9e92554b
> summary:     ignore changes in .settings
> 
> changeset:   1347:7dcdf2876dc1
> summary:     ignore deprecated, add override, deprecated annotations
> 
> changeset:   1348:03b848411f89
> summary:     add option -E to disable xref file compression
> 
> changeset:   1349:2c97452fe3b3
> summary:     Backed out of changeset 1347:7dcdf2876dc1
> 
> changeset:   1350:4d69d4686eb5
> summary:     Merge with SHA: 2c97452fe3b3e5ecd2c5a220270349d265e25fbe
> 
> changeset:   1351:17cbd57d3156
> summary:     eclipse cleanup profile
> 
> changeset:   1352:dd0dc4a0e294
> summary:     add index launch config
> 
> changeset:   1353:daf3e643037c
> summary:     merge index launcher
> 
> changeset:   1354:09e388dc4be9
> summary:     fix label for
> 
> changeset:   1355:e98f333288dc
> summary:     add documentation
> 
> changeset:   1356:d1595f28ae3d
> summary:     refactor JS and give more control to the JS client app
> 
> changeset:   1357:ed1888336c51
> tag:         tip
> summary:     web app: reduce the bloat, avoid DOM changes as much as possible

**Comment by tulinkry** [comment]
I have no idea what is this, but I'd say we can close after the years.

**Comment by vladak** [comment]
Possibly. This is a reminder that we need to be more reactive w.r.t. pull requests.
