### ISSUE TITLE
add per browser instance configurable option to produce Javascript-less pages (Bugzilla #19193)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#542]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

Original attachment names and IDs:
- _PageSpeed-cached_page.png_ (ID 4635)

On 2012-03-12 12:25:05 +0000, Vladimir Kotal wrote:

> Some browsers (such as older Firefox 3.x/4.x) and hardware (Sunray, ipad, ...) have troubles rendering pages with long source code file because of heavy Javascript processing. For these use cases it might make sense to produce the pages without any Javascript.
> 
> This could be done with per-browser cookie.

On 2012-03-12 21:07:43 +0000, Jens Elkner wrote:

> (In reply to comment # 0)
> 
> > Some browsers (such as older Firefox 3.x/4.x) and hardware (Sunray, ipad, ...)
> > have troubles rendering pages with long source code file because of heavy
> > Javascript processing. For these use cases it might make sense to produce the
> > pages without any Javascript.
> 
> Wondering, whether you have any "data", which confirms this assumption? ...
> 
> > This could be done with per-browser cookie.
> 
> Igitt.

On 2012-03-13 08:11:29 +0000, Vladimir Kotal wrote:

> (In reply to comment # 1)
> 
> > (In reply to comment # 0)
> > 
> > > Some browsers (such as older Firefox 3.x/4.x) and hardware (Sunray, ipad, ...)
> > > have troubles rendering pages with long source code file because of heavy
> > > Javascript processing. For these use cases it might make sense to produce the
> > > pages without any Javascript.
> > 
> > Wondering, whether you have any "data", which confirms this assumption? ...
> 
> Based on first hand experience and also user reports. The sun4v based Sunrays are indeed quite slow for single thread processing like JS requires.

On 2012-03-13 12:28:29 +0000, Vladimir Kotal wrote:

> Created attachment 4635
> PageSpeed extansion measurement of cached source code file
> 
> tcp.c is one of the biggest files, it takes 4 seconds to fully load the page. PageSpeed Firefox extension says half of it is DOM load, another half would be JavaScript, I guess.

On 2012-03-14 07:08:58 +0000, Knut Anders Hatlen wrote:

> Which part of the javascript code is causing the problems on large source files? Is there some other mechanism (css, html?) that could be used instead of javascript to achieve the same? If it's possible to fix the root cause, I'd prefer that to adding more options/cookies.

On 2012-03-14 08:45:28 +0000, Vladimir Kotal wrote:

> (In reply to comment # 4)
> 
> > Which part of the javascript code is causing the problems on large source
> > files? Is there some other mechanism (css, html?) that could be used instead of
> > javascript to achieve the same? If it's possible to fix the root cause, I'd
> > prefer that to adding more options/cookies.
> 
> Not sure. Is there any way how to tell ?

On 2012-03-14 09:57:57 +0000, Knut Anders Hatlen wrote:

> (In reply to comment # 5)
> 
> > (In reply to comment # 4)
> > 
> > > Which part of the javascript code is causing the problems on large source
> > > files? Is there some other mechanism (css, html?) that could be used instead of
> > > javascript to achieve the same? If it's possible to fix the root cause, I'd
> > > prefer that to adding more options/cookies.
> > 
> > Not sure. Is there any way how to tell ?
> 
> I was thinking maybe someone who knew that part of the code could tell if there were parts that would run through every line in the source file. :) I've never debugged javascript code myself, so I wouldn't know...
> 
> There's of course the annotation and line number toggles that would process every line, but I'd assume they don't run unless the toggle buttons are actually clicked.

On 2012-03-20 06:14:51 +0000, Jens Elkner wrote:

> (In reply to comment # 6)
> 
> > (In reply to comment # 5)
> > 
> > > (In reply to comment # 4)
> > > 
> > > > Which part of the javascript code is causing the problems on large source
> > > > files?
> 
> Basically the problem with large files is not JS but the number of DOM nodes and structure of the page. If the page is structured in a way, that prevents the browser from calculating the box sizes early (e.g. to decide, whether to show a scrollbar or not), the only way to speed it up is to actually use JS to
> provided the required information. I.e. usually the perception of speed gets
> increased with such tricks, the overall "page ready" time gets slightly increased.  
> 
> > > > Is there some other mechanism (css, html?) that could be used instead of
> > > > javascript to achieve the same?
> 
> Wrt. CSS it is important to be specific as possible: I.e. IDs are usually cached and thus the entry node can be found very easy. On the other hand if one just say 'a b' the complete DOM structure needs to be worked through, which is obviously a little bit toxic. So e.g. '#id > a > b' is cheap, max walking depth is 2 ...
> 
> Wrt. html as said, the number of DOM nodes and layout is important. E.g. the current structure is still not perfect wrt. line numbers and annotations. If you think in terms of 3 boxes aligned side by side, where the first contains the line numbers, the 2nd the annotations and the 3rd the source, hide/show of the line number/annotation block can be really fast, since it would require a simple "image" blitting (shift left/right) only, instead of touching the DOM (which is really slow, since a priory DOM is considered to be slow) and re-rendering several times. Furthermore, since with the latest changes source gets emitted line oriented, there is no need to include line numbers in the xrefs anymore. Those can be calculated by JS on the fly (while the DOM/page components are loaded) and has the advantage, that the DOM doesn't need to be fully loaded, to know the final #content size (and the side effect to fix the copy-and-paste problem as well ;-)). That's at least the theory ;-)
> This requires of course another xref changes wrt. list.jsp, the html fragment in the file as well as the file format itself (to provide the number of lines first) ...
> 
> > > > If it's possible to fix the root cause, I'd
> > > > prefer that to adding more options/cookies.
> 
> Haven't had the time to look on the server side, how cookies are used right now, but IMHO it is the wrong approach (prevents proper caching). IMHO local storage is the way to go.  
> 
> > > Not sure. Is there any way how to tell ?
> > 
> > I was thinking maybe someone who knew that part of the code could tell if there
> > were parts that would run through every line in the source file. :)
> 
> As said, avoid DOM walking and modification as much as possible - so line numbers and annotations should be the next target ... 
> 
> > I've never
> > debugged javascript code myself, so I wouldn't know...
> 
> Pretty easy: Download the Firebug Add-On for firefox, load the debug enable components, e.g. http://src.iws.cs.ovgu.de/source/xref/opengrok-jel/web/static/opengrok-symbols-panel.js?debug, enable firebug for the page, enable "Script", select the script of interest in the left box and set a breakpoint somewhere ...
> 
> > There's of course the annotation and line number toggles that would process
> > every line, but I'd assume they don't run unless the toggle buttons are
> > actually clicked.
> 
> Yepp, but as said, that's not really necessary ...

**Comment by tulinkry** [comment]
I think with current javascript boom this issue is no longer relevant.

**Comment by vladak** [comment]
Actually, I am still getting complaints of slow page rendering.
