### ISSUE TITLE
Misc enhancements and bug fixes (Bugzilla #19194)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#543]
status NEW severity _normal_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

Original attachment names and IDs:
- _opengrok-patches.tgz_ (ID 4636)

On 2012-03-19 17:56:08 +0000, Jens Elkner wrote:

> Created attachment 4636
> changesets mentioned in the description
> 
> changeset:   1356:07929c1db0b2
> summary:     switch over from jQuery to YUI3
> 
> changeset:   1357:7e59b0ba2018
> summary:     fix defs window creation
> 
> changeset:   1358:c0423da71f8d
> summary:     fix project selection, add YUI module info to status page
> 
> changeset:   1359:4a0d1278d326
> summary:     cleanup build.xml - output of 'ant -projecthelp' should be spottable and consistent
> 
> changeset:   1360:29131f299b84
> summary:     add missing ${}
> 
> changeset:   1361:ca2042a84fb0
> summary:     use more complete YUI.Escape instead of home grown version
> 
> changeset:   1362:f005790afe66
> summary:     eclipse: add JS nature
> 
> changeset:   1363:2bcb81e4077d
> summary:     split opengrok.js, add yuicompression
> 
> changeset:   1364:bacb8cfb6fef
> summary:     use YUI3 widget for symbol list popup
> 
> changeset:   1365:d78adba8134b
> summary:     fix NPE if property file is n/a
> 
> changeset:   1366:57e41a6d7dbe
> summary:     # 19188: proper path encoding within URIs
> 
> changeset:   1367:cdb5b6d69abf
> summary:     # 19178: fix eftar fd leak
> 
> changeset:   1368:a52110fd1c60
> summary:     # 19184: README file contents not displayed, URIencode all 'rawPath's
> 
> changeset:   1369:5a7a3749b868
> summary:     fix jsp error
> 
> changeset:   1370:d34c747688ba
> summary:     optimze xref file structure wrt. faster loading/display,

On 2012-03-20 09:25:40 +0000, Lubos Kosco wrote:

> thanks for all the changes Jens !
> (can I ask what's the advanteges of yui over jquery? google and lots of other companies are using jquery over yui, so why do we want to move away ? :) )
> 
> I'll try to review along the rest and get them pushed
> don't expect high speed though, I am a bit ill and we finish a product release in my day job, so we talk weeks here
> I'll try to ask Knuth and Trond to help ...
> 
> thank you & keep them coming
> L

On 2012-03-20 17:10:00 +0000, Jens Elkner wrote:

> (In reply to comment # 1)
> 
> > thanks for all the changes Jens !
> 
> NP :)
> 
> > (can I ask what's the advanteges of yui over jquery?
> 
> Yes, of course.
> 
> > google and lots of other
> > companies are using jquery over yui,
> 
> Well, that doesn't says much as well as that Microsoft/Nokia took "ownership" of it ;-). Not sure, whether "over yui" applies at all - I can imagine, that they just tried jQuery (because there seems to be a kind of hype right now) and because it fits their needs, they didn't look around for anything else ...
> 
> > so why do we want to move away ? :)
> 
> First: I think any JS framework can be used to accomplish the required stuff. But the question is: where you wanna go?
> 
> I see jQuery more or less like PHP in its early days: a very loosely coupled collection of perl scripts and YUI like Java ~ 1.3.
> 
> I.e. if one just needs to quickly hack something, jQuery is IMHO ok. But if one wanna write long living, maintainable applications, jQuery gets quickly out of scope - one needs more than just a little bit of "syntactic sugar". And here YUI slips in: One can simply extend the framework and keep its own bits separately (as shown with the symbols panel), i.e. usually no need to hack the framework itself and thus can take advantage of updates/fixes without much trouble. Also it is probably a better choice for test adiccted developers (e.g. YUI Yeti) ;-).
> That's basically it (there is much more, but probably needs hours to write it down ;-)).
> 
> Some IMHO valuable links I've found for this are:
> http://dsheiko.com/weblog/yui3-vs-jquery
> http://www.youtube.com/watch?v=x0OuYNlnCZ8&feature=youtube_gdata_player
> http://yuilibrary.com/theater/
> 
> > I'll try to review along the rest and get them pushed
> > don't expect high speed though, I am a bit ill and we finish a product release
> > in my day job, so we talk weeks here
> 
> Yepp, no problem. Semester break is almost over, so I'll probably slow down as well ;-)
> 
> > I'll try to ask Knuth and Trond to help ...
> > 
> > thank you & keep them coming
> 
> Have fun,
> jel.

**Comment by tulinkry** [comment]
Another patch which wouldn't make sense to merge it today.
