### ISSUE TITLE
OpenGrok leaks file descriptors (Bugzilla #19215)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#556]
status NEW severity _critical_ in component _agent_ for _---_
Reported in version _unspecified_ on platform _i86pc/i386_
Assigned to: Trond Norbye

Original attachment names and IDs:
- _message.eml_ (ID 4665)

On 2012-06-04 10:07:48 +0000, Gustavo Lopes wrote:

> Each search is leaking 6 additional five descriptors in the mrcurial tip ccc849159329. I haven't tested earlier versions. Forcing garbage collection doesn't close these file descriptors.
> 
> The opened file descriptors look like this:
> 
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 94 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.frq
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 95 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.prx
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 96 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.fdt
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 97 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.fdx
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 98 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.nrm
> lr-x------ 1 jetty nogroup 64 Jun  4 05:00 99 -> /opt/opengrok-new/data/index/PHP_TRUNK/_9.tis

On 2012-06-04 10:33:56 +0000, Gustavo Lopes wrote:

> This is 6 file descriptors per project. If you select 10 projects, it leaks 60 file descriptors.

On 2012-06-04 11:31:38 +0000, Gustavo Lopes wrote:

> I did a binary search and this problem was introduced in 1b9fa840d93b when upgrading to lucene 3.5.0

On 2012-06-04 12:47:05 +0000, Lubos Kosco wrote:

> current trunk is on 3.6.0 , can you rebuild and retry?
> 
> also release version is on older lucene than 3.5, so it seems you're somewhere between ;)
> 
> hmm?
> L

On 2012-06-04 13:34:37 +0000, Gustavo Lopes wrote:

> I tried with lucene 3.6.0, as that's what's the development tip uses.
> 
> Anyway, I would guess the problem is that the IndexReaders instantiated on each search request in SearchHelper are not closed.
> 
> This commit fixes the issue for me:
> 
> https://bitbucket.org/cataphract/opengrok/changeset/0b023ef9643e

On 2012-06-04 13:47:18 +0000, Lubos Kosco wrote:

> cool patch
> 
> would you be willing to send it upstream?
> 
> if you have an OCA# I can accept it immediately
> if not you can get a # by following the few steps http://hub.opensolaris.org/bin/view/Main/oracle_contributor_agreement
> (I know, more work, but it's just about sending a mail with a picture to Oracle, if you'd agree to the terms our lawyers setup for external contributions to OpenSolaris projects ... )
> 
> thanks in advance
> Lubos

On 2012-06-04 14:03:59 +0000, Gustavo Lopes wrote:

> (In reply to comment # 5)
> 
> > cool patch
> > 
> > would you be willing to send it upstream?
> > 
> > if you have an OCA# I can accept it immediately
> > if not you can get a # by following the few steps
> > http://hub.opensolaris.org/bin/view/Main/oracle_contributor_agreement
> > (I know, more work, but it's just about sending a mail with a picture to
> > Oracle, if you'd agree to the terms our lawyers setup for external
> > contributions to OpenSolaris projects ... )
> 
> Very well, I'll sign it, but before merging this still needs some changes. For instance, the project appears to use spaces, not tabs and RuntimeEnvironment is not really the place where to have the pooled threads and cached IndexReaders because that class is about configuration (it's in the org.opensolaris.opengrok.configuration package). I was just trying to get the application server not to die owing to hitting file descriptor limit.
> 
> So I'll clean up the patch and send the agreement.

On 2012-06-04 15:11:43 +0000, Lubos Kosco wrote:

> thank you, Knut, me or Trond will review once you're done and push with your name

On 2012-06-07 20:48:19 +0000, Gustavo Lopes wrote:

> I've cleaned it up on https://bitbucket.org/cataphract/opengrok/changeset/f7f76d48ef8c
> 
> I've also sent the documents, I'll notify you when I get a response.

On 2012-06-08 11:33:00 +0000, Lubos Kosco wrote:

> (In reply to comment # 8)
> 
> > I've cleaned it up on
> > https://bitbucket.org/cataphract/opengrok/changeset/f7f76d48ef8c
> > 
> > I've also sent the documents, I'll notify you when I get a response.
> 
> thank you for this, looks ok
> once you send me the OCA number I will accept this patch

On 2012-06-08 13:05:08 +0000, Jens Elkner wrote:

> +1 for the idea to share IndexReaders.
> 
> However, AFAICS, the implementation is buggy and has IMHO other problems. 
> 
> BTW: The given URL doesn't show all changes and doesn't provide a proper "diff" for the change wrt. the osol tip (prevents me from having a closer look at it ...).

On 2012-06-08 13:11:53 +0000, Lubos Kosco wrote:

> (In reply to comment # 10)
> 
> > +1 for the idea to share IndexReaders.
> > 
> > However, AFAICS, the implementation is buggy and has IMHO other problems. 
> 
> which ones in particular? 
> I am sure Gustavo can address them
> 
> > BTW: The given URL doesn't show all changes and doesn't provide a proper "diff"
> > for the change wrt. the osol tip (prevents me from having a closer look at it
> > ...).
> 
> I pulled his repo and did a diff between osol tip and latest change

On 2012-06-08 14:18:15 +0000, Gustavo Lopes wrote:

> I created a new branch with just the pertinent changes cherry picked:
> 
> https://bitbucket.org/cataphract/opengrok/compare/bug19215..default

On 2012-06-08 14:24:28 +0000, Gustavo Lopes wrote:

> Make that
> 
> https://bitbucket.org/cataphract/opengrok/compare/bug19215..ce0b759
> 
> now that I've updated the default branch.

On 2012-06-11 13:27:27 +0000, Gustavo Lopes wrote:

> I have updated my branch on bitbucket to address several points raised on the code review.

On 2012-06-11 13:39:58 +0000, Gustavo Lopes wrote:

> Created attachment 4665
> Code review reply
> 
> This is my reply to the code review. Unfortunately, Jens mail server rejected my e-mail (said it was spam) and the message to opengrok-dev was held in moderation.

On 2012-06-12 07:29:06 +0000, Gustavo Lopes wrote:

> My Oracle Contributor Agreement number is OS0489.

On 2012-06-19 12:51:17 +0000, Lubos Kosco wrote:

> Thank you Gustavo
> 
> I spoke with Trond and Knut and we will take some more time to review
> 
> for the time being I only pushed Jenses small change that somehow mitigates this problem
> ( changeset:   1381:d2b04bc47598 , note that I didn't test it large scale, I hope Jens did ;) )
> 
> We will try to tackle this patch request along others in the queue (e.g. Jenses about the jquery->yui and some more, Trond already started doing some justice :) )
> 
> thanks for the patience
> Lubos
> 
> (In reply to comment # 16)
> 
> > My Oracle Contributor Agreement number is OS0489.

**Comment by tulinkry** [comment]
I'm not sure if this is relevant now. I don't know about any other reported issue for this.

**Comment by vladak** [comment]
Well, it would not hurt to go through the changesets mentioned above to see if there is any value there.

**Comment by vladak** [comment]
I looked at the changes and it basically implements similar idea as was done in #1132 (i.e. map of `SearcherManager` objects and reuse of `IndexSearcher` objects), hence closing.
