### ISSUE TITLE
Problem with OpenGrok and ClearCase

### ISSUE THREAD

**Issue by avirosenfeld** [oracle/opengrok#58]
When starting Catalina run, I get the following two problems:

WARNING: ClearCaseRepository not working (missing binaries?):  SNAPSHOT-VIEW-DIR

May 02, 2013 3:11:36 PM org.opensolaris.opengrok.web.WebappListener contextInitialized
SEVERE: OpenGrok: Failed to start configuration listener thread

Any idea, Anyone?

Thanks,
Avi

**Comment by vladak** [comment]
`startConfigurationListenerThread` got removed with the transition to the RESTful API, hence closing. The issue has too little information about the Clearcase problem.
