### ISSUE TITLE
allow classication/tagging of projects (Bugzilla #5881)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#599]
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Trond Norbye

On 2008-12-17 08:35:53 +0000, Vladimir Kotal wrote:

> For sites with bigger project count it often happens that the list of projects on the front page is a) too big (see bug # 5879) b) difficult to navigate.
> 
> For better navigation, the projects can be divided into multiple groups,
> e.g. according to tags [*]. In the list of projects there would be a separator
> between multiple project groups.
> 
> [*] e.g. ON gates, Testing gates, etc.

**Comment by tulinkry** [comment]
I think we chose different path than this and groupings is implemented. A candidate for closing.

**Comment by vladak** [comment]
Yes, this is a dup of project groups enhancement.
