### ISSUE TITLE
Patch: make indexer quieter when not in verbose mode (Bugzilla #8291)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#611]
status NEW severity _minor_ in component _indexer_ for _---_
Reported in version _unspecified_ on platform _Other_
Assigned to: Trond Norbye

On 2009-04-20 04:08:57 +0000, Julian Clifton-Thompson wrote:

> Hi,
> 
> I wrote the following trivial patch to ensure that OpenGrok is quiet when not running in verbose mode (helps reduce email spam when running via cron :-):
> 
> --- opengrok-0.7-src/src/org/opensolaris/opengrok/index/Indexer.java.orig       2008-10-17 11:15:23.000000000 +0100
> +++ opengrok-0.7-src/src/org/opensolaris/opengrok/index/Indexer.java    2009-04-20 11:39:25.819595000 +0100
> @@ -469,7 +469,9 @@
>              throws IOException {
>          RuntimeEnvironment env = RuntimeEnvironment.getInstance();
>          env.register();
> -        log.info("Starting indexExecution");
> -        if (env.isVerbose()) {
> -            log.info("Starting indexExecution");
> - ```
>      }
>   
>    ExecutorService executor = Executors.newFixedThreadPool(noThreads);
>   ```
> 
> I really appreciate this excellent tool :-)
> 
> Kind regards,
> Julian

**Comment by tulinkry** [comment]
This is no longer relevant.

**Comment by vladak** [comment]
Yes, the verbose flag is currently just manipulating log level.
