### ISSUE TITLE
/index/ of several versions of the same source tree should be efficient

### ISSUE THREAD

**Issue by cnst** [oracle/opengrok#635]
It would be useful if it was possible to index several version of the same tree without the linear growth in the disc space requirements, especially for the Lucene `/index/` database.

This is likely a very non-trivial problem, but a feature that would be very nice to have for projects like the open-source BSD systems, where each version by itself already requires at least 1GB of OpenGrok's disc space.  Android also comes to mind.

Alternatively, it might be interesting to investigate whether some kind of filesystem compression already solves this problem, even if partially so.

My main concern is the `/index/` itself.  In order to be fast and cacheable, it has to be reasonably small, and linear growth is not acceptable.  The `/source/` and `/xref/` are secondary (and `/historycache/` would likely be shareable anyways, if it is not, that's a separate and non-directly-related issue).

**Comment by vladak** [comment]
Unlikely to be ever addressed, hence closing.
