### ISSUE TITLE
per project history cache generation

### ISSUE THREAD

**Issue by cdgz** [oracle/opengrok#639]
Simple question: why ./OpenGrok {index, update, updateQuietly} tasks use always -H option ("Generate history cache for all repositories") enabled in UpdateGeneratedData()? 

Does it make sense to have it configurable, e.g. 

if [ -z "${OPENGROK_HISTORY_CACHE}" ]
then
    HISTORY_CACHE="-H"
fi

and call only StdInvocation() with ${HISTORY_CACHE} among opts?

Everytime I update OpenGrok package, I tweak bin/OpenGrok to remove -H, since it takes quite long to index our repo histories

**Comment by vladak** [comment]
JavaDB (or storing history cache in any database) is no longer supported by OpenGrok so this part got simpler.

**Comment by vladak** [comment]
To summarize what I think is needed:
  - disable history generation by default in `OpenGrok` shell script
  - introduce per-project tunable that will allow generating history cache only for some projects

**Comment by vladak** [comment]
Resolved via #1783 and #1728.
