### ISSUE TITLE
OpenGrok 0.11.1 not generating Perforce History and Annotate links

### ISSUE THREAD

**Issue by inqueue** [oracle/opengrok#703]
I am seeing an issue generating the History and Annotate links for Perforce repositories in OpenGrok 0.11.1. Despite what appears to be successful generation of the historycache, the links are dimmed on the UI. I have an SVN repository in my configuration and those History and Annotate links work as expected.

**Comment by ymnick** [comment]
Hi, I am struggling to find clear configuration instructions for Perforce repositories, could you please point me in the right direction? All I see is how to configure OpenGrok to work with local source copy, and I am looking to make it work against Perforce repository instead. Thanks!

**Comment by ymnick** [comment]
@inqueue I have the same issue with Perforce repositories you reported back in Dec 2013, could you please clarify how it was fixed?

WARNING: Failed to instanciate internal repository data for Perforce in /usr/opengrok/source

Thanks,
ymnick

**Comment by inqueue** [comment]
@ymnick I am still having trouble with Perforce history. History is produced and placed in historycache, but I am unable to access it within OpenGrok. I have not had any time to take a deeper dive into it.

**Comment by ymnick** [comment]
Thank you, I was under impression you got it working...

**Comment by inqueue** [comment]
I had it working initially, but it stopped sometime after adding more repositories to the configuration. I am indexing 6 branches from an SVN repository and 15 branches from a Perforce repo within a single OpenGrok instance. I figured I would get back on this when I get the time to upgrade OpenGrok to the latest.

**Comment by ymnick** [comment]
I have the latest OpenGrok installed both on Linux and Windows with Tomcat 7 and have the same issue with Perforce history and annotations in both installations. I do see 'historycache' being populated under OpenGrok data folder but it doesn't work in web UI.

**Comment by tarzanek** [comment]
the other option is to try the trunk build ... (but make sure you index from scratch, we updated lucene and xref format), Vlada fixed some small issues with history there

**Comment by RabihAntoun** [comment]
your problem is caused by the file ownership of the indexed files.
Make sure tomcat:tomcat is the owner of the indexed files and the history will show again.

As for the annotate and history make sure your tomcat is launched with java 64b and with an XMX of minimum 4GB as it fails on heap space when trying to get the p4 information from the server.

**Comment by lwonseop** [comment]
I have the same issue with SVN..History and Annotate are now working on OpenGrok...
