### ISSUE TITLE
Ignore history indexing of repositories matching IGNORE_PATTERNS

### ISSUE THREAD

**Issue by naseer** [oracle/opengrok#770]
This is related to https://github.com/OpenGrok/OpenGrok/issues/652.
 When indexing an Android repo, there are certain projects that have large binary files such as prebuilts/ndk which aren't necessary to index. Putting such directories in the ignore patterns skips the source indexing for that directory but the history index is still created. The history caching can sometimes take upwards of 30 minutes for such repositories.
Use IGNORE_PATTERNS or some similar mechanism to skip history indexing of these repos.

**Comment by unhipzippo** [comment]
In a similar vein, there may also be files that are updated so frequently that querying their history during indexing times out:

```
Dec 18, 2019 11:05:01 AM org.opengrok.indexer.util.Executor$2 run
WARNING: Terminating process of command [cleartool lshistory -fmt $'%e\n%Nd\n%Fu (%u)\n%Vn\n%Nc\n.\n' viking_build/build/ome/tx8260/sim/40g_oci/lb_warning.count] in directory /localdisk/opengrok/main/src/OME_12.40_XP1/vobs due to timeout 600 seconds
Dec 18, 2019 11:05:01 AM org.opengrok.indexer.util.Executor$1 run
SEVERE: Error while executing command [cleartool lshistory -fmt $'%e\n%Nd\n%Fu (%u)\n%Vn\n%Nc\n.\n' viking_build/build/ome/tx8260/sim/40g_oci/lb_warning.count] in directory /localdisk/opengrok/main/src/OME_12.40_XP1/vobs
Dec 18, 2019 11:05:01 AM org.opengrok.indexer.util.Executor$1 run
SEVERE: Error during process pipe listening
java.io.IOException: Stream closed
...
...
Dec 18, 2019 11:05:01 AM org.opengrok.indexer.util.Executor exec
WARNING: Non-zero exit status 4 from command [cleartool lshistory -fmt $'%e\n%Nd\n%Fu (%u)\n%Vn\n%Nc\n.\n' viking_build/build/ome/tx8260/sim/40g_oci/lb_warning.count] in directory /localdisk/opengrok/main/src/OME_12.40_XP1/vobs
Dec 18, 2019 11:05:01 AM org.opengrok.indexer.analysis.AnalyzerGuru populateDocument
WARNING: An error occurred while reading history: 
org.opengrok.indexer.history.HistoryException: Failed to get history for: "/localdisk/opengrok/main/src/OME_12.40_XP1/vobs/viking_build/build/ome/tx8260/sim/40g_oci/lb_warning.count" Exit code: 4
```

In the above case, "lb_warning.count" is a file which gets updated automatically by our formal loadbuild hooks (as it tracks compiler warning metrics), so the file can potentially have many many versions (18,000+) -- ClearCase's "cleartool lshistory" takes long enough that the OpenGrok indexer times out waiting.

Our ClearCase projects also have multiple build products in them, each with their own lb_warning.count files, so a particular OpenGrok ClearCase project may encounter these 600+ second timeouts upwards of 100+ times.
