### ISSUE TITLE
repository detection could be parallelized

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#773]
When indexing large code base with `-S` the repository detection takes non-trivial time to complete. I wonder if this step could be made parallel.

**Comment by tulinkry** [comment]
@vladak didn't you fix this with the #1375

**Comment by vladak** [comment]
The "another problem" yes, however the scan itself is still sequential I believe.

**Comment by tulinkry** [comment]
ping

**Comment by vladak** [comment]
This needs to be done correctly w.r.t. #1461.
