### ISSUE TITLE
OpenGrok index performance..

### ISSUE THREAD

**Issue by martin83tmp** [oracle/opengrok#802]
Hi, OpenGrok experts.

I'm martin.
I manage five android projects by using OpenGrok in my company.
And 'OpenGrok index src_folder' every day to update new source on OpenGrok.
It seems that indexing speed is not enough to using my android projects.
(I know android projects are too heavy to index.)

```
android_prj_1
android_prj_2
android_prj_3
android_prj_4
android_prj_5
```

It takes too much time to indexing.
Is there a way to use 'OpenGrok index' as multiple threads?
Or could you help me to deal with this? or Any Idea?

**Comment by tulinkry** [comment]
No reaction from the author for years. Use current latest version 1.1.2 which contains different parallelization approach for indexing, thus making it faster. A candidate for closing.
