### ISSUE TITLE
OpenGrok Web Interface fails to index Eiffel files correctly

### ISSUE THREAD

**Issue by AdityaSriramM** [oracle/opengrok#810]
My code has components from all languages (C/C++, Java, Perl, Shell Scripting, Eiffel etc). While all the other languages are properly indexed, when it comes to Eiffel files (*.e files), the indexing of classes, variables, functions is not proper (no referential links.. instead they are detected as paths).

![image](https://f.cloud.github.com/assets/7066923/2521982/04b80f5c-b4b6-11e3-8327-916bea038323.png)

The highlighted link in the image is redirecting to: http://localhost:8080/source/s?path=items.item&project=Open_Grok_Repo.

While I searched the net little surprised to see no one else seeing this issue. Want to know if I am missing something? Or what should I do to enable proper indexing of Eiffel (*.e) files.

Version of ctags = 5.8, Opengrok = 0.11.1

**Comment by idodeclare** [comment]
My PR #1955 on this was accepted.

**Comment by tarzanek** [comment]
indeed it was, thank you @idodeclare :-D
@AdityaSriramM  can you test with latest build from master ? (or 1.1 RC 19 once it will be out, or 1.1)

**Comment by tarzanek** [comment]
closing this for now, @AdityaSriramM if any probs, please open a new issue
