### ISSUE TITLE
"null.null" in Configuration refresh message in Tomcat

### ISSUE THREAD

**Issue by kosi2801** [oracle/opengrok#812]
When the "OpenGrok" script sends the running Tomcat a signal to refresh its configuration, the catalina.out contains a line

```
27-Mar-2014 00:17:04.749 INFO [Thread-22] null.null Configuration updated: /var/opengrok/src
```

It's only cosmetics, but probably the null.null could either be left out or be set to something meaningful.

**Comment by tulinkry** [comment]
I believe there's nothing we can do about this. It's a problem of the logging facility. Also I haven't encountered this problem with recent code. A candidate for closing.
