### ISSUE TITLE
Indexing take much time approximately 12000min. ver 0.11

### ISSUE THREAD

**Issue by jiungbaek** [oracle/opengrok#822]
Ubuntu 12.04.2 LTS
32core
80G Memory
src size : 60~70G android
java 1.7.0_51
python 2.7.3

$ ctags --version
Exuberant Ctags 5.9~svn20110310
git  : 1.8.3.4
## in Opengrok file,

OPENGROK_VERBOSE="true"
OPENGROK_SCAN_DEPTH="99"

JAVA_OPTS="
${JAVA_OPTS:--Xms4g
 -Xmx25g
 -XX:NewRatio=3
 -XX:PermSize=2g
 -XX:MaxPermSize=2g
 -XX:+UseParNewGC
 -XX:+CMSParallelRemarkEnabled
 -XX:SurvivorRatio=10
 -XX:TargetSurvivorRatio=90
 -Dnet.sf.ehcache.skipUpdateCheck=true
 -XX:+DoEscapeAnalysis
 -XX:+UseConcMarkSweepGC
 -XX:-TraceClassUnloading
 -XX:CMSInitiatingOccupancyFraction=60
 -XX:+UseCMSInitiatingOccupancyOnly
 -XX:+PrintGCDetails
 -XX:+PrintGCTimeStamps
 -verbose:gc
 -XX:ParallelGCThreads=32
 -XX:MaxTenuringThreshold=0}
##  "

Usually indexing process use 10~20G physical memory even i set virtual memory to 50G

---

Hi. i use opengrok for android source search.

i have some problem after KK version.

usually, first indexing, It takes approximately 1000min ~ 1200min.

However, nowadays new source and indexing take 12000min or more.

I tested other servers(specs are little bit difference), indexing time is the same.

something wierd. Would you guys please provide some help.

If you guys need more information, please let me know.

Thank you.

**Comment by tulinkry** [comment]
Version 1.1.2 uses different approach for parallelization, thus the index time should be much shorter. I suggest upgrading. A candidate for closing.
