### ISSUE TITLE
Point to multiple projects.

### ISSUE THREAD

**Issue by ganeshgore555** [oracle/opengrok#840]
When we run indexes we specify the SRC_ROOT, in normal case which will be a SVN_ROOT. So that all the source project under that SRC_ROOT get indexed. In our SVN we have structure as below:

SVN_ROOT -> Project1 -> Branch1..N
SVN_ROOT -> Project2 -> Branch1..N
SVN_ROOT -> Project3 -> Branch1..N
SVN_ROOT -> Project4 -> Branch1..N

Now issue is I want to include only Branch1 under all projects and not all Branches. If I set SVN_ROOT as source root all branches will be included and indexed. Also I don't want to checkout code spererately.

I am not able to find out any way. Please suggest some solution.

**Comment by tulinkry** [comment]
It’s time to test this again.  Ignored names is used also in ui so the issue should be resolved.

**Comment by vladak** [comment]
I think there is no solution to this - if a branch is to be indexed it has to be checked out.
