### ISSUE TITLE
Need some clarity about OPENGROK_SCAN_DEPTH and OPENGROK_REMOTE_REPOS

### ISSUE THREAD

**Issue by AlexandrSergei4** [oracle/opengrok#857]
What actually do OPENGROK_SCAN_DEPTH when using remote repos ?
I've used to think, that variable OPENGROK_SCAN_DEPTH influence only on depth of  scan source root directory, but if we are using remote repos, how then opengrok will be apply  OPENGROK_SCAN_DEPTH ?

**Comment by tulinkry** [comment]
No reactions for years. Env variables are no longer part of our routine. A candidate for closing.
