### ISSUE TITLE
 Handle symlinks correctly for OpenGrok shell script

### ISSUE THREAD

**Issue by zjj** [oracle/opengrok#870]
line 99 of OpenGrok shell script
opengrokbin=$(readlink -f ${0})
SCRIPT_DIRECTORY="`dirname ${opengrokbin}`"
SCRIPT_DIRECTORY="`cd ${SCRIPT_DIRECTORY}; pwd`"

A small apporch  to that

**Comment by tulinkry** [comment]
We no longer use OpenGrok shell script.
