### ISSUE TITLE
$OPENGROK_INSTANCE_BASE ignored when reading configuration; configuration still read from /var/opengrok/etc

### ISSUE THREAD

**Issue by tstuefe** [oracle/opengrok#928]
Hi all,

I set up opengrok 0.12.1 on Ubuntu 14.4. I use $OPENGROK_INSTANCE_BASE to change location of installation.

Indexing works, data directory is populated and opengrok works fine. Configuration is saved under $OPENGROK_INSTANCE_BASE/etc. 

But when apache is shut down and restarts, it attempts to read configuration from /var/opengrok/etc, ignoring $OPENGROK_INSTANCE_BASE. I need to reindex to fix this (which runs through very quickly). 

Now I created a softlink from /var/opengrok/etc to $OPENGROK_INSTANCE_BASE/etc as a workaround, which works. But I consider this a bug. 

Thanks,

Thomas

**Comment by tarzanek** [comment]
I agree with this being a bug
but it's kinda hard to introduce a "proper" fix - 
right now we are loosely coupled with a web app server - for various reasons (different types, versions, custom modifications to webapp, etc. )
so ideally we would start indexing, which would pre-create the proper .war file (/var/opengrok is hardcoded path in war) and then deploy it

BUT - you want to deploy the war just once, but at that time you didn't have to specify OPENGROK_INSTANCE_BASE ... and default will be used
Then later on you CAN use instance base with indexing and war would still point elsewhere, but indexing does send the config file to webapp using a port :) (port is also hardcoded in webapp)

So ideally instance base, port and webapp prefix (/source by default) should be variables of webapp deploy ... (with current defaults, if you specify none of them)
So this would be a fix I'd like, if you're interested you can pick this up - to make deploy more intelligent and self fixing the webapp .war file for the user env ...

tia
Lubos

**Comment by tarzanek** [comment]
So to make it short and nice, proper fix imho needs to happen in:
https://github.com/OpenGrok/OpenGrok/blob/master/OpenGrok#L872
- needs improvement in sense that it should patch the path to instance base, ev. port in web.xml and eventually rename the .war in case people specify those options, namely those need to be honored:
OPENGROK_INSTANCE_BASE - data dir with config
OPENGROK_WEBAPP_CFGADDR - port number to listen to, in case this is localhost (or its IP)
OPENGROK_WEBAPP_CONTEXT - prefix of webapp, rename fixed war to this before deploy

marking this as enhancement, fix is nice shell game, who is interested? (and OpenGrok shell script needs fixing of some [ ] in if-s , too )

**Comment by tulinkry** [comment]
Env variable are no longer part of the configuration routine in 1.1.2. A candidate for closing.

**Comment by vladak** [comment]
I concur. The configuration path in the `web.xml` file is separate from Indexer arguments in the Python tools.
