### ISSUE TITLE
How can I change service url?

### ISSUE THREAD

**Issue by verascone** [oracle/opengrok#933]
Hello.

I want to change url of opengrok webapp from source to my.
1. I changed war file name.
   source.war --> my.war
2. I add variable into OpenGrok file.
    OPENGROK_WEBAPP_CONTEXT="my"
3. I deployed and indexed it but it doesn't  work correctly
   When I click link in a particular file the following messasge appears.

type Status report
message /source/s
description The requested resource is not available.

This is redirected url. '/source/' part has not changed into '/my/'. 
http://my_url.com/source/s?refs=BuildData&project=src

How can I change service url properly?
Please let me know.

Thank you.

**Comment by tarzanek** [comment]
OPENGROK_WEBAPP_CONTEXT="my" OpenGrok index ...
should create proper xrefs ...
I will try to validate, but that code didn't change recently ...

**Comment by tulinkry** [comment]
Solution given and no reaction for years. A candidate for closing

**Comment by vladak** [comment]
The solution is actually much easier now - just deploy the renamed WAR file.
