### ISSUE TITLE
OpenGrok shell script not fully OK

### ISSUE THREAD

**Issue by tarzanek** [oracle/opengrok#947]
ssh sun-n1
cd your_WS
shellcheck OpenGrok

prints a lot of errors, e.g. broken if-s , missing ""

**Comment by vladak** [comment]
could you paste the errors so that anyone can fix them ?

**Comment by tarzanek** [comment]
http://www.shellcheck.net/
can be used

I am not pasting them on purpose, some of them might be red herrings

**Comment by vladak** [comment]
89 comments is quite a lot. Bulk of it is replacement for command execution using back ticks for `$()`. Some of them (in particular some of the double quote comments) are definitely false - if they were followed it would lead to regressions.

**Comment by tarzanek** [comment]
I just remember folks on discuss saying ifs are wrong ... and they were valid
but I didn't fix it yet, so that's why this bug saw the light of world ...

**Comment by kahatlen** [comment]
Pull request #951 fixes one bashism. Don't know if that's one of the problems you're seeing, though, as that particular bash extension (==) is also a ksh extension. But it's not working with dash.

**Comment by tarzanek** [comment]
yes, one of them, but there are more

**Comment by vladak** [comment]
before anyone goes and fixes this, keep in mind that #1783 exists.

**Comment by tulinkry** [comment]
I think this can be closed now

**Comment by vladak** [comment]
happily closing
