### ISSUE TITLE
CVS History parsing silently fails for few commit logs

### ISSUE THREAD

**Issue by pratikone** [oracle/opengrok#957]
We have deployed Opengrok on our office source code which is based on C and C++ and using CVS as remote repo server.
It indexes a locally checked out branch of the source code.  We have already filed an issue under #943 . It contains further details of our setup.
# What is the problem ?

In History page of some certain files, not full history is shown. History will be shown only upto few commits. It is **NOT** related to `cvs log` result being huge. Many other files with larger output of `cvs log` show their history correctly without any problem. In some files, the full log message of last shown commit itself is not displayed and is cut in between arbitrarily.
# Root cause

We dug around and narrowed down to the root cause. It is due to the way Opengrok CVS parser parses the output of `cvs log <filename>`.  
The cvs log entries are separated by a `---------` and the final entry is followed by `======`. CVSHistoryParser works on these principles. But this conflicts with the cvs log comments. If a comment contains `--------` in a new line, it is cut short just after that. And, if a comment contains `======` in a new line then the whole history parsing for that file ends.
Here is the code : https://github.com/OpenGrok/OpenGrok/blob/1b8e3972dd24d151c2a8928d754f239555dbba08/src/org/opensolaris/opengrok/history/CVSHistoryParser.java#L131
# How to fix this ?

There could be multiple solutions. I thought it would be better to discuss before sending a patch. Please suggest few.

**Comment by tarzanek** [comment]
first thing that came to my mind is to make the entry dividers configurable ?

**Comment by pratikone** [comment]
But first time users are not expected to do that much configuration. We need a simple solution which works for most of the cases and for the cases it would fail, configurable divider entry be provided.

Btw, cvs log output will continue to use `-------` as divider anyways. We cannot change that.

**Comment by vladak** [comment]
The `startsWith` is definitely not very cautious thing to do, the match should be exact. I'd start with that.

**Comment by vladak** [comment]
Another possibility is to make the state transition conditions more complicated - e.g. for the switch to REVISION there would have to a match of 2 lines: the `----------------------------` line and a line which starts with `revision x.y...`.

**Comment by pratikone** [comment]
First of all, a state transition for `==========` is not needed at all. Cvs log output ends with a `========`. We just issue the command `cvs log <filename>` and get the output back. The end of output is anyway well-defined and should not be dependent on something like `===========` for its operation.

**Comment by vladak** [comment]
> First of all, a state transition for `==========` is not needed at all. Cvs log output ends with a `========`. We just issue the command `cvs log <filename>` and get the output back. The end of output is anyway well-defined and should not be dependent on something like `===========` for its operation.

The `=== ... ===` matching is actually needed when requesting the history of a directory in the webapp. When `cvs log` is run on a directory, it will emit the history for each file therein. The revision entries for the files will be divided using the equal marks.

**Comment by pratikone** [comment]
Good to see this bug getting fixed after many years. Thanks for doing it. I no longer work with Java codebase but Opengrok was an important piece of software to help understand and share it.
