### ISSUE TITLE
The mk file not be recognized in group "Shell script"

### ISSUE THREAD

**Issue by AsCatgz** [oracle/opengrok#961]
In android, the most make file is "Android.mk", which is endwith "mk". Now the make file in in group "Shell script", this group include "MAKEFILE", and file endwith "SH", "KSH", "KSHLIB", "CSH", "BASH", "RUBY", "RB", "P5", "AWK", "GMK", "CONF", "COM", "SPEC", "FLG", "XCL", but NO "mk", so the "Android.mk" in android can't be recognized in group "Shell script".

**Comment by tarzanek** [comment]
I can see #962 is trying to solve this.
Note that you can get EVEN better support for makefiles, by creating a special analyzer for them,
ctags support them out of box: http://ctags.sourceforge.net/languages.html
Have a look at older commits, it's very easy to write an analyzer and fun too!

**Comment by tulinkry** [comment]
I think this is solved #962
